### ISSUE TITLE
Task test fails with MalformedParameterizedTypeException

### ISSUE THREAD

**Issue by anti43** [grails/grails-core#10017]
### Steps to Reproduce

run task "test", with or without actual tests defined. happens in intellij and gitlab runner.

note:  at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:394)
Java5 is used (no Java 1.5 on my system) !

### Expected Behaviour

Tests should run

### Actual Behaviour

```
Error occurred calling Trait injector [org.grails.compiler.injection.TraitInjectionUtils]: Unable to configure class node for class grails.events.Events due to malformed parameterized types
java.lang.RuntimeException: Unable to configure class node for class grails.events.Events due to malformed parameterized types
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:394)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:265)
	at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:360)
	at org.codehaus.groovy.ast.ClassNode.declaresInterface(ClassNode.java:976)
	at org.codehaus.groovy.ast.ClassNode.declaresInterface(ClassNode.java:981)
	at org.codehaus.groovy.ast.ClassNode.implementsInterface(ClassNode.java:956)
	at org.codehaus.groovy.transform.stc.StaticTypeCheckingSupport.implementsInterfaceOrIsSubclassOf(StaticTypeCheckingSupport.java:771)
	at org.codehaus.groovy.ast.tools.GenericsUtils.parameterizeType(GenericsUtils.java:218)
	at org.codehaus.groovy.transform.trait.Traits.collectAllInterfacesReverseOrder(Traits.java:274)
	at org.codehaus.groovy.transform.trait.TraitComposer.findTraits(TraitComposer.java:116)
	at org.codehaus.groovy.transform.trait.TraitComposer.doExtendTraits(TraitComposer.java:101)
	at org.grails.compiler.injection.TraitInjectionUtils.doInjectionInternal(TraitInjectionUtils.java:72)
	at org.grails.compiler.injection.TraitInjectionUtils.processTraitsForNode(TraitInjectionUtils.java:104)
	at org.grails.compiler.injection.GlobalGrailsClassInjectorTransformation.visit(GlobalGrailsClassInjectorTransformation.groovy:122)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:321)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:931)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:525)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:167)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:54)
	at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
	at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:365)
	... 39 more
:compileGroovy FAILED

```
### Environment Information

- **Operating System**:  Windows 10 64bit
- **Grails Version:** 3.1.8
- **JDK Version:** 1.7._79
- **Gradle:** 2.14

**Comment by anti43** [comment]
Goes away with newest gradle distro
