### ISSUE TITLE
 Error occurred running Grails CLI

### ISSUE THREAD

**Issue by ManjunathSeetharam** [grails/grails-core#10026]
Hi Folks,

I installed latest version of  grails-3.1.9 on my system with latest version of JDK.
When I type grails -version, I am getting grails version with one warning:

**Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this releas
| Grails Version: 3.1.9
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_92**

when I type grails create-app race --stackrace

| Error Error occurred running Grails CLI: This is usually a temporary error dur
ing hostname resolution and means that the local server did not receive a respon
se from an authoritative server (NOTE: Stack trace has been filtered. Use --verb
ose to see entire trace.)
java.net.UnknownHostException: This is usually a temporary error during hostname
 resolution and means that the local server did not receive a response from an a
uthoritative server
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefa
ultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHost
name(DefaultClientConnectionOperator.java:278)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnect
ion(DefaultClientConnectionOperator.java:162)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedCli
entConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(Default
RequestDirector.java:643)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultReq
uestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:906)
        at org.apache.http.impl.client.DecompressingHttpClient.execute(Decompres
singHttpClient.java:137)
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTranspo
rter.java:287)
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTranspo
rter.java:243)
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(Ab
stractTransporter.java:59)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRu
nner.runTask(BasicRepositoryConnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunne
r.run(BasicRepositoryConnector.java:350)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(Runn
ableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExe
cutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(Basic
RepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownl
oads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(Defa
ultArtifactResolver.java:421)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
acts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
act(DefaultArtifactResolver.java:223)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.
loadPom(DefaultArtifactDescriptorReader.java:320)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.
readArtifactDescriptor(DefaultArtifactDescriptorReader.java:217)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCa
chedArtifactDescriptor(DefaultDependencyCollector.java:535)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifa
ctDescriptorResult(DefaultDependencyCollector.java:519)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDe
pendency(DefaultDependencyCollector.java:409)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDe
pendency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(D
efaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDe
pendencies(DefaultDependencyCollector.java:254)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDepen
dencies(DefaultRepositorySystem.java:341)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve
(AetherGrapeEngine.java:302)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve
(AetherGrapeEngine.java:284)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve
(AetherGrapeEngine.java:276)
        at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyV
ersions.groovy:53)
        at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyV
ersions.groovy:49)
        at org.grails.cli.profile.repository.MavenProfileRepository.<init>(Maven
ProfileRepository.groovy:55)
        at org.grails.cli.GrailsCli.createMavenProfileRepository(GrailsCli.groov
y:329)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:238)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:163)
| Error Error occurred running Grails CLI: This is usually a temporary error dur
ing hostname resolution and means that the local server did not receive a respon
se from an authoritative server

I found one solution where user sets export GRAILS_OPTS="-XX:-UseSplitVerifier -Xverify:none"
But, this is not working for me

Please help me in solving this problem

Regards,
Manjunath S

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)

**Comment by trinhnguyenformos** [comment]
Please trying to reinstall a higher Java version. I tried & It works find now.
