### ISSUE TITLE
grails 3.1.9 can not set request attribute in interceptor or action

### ISSUE THREAD

**Issue by shawnchain** [grails/grails-core#10046]
### Steps to Reproduce

1. Create a app with a domaon Foo and FooController/FooInterceptor
2. In controller and interceptor, put following test code

Controller:
```
    def test(){
        request['foobar'] = 'foobar' // success!
        request.setAttribute('session','foobar_session'); // failed!
        request['session'] = 'foobar_session' // failed!
        render "OK"
    }
```

Interceptor:
```
    boolean before() {
        request.setAttribute('session','foobar_session'); // success!
        request['session'] = 'foo'; // failed!
        return true
    }

```

3. Run app and access from browser, the error message occurred:

 ```
ERROR org.grails.web.errors.GrailsExceptionResolver - GroovyRuntimeException occurred when processing request: [GET] /user/test
Cannot set read-only property: session. Stacktrace follows:
groovy.lang.GroovyRuntimeException: Cannot set read-only property: session
	at hellog3.UserInterceptor.before(UserInterceptor.groovy:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

### Expected Behaviour

 - Behavior of reqeust.setAttribute('foo') and request['foo'] should be the same
 - attribute 'session' in request object ( the request['session']) should not be occupied by the framework

### Actual Behaviour
  - Got exception: "Cannot set read-only property: session"

### Environment Information

- **Operating System**: OSX 10.10
- **Grails Version:** 3.1.9
- **JDK Version:** 1.8
- **Container Version (If Applicable):** N/A

### Example Application

- N/A

**Comment by burtbeckwith** [comment]
You're seeing behavior defined in extensions methods in https://github.com/grails/grails-core/blob/master/grails-web/src/main/groovy/org/grails/web/servlet/HttpServletRequestExtension.groovy#L40

In trying to set a request attribute named 'session' it's seeing that `HttpServletRequest` has a read-only property with that name (because of the `getSession()` method), so you end up being blocked from setting the attribute. I suppose it might make sense to set an attribute if the property is read-only, but there would still be ambiguity when access the property and the attribute. Using real methods works fine, but since property access and attribute access both share an operator overload, you can only retrieve one of them.

**Comment by shawnchain** [comment]
@burtbeckwith Thanks for the quick reply.  So can I think this is much like a "undefined behavior of http request attribute operations" in stead of a bug ? 
As most of the developer may code that way according to the grails guide document  without take a deep look into the grails source code.

**Comment by burtbeckwith** [comment]
Yes, and having a brief description of the behavior in the docs would help. I'm curious though, why would you want to set a request attribute named 'session'?
