### ISSUE TITLE
App using spring security HierarchyRole not working within an IDE

### ISSUE THREAD

**Issue by gsartori** [grails/grails-core#10057]
### Steps to Reproduce
1. Import the app with Gradle (Tested with Standard Eclipse NEON + Groovy plugin and IntelliJ Idea CE.)
2. Run the provided application with "grails run-app" or "./gradlew bootRun" or the IDE gradle taks "bootRun" -> it should work (user: test, password: test)
3. Run the provided application within the IDE launching "Application.groovy" as a standard Groovy application -> it should give you an exception

### Expected Behaviour
The app should run from an IDE launching "Application.groovy"

### Actual Behaviour
Returns the following exception:

```
java.lang.ClassNotFoundException: [:]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_92]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_92]
	at grails.plugin.springsecurity.SpringSecurityService.reloadDBRoleHierarchy(SpringSecurityService.groovy:154) ~[spring-security-core-3.1.1.jar:na]
	at grails.plugin.springsecurity.SpringSecurityService$reloadDBRoleHierarchy.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-2.4.7.jar:2.4.7]
	at test.TestService.createRole(TestService.groovy:21) ~[build/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384) ~[groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166) [groovy-2.4.7.jar:2.4.7]
	at BootStrap$_closure1$_closure3.doCall(BootStrap.groovy:11) ~[build/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:414) ~[groovy-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:430) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:242) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.dgm$757.invoke(Unknown Source) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-2.4.7.jar:2.4.7]
	at BootStrap$_closure1.doCall(BootStrap.groovy:9) ~[build/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1089) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:414) ~[groovy-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:408) ~[groovy-2.4.7.jar:2.4.7]
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:437) ~[grails-bootstrap-3.1.9.jar:3.1.9]
	at grails.util.Environment.executeForEnvironment(Environment.java:430) ~[grails-bootstrap-3.1.9.jar:3.1.9]
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:406) ~[grails-bootstrap-3.1.9.jar:3.1.9]
	at org.grails.web.servlet.boostrap.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:62) ~[grails-web-3.1.9.jar:3.1.9]
	at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:65) ~[grails-web-3.1.9.jar:3.1.9]
	at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:53) ~[grails-plugin-controllers-3.1.9.jar:3.1.9]
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:238) ~[grails-core-3.1.9.jar:3.1.9]
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy) ~[grails-core-3.1.9.jar:3.1.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:55) [grails-core-3.1.9.jar:3.1.9]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:374) [grails-core-3.1.9.jar:3.1.9]
	at grails.boot.GrailsApp.run(GrailsApp.Caught: java.lang.reflect.UndeclaredThrowableExceptiongroovy:363) [grails-core-3.1.9.jar:3.1.9]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-3.1.9.jar:3.1.9]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-2.4.7.jar:2.4.7]
	at test.Application.main(Application.groovy:23) [Application.groovy:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1448) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:897) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:287) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.GroovyShell.run(GroovyShell.java:518) [groovy-2.4.7.jar:2.4.7]
	at groovy.lang.GroovyShell.run(GroovyShell.java:507) [groovy-2.4.7.jar:2.4.7]
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:653) [groovy-2.4.7.jar:2.4.7]
	at groovy.ui.GroovyMain.run(GroovyMain.java:384) [groovy-2.4.7.jar:2.4.7]
	at groovy.ui.GroovyMain.process(GroovyMain.java:370) [groovy-2.4.7.jar:2.4.7]
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129) [groovy-2.4.7.jar:2.4.7]
	at groovy.ui.GroovyMain.main(GroovyMain.java:109) [groovy-2.4.7.jar:2.4.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109) [groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131) [groovy-2.4.7.jar:2.4.7]

2016-07-19 23:20:48.553  INFO 28819 --- [           main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: []

java.lang.reflect.UndeclaredThrowableException
	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:317)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:844)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:374)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:363)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at test.Application.main(Application.groovy:23)
Caused by: java.lang.ClassNotFoundException: [:]
	at grails.plugin.springsecurity.SpringSecurityService.reloadDBRoleHierarchy(SpringSecurityService.groovy:154)
	at grails.plugin.springsecurity.SpringSecurityService$reloadDBRoleHierarchy.call(Unknown Source)
	at test.TestService.createRole(TestService.groovy:21)
	at BootStrap$_closure1$_closure3.doCall(BootStrap.groovy:11)
	at BootStrap$_closure1.doCall(BootStrap.groovy:9)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:437)
	at grails.util.Environment.executeForEnvironment(Environment.java:430)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:406)
	at org.grails.web.servlet.boostrap.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:62)
	at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:65)
	at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:53)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:238)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	... 5 more
```

### Environment Information
- **Operating System**: Linux
- **Grails Version:**  3.1.9
- **JDK Version:** 1.8

### Example Application
https://github.com/gsartori/role-hierarchy-not-working-from-IDE.git

**Comment by burtbeckwith** [comment]
It's not the plugin's fault, it's the abandoned IDE with aging and increasingly useless support for Grails and Groovy.
