### ISSUE TITLE
How to build grails 1.3.6

### ISSUE THREAD

**Issue by lenikirilov-taulia** [grails/grails-core#10105]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

I want to build 1.3.6 and try to patch some of the testings scripts, so that I can create the integration environment once, but rerun test (recompiled using JRebel), because it takes 2-3 minutes.

1. I have the sources using `sdk install grails 1.3.6`
2. I use gradle 0.9 as seen from the gradle wrapper definition in build.gradle
3. Execute `gradle wrapper` or `gradle assemble`

### Expected Behaviour

Build the grails project so that I can use it locally to play around and "contribute" 

### Actual Behaviour

I hit gradle errors like missing properties, unsupported parameters etc

> Caused by: groovy.lang.MissingPropertyException: No such property: systemProperties for class: org.gradle.api.tasks.testing.junit.JUnitOptions
> org.gradle.api.LocationAwareGradleScriptException: Script '/Users/lenikirilov/.sdkman/candidates/grails/1.3.6/gradle/unit-test.gradle' line: 64

Stack trace:

* Exception is:
```
org.gradle.api.LocationAwareGradleScriptException: Script '/Users/lenikirilov/.sdkman/candidates/grails/1.3.6/gradle/unit-test.gradle' line: 64
A problem occurred evaluating script.
	at org.gradle.groovy.scripts.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:51)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:127)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:82)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:32)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:54)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:114)
	at org.gradle.api.internal.project.AbstractProject.apply(AbstractProject.java:866)
	at org.gradle.api.Project$apply$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:31)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:44)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at build_gradle_966a90994b15d3ef6d947a1677149db0.run(/Users/lenikirilov/.sdkman/candidates/grails/1.3.6/build.gradle:81)
	at org.gradle.groovy.scripts.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:49)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:127)
	at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
	at org.gradle.configuration.DefaultProjectEvaluator.evaluate(DefaultProjectEvaluator.java:38)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:506)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:71)
	at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:23)
	at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:21)
	at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuildConfigurer.java:38)
	at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuildConfigurer.java:35)
	at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:482)
	at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:477)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:136)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:107)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:75)
	at org.gradle.launcher.RunBuildAction.execute(RunBuildAction.java:41)
	at org.gradle.launcher.RunBuildAction.execute(RunBuildAction.java:27)
	at org.gradle.launcher.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory.java:209)
	at org.gradle.launcher.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory.java:193)
	at org.gradle.launcher.Main.execute(Main.java:55)
	at org.gradle.launcher.Main.main(Main.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.launcher.ProcessBootstrap.runNoExit(ProcessBootstrap.java:46)
	at org.gradle.launcher.ProcessBootstrap.run(ProcessBootstrap.java:28)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:24)
Caused by: groovy.lang.MissingPropertyException: No such property: systemProperties for class: org.gradle.api.tasks.testing.junit.JUnitOptions
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:49)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:485)
	at unit_test_gradle_2e0ef2040a202ebecb6d2474e01ddb84$_run_closure6.doCall(/Users/lenikirilov/.sdkman/candidates/grails/1.3.6/gradle/unit-test.gradle:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:88)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:273)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)
	at groovy.lang.Closure.call(Closure.java:282)
	at groovy.lang.Closure.call(Closure.java:295)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:61)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:31)
	at org.gradle.api.internal.DefaultNamedDomainObjectContainer$ContainerElementsDynamicObject.invokeMethod(DefaultNamedDomainObjectContainer.java:307)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:93)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:93)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:93)
	at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.groovy:68)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:88)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:813)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1107)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1060)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:44)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at unit_test_gradle_2e0ef2040a202ebecb6d2474e01ddb84.run(/Users/lenikirilov/.sdkman/candidates/grails/1.3.6/gradle/unit-test.gradle:63)
	at org.gradle.groovy.scripts.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:49)
	... 45 more
```

### Environment Information

- **Operating System**: mac 
- **Grails Version:** 1.3.6
- **JDK Version:** 1.7

**Comment by jeffbrown** [comment]
The issue tracker is for bug reports and feature requests.  Please ask questions on the mailing list at https://groups.google.com/forum/#!forum/grails-dev-discuss, our Slack channel at http://grails.slack.com/ or on http://stackoverflow.com.
