### ISSUE TITLE
Grails 3.0.15 No Session Found For Current Thread

### ISSUE THREAD

**Issue by ilan18** [grails/grails-core#10115]
Using Grails 3.0.15.  From Quartz calling Grails Service, which explicitly calls domain class withTransaction.  Getting error "No Session found for current thread".  See stack traceback below:

```
2016-08-23 14:43:37.147 [QuartzScheduler2_Worker-12] ERROR com.the.company.name.TheQuartzJob - _execute_closure2 threw unexpected throwable (Heuristic completion: outcome state is mixed; nested exception is org.springframework.orm.hibernate4.HibernateSystemException: No Session found for current thread; nested exception is org.hibernate.HibernateException: No Session found for current thread).  Marking job as failed
org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is mixed; nested exception is org.springframework.orm.hibernate4.HibernateSystemException: No Session found for current thread; nested exception is org.hibernate.HibernateException: No Session found for current thread
        at org.grails.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:174) ~[ChainedTransactionManager.class:3.0.11]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150) ~[TransactionTemplate.class:4.1.8.RELEASE]
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93) ~[GrailsTransactionTemplate.class:3.0.11]
        at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:822) ~[GormStaticApi.class:na]
        at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:722) ~[GormStaticApi.class:na]
        at org.grails.datastore.gorm.GormStaticApi$withTransaction$2.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:2.4.5]
        at org.grails.datastore.gorm.GormStaticApi$withTransaction$2.call(Unknown Source) ~[na:na]
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.withTransaction(GormEntity.groovy:724) ~[GormEntity$Trait$Helper.class:na]
        at org.grails.datastore.gorm.GormEntity$Trait$Helper$withTransaction$1.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[AbstractCallSite.class:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) ~[AbstractCallSite.class:2.4.5]
        at com.the.company.name.directory.Contact.withTransaction(Contact.groovy) ~[Contact.class:na]
        at com.the.company.name.directory.Contact$withTransaction$5.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[AbstractCallSite.class:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[AbstractCallSite.class:2.4.5]

```

Have tried:

- One or both of withSession() withNewSession() withTransaction() and withNewTransaction() in varying places in the code calling hierarchy
- Using @Tranactional on various Services methods

The project has similar code from Quartz calling withTransaction() successfully.  No idea what is different about this one and why this one does not work.

- **Operating System**:  Same issue seen when resulting war deployed in Windows 10 and Linux
- **Grails Version:**  3.0.15
- **JDK Version:** 1.7.0_79
- **Container Version (If Applicable):** Tomcat 8.0.14

**Comment by graemerocher** [comment]
Report the issue to https://github.com/grails-plugins/grails-quartz/issues
