### ISSUE TITLE
grailsUrlMappingsHolder ->  IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by valerius** [grails/grails-core#10128]
Thanks for all the great work! Unfortunately after many hours of trying, this issue for me is too intermittent to provide reproducible steps, though I will continue to work on it, and for purposes here try and recreate it with a new app. However, basically, I migrated my app from grails 2.4 and it works fine with my inline plugins mostly, however I do received this exception only occasionally when running integration test. My testing process include a clean, then run integration test.  Exception below, I'm more seeking the next thing to try to debug, perhaps its not a grails specific issue?

Another ticket for grails simular to this was closed in the past. See: https://github.com/grails/grails-core/issues/665

Environments (Try all these combinations):
JDK: Tried 7 & 8
Grails: 3.1.10 & 3.1.9

Exception:
```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:228)
	at org.spockframework.spring.SpringTestContextManager.prepareTestInstance(SpringTestContextManager.java:49)
	at org.spockframework.spring.SpringInterceptor.interceptSetupMethod(SpringInterceptor.java:42)
	at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:28)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urlMappingsErrorPageCustomizer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private grails.web.mapping.UrlMappings org.grails.web.mapping.servlet.UrlMappingsErrorPageCustomizer.urlMappings; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsUrlMappingsHolder': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 25 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urlMappingsErrorPageCustomizer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private grails.web.mapping.UrlMappings org.grails.web.mapping.servlet.UrlMappingsErrorPageCustomizer.urlMappings; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsUrlMappingsHolder': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:195)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:158)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
	... 34 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urlMappingsErrorPageCustomizer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private grails.web.mapping.UrlMappings org.grails.web.mapping.servlet.UrlMappingsErrorPageCustomizer.urlMappings; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsUrlMappingsHolder': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:534)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1170)
	at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.getCustomizers(EmbeddedServletContainerCustomizerBeanPostProcessor.java:77)
	at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.postProcessBeforeInitialization(EmbeddedServletContainerCustomizerBeanPostProcessor.java:67)
	at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.postProcessBeforeInitialization(EmbeddedServletContainerCustomizerBeanPostProcessor.java:54)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	... 42 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private grails.web.mapping.UrlMappings org.grails.web.mapping.servlet.UrlMappingsErrorPageCustomizer.urlMappings; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsUrlMappingsHolder': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 57 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsUrlMappingsHolder': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 59 more
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at org.grails.web.mapping.DefaultUrlMappingsHolder.sortMappings(DefaultUrlMappingsHolder.java:204)
	at org.grails.web.mapping.DefaultUrlMappingsHolder.initialize(DefaultUrlMappingsHolder.java:124)
	at org.grails.web.mapping.UrlMappingsHolderFactoryBean.afterPropertiesSet(UrlMappingsHolderFactoryBean.java:118)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 69 more
```

Mappings (I actually have serval from inline plugins, though only two should be included as plugins wont use the default UrlMappings):

MainAppMapping
```groovy

class UrlMappings {

    static String serviceNames = [
            "echo_v", 'addFactoid', 'addHeadline', 'removePost','ratePost','reportPost'
    ].join('|')

    static String feedNames = [
            "factoids", 'headlines', 'annotations', 'posts'
    ].join('|')

    static mappingServiceConstraints = {
        target matches: /(${serviceNames})/ as String
    }

    static mappingFeedConstraints = {
        target matches: /(${feedNames})/ as String
    }

    static mappings = {

        /********************************************************
         RESOURCE MAPPINGS
         ********************************************************/
        "/api/data/articles"(resources:"article", controller: ArticleController, namespace:'rest')
        "/api/data/categories"(resources:"category",controller: CategoryController, namespace:'rest')
        "/api/data/websites"(resources:"website")

        "/sp/service/$target?(.${format})?" {
            controller = 'post'
            method = {
                [shout: 'echo'].get(params.target) ?: params.target
            }
            action = 'rest'
            constraints this.mappingServiceConstraints
        }


        "/syndicate/$target?(.${format})?" {
            controller = 'postFeed'
            action = {
                ['posts': 'all'].get(params.scope ?: params.target) ?: params.scope ?: params.target
            }
            constraints this.mappingFeedConstraints
        }

        "/sp/service/xmlrpc/v2"(controller: "post", action: "xmlrpc")
        
        "/sp/perspective/list"(controller: "annotation",action:'perspectives')
        //browser API for annoations
        "/sp/annotations/auth"(controller: "annotation",action:'token')
        "/sp/annotations/list"(controller: "annotation", action: 'index')
        "/sp/annotation/$id?"(controller: "annotation", action: 'show')
        "/sp/annotations/$id?"(controller: "annotation") {
            action = { [
                    GET   : "index",
                    DELETE: "delete",
                    POST  : "save",
                    PUT   : 'update',
                    OPTIONS: 'options'
                    //PUT:"update",
            ].get(request.method.toUpperCase()) }
        }


        "/$controller/$action?/$id?" {
            constraints {
                // apply constraints here
            }
        }

       "/logout" {
            controller = "logout"
            action = "index"
        }

        "/health_check" {
            controller = "healthCheck"
            action = "index"
        }

        "/p/$slug" {
            controller = "tinyURL"
            action = "index"
        }

        "/debugger" {
            controller = "console"
            action = "index"
        }

        "/debugger/execute" {
            controller = "console"
            action = "execute"
        }

        "/api/remarks/entry(.$format)?"(controller: 'remark', action: 'entry')

        "/api/remarks/comments(.$format)?"(controller: 'remark', action: 'comments')
        "/api/remarks/replies(.$format)?"(controller: 'remark', action: 'replies')
        "/api/config/preview.js"(controller: 'preview', action: 'config')

        "/"(view: "/index")
        "/register/password_updated.gsp"(view: "/register/password_updated")
        "/register/welcome.gsp"(view: "/register/welcome")
        "/legal/privacy_policy"(view: "/legal/privacy_policy")
        "/legal/privacy_policy.gsp"(view: "/legal/privacy_policy")
        "/legal/terms"(view: "/legal/terms")
        "/legal/terms.gsp"(view: "/legal/terms")
        "500"(view: '/error')
    }
}
```

Inline Plugin Mapping 

```groovy
class SubportalUrlMappings {
    static String serviceNames =  [
            "authenticate", "openAuth", "logout","echo",
            "registerArticle", "commentOnArticle", "respondToComment",
            'usedDeal','redeemDeal','issueDeal','entryInfo',
            "affirmComment", "reportComment", "registerSubscriber", "registerDevice",
            "registerToken", "rateEntry", "listProducts", "verifyPurchase", "fundTransaction",
            "profileImage", "recordHistory", "report", "clipCoupon", "issueCoupon", "bookmark","bookmarkEntry",
            "unbookmark", "acceptInvitation", "denyInvitation", "inviteMember", "removeMember"
    ].join('|')

    static String syndicateNames = [
            "affiliates",
            "comment", "comments", "conversations",
            "offers","coupons","loyalty", "deals",
            "articles","classifieds",
            "entry",  "entries","weblogs"
    ].join('|')

    static mappingSyndicateConstraints = {
        target matches: /(${syndicateNames})/ as String
    }

    static mappingServiceConstraints = {
        target matches: /(${serviceNames})/ as String  // /(authenticate|openAuth|logout|registerArticle|commentOnArticle|respondToComment|affirmComment|reportComment|registerSubscriber|registerDevice|registerToken|rateEntry|listProducts|verifyPurchase|fundTransaction|profileImage|recordHistory|report|clipCoupon|issueCoupon|bookmark|unbookmark|bookmark|acceptInvitation|denyInvitation|inviteMember|removeMember|echo)/
    }

    static mappings = {
        "/sp/$controller/$action?/$id?" {
            constraints {
                // apply constraints here
            }
        }

        "/syndicate/$target" {
            controller = 'syndicateFeed'
            action = {
                if(params.scope == "bookmarked")
                    "bookmarks"
                else
                    [entries:'articles'].get( params.target) ?: params.target
            }
            constraints this.mappingSyndicateConstraints
        }


        "/sp/service/$target?(.${format})?" {
            controller = 'service'
            method = {
                [shout: 'echo'].get(params.target) ?: params.target
            }

            action = 'rest'
            constraints this.mappingServiceConstraints
        }
        

        "/sp/img/profile_photo_upload"(controller: "images", action: "uploadProfilePhoto")

        "/sp/img/profile"(controller: "images", action: "profile")

        "/sp/service/xmlrpc"(controller: "service", action: "xmlrpc")

        "/sp/"(view: "/index")

        "/sp/password/lost_password"(controller: "passwordReset", action: "index")
        "/sp/password/email"(controller: "passwordReset", action: "email") 
        "/sp/password/identify"(controller: "passwordReset", action: "identify") 
        "/sp/password/reset"(controller: "passwordReset", action: "reset")

        "500"(view: '/error')
    }
}
```

**Comment by jameskleeh** [comment]
Include here the mappings that you are using when the error occurs

**Comment by valerius** [comment]
Thanks so much for the quick response... I've edited the issue (above) to include the mappings. If I can help in any other way please let me know :)

**Comment by valerius** [comment]
Finally figured a deterministic way to reproduce the issue. If you run the integration test of   the following project you will receive the aforementioned exception. To resolve the exception (search for DEBUG: ), you may comment out various lines in the following files:

```
./app/main-app/build.gradle
./app/main-app/grails-app/controllers/main/app/UrlMappings.groovy
./dep/routes-one/build.gradle
```
Which includes either commenting out 'grails-console' plugin, commenting out an inline dependency, or a specific route. The project is here:
```
git@github.com:valerius/debug-grails-mappings.git
```
Then:

```
gradle integrationTest
```
Which runs:
```
app/main-app/src/integration-test/groovy/org/grails/debug/RoutesTest.groovy
```
And of course fails as mentioned. While currently knowing this I can work around the issue, though I presume this painstakingly hard scenario to create with a sample project may be helpful in resolving such a bug, should it exists in grails-core. Thanks so much for the great work!
