### ISSUE TITLE
Controller include in notFound.gsp produces StackOverflowError

### ISSUE THREAD

**Issue by sascharitter** [grails/grails-core#10149]
### Steps to Reproduce

1. Create new app
2. Create a new controller
3. Include the controller in notFound.gsp via `<g:include />`
4. Call an URL that results in 404

### Expected Behaviour

The controller action should be executed and the result included in the HTML.

### Actual Behaviour

The app gets stuck in a loop and produces StackOverflowErrors.

    ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet grailsDispatcherServlet threw exception
    java.lang.StackOverflowError: null
        at D__grails_3_controller_include_grails_app_views_notFound_gsp$_run_closure1.doCall(D__grails_3_controller_include_grails_app_views_notFound_gsp:22)
        at D__grails_3_controller_include_grails_app_views_notFound_gsp.run(D__grails_3_controller_include_grails_app_views_notFound_gsp:31)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:193)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at D__grails_3_controller_include_grails_app_views_notFound_gsp$_run_closure2.doCall(D__grails_3_controller_include_grails_app_views_notFound_gsp:35)
        at D__grails_3_controller_include_grails_app_views_notFound_gsp.run(D__grails_3_controller_include_grails_app_views_notFound_gsp:40)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:193)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at D__grails_3_controller_include_grails_app_views_notFound_gsp$_run_closure2.doCall(D__grails_3_controller_include_grails_app_views_notFound_gsp:35)
        at D__grails_3_controller_include_grails_app_views_notFound_gsp.run(D__grails_3_controller_include_grails_app_views_notFound_gsp:40)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:193)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        ...

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.1.11
- **JDK Version:** 1.7.0_75

### Example Application

[controller-include-bug-report-13092016.zip](https://github.com/grails/grails-core/files/469996/controller-include-bug-report-13092016.zip)

**Comment by sascharitter** [comment]
Since there seems to be a bug using the command `grails bug-report` ("gradle.properties" is not packaged in the ZIP-file) I recreated the example project using the latest Grails version 3.2.0: https://github.com/sascharitter/grails-issue-controller-include
