### ISSUE TITLE
grails 3.1.10 doesn't render view templates scaffolded

### ISSUE THREAD

**Issue by milanwebdev** [grails/grails-core#10187]
Playing with Grails 3.* with longer experience in version 2 and able to render custom view templates stored in scaffolding and called by main.gsp via <g:render tag.

### Steps to Reproduce

1. create a template src/main/templates/scaffolding/_pippo.gsp

2. add it in main.gsp via `<g:render template="pippo"/>`

### Expected Behaviour

Page _pippo.gsp rendered in any controller without the need to put it directly in each views folder.

### Actual Behaviour

Calling for example the controller /user/listAjax  we got the "Template not found for name [pippo] " with the following stacktrace:

`ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error applying layout : main] with root cause
org.grails.taglib.GrailsTagException: [views/layouts/main.gsp:157] [views/layouts/main.gsp:155] Template not found for name [pippo] and path [/user/_pippo.gsp]
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp$_run_closure2.doCall(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:170)
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp.run(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:241)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at java.lang.Thread.run(Thread.java:722)
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet grailsDispatcherServlet threw exception
org.grails.taglib.GrailsTagException: [views/layouts/main.gsp:161] [views/layouts/main.gsp:159] Template not found for name [pippo] and path [/user/_pippo.gsp]
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp$_run_closure2.doCall(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:179)
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp.run(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:241)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at java.lang.Thread.run(Thread.java:722)
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] - Exception Processing ErrorPage[errorCode=500, location=/error]
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error applying layout : main
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:979)
                at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
                at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:468)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
                at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:442)
                at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:301)
                at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:396)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:176)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
                at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:722)
Caused by: org.grails.gsp.GroovyPagesException: Error applying layout : main
                at org.grails.web.servlet.view.GroovyPageView.rethrowRenderException(GroovyPageView.java:187)
                at org.grails.web.sitemesh.SpringMVCViewDecorator.render(SpringMVCViewDecorator.java:78)
                at org.grails.web.sitemesh.GrailsLayoutView.renderTemplate(GrailsLayoutView.java:67)
                at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
                at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
                at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
                at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1246)
                at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1029)
                at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:973)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
                ... 25 common frames omitted
Caused by: org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/layouts/main.gsp:161] [views/layouts/main.gsp:159] Template not found for name [pippo] and path [/user/_pippo.gsp]
                at org.grails.web.servlet.view.GroovyPageView.createGroovyPageException(GroovyPageView.java:135)
                at org.grails.web.servlet.view.GroovyPageView.handleException(GroovyPageView.java:112)
                at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:80)
                at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
                at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
                at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
                at org.grails.web.sitemesh.SpringMVCViewDecorator.render(SpringMVCViewDecorator.java:69)
                ... 34 common frames omitted
Caused by: org.grails.taglib.GrailsTagException: [views/layouts/main.gsp:161] [views/layouts/main.gsp:159] Template not found for name [pippo] and path [/user/_pippo.gsp]
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp$_run_closure2.doCall(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:179)
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp.run(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:241)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                ... 1 common frames omitted
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet grailsDispatcherServlet threw exception
org.grails.taglib.GrailsTagException: [views/layouts/main.gsp:161] [views/layouts/main.gsp:159] Template not found for name [pippo] and path [//_pippo.gsp]
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp$_run_closure2.doCall(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:179)
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp.run(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:241)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at java.lang.Thread.run(Thread.java:722)
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] - Exception Processing ErrorPage[errorCode=404, location=/error]
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error applying layout : main
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:979)
                at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
                at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:468)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
                at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:442)
                at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:301)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:178)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
                at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:722)
Caused by: org.grails.gsp.GroovyPagesException: Error applying layout : main
                at org.grails.web.servlet.view.GroovyPageView.rethrowRenderException(GroovyPageView.java:187)
                at org.grails.web.sitemesh.SpringMVCViewDecorator.render(SpringMVCViewDecorator.java:78)
                at org.grails.web.sitemesh.GrailsLayoutView.renderTemplate(GrailsLayoutView.java:67)
                at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
                at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
                at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
                at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1246)
                at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1029)
                at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:973)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
                ... 24 common frames omitted
Caused by: org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/layouts/main.gsp:161] [views/layouts/main.gsp:159] Template not found for name [pippo] and path [//_pippo.gsp]
                at org.grails.web.servlet.view.GroovyPageView.createGroovyPageException(GroovyPageView.java:135)
                at org.grails.web.servlet.view.GroovyPageView.handleException(GroovyPageView.java:112)
                at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:80)
                at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
                at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
                at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
                at org.grails.web.sitemesh.SpringMVCViewDecorator.render(SpringMVCViewDecorator.java:69)
                ... 33 common frames omitted
Caused by: org.grails.taglib.GrailsTagException: [views/layouts/main.gsp:161] [views/layouts/main.gsp:159] Template not found for name [pippo] and path [//_pippo.gsp]
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp$_run_closure2.doCall(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:179)
                at C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp.run(C__svn_CIBIT_LAPPS_groovy_IdeaProjects_test_grails_app_views_layouts_main_gsp:241)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                ... 1 common frames omitted
`

On the contrary, storing the template _pippo.gsp directly in views/user/ the template is resolved.

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.1.10
- **JDK Version:** 1.7.21
- **Container Version (If Applicable):** embedded in grails

**Comment by jeffbrown** [comment]
The project at https://github.com/jeffbrown/issue10187 demonstrates one way to manage this.

See the following:

https://github.com/jeffbrown/issue10187/blob/f735659f584de723ccacb035b3218e5088c731ea/grails-app/views/templates/_pippo.gsp

https://github.com/jeffbrown/issue10187/blob/f735659f584de723ccacb035b3218e5088c731ea/grails-app/views/layouts/main.gsp#L39

**Comment by jeffbrown** [comment]
I think this is probably not a bug and maybe accidentally used to behave differently.  @milanwebdev do you know if there are docs that suggest that the system should behave as you described above with templates under `src/main/templates/scaffolding/`?  Separate question, is there any reason that defining them under `grails-app/views/` as I did in the sample above might be problematic?

Thanks for your feedback.  We appreciate it.

**Comment by milanwebdev** [comment]
Honestly I don't have a doc reference to this point but in Grails 2.0.* version we have some "template gsp" (meaning they have the underscore prefix) in ` src/main/templates/scaffolding/ ` that are rendered "on the fly" like other non-template gsp.
Basically I have always though "templates gsp" (like `_pippo.gsp`) and "normal gsp" (like `index.gsp`) behave in the same way from the scaffold perspective.

The way you suggest is feasible but of course it is needed to generate views without taking advantage of the runtime rendering.

**Comment by jeffbrown** [comment]
I think the templates in `src/main/templates/scaffolding/` are intended to be the templates that the scaffolding uses for runtime generated artifacts (views, controllers, tests, etc...), which is different than GSP templates, which are just page fragments.  I don't think runtime view rendering should resolve GSP templates from `src/main/templates/scaffolding/`.  Maybe the fact that they are both "templates" has caused some confusion, but I think those are different things.

**Comment by milanwebdev** [comment]
Clear. Then I probably misunderstood a bit the matter.

Thank you for your support

**Comment by khausam** [comment]
I realize I'm a year and a half late on this discussion, but just wanted to make the case that the functionality should be restored to the way it was in grails 2 for the sole purpose of DRY principals. 

* GSP templates (hereafter referred to as a partials) exist to abstract out common view code across multiple views. A great example is _form.gsp used by both create.gsp and edit.gsp
* Dynamic scaffolding exists to avoid having to either 1) Regenerate all of the files each time an edit is made, or 2) Manually edit all of the generated files.

90% of my _form.gsp partial code can be handled via a scaffolded _form.gsp. The other 10% are custom and are defined in their respective view folders. So in grails 2, if I need to make an edit to the 90%, I would simply edit /templates/scaffolding/_form.gsp. Done. In grails 3, I will need to edit /templates/scaffolding/_form.gsp, regenerate all _form.gsp into their respective view folders, and then restore the 10% that are custom back to their original form. Not impossible, but it feels like we're regressing, not progressing. Maybe most importantly, is there any advantage to the grails 3 behavior vs. grails 2 behavior that I am overlooking? 

Thank you for indulging my rant.
