### ISSUE TITLE
Grails 3.1.10  - Issue with binding single ended associations by .id

### ISSUE THREAD

**Issue by kalpanaDasireddy** [grails/grails-core#10186]
I'm migrating grails application from 2.2.3 to 3.1.10. Id is not mapped to object for single ended associations
Example application to replicate the issue can be found in 
https://github.com/kalpanaDasireddy/Grails3Migration
Steps to reproduce:
Start the webapp and go to url 
http://localhost:8080/item/create
It fails  with error 
Exception grails.validation.ValidationException: Validation Error(s) occurred during save(): - Field error in object 'Item' on field 'status': rejected value [null]; codes [Item.status.nullable.error.Item.status,Item.status.nullable.error.status,Item.status.nullable.error.Status,Item.status.nullable.error,item.status.nullable.error.Item.status,item.status.nullable.error.status,item.status.nullable.error.Status,item.status.nullable.error,Item.status.nullable.Item.status,Item.status.nullable.status,Item.status.nullable.Status,Item.status.nullable,item.status.nullable.Item.status,item.status.nullable.status,item.status.nullable.Status,item.status.nullable,nullable.Item.status,nullable.status,nullable.Status,nullable]; arguments [status,class Item]; default message [Property [{0}] of class [{1}] cannot be null]

Item.groovy
public class Item
{
	Status status

	static constraints = {
		status nullable:false
	}
}

ItemController.groovy

class ItemController {

	def create()
	{
		Item item

		try 
		{
			**item = new Item(['status.id':1])**
			item.save(failOnError:true)
		}
		catch(Exception e) {
			e.printStackTrace()
			render "Exception ${e}"

		}
	
	}
}

If I change the highlighted line to 

item = new Item(['status.id':1, status:[id:1]), it works.

Expected it to work with 
item = new Item(['status.id':1]) 
as it was working in previous version grails (2.2.3)

**Comment by graemerocher** [comment]
We have an ISSUE_TEMPLATE for a reason, please follow it and provide all of the requested information including a sample application that reproduces the issue.

See https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

**Comment by kalpanaDasireddy** [comment]
Stacktrace:
grails.validation.ValidationException: Validation Error(s) occurred during save(
):
- Field error in object 'Item' on field 'status': rejected value [null]; codes [Item.status.nullable.error.Item.status,Item.status.nullable.error.status,Item.st
atus.nullable.error.Status,Item.status.nullable.error,item.status.nullable.error
.Item.status,item.status.nullable.error.status,item.status.nullable.error.Status
,item.status.nullable.error,Item.status.nullable.Item.status,Item.status.nullabl
e.status,Item.status.nullable.Status,Item.status.nullable,item.status.nullable.I
tem.status,item.status.nullable.status,item.status.nullable.Status,item.status.n
ullable,nullable.Item.status,nullable.status,nullable.Status,nullable]; argument
s [status,class Item]; default message [Property [{0}] of class [{1}] cannot be
null]

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
        at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1717)
        at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1534)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeConstructorOf(InvokerHelper.java:954)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.newInstance(DefaultGroovyMethods.java:15645)
        at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:131)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper$save.call(Unknown Source)
        at Item.save(Item.groovy)
        at Item.save(Item.groovy)
        at org.grails.datastore.gorm.GormEntity$save.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at ItemController$$EPyBQZG5.create(ItemController.groovy:10)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReloadedTypeInvoker$2.invoke(ReloadedTypeInvoker.java:133)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1461)
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:210)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:281)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:115)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by kalpanaDasireddy** [comment]
It works with map ['status':1] aswell.

**Comment by jeffbrown** [comment]
You have the following in the sample app:

    item = new Item(['status.id':1])

If you change that to this, I think it works:

    item = new Item([status: [id: 1]])

If you change it to something like this:

    item = new Item([status: [id: 1]])

Then that will work with a request like http://localhost:8080/item/create?status.id=1.

**Comment by kalpanaDasireddy** [comment]
Yes. But just like in the example given, data for binding is not populated from the http request but in the controller or service class.
