### ISSUE TITLE
Unable to build from brand new app : Failed to apply plugin [id 'org.gradle.war']

### ISSUE THREAD

**Issue by bdbogjoe** [grails/grails-core#10193]
### Steps to Reproduce

* create new app using : `grails create-app test`
* `cd test`
* `gradle build`

### Expected Behaviour

The build should work

### Actual Behaviour

The build failed

**Error :** 
`What went wrong:
A problem occurred evaluating root project 'test'.
  Failed to apply plugin [id 'org.gradle.war']
    Cannot execute null+file collection`
**Exception :** 

`
Caused by: java.lang.NullPointerException: Cannot execute null+file collection
        at org.grails.gradle.plugin.web.gsp.GroovyPagePlugin$_apply_closure5.doCall(GroovyPagePlugin.groovy:66)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:136)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:519)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:76)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:172)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:166)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:100)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:79)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:97)
        at org.gradle.api.plugins.WarPlugin.apply(WarPlugin.java:74)
        at org.gradle.api.plugins.WarPlugin.apply(WarPlugin.java:38)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
        ... 68 more
`

### Environment Information

- **Operating System**: linux
- **Grails Version:** 3.2.0
- **JDK Version:** 1.8.0_102

**Comment by graemerocher** [comment]
You're using an older version of Gradle that is incompatible with Grails 3.2.0

What version of Gradle are you using?

**Comment by bdbogjoe** [comment]
gradle -version

------------------------------------------------------------
Gradle 3.0
------------------------------------------------------------

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Linux 4.1.13-100.fc21.x86_64 amd64

**Comment by bdbogjoe** [comment]
works fine with 

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Linux 4.1.13-100.fc21.x86_64 amd64

**Comment by graemerocher** [comment]
Interesting, works fine for me with Gradle 3.0... most be something environment specific

**Comment by jeffbrown** [comment]
Does the problem also happen when using the default generated `gradlew`?

**Comment by jeffbrown** [comment]
I can't reproduce on OS X.
