### ISSUE TITLE
Validators are not executed in unit test (String-based queries like [executeQuery] are currently not supported in this implementation of GORM)

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10200]
After upgrading to Grails 3.2 [](https://github.com/saw303/grails-issues) I found a problem with a unit test that uses in memory database support.

When I use the annotation `TestFor` the specified domain field validation are working as expected but the String-based queries are not supported.

```
java.lang.UnsupportedOperationException: String-based queries like [executeQuery] are currently not supported in this implementation of GORM. Use criteria instead.

    at org.grails.datastore.gorm.GormStaticApi.unsupported(GormStaticApi.groovy:1124)
    at org.grails.datastore.gorm.GormStaticApi.executeQuery(GormStaticApi.groovy:1028)
    at org.grails.datastore.gorm.GormStaticApi.executeQuery(GormStaticApi.groovy:1024)
    at org.grails.datastore.gorm.GormEntity$Trait$Helper.executeQuery(GormEntity.groovy:1030)
    at grails.issues.Season.between(Season.groovy:64)
    at grails.issues.SeasonSpec.Find all season between #aDate and #bDate(SeasonSpec.groovy:49)
```` 

If I remove the `TestFor` annotation the behaviour changes the other way around. Validation does not work but the String-based queries are supported.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Check out [example](https://github.com/saw303/grails-issues)
2. Run this [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/SeasonWithoutTestForSpec.groovy#L24)
3. This [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/SeasonSpec.groovy#L26) works as expected since it uses the `TestFor` annotation

### Expected Behaviour

The validator should be called in a unit test in any case. With or without the using the `TestFor` annotation. executeQuery operations should be supported.

### Actual Behaviour

If I remove the `TestFor` annotation the validator does not get called but executeString operations are supported.

### Environment Information

- **Operating System**: OSX 10.11.6
- **Grails Version:** 3.2
- **JDK Version:** 1.8.0_102

### Example Application

- [Example](https://github.com/saw303/grails-issues) application

**Comment by saw303** [comment]
This one does not seems to be fixed in Grails 3.2.1. The following [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/SeasonSpec.groovy#L34) still fails if you use `@TestFor.
