### ISSUE TITLE
Unit testing services with Hibernate is broken

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10201]
Using @TestFor in Grails 3.2 and Gorm 6 seems to break unit testing completely.

The following test code 

```
@TestFor(SeasonService)
class SeasonServiceSpec extends HibernateSpec {

    @Override
    List<Class> getDomainClasses() {
        [Season]
    }

    void "Find all seasons"() {

        when:
        List<Season> seasons = service.findAll()

        then:
        seasons.size() == 0
    }
}
```
fails with the that exception:

```
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread

	at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:274)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:230)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:187)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:110)
	at org.grails.orm.hibernate.HibernateGormStaticApi.list(HibernateGormStaticApi.groovy:70)
	at org.grails.orm.hibernate.HibernateGormStaticApi.list(HibernateGormStaticApi.groovy:69)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.list(GormEntity.groovy:654)
	at grails.issues.SeasonService.$tt__findAll(SeasonService.groovy:10)
	at grails.issues.SeasonService.findAll_closure1(SeasonService.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at grails.issues.SeasonServiceSpec.Find all seasons(SeasonServiceSpec.groovy:20)
```
### Steps to Reproduce

1. Clone [project](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/SeasonServiceSpec.groovy#L10)
2. Run [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/SeasonServiceSpec.groovy#L10) 

### Expected Behaviour

Should work as in Grails 3.1 and below

### Actual Behaviour

@TestFor brakes quite a lot in unit testing environment

### Environment Information

- **Operating System**: OSX 10.11.6
- **Grails Version:** 3.2
- **JDK Version:** 1.8.0_102

### Example Application

- see step 1 in _steps to reproduce_

**Comment by graemerocher** [comment]
This can be worked around by adding:

```groovy
    PlatformTransactionManager getTransactionManager() {
        super.getTransactionManager()
    }
```

To the unit test

**Comment by saw303** [comment]
This does not work if your test class extends `HibernateSpec`. There is no `getTransactionManager()` on `HibernateSpec`.

**Comment by graemerocher** [comment]
yes there is https://github.com/grails/gorm-hibernate5/blob/master/grails-plugin/src/main/groovy/grails/test/hibernate/HibernateSpec.groovy#L23

**Comment by saw303** [comment]
I'm sorry.... of course there is that getter method.
