### ISSUE TITLE
Grails 3.2.0 not working behind proxies!

### ISSUE THREAD

**Issue by aadrian** [grails/grails-core#10211]
Grails 3.2.0 does not seem to work behind corporate proxies :(.
On the same machines, Grails 2.x various sub-versions work without problems, by making use of the ```$home/.grails/ProxySettings.groovy``` file.

Each version from Grails 2.x will create in ```$home/.grails/``` a sub-directory with the version number, but Grails 3 does not seem to create it.

**None** of the commands except ```grails --version``` seems to work, even ```grails --help``` will show an error. 

### Stacktrace
On machines with German locale, the following stacktrace is displayed:
```
c:\work\trials_grails>grails --stacktrace
Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
Resolving dependencies..
| Error Error occurred running Grails CLI: Dies ist normalerweise ein zeitweiliger Fehler bei der Aufl÷sung vo
n Hostnamen. Grund ist, dass der lokale Server keine R³ckmeldung vom autorisierenden Server erhalten hat (NOTE
: Stack trace has been filtered. Use --verbose to see entire trace.)
java.net.UnknownHostException: Dies ist normalerweise ein zeitweiliger Fehler bei der Aufl÷sung von Hostnamen.
 Grund ist, dass der lokale Server keine R³ckmeldung vom autorisierenden Server erhalten hat
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOp
erator.java:278)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOpe
rator.java:162)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:287)
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:243)
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryCo
nnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector
.java:350)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryC
onnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.j
ava:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.j
ava:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.ja
va:223)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescrip
torReader.java:320)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(Default
ArtifactDescriptorReader.java:217)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(Default
DependencyCollector.java:535)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDepe
ndencyCollector.java:519)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyColl
ector.java:409)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyColl
ector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java
:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCo
llector.java:254)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySyste
m.java:341)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:302)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:284)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:276)
        at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:53)
        at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:49)
        at org.grails.cli.profile.repository.MavenProfileRepository.<init>(MavenProfileRepository.groovy:53)
        at org.grails.cli.GrailsCli.createMavenProfileRepository(GrailsCli.groovy:333)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:234)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Error occurred running Grails CLI: Dies ist normalerweise ein zeitweiliger Fehler bei der Aufl÷sung vo
n Hostnamen. Grund ist, dass der lokale Server keine R³ckmeldung vom autorisierenden Server erhalten hat
```

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.0
- **JDK Version:**  1.8.0_51

**Comment by jeffbrown** [comment]
Have you setup proxy settings in `~/.gradle/gradle.propertis`?

An example from https://docs.gradle.org/current/userguide/build_environment.html:

    systemProp.http.proxyHost=www.somehost.org
    systemProp.http.proxyPort=8080
    systemProp.http.proxyUser=userid
    systemProp.http.proxyPassword=password
    systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost

**Comment by aadrian** [comment]
> Have you setup proxy settings in ~/.gradle/gradle.properties?

Of course. Gradle (3.1, so the lastest) is working on the same machines without problems (since it's used by other projects too).

**Comment by jeffbrown** [comment]
> Of course.

Right. My mistake.

**Comment by jeffbrown** [comment]
> Each version from Grails 2.x will create in $home/.grails/ a sub-directory with the version number, but Grails 3 does not seem to create it.

That is expected.

**Comment by aadrian** [comment]
> That is expected.

Anything else I could run/test to give you more feedback in order to be able to reproduce/fix the problem?

**Comment by graemerocher** [comment]
You have to pass these same properties to the `grails` command:

```
grails -Dhttp.proxyHost=www.somehost.org -Dhttp.proxyPort=8080 -Dhttp.proxyUser=userid -Dhttp.proxyPassword=password -Dhttp.nonProxyHosts=*.nonproxyrepos.com|localhost
```

**Comment by aadrian** [comment]
> You have to pass these same properties to the grails command:

If I try to pass the proxy settings to Grails directly (instead of Grails picking them from the config), the error is still the same as above. As if some new parts of Grails (Aether?) is ignoring them :(.

**Comment by graemerocher** [comment]
If there is a problem it would be here. By default Aether is configured to use `JreProxySelector`:

https://github.com/eclipse/aether-core/blob/master/aether-util/src/main/java/org/eclipse/aether/util/repository/JreProxySelector.java#L49

The behavior of this implementation is described here:

https://github.com/eclipse/aether-core/blob/master/aether-util/src/main/java/org/eclipse/aether/util/repository/JreProxySelector.java#L31

On windows systems it seems you may need to pass `-Djava.net.useSystemProxies=true` it seems.

If you are having issues try attach a debugger to the `grails` process by using 

```
export GRAILS_OPTS=-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005
```

And setting a break point on https://github.com/eclipse/aether-core/blob/master/aether-util/src/main/java/org/eclipse/aether/util/repository/JreProxySelector.java#L49

**Comment by ilopmar** [comment]
I've setup a local proxy (tinyproxy) on my laptop to test this issue. This is the content of my `~/.gradle/gradle.properties` file:

```
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=8888
#systemProp.http.proxyUser=userid
#systemProp.http.proxyPassword=password
systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost

systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=8888
#systemProp.https.proxyUser=userid
#systemProp.https.proxyPassword=password
systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost
```

If I don't start the proxy this is the log. You can see that grails is trying to connect my local proxy (127.0.0.1:8888):

```
$ grails --stacktrace
| Resolving Dependencies. Please wait...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'asd'.
> Could not resolve all dependencies for configuration ':runtime'.
   > Could not determine artifacts for org.grails:grails-dependencies:3.2.0
      > Could not get resource 'https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.2.0/grails-dependencies-3.2.0.jar'.
         > Could not HEAD 'https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.2.0/grails-dependencies-3.2.0.jar'.
            > Connect to 127.0.0.1:8888 [/127.0.0.1] failed: Connection refused

Total time: 5.133 secs
| Error Error initializing classpath: Connection refused (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.net.ConnectException: Connection refused
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:388)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:102)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:79)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:70)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRawHead(HttpClientHelper.java:50)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHead(HttpClientHelper.java:54)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.getMetaData(HttpResourceAccessor.java:85)
	at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.getMetaData(DefaultExternalResourceConnector.java:63)
	at org.gradle.internal.resource.transport.DefaultExternalResourceRepository.getResourceMetaData(DefaultExternalResourceRepository.java:68)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.staticResourceExists(DefaultExternalResourceArtifactResolver.java:69)
	...
	...
```

But If I start the proxy it works:

```
$ grails --stracktrace
| Resolving Dependencies. Please wait...
Download https://repo.grails.org/grails/core/org/grails/grails-plugin-gsp/3.2.0/grails-plugin-gsp-3.2.0.pom
Download https://repo.grails.org/grails/core/org/grails/grails-plugin-services/3.2.0/grails-plugin-services-3.2.0.pom
Download https://repo.grails.org/grails/core/org/grails/grails-plugin-url-mappings/3.2.0/grails-plugin-url-mappings-3.2.0.pom
...
```

And in the proxy's logs:

```
CONNECT   Oct 11 12:41:00 [15657]: Request (file descriptor 9): CONNECT repo.grails.org:443 HTTP/1.1
INFO      Oct 11 12:41:00 [15657]: No upstream proxy for repo.grails.org
CONNECT   Oct 11 12:41:00 [15657]: Established connection to host "repo.grails.org" using file descriptor 10.
...
```

@aadrian can you double-check your proxy configuration in the file `~/.gradle/gradle.properties`?

**Comment by aadrian** [comment]
> can you double-check your proxy configuration in the file ~/.gradle/gradle.properties?

Yes, it's correct, and Gradle is working. Several Gradle (3.1) based projects work here without problems, fetch dependencies, etc.

On the same machines, other tools that work with the same settings (but different from tool to tool):
- nodeJS, NPM, Bower
- Git, wget, curl
- Maven, Leiningen, Ruby

> On windows systems it seems you may need to pass -Djava.net.useSystemProxies=true it seems

@graemerocher  With this setting none of the Java based tools are working (Eclipse, IntelliJ, ANT, etc.), hence the need to directly specify a proxy. This is a old but known windows/java problem with WPAD :(.

**Comment by aadrian** [comment]
> can you double-check your proxy configuration in the file ~/.gradle/gradle.properties?

Using https://technet.microsoft.com/en-US/sysinternals/processmonitor.aspx (replacement for the old FileMonitor) and filtering the Path property on ```gradle.properties``` is visible that:

 - calling ```gradle help```, the ```java.exe``` process will access the ```$home/.gradle/gradle.properties``` file
 - calling ```grails help```, **no process** will try to access that file

So Grails 3.2.0 does not seem to make use of the installed (and working) Gradle (nor their config files) at all :(.

**Comment by graemerocher** [comment]
There are 2 things here, one is Gradle, that is separate to the `grails` command the CLI. I was able to pass the proxy settings onto the `grails` CLI using 

```
export GRAILS_OPTS=-Dhttps.proxyHost=www.somehost.org -Dhttps.proxyPort=8080 -Dhttps.proxyUser=userid -Dhttps.proxyPassword=password 
```

On Windows this would be specified in the environment variables

**Comment by testorubel** [comment]
You are still going to have issues with cross cutting concern and not sharing your I/O data across your distributed architecture due to your binding of communication logic with business logic. You have to abstract you communication data/logic from business logic so that you can synchronize it in a distributed architecture.

http://www.slideshare.net/bobdobbes/io-state-in-distributed-api-architecture

**Comment by testorubel** [comment]
shall we escalate or shall we resolve?

**Comment by aadrian** [comment]
> There are 2 things here, one is Gradle, that is separate to the grails command the CLI.

Good to know :) . I haven't seen to be mentioned that there are 2 things that need 2 separate configurations starting with Grails 3.2.0

> export GRAILS_OPTS=-Dhttps.proxyHost=www.somehost.org -Dhttps.proxyPort=8080 -Dhttps.proxyUser=userid -Dhttps.proxyPassword=password 
> On Windows this would be specified in the environment variables

I'm specifying this in ```bin/grails.bat``` L16 with (with the correct proxy values):
```set GRAILS_OPTS=-Dhttps.proxyHost=www.somehost.org -Dhttps.proxyPort=8080 -Dhttps.proxyUser=userid -Dhttps.proxyPassword=password```

and also echo it L68 with:
```echo "%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRAILS_OPTS%  -classpath "%CLASSPATH%" org.grails.cli.GrailsCli %CMD_LINE_ARGS%```

to be sure that it's passed correctly.

Still has no effect :(.

However, if I build Grails 3.2.0 from sources, on the same machines with ```gradlew install -x groovydoc -x javadoc```, and set the ```GRAILS_HOME``` to it, the ```grails help``` command will work without further settings (as opposed to the official distribution that is throwing the exception even for ```grails help``` ). 

```grails create-app myapp``` will still fail however, with the mentioned error message :( .

**Comment by graemerocher** [comment]
So I setup squid with HTTP basic auth enabled. I then set the following environment variable:

```
export GRAILS_OPTS="-Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3128 -Dhttp.proxyUser=test -Dhttp.proxyPassword=test"
```

Grails successfully authenticated.

**Comment by graemerocher** [comment]
I have added documentation on this subject https://github.com/grails/grails-doc/commit/5f1bb09b6e02d3a07fce82a74f4dff7ec6a0e618

As far as I can see there is no bug here, simply a matter of getting the configuration right.

**Comment by aadrian** [comment]
> As far as I can see there is no bug here, simply a matter of getting the configuration right.

I don't agree :( . With Grails 2.x everything was working correctly (platform independent) and it was fetching the proxy settings from ```$home/.grails/ProxySettings.groovy```.

Grails 3.x just seems to be totally incompatible with Grails 2.x without a reason: for proxy settings too :( .

**Comment by graemerocher** [comment]
The way you configure the CLI differs that we can agree on, but as far as I can tell via environment variables it is possible to configure Grails 3 to work behind a proxy. Or are you saying that it is not true?

**Comment by aadrian** [comment]
>  Or are you saying that it is not true? 

Exactly, it's not working with env variables for Grails 3.2.0 behind wpad proxies (something most big companies have). The previous versions - 2.x (without env variables) were working.

**Comment by graemerocher** [comment]
Not sure what I can suggest in that case. For me it works fine with a squid proxy and the configuration mentioned.

**Comment by aadrian** [comment]
> Not sure what I can suggest in that case.

Can't we have the ```$home/.grails/ProxySettings.groovy``` functionality back? It was working without problems.

**Comment by graemerocher** [comment]
1. Grails 2 used Ivy whilst Grails 3 uses Aether to resolve dependencies so the implementations are different
2. Even if we parsed `$home/.grails/ProxySettings.groovy`, all we would do then is set the various system properties (`https.proxyHost` etc.), so the net effect would be exactly the same as if they were specified in `GRAILS_OPTS`

So what is being debated here is if there is any benefit from having a platform neutral way (in Grails 2 `ProxySettings`) to specify these system properties that doesn't rely on setting environment variables. So far I don't see any benefit, it just seems like duplicating functionality and all it would do is slow down the CLI.

**Comment by graemerocher** [comment]
For reference http://stackoverflow.com/questions/29740737/grails-3-0-1-proxy-settings

**Comment by lalitvchau** [comment]
This error to due to maven was installed in you system..

follow the below steps 
1. delete the c:\Users\.m2 or related directory in windows (Not sure about Unix or Mac but you can find the local cache of maven. Delete .m2 directory) 
2. delete maven related environment variable. 
3. delete ./gradlew 
4. delete environment variable related to groovy also

try to above step.. it will work fine

**Comment by igorrosenberg** [comment]
Thanks @lalitvchau for the hint: 

```
set MAVEN_HOME=
```

Totally at lost why, but it helped me _unset_ the proxy I no longer required
