### ISSUE TITLE
Grails 3.2.1 application deployed Tomcat 7 and 8.5 fails creating data

### ISSUE THREAD

**Issue by jknudsen** [grails/grails-core#10248]
After upgrading from 3.2.0  to 3.2.1 (moved the BootStrap to a package now and updated the Hibernate dependency).  Now I can no longer create data and other DB actions after deploying to a Tomcat container.  I created a simple example that creates records in Bootstrap and fails when running on Tomcat 7 and 8.  When running with grails run-app or via the IDE in development the application runs great.  I reverted by to 3.2.0 (with the workaround to run on Tomcat) and moved the BootStrap back and things ran without issue again.  Something seems with the DB wiring is wrong when running on external Tomcat.

### Task List

- [ ] Try running the 3.2.1 war attached in Tomcat 7 or 8

### Steps to Reproduce

1. Try creating a war for the 3.2.1 application attached in Tomcat 7.0.64 or 8.5.5
2. Tried both SQL Server and H2 so example using H2

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.1
- **JDK Version:** 1.8.0_101
- **Container Version (If Applicable):** Tomcat-7.0.64-x64

### Example Application

[test321bug.zip](https://github.com/grails/grails-core/files/540350/test321bug.zip)

**Comment by jknudsen** [comment]
I do not see a web.xml include in the war.  Is web.xml required?  Here is an error I get from Tomcat 7 on startup:

WARNING: Unknown version string [3.1]. Default version will be used.

**Comment by jknudsen** [comment]
Here is a Stack Trace example.  I noticed I had 2 package with BootStraps and deleted the default BootStrap.groovy and left the one in the testdisrupt package and the issue persists.

`SEVERE: ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngin
e[Catalina].StandardHost[localhost].StandardContext[/test321bug-0.1]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase
.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:87
7)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)

        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095
)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:
1930)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.apache.tomcat.util.res.StringManager
.getManager(Ljava/lang/Class;)Lorg/apache/tomcat/util/res/StringManager;
        at org.apache.tomcat.websocket.WsWebSocketContainer.<clinit>(WsWebSocket
Container.java:77)
        at org.apache.tomcat.websocket.server.WsSci.init(WsSci.java:131)
        at org.apache.tomcat.websocket.server.WsSci.onStartup(WsSci.java:47)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContex
t.java:5506)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 10 more

Oct 19, 2016 5:19:43 PM org.apache.catalina.startup.HostConfig deployWAR
SEVERE: Error deploying web application archive C:\util\tomcat7Java8\webapps\tes
t321bug-0.1.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catal
ina.LifecycleException: Failed to start component [StandardEngine[Catalina].Stan
dardHost[localhost].StandardContext[/test321bug-0.1]]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase
.java:905)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:87
7)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)

        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095
)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:
1930)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by jeffbrown** [comment]
When I build a war from the project at https://github.com/jeffbrown/issue10248 and deploy that to Tomcat 8.5.5 on OS X I get the following: https://gist.github.com/jeffbrown/10d47551a46910262e47637656042c97

**Comment by graemerocher** [comment]
@jknudsen your error is likely because your `spring-boot-starter-tomcat` dependency is not specified as `provided` in your `build.gradle`

@jeffbrown your error is likely #10244 which containers a workaround for the issue.

**Comment by jknudsen** [comment]
Opps when you switch to provided you get an error like Jeff got.  I missed that trying to give a simple sample project.

**Comment by jknudsen** [comment]
Corrected the tomcat dependency.

[test321bug.zip](https://github.com/grails/grails-core/files/542027/test321bug.zip)

**Comment by jknudsen** [comment]
Switching version to 3.2.2.BUILD-SNAPSHOT solved my problem.  Thanks Jeff for providing a better error message!
