### ISSUE TITLE
Angular 2 initial tests failure

### ISSUE THREAD

**Issue by musketyr** [grails/grails-core#10241]
### Steps to Reproduce

1. Create new Angular2 application
2. Run tests `/gradew :client:test`

### Expected Behaviour

Initial tests should not fail.

### Actual Behaviour

The initial tests fails with:

```
hrome 53.0.2785 (Mac OS X 10.11.6) Component: Nav should create the app FAILED
        Error: Error in ./NavComponent class NavComponent - inline template:11:6 caused by: No provider for NgbDropdownConfig!
        Error: No provider for NgbDropdownConfig!
            at NoProviderError.Error (native)
            at NoProviderError.BaseError [as constructor] (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/facade/errors.js:24:0 <- src/test.ts:2714:34)
            at NoProviderError.AbstractProviderError [as constructor] (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_errors.js:42:0 <- src/test.ts:26509:16)
            at new NoProviderError (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_errors.js:73:0 <- src/test.ts:26540:16)
            at ReflectiveInjector_._throwOrNull (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:761:0 <- src/test.ts:42006:19)
            at ReflectiveInjector_._getByKeyDefault (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:789:0 <- src/test.ts:42034:25)
            at ReflectiveInjector_._getByKey (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:752:0 <- src/test.ts:41997:25)
            at ReflectiveInjector_.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:561:0 <- src/test.ts:41806:21)
            at TestBed.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/bundles/core-testing.umd.js:858:0 <- src/test.ts:8066:67)
            at ElementInjector.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/linker/element_injector.js:29:0 <- src/test.ts:42170:48)
        Expected undefined to be truthy.
            at webpack:///Users/ladin/development/sandbox/my-app/client/src/app/nav/nav.component.spec.ts:40:22 <- src/test.ts:46889:27
            at ZoneDelegate.invoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/zone.js:192:0 <- src/test.ts:63457:28)
            at AsyncTestZoneSpec.onInvoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/async-test.js:30:0 <- src/test.ts:37421:43)
            at ProxyZoneSpec.onInvoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/proxy.js:57:0 <- src/test.ts:38018:43)
Chrome 53.0.2785 (Mac OS X 10.11.6): Executed 4 of 6 (1 FAILED) (0 secs / 1.198 secs)
Chrome 53.0.2785 (Mac OS X 10.11.6) Component: Nav should create the app FAILED
        Error: Error in ./NavComponent class NavComponent - inline template:11:6 caused by: No provider for NgbDropdownConfig!
        Error: No provider for NgbDropdownConfig!
            at NoProviderError.Error (native)
            at NoProviderError.BaseError [as constructor] (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/facade/errors.js:24:0 <- src/test.ts:2714:34)
            at NoProviderError.AbstractProviderError [as constructor] (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_errors.js:42:0 <- src/test.ts:26509:16)
            at new NoProviderError (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_errors.js:73:0 <- src/test.ts:26540:16)
            at ReflectiveInjector_._throwOrNull (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:761:0 <- src/test.ts:42006:19)
            at ReflectiveInjector_._getByKeyDefault (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:789:0 <- src/test.ts:42034:25)
            at ReflectiveInjector_._getByKey (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:752:0 <- src/test.ts:41997:25)
            at ReflectiveInjector_.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:561:0 <- src/test.ts:41806:21)
            at TestBed.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/bundles/core-testing.umd.js:858:0 <- src/test.ts:8066:67)
            at ElementInjector.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/linker/element_injector.js:29:0 <- src/test.ts:42170:48)
        Expected undefined to be truthy.
            at webpack:///Users/ladin/development/sandbox/my-app/client/src/app/nav/nav.component.spec.ts:40:22 <- src/test.ts:46889:27
            at ZoneDelegate.invoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/zone.js:192:0 <- src/test.ts:63457:28)
            at AsyncTestZoneSpec.onInvoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/async-test.js:30:0 <- src/test.ts:37421:43)
Chrome 53.0.2785 (Mac OS X 10.11.6) Component: Nav should set applicationData on init FAILED
        Error: Error in ./NavComponent class NavComponent - inline template:11:6 caused by: No provider for NgbDropdownConfig!
        Error: No provider for NgbDropdownConfig!
            at NoProviderError.Error (native)
            at NoProviderError.BaseError [as constructor] (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/facade/errors.js:24:0 <- src/test.ts:2714:34)
            at NoProviderError.AbstractProviderError [as constructor] (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_errors.js:42:0 <- src/test.ts:26509:16)
            at new NoProviderError (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_errors.js:73:0 <- src/test.ts:26540:16)
            at ReflectiveInjector_._throwOrNull (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:761:0 <- src/test.ts:42006:19)
            at ReflectiveInjector_._getByKeyDefault (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:789:0 <- src/test.ts:42034:25)
            at ReflectiveInjector_._getByKey (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:752:0 <- src/test.ts:41997:25)
            at ReflectiveInjector_.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:561:0 <- src/test.ts:41806:21)
            at TestBed.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/bundles/core-testing.umd.js:858:0 <- src/test.ts:8066:67)
            at ElementInjector.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/linker/element_injector.js:29:0 <- src/test.ts:42170:48)
        TypeError: Cannot read property 'ngOnInit' of undefined
            at Object.<anonymous> (webpack:///Users/ladin/development/sandbox/my-app/client/src/app/nav/nav.component.spec.ts:44:14 <- src/test.ts:46892:18)
            at ZoneDelegate.invoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/zone.js:192:0 <- src/test.ts:63457:28)
            at ProxyZoneSpec.onInvoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/proxy.js:60:0 <- src/test.ts:38021:43)
            at ZoneDelegate.invoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/zone.js:191:0 <- src/test.ts:63456:34)
            at Zone.run (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/zone.js:85:0 <- src/test.ts:63350:43)
            at Object.<anonymous> (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/jasmine-patch.js:78:27 <- src/test.ts:37786:50)
            at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/jasmine-patch.js:106:0 <- src/test.ts:37814:42)
Chrome 53.0.2785 (Mac OS X 10.11.6): Executed 5 of 6 (2 FAILED) (0 secs / 1.541 secs)
Chrome 53.0.2785 (Mac OS X 10.11.6) Component: Nav should set applicationData on init FAILED
        Error: Error in ./NavComponent class NavComponent - inline template:11:6 caused by: No provider for NgbDropdownConfig!
        Error: No provider for NgbDropdownConfig!
            at NoProviderError.Error (native)
            at NoProviderError.BaseError [as constructor] (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/facade/errors.js:24:0 <- src/test.ts:2714:34)
            at NoProviderError.AbstractProviderError [as constructor] (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_errors.js:42:0 <- src/test.ts:26509:16)
            at new NoProviderError (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_errors.js:73:0 <- src/test.ts:26540:16)
            at ReflectiveInjector_._throwOrNull (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:761:0 <- src/test.ts:42006:19)
            at ReflectiveInjector_._getByKeyDefault (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:789:0 <- src/test.ts:42034:25)
            at ReflectiveInjector_._getByKey (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:752:0 <- src/test.ts:41997:25)
            at ReflectiveInjector_.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/di/reflective_injector.js:561:0 <- src/test.ts:41806:21)
            at TestBed.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/bundles/core-testing.umd.js:858:0 <- src/test.ts:8066:67)
            at ElementInjector.get (webpack:///Users/ladin/development/sandbox/my-app/client/~/@angular/core/src/linker/element_injector.js:29:0 <- src/test.ts:42170:48)
        TypeError: Cannot read property 'ngOnInit' of undefined
            at Object.<anonymous> (webpack:///Users/ladin/development/sandbox/my-app/client/src/app/nav/nav.component.spec.ts:44:14 <- src/test.ts:46892:18)
            at ZoneDelegate.invoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/zone.js:192:0 <- src/test.ts:63457:28)
            at ProxyZoneSpec.onInvoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/proxy.js:60:0 <- src/test.ts:38021:43)
            at ZoneDelegate.invoke (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/zone.js:191:0 <- src/test.ts:63456:34)
            at Zone.run (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/zone.js:85:0 <- src/test.ts:63350:43)
            at Object.<anonymous> (webpack:///Users/ladin/development/sandbox/my-app/client/~/zone.js/dist/jasmine-patch.js:78:27 <- src/test.ts:37786:50)
Chrome 53.0.2785 (Mac OS X 10.11.6): Executed 6 of 6 (2 FAILED) (1.817 secs / 1.563 secs)
```

- **Operating System**: 15.6.0 Darwin Kernel Version 15.6.0: root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
- **Grails Version:** 3.2.1
- **JDK Version:** 1.8.0_92-b14

### Example Application

- `grails create-app my-app --profile angular2`

**Comment by jameskleeh** [comment]
Change line 25 of `client/src/app/nav/nav.component.spec.ts` to `NgbModule.forRoot()`. Fixed in the profile
