### ISSUE TITLE
Angular 2 integration tests fails to compile

### ISSUE THREAD

**Issue by musketyr** [grails/grails-core#10240]
### Steps to Reproduce

1. Create new application with Angular 2 profile
2. Run ` ':client:integrationTest'.`

### Expected Behaviour

Gradle should start a test server, run Protractor tests and kill the test server again.

### Actual Behaviour

Gradle fails with following message

```
[02:48:00] I/launcher - Running 1 instances of WebDriver
[02:48:03] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
e2e/app.po.ts (1,38): Cannot find module 'protractor/globals'. (2307)
    at getOutput (/Users/ladin/development/sandbox/my-app/client/node_modules/ts-node/src/index.ts:258:17)
    at /Users/ladin/development/sandbox/my-app/client/node_modules/ts-node/src/index.ts:267:16
    at Object.compile (/Users/ladin/development/sandbox/my-app/client/node_modules/ts-node/src/index.ts:403:17)
    at loader (/Users/ladin/development/sandbox/my-app/client/node_modules/ts-node/src/index.ts:289:33)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/ladin/development/sandbox/my-app/client/node_modules/ts-node/src/index.ts:306:14)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ladin/development/sandbox/my-app/client/e2e/app.e2e-spec.ts:2:16)
[02:48:03] E/launcher - Process exited with error code 100
```

### Environment Information

- **Operating System**: 15.6.0 Darwin Kernel Version 15.6.0: root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
- **Grails Version:** 3.2.1
- **JDK Version:** 1.8.0_92-b14

### Example Application

- `grails create-app my-app --profile angular2`

**Comment by jameskleeh** [comment]
Change the first line in `client/e2e/app.po.ts` to `import { browser, element, by } from 'protractor';`

**Comment by musketyr** [comment]
works fine now :-) now you have to change this in the profile as well I guess :-)

**Comment by jameskleeh** [comment]
Fixed in the profile
