### ISSUE TITLE
Incorrect db connection management by Grails/Hibernate

### ISSUE THREAD

**Issue by gubespam** [grails/grails-core#10296]
This is an issue we ran into while attempting to upgrade from 2.x to 3.1.5.

### Steps to Reproduce

1. Spin up an instance of JBoss (Wildfly) with a datasource deployed to JNDI at [java:/MyDataSource]. This should be an XA datasource, though I am uncertain whether this matters. I have tested with Oracle, but I think this problem will likely happen with any backend database.
2. Build the attached sample application and deploy to the server

Note the entries in the resources.groovy file. This application uses JTA transaction management provided by the JBoss server. In our real application, we have multiple datasources, and thus our need for JTA/XA.

### Expected Behaviour
Application should deploy to app server without any issues.

### Actual Behaviour

During deployment/startup, an error like the following will occur:

    11-04 18:00:38,388 ERROR [org.jboss.as.web.deployment.JBossContextConfig] (ServerService Thread Pool -- 77) JBAS018202: Error calling onStartup for servlet container initializer: org.springframework.web.SpringServletContainerInitializer: org.hibernate.exception.GenericJDBCException: could not inspect JDBC autocommit mode
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
        at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.isAutoCommit(LogicalConnectionImpl.java:325)
        at org.hibernate.engine.transaction.internal.TransactionCoordinatorImpl.afterNonTransactionalQuery(TransactionCoordinatorImpl.java:199)
        at org.hibernate.internal.SessionImpl.afterOperation(SessionImpl.java:503)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1726)
        at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)
        at org.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder.invokeMethod(AbstractHibernateCriteriaBuilder.java:1687) [grails-datastore-gorm-hibernate-core-5.0.4.RELEASE.jar:]
        at org.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder.list(AbstractHibernateCriteriaBuilder.java:1558) [grails-datastore-gorm-hibernate-core-5.0.4.RELEASE.jar:]
        at org.grails.datastore.mapping.query.api.BuildableCriteria$list.call(Unknown Source)
        at com.app.service.SourceService.$tt__serviceMethod(SourceService.groovy:11)
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
        at com.app.service.SourceService$serviceMethod.call(Unknown Source)
        at BootStrap$_closure1.doCall(BootStrap.groovy:7)
        at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:437)
        at grails.util.Environment.executeForEnvironment(Environment.java:430)
        at grails.util.Environment.executeForCurrentEnvironment(Environment.java:406)
        at org.grails.web.servlet.boostrap.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:62)
        at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:65)
        at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:53)
        at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:240)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
        at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:149)
        at org.grails.boot.context.web.GrailsAppServletInitializer.createRootApplicationContext(GrailsAppServletInitializer.groovy:57)
        at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85)
        at org.jboss.as.web.deployment.JBossContextConfig.lifecycleEvent(JBossContextConfig.java:187)
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:163)
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:61)
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
    Caused by: java.sql.SQLException: Connection is not associated with a managed connection.org.jboss.jca.adapters.jdbc.jdk6.WrappedConnectionJDK6@6a574a5b
        at org.jboss.jca.adapters.jdbc.WrappedConnection.lock(WrappedConnection.java:155)
        at org.jboss.jca.adapters.jdbc.WrappedConnection.getAutoCommit(WrappedConnection.java:729)
        at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:376)
        at com.sun.proxy.$Proxy80.getAutoCommit(Unknown Source)
        at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:240)
        at com.sun.proxy.$Proxy80.getAutoCommit(Unknown Source)
        at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.isAutoCommit(LogicalConnectionImpl.java:322)
        ... 76 more

### Initial Analysis of Problem

After doing a lot of tracing, I figured out that the following seems to be happening:

1. In the first call to the service method, Hibernate opens a new database connection when Source.createCriteria().list() is called. One of the datasource layers provided by grails (either TransactionAwareDataSourceProxy or LazyConnectionDataSourceProxy) calls org.springframework.jdbc.datasource.doGetConnection(), which in turn calls TransactionSynchronizationManager.registerSynchronization(). This registers a listener for when the current transaction completes.
2. At the end of the first call to the service method, because the service is marked with `@Transactional`, the GrailsTransactionTemplate calls commit on the transaction. This causes a release/closure of the database connection opened above, due to the listener registered above.
3. During the second call to the service method, Hibernate reuses the connection it already has, which has been closed already due to the transaction listener above. 

So the problem seems to be either that a) Hibernate doesn't know the connection is closed (since Grails/Spring closed it) OR b) Grails/Spring shouldn't be closing the connection, since it was not the one who opened it in the first place.

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 3.1.5
- **JDK Version:** 8
- **Container Version (If Applicable):** N/A

### Example Application

- See attachment:
[new-app.zip](https://github.com/grails/grails-core/files/572948/new-app.zip)

**Comment by graemerocher** [comment]
Please state which version of Wildfly as there are many and behaviour differs between them

**Comment by graemerocher** [comment]
I followed the steps with JBoss 7.1 and Grails 3.2.3 snapshot and could not reproduce the issue

**Comment by gubespam** [comment]
We are actually using JBoss EAP 6.4.0. It [appears](http://stackoverflow.com/questions/37954144/what-is-the-wildfly-equivalent-of-jboss-eap-6-4) this might be close to the same as Wildfly 7.1.1

**Comment by gubespam** [comment]
I will see if changing to Grails 3.2.2 helps (I couldn't find any place to download the 3.2.3 snapshot binaries).

**Comment by gubespam** [comment]
I am not able to upgrade to Grails 3.2.2 at this time because it uses Hibernate 5, and EAP 6 appears to be incompatible with Hibernate 5, due (at least) to the version of jboss-logging that it uses.

Is Grails 3.2.2 compatible with Hibernate 4? I'm just wondering if I can switch to 4 and test, to try to isolate where the issue is.

**Comment by jameskleeh** [comment]
@gubespam http://gorm.grails.org/latest/hibernate/manual/index.html#hibernateVersions

**Comment by gubespam** [comment]
I created a new sample application from Grails 3.2.2 and added the same classes/etc. as described above, and switched to hibernate 4, using the information from the link James posted here. I am still receiving the same error.

**Comment by gubespam** [comment]
[This link from Red Hat](https://access.redhat.com/articles/112673#EAP_6) seems to indicate that EAP 6.4 is equivalent to Wildfly 7.5.0.

**Comment by graemerocher** [comment]
Will try on EAP 6.4.. thanks for the feedback

**Comment by gubespam** [comment]
I have decided to switch to running Grails 3.2.2 as a standalone application, outside of JBoss, in order to resolve this issue.

**Comment by graemerocher** [comment]
@gubespam please upgrade to 3.2.3 ;)
