### ISSUE TITLE
unable to resolve class in application.groovy

### ISSUE THREAD

**Issue by purpleraven** [grails/grails-core#10317]
Starting from grails 3.1.10 import of files in application.groovy not works
During upgrading from 3.1.9 to 3.1.10 I get error:

```
| Error Error occurred running Grails CLI: startup failed:
script1479231350405936681851.groovy: 1: unable to resolve class import com.xxx.XxxType
 @ line 1, column 1.
   import import com.xxx.XxxType
   ^

1 error
 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script1479231350405936681851.groovy: 1: unable to resolve class import com.xxx.XxxType
 @ line 1, column 1.
   import import com.xxx.XxxType
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:946)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:542)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:211)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:221)
	at groovy.lang.GroovyClassLoader$parseClass.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at groovy.util.ConfigSlurper.parse(ConfigSlurper.groovy:170)
	at org.grails.config.CodeGenConfig.loadGroovy(CodeGenConfig.groovy:148)
	at org.grails.cli.GrailsCli.loadApplicationConfig(GrailsCli.groovy:588)
	at org.grails.cli.GrailsCli.initializeApplication(GrailsCli.groovy:295)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:273)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:163)
| Error Error occurred running Grails CLI: startup failed:
script1479231350405936681851.groovy: 1: unable to resolve class import com.xxx.XxxType
 @ line 1, column 1.
   import import com.xxx.XxxType
   ^

1 error
```

reproduced also in grails 3.1.14 and 3.2.3 
JDK 8.0.102
app started in Idea via command run-app --stacktrace

**Comment by jameskleeh** [comment]
http://docs.grails.org/latest/guide/upgrading.html#upgrading31x

Under "application.groovy Changes"

**Comment by KapudanPasha** [comment]
Shared constraints live in application.groovy. If they happen to reference non-core classes and are then moved to runtime.groovy as suggested Grails can no longer see them.

**Comment by demon101** [comment]
@KapudanPasha  looks like a bug

**Comment by priyankthakkar** [comment]
Well, I was facing the same issue and I realised that there was an import statement for some string constants and grails didn't like

**Comment by saqib-ahmed** [comment]
Just 

> http://docs.grails.org/latest/guide/upgrading.html#upgrading31x
> 
> Under "application.groovy Changes"

The link mentioned here doesn't have `application.groovy changes` anymore. You can see that in this link: http://docs.grails.org/3.2.3/guide/upgrading.html#upgrading31x
