### ISSUE TITLE
Invalid input + relationship blows up app with Hibernate exception

### ISSUE THREAD

**Issue by namgang** [grails/grails-core#10324]
A trivial app, created with *create-app* and *generate-all* easily blows up with exception on invalid user input. This happens if the domain class also contains a relationship. The issue may belong to grails-core, the scaffolding plugin or the fields plugin, I cannot tell where in the architecture it should be fixed. It does not happen with client-side validation. For instance, integer input is efficiently validated client-side.

My understanding (probably incomplete) is that the issue is triggered if invalid input goes back to the controller and is then bounced to the *edit* view to be updated by the user. If the domain contains a relationship a session is needed to retrieve and display the far side of the relationship. There is no session due to the validation conflict, so an exception is thrown in Hibernate.

### Steps to Reproduce

1. Clone or download example provided on [GitHub](https://github.com/namgang/grails323-input-issue)
2. Set up a suitable Grails environment. Use the provided `setup.sh` or use your own conventions
3. Run it as described in the README.

### Expected Behaviour

On invalid input: The failing field is highlighted, a message is shown.

### Actual Behaviour

The app blows up with an exception. This sample output begins with a log message from the controller that shows the validation error. In this case the input is "x" in a field that expects a double.
```
2016-11-20 08:45:58.681 DEBUG --- [nio-8080-exec-7] g.a.controllers.pingpong.PingController  : --PING UPDATE ERRORS: Field error in object 'pingpong.Ping' on field 'weight': rejected value [x]; codes [pingpong.Ping.weight.typeMismatch.error,pingpong.Ping.weight.typeMismatch,ping.weight.typeMismatch.error,ping.weight.typeMismatch,typeMismatch.pingpong.Ping.weight,typeMismatch.weight,typeMismatch.java.lang.Double,typeMismatch]; arguments [weight]; default message [Data Binding Failed]
2016-11-20 08:45:58.760 ERROR --- [nio-8080-exec-7] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/ping/edit.gsp:37] Error executing tag <g:form>: [views/ping/edit.gsp:32] Error executing tag <f:all>: failed to lazily initialize a collection of role: pingpong.Ping.pongs, could not initialize proxy - no Session] with root cause

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: pingpong.Ping.pongs, could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:584)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:201)
        at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:145)
        at org.hibernate.collection.internal.PersistentSet.isEmpty(PersistentSet.java:149)
        at grails.plugin.formfields.FormFieldsTagLib.buildModel(FormFieldsTagLib.groovy:336)
        at grails.plugin.formfields.FormFieldsTagLib$_closure3.doCall(FormFieldsTagLib.groovy:140)
        at org.grails.taglib.TagOutput.captureTagOutput(TagOutput.java:78)
        at grails.plugin.formfields.FormFieldsTagLib$_closure2.doCall(FormFieldsTagLib.groovy:101)
        at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:410)
        at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:335)
        at home_hs_grails_grails323_input_issue_grails_app_views_ping_edit_gsp$_run_closure2$_closure27.doCall(home_hs_grails_grails323_input_issue_grails_app_views_ping_edit_gsp:81)
        at org.grails.taglib.TagBodyClosure.executeClosure(TagBodyClosure.java:200)
        at org.grails.taglib.TagBodyClosure.captureClosureOutput(TagBodyClosure.java:102)
        at org.grails.taglib.TagBodyClosure.call(TagBodyClosure.java:213)
        at org.grails.plugins.web.taglib.FormTagLib$_closure9.doCall(FormTagLib.groovy:447)
        at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:417)
        at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:335)
        at home_hs_grails_grails323_input_issue_grails_app_views_ping_edit_gsp$_run_closure2.doCall(home_hs_grails_grails323_input_issue_grails_app_views_ping_edit_gsp:86)
        at org.grails.taglib.TagBodyClosure.executeClosure(TagBodyClosure.java:200)
        at org.grails.taglib.TagBodyClosure.captureClosureOutput(TagBodyClosure.java:102)
        at org.grails.taglib.TagBodyClosure.call(TagBodyClosure.java:213)
        at org.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy:48)
        at org.grails.plugins.web.taglib.SitemeshTagLib$_closure3.doCall(SitemeshTagLib.groovy:156)
        at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:417)
        at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:335)
        at home_hs_grails_grails323_input_issue_grails_app_views_ping_edit_gsp.run(home_hs_grails_grails323_input_issue_grails_app_views_ping_edit_gsp:89)
        at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
        at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
        at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:76)
        at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
        at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
        at org.grails.web.sitemesh.GrailsLayoutView.renderInnerView(GrailsLayoutView.java:150)
        at org.grails.web.sitemesh.GrailsLayoutView.obtainContent(GrailsLayoutView.java:128)
        at org.grails.web.sitemesh.GrailsLayoutView.renderTemplate(GrailsLayoutView.java:63)
        at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
        at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

### Environment Information

- Ubuntu 14.04.5 LTS
- Tested with Grails 3.2.3 and 3.2.2
- Oracle Java SE 1.8.0_102-b14

### Example Application

Link to GitHub, [the grails323-input-issue repo](https://github.com/namgang/grails323-input-issue)

**Comment by graemerocher** [comment]
So this is due to the nature of the way Spring handles Hibernate transactions. When a transaction is rolled back the session is cleared https://github.com/spring-projects/spring-framework/blob/master/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateTransactionManager.java#L627

This means that the entity becomes detached and you can no longer initialise the associations of the entity. 

There are a few solutions that can be added in your code:

1) Load the association in the action by doing `ping.pongs`
2) Instead of relying on the default scaffolding which uses the `get(..)` method modify the code to do a join:

```groovy
def update(Long id) {
     Ping ping = Ping.get(id, [fetch:[pongs:'join']])
}
````
The above will perform a join to obtain the associations which will perform better too.

It could be argued that the fields plugin should not traverse into a lazy associations and cause this error in the first place. If you believe this to be the case feel free to report this issue here https://github.com/grails-fields-plugin/grails-fields/issues

Other than that there isn't much we can do on the Grails side to resolve this, and it is one of the cases where you need to modify the existing generated code in order to move forward.

**Comment by namgang** [comment]
This is valuable information for those already into Grails, thanks a lot. For those beginning to check out Grails I'm just a little worried about their first impression. If there is unexpected trouble the Grails brand will suffer, no matter what the correct diagnosis might be.

**Comment by graemerocher** [comment]
Then Spring and Hibernate will be suffering too because the behaviour is the same across the Java ecosystems.
