### ISSUE TITLE
belongsTo fails with additional reference to same type

### ISSUE THREAD

**Issue by mkuchin** [grails/grails-core#10329]
Application with two domain classes with oneToMany relationship fails to run if I add an additional reference to parent class to the child class. 

### Steps to Reproduce

`grails run-app`

### Actual Behaviour

`grails run-app` fails with exception:
```
Caused by: org.hibernate.MappingException: Foreign key (FKpe6vy9gxh40jtb0u5mfqq2iaf:chapter [])) must have same number of columns as the referenced primary key (book [id])
	at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:148)
	at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:130)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.secondPassCompileForeignKeys(InFlightMetadataCollectorImpl.java:1854)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.secondPassCompileForeignKeys(InFlightMetadataCollectorImpl.java:1774)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1593)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:278)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:83)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:418)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:87)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:692)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:264)
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:86)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:38)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:22)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:206)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 72 common frames omitted
```

### Environment Information

- **Grails Version:** 3.2.3
- **JDK Version:** 1.8.0_7

### Example Application
Book.groovy:
```
class Book {
  String name
  static hasMany = [chapters: Chapter]
}
```
Chapter.groovy:
```
class Chapter {
  String name
  Book book
// fails then I add next line
  Book otherBook
  static belongsTo = [book: Book]
}
```

**Comment by graemerocher** [comment]
You need to add `mappedBy` http://docs.grails.org/latest/ref/Domain%20Classes/mappedBy.html since the mapping is ambiguous

**Comment by mkuchin** [comment]
Thank you, @graemerocher !
Adding 
```
static mappedBy = [ chapters: 'book']
```
to Book.groovy solved the problem.
