### ISSUE TITLE
grails recompiling failure when groovy code contains unicode

### ISSUE THREAD

**Issue by maplye** [grails/grails-core#10351]
The service class code contains unicode under version 3.2.3, grails recompiling failure when I change the code. The error message as follows:

grails> File D:\Projects\PMTProj\pmt\grails-app\services\c
om\conti\pmt\TaskService.groovy changed, recompiling...
ERROR grails.boot.GrailsApp - Compilation Error: startup failed:
D:\Projects\PMTProj\pmt\grails-app\services\com\conti\pmt\
TaskService.groovy: 46: expecting anything but ''\n''; got it anyway @ line 46,
column 62.
   nException("浠诲姟淇濆瓨澶辫触锛?, task)
                                 ^

1 error

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
D:\Projects\PMTProj\pmt\grails-app\services\com\conti\pmt\
TaskService.groovy: 46: expecting anything but ''\n''; got it anyway @ line 46,
column 62.
   nException("浠诲姟淇濆瓨澶辫触锛?, task)
                                 ^

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollecto
r.java:310)
        at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollect
or.java:150)
        at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.ja
va:120)
        at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.ja
va:132)
        at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:360)
        at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(Antlr
ParserPlugin.java:140)
        at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugi
n.java:111)
        at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:237)
        at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.ja
va:167)
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(Compil
ationUnit.java:931)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(Compilat
ionUnit.java:593)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(Co
mpilationUnit.java:569)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.j
ava:546)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.j
ava:525)
        at grails.boot.GrailsApp.compileGroovyFile(GrailsApp.groovy:314)
        at grails.boot.GrailsApp.recompile(GrailsApp.groovy:300)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(Refl
ectiveInterceptor.java:1426)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:384)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(Po
goMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
tractCallSite.java:182)
        at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(Gra
ilsApp.groovy:241)
        at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(Gra
ilsApp.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(Refl
ectiveInterceptor.java:1426)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at groovy.lang.Closure.run(Closure.java:495)
        at java.lang.Thread.run(Thread.java:744)

**Comment by jeffbrown** [comment]
Can you provide a sample app which demonstrates the problem?

Thanks for the feedback.

**Comment by maplye** [comment]
![1](https://cloud.githubusercontent.com/assets/105527/21450023/16e890e0-c92e-11e6-8415-c1573d763369.png)
![2](https://cloud.githubusercontent.com/assets/105527/21450025/16ed86a4-c92e-11e6-9566-1fdbef4590bc.png)
![3](https://cloud.githubusercontent.com/assets/105527/21450024/16ec8114-c92e-11e6-9609-27fdd6e523a7.png)
[test1.zip](https://github.com/grails/grails-core/files/670464/test1.zip)

**Comment by graemerocher** [comment]
Can't reproduce this personally, maybe try pass `-Dfile.encoding` to the Grails JVM (see http://mrhaki.blogspot.com.es/2015/09/grails-goodness-passing-system.html) and ensure your JVM encoding is configured correctly

**Comment by romejiang** [comment]
same problem, such a solution.

add "systemProperty "file.encoding", "utf-8" " to build.gredle file inside bootRun.


```
bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    addResources = true
    systemProperty "file.encoding", "utf-8"
}
```
