### ISSUE TITLE
[Grails 3.2.4] - Execution failed for task ':compileGsonViews'

### ISSUE THREAD

**Issue by Kaishley** [grails/grails-core#10378]
### Steps to Reproduce

I have `grails.views.json.compileStatic: false`  in `application.yml` for my JSON Views.

1. Upgraded from Grails 3.2.3 to 3.2.4
2. Ran `grails war`

### Expected Behaviour

Successful compilation

### Actual Behaviour

The exception message below changes according to what I have set for `grails.views.json.compileStatic`.

`grails.views.json.compileStatic: false` = _conversion of **false** to boolean not implemented_

`grails.views.json.compileStatic: true` = _conversion of **true** to boolean not implemented_

```
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:findMainClass
:buildProperties UP-TO-DATE
:processResources
:classes
:compileGsonViews
Exception in thread "main" java.lang.RuntimeException: conversion of false to boolean not implemented
        at org.grails.config.CodeGenConfig.convertToOtherTypes(CodeGenConfig.groovy:213)
        at org.grails.config.CodeGenConfig.convertToType(CodeGenConfig.groovy:208)
        at org.grails.config.CodeGenConfig.getProperty(CodeGenConfig.groovy:264)
        at grails.views.GenericViewConfiguration$Trait$Helper.readConfiguration(GenericViewConfiguration.groovy:117)
        at grails.views.GenericViewConfiguration$Trait$Helper$readConfiguration$6.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at grails.plugin.json.view.JsonViewConfiguration.readConfiguration(JsonViewConfiguration.groovy)
        at grails.views.GenericViewConfiguration$Trait$Helper.readConfiguration(GenericViewConfiguration.groovy:98)
        at grails.views.GenericViewConfiguration$Trait$Helper$readConfiguration$5.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at grails.plugin.json.view.JsonViewConfiguration.readConfiguration(JsonViewConfiguration.groovy)
        at grails.views.GenericViewConfiguration$readConfiguration$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at grails.views.AbstractGroovyTemplateCompiler.run(AbstractGroovyTemplateCompiler.groovy:101)
        at grails.plugin.json.view.JsonViewCompiler.main(JsonViewCompiler.groovy:41)
:compileGsonViews FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGsonViews'.
```

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.4
- **JDK Version:** 1.8.0_112

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-core/commit/0dfdd0a525ce9f4639c12a5387c9d13694dcdccb
