### ISSUE TITLE
grails plugin profile integration test fails with java.lang.NoClassDefFoundError: javax/servlet/ServletException

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10379]
When a plugin is created with profile plugin, the integration test fails with  java.lang.NoClassDefFoundError: javax/servlet/ServletException

stacktrace
```

java.lang.NoClassDefFoundError: javax/servlet/ServletException
	at java.lang.Class.forName(Class.java:264)
	at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:585)
	at grails.boot.GrailsApp.createApplicationContext(GrailsApp.groovy:74)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:111)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.AutoConfigureReportTestExecutionListener.prepareTestInstance(AutoConfigureReportTestExecutionListener.java:46)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.spockframework.spring.SpringTestContextManager.prepareTestInstance(SpringTestContextManager.java:49)
	at org.spockframework.spring.SpringInterceptor.interceptSetupMethod(SpringInterceptor.java:42)
	at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:28)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more
```

### Environment Information

- **Operating System**: OSX ELCapitan
- **Grails Version:** 3.2.0
- **JDK Version:**  JDK 8

### Example Application
Find attached sample plugin

[test.zip](https://github.com/grails/grails-core/files/675375/test.zip)

**Comment by jameskleeh** [comment]
You don't have any GORM implementation as a dependency of your plugin

Create a plugin with: `grails create-plugin test-plugin -features hibernate5` and then integration tests will run. Verified with 3.2.4.

**Comment by snimavat** [comment]
@jameskleeh -- so does that mean, even if i create a plugin with profile "plugin" and not web -- i still need tomcat as dependency ?

**Comment by jameskleeh** [comment]
@snimavat If you want to run integration tests, yes. You could try just adding it to the testCompile scope

**Comment by snimavat** [comment]
Okay, got it. but still thats little strange, if my plugin isnt doing anything webspecific, why test phase is pulling the servlet dependencies ? -- shouldnt this be considered a bug ?

**Comment by jameskleeh** [comment]
No. An integration test requires the application to be started. You need a servlet container to run a Grails application.

**Comment by snimavat** [comment]
Aah.. got it.

**Comment by snimavat** [comment]
adding tomcat as testCompile fixes the compilation issue, however still, for plugin integration tests, the Plugin file is not executed, and so any of the beans registered by the plugin is not injected to tests
