### ISSUE TITLE
Multiple issues with HyphenatedUrlConverter 

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10390]
When hyphanted url converter is configured, and default action name has two words in it, it would cause java.lang.IllegalArgumentException: Invalid action name: testMe

### Task List

Configure hyphenated url converter

Given following controller
```
class BookTestController {
	static defaultAction = "testMe"

	def testMe() {}
}

```

Trying to access http://localhost:8080/book-test/
Would result in following stacktrace

```
java.lang.IllegalArgumentException: Invalid action name: testMe
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:186)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

The problem is [here](https://github.com/snimavat/grails-core/blob/a454a0c8ac95dd364563c8b00ac79955517cdc14/grails-core/src/main/groovy/org/grails/core/DefaultGrailsControllerClass.java#L170-L170) 

**DefaultGrailsControllerClass** keeps cached names of **actions** and **actionUriToViewName** which are convereted using the registered url converter. however when the action name is not in url, UrlMappingHandlerAdapter would get the defaultActionName from controller - [here](https://github.com/snimavat/grails-core/blob/bd83cc77244a60e8ab3ccdbe517596639b16898c/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/mvc/UrlMappingsInfoHandlerAdapter.groovy#L84-L84)  -- but this name is not hyphenated, so it can not find the action method resulting in error.

**There are more issues with view resolution, read below comments**

- **Grails Version:** 3.2.4

### Example Application

[bugwork324.zip](https://github.com/grails/grails-core/files/691557/bugwork324.zip)

**Comment by snimavat** [comment]
Also #9478 is still reproducible with 3.2.4 -- 
If you hit the url http://localhost:8080/book-test/test-me -- it would find the action, but would fail on finding the view and result in error javax.servlet.ServletException: Could not resolve view with name '/bookTest/test-me' in servlet with name 'grailsDispatcherServlet'

It has to do with this change -https://github.com/grails/grails-core/commit/8528904c1be5cd225c68a360c11e54c6b64c8e22#diff-4d0cafafb9cec54782580b94eab606ca

It does controllerClass.actionUriToViewName(action) when action returns map, but does not do the same when action returns null, resulting in it trying to find the wrong view.

**Comment by snimavat** [comment]
I just debugged it further, and i think this change https://github.com/grails/grails-core/commit/8528904c1be5cd225c68a360c11e54c6b64c8e22#diff-4d0cafafb9cec54782580b94eab606ca is completely broken, even when the controller action returns empty map, it is still unable to find the view..

Because when view name is not a uri GroovyPageViewResolver prefixes the controller name [here](https://github.com/snimavat/grails-core/blob/cfe1d1a06e00c8e8ee2cc6d4d520c1e736bfbc49/grails-web-gsp/src/main/groovy/org/grails/web/servlet/view/GroovyPageViewResolver.java#L88-L88) 
Which in turn gets current controller name using GrailsWebRequest.getControllerName which returns hyphenated controller name, resulting in it trying to find wrong view (book-test/testMe.gsp)

**Comment by snimavat** [comment]
The UrlConverter issue affects even the convention based layout resolution.
So when no layout is specified explicitely, and when hyphenated url converter is configured, it will try to find following layouts

- /layouts/book-test/test-me.gsp
- /layouts/book-test.gsp
