### ISSUE TITLE
Problem With HibernateTransactionManager

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#10426]
See the project at https://github.com/jeffbrown/sessionstuff.

```groovy
package demo

import grails.transaction.Transactional

class DemoController {

    HelperService helperService

    @Transactional()
    def index() {
        Person.withNewSession {
            helperService.doSomething()
        }

        render 'Success'
    }
}
```

```groovy
package demo

import grails.transaction.Transactional

@Transactional
class HelperService {

    void doSomething() {}
}
```

```groovy
package demo

class Person {
    String name
}
```

Sending a request to the `index` action in the `demo` controller results in the following:

```
Caused by: org.springframework.transaction.IllegalTransactionStateException: Pre-bound JDBC Connection found! HibernateTransactionManager does not support running within DataSourceTransactionManager if told to manage the DataSource itself. It is recommended to use a single HibernateTransactionManager for all transactions on a single DataSource, no matter whether Hibernate or JDBC access.
        at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:420)
        at org.grails.orm.hibernate.GrailsHibernateTransactionManager.doBegin(GrailsHibernateTransactionManager.groovy:34)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
        at demo.DemoController$__tt__index_closure2.doCall(DemoController.groovy:12)
        at org.grails.orm.hibernate.GrailsHibernateTemplate$1.doInHibernate(GrailsHibernateTemplate.java:140)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:243)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:187)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.executeWithNewSession(GrailsHibernateTemplate.java:137)
        at org.grails.orm.hibernate.AbstractHibernateDatastore.withNewSession(AbstractHibernateDatastore.java:320)
        at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.withNewSession(AbstractHibernateGormStaticApi.groovy:59)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.withNewSession(GormEntity.groovy:999)
        at demo.DemoController.$tt__index(DemoController.groovy:11)
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
        ... 14 common frames omitted
```

**Comment by jeffbrown** [comment]
The linked project uses Grails 3.2.4.

**Comment by jeffbrown** [comment]
Same thing happens if the service is changed to look like this:

```groovy
package demo

class HelperService {

    void doSomething() {
        Person.withTransaction {}
    }
}
```

**Comment by theleancoder** [comment]
Why is @Transactional used for the index() action?

**Comment by theleancoder** [comment]
Seems like Hibernate is not allowing both the HelperService and withNewSession method to bind to the same JDBC datasource in a single session.

The application is working by moving the HelperService out of the withNewSession method.

```
    @Transactional()
    def index() {
        helperService.doSomething()
        Person.withNewSession {
        }

        render 'Success'
    }
```

Ref - http://docs.grails.org/latest/ref/Domain%20Classes/withNewSession.html

**Comment by jeffbrown** [comment]
> Why is @Transactional used for the index() action?

Because in the real app, there are things happening in the action which need to be transactional.

**Comment by jeffbrown** [comment]
> The application is working by moving the HelperService out of the withNewSession method.

Right, but they want to invoke a transactional service method and have that happen in a new session.  The simple code sample I provided demonstrates a valid scenario as far as I can tell.  I think we need to fix the behavior.

**Comment by jeffbrown** [comment]
Another way to represent this that doesn't require the controller being transactional is to do something like this:

```groovy
package demo

class DemoController {

    HelperService helperService

    def index() {
        helperService.doSomething()

        render 'Success'
    }
}
```

```groovy
package demo

import grails.transaction.Transactional

@Transactional
class HelperService {

    void doSomething() {
        Person.withNewSession {
            // this will not work...
            doSomethingElse()
        }
    }

    void doSomethingElse() {
        // do stuff here
    }
}
```

A way to workaround that is to do something like this:

```groovy
package demo

import grails.transaction.Transactional

@Transactional
class HelperService {

    void doSomething() {
        doSomethingElse()
    }

    void doSomethingElse() {
        Person.withNewSession {
            // do stuff here
        }
    }
}
```

**Comment by timbonicus** [comment]
Will this fix be ported to gorm-hibernate4, or is there a workaround for using withNewSession inside a transactional method?
