### ISSUE TITLE
grailsw fails behind a proxy

### ISSUE THREAD

**Issue by hanafey** [grails/grails-core#10465]
When working behind a non-authenticating proxy the "./grailsw war" command fails with the following:

~~~
# Wrapper modified to print exec command:
#exec /alternate/opt/jdk1.7.0_80/bin/java -jar /home/hanafemi/tmp/ldapper3/grails-wrapper.jar -Dhttp.proxyHost=proxy1.phi.com -Dhttp.proxyPort=80 -Dhttps.proxyHost=proxy1.phi.com -Dhttps.proxyPort=80  -Dhttp.nonProxyHosts=localhost|127.0.0.1|*.es.d.com|*.phi.com war

Resolving dependencies...
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at grails.init.Start.main(Start.java:123)
Caused by: org.springframework.boot.cli.compiler.grape.DependencyResolutionFailedException: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.grails:grails-shell:jar:3.2.3
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:307)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at grails.init.RunCommand.main(RunCommand.groovy:30)
	... 5 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.grails:grails-shell:jar:3.2.3
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:380)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:302)
	... 16 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.grails:grails-shell:jar:3.2.3
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	... 17 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.grails:grails-shell:jar:3.2.3
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:335)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:217)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	... 18 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.grails:grails-shell:pom:3.2.3 from/to grailsCentral (https://repo.grails.org/grails/core): Connect to repo.grails.org:443 timed out
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.grails:grails-shell:pom:3.2.3 from/to grailsCentral (https://repo.grails.org/grails/core): Connect to repo.grails.org:443 timed out
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
~~~

The same proxy config allows the "./gradlew -Dgrails.env=production war" to function normally, and a bunch of external downloads via the proxy happen without problem.

On a host that does not require a proxy the build proceeds with either "grailsw" or "gradlew". 

For reproducible  testing the .m2, .grails, and .groovy directories are cleared. If the dependencies are in the local caches the problem does not happen.

### Environment Information

- Linux lxjh416 2.6.32-642.1.1.el6.x86_64 #1 SMP Tue May 31 21:57:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Grails 3.2.3
- jdk1.7.0_80

**Comment by jameskleeh** [comment]
Can you confirm that this works with the normal `grails` command?

**Comment by jeffbrown** [comment]
@hanafey Can you test using the `grails` command (not `grailsw`) and report back to indicate whether or not that yields the same problem for you?

Thanks for the input!

**Comment by kdpeders** [comment]
I've got the same issue.  The `grails` command works behind a proxy but `grailsw` does not.

It appears that the `grailsw` command does not use the `gradle-wrapper.properties` settings while the `grails` command does use the `gradle.properties` settings.

Here is the error I get from `grailsw` when running for the first time in an environment w/o running `grails` first.
```
./grailsw clean

You must be connected to the internet the first time you use the Grails wrapper
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:344)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1039)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:975)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:893)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1343)
	at java.net.URL.openStream(URL.java:1048)
	at grails.init.Start.getVersion(Start.java:34)
	at grails.init.Start.main(Start.java:79)
```

**Comment by jameskleeh** [comment]
@kdpeders That looks like a different issue to me. Does your proxy require authentication?

If so, try replacing the `grails-wrapper.jar` file in your application with this one: https://drive.google.com/file/d/0BwWZI3aXMttFWm1CUGJVcDZLblk/view?usp=sharing

**Comment by jameskleeh** [comment]
@hanafey I'm not sure how or why this would work differently since Grails itself doesn't do anything with `-Dhttp.proxyHost=proxy1.phi.com -Dhttp.proxyPort=80`. Similar to this issue here https://github.com/grails/grails-core/issues/9856

**Comment by kdpeders** [comment]
Setting those options (as well as `https` proxy options) had not effect.  Note:  I'm able to run `grails` command but not `grailsw` (unless I've successfully run `grails` first in that environment).  

> Note:  my proxy does not require authentication

I believe my issues is related to your original issue.

**Comment by jameskleeh** [comment]
@kdpeders @hanafey I believe I have gotten to the bottom of this. If you would like to test before 3.2.7 is released, copy `grailsw`, `grailsw.bat`, and `grails-wrapper.jar` from https://github.com/grails-profiles/base/tree/master/skeleton to your project and test

**Comment by kdpeders** [comment]
That worked.  Thanks for the quick turnaround.
