### ISSUE TITLE
Default dataSource not available in applicationContext using multiple datasources

### ISSUE THREAD

**Issue by tkvw** [grails/grails-core#10477]
**Update: ** Title is updated, because of comments and investigation below

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. git clone https://github.com/tkvw/grailsIssueDatabasemigration
2. gradlew bootRun

### Expected Behaviour
The application should start normally.

### Actual Behaviour
The application throws an Exception: 
`org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is rolled back; nested exception is org.springframework.transaction.IllegalTransactionStateException: Transaction is already completed - do not call commit or rollback more than once per transaction
	at org.grails.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:183)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at grails.transaction.GrailsTransactionTemplate$execute.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.grails.plugins.databasemigration.DatabaseMigrationTransactionManager.withTransaction(DatabaseMigrationTransactionManager.groovy:31)
	at ....

Caused by: org.springframework.transaction.IllegalTransactionStateException: Transaction is already completed - do not call commit or rollback more than once per transaction
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:704)
	at org.grails.transaction.MultiTransactionStatus.commit(MultiTransactionStatus.java:73)
	at org.grails.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:156)
	... 56 common frames omitted`

If you remove a random domainclass, the application runs normally! 
If you remove the "other" datasource, the application runs normally! 

@See: http://stackoverflow.com/questions/42136918/error-upgrading-grails-app-from-3-1-10-to-3-2-5
for other people having the same issue. 

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.6
- **JDK Version:** 1.8

### Example Application
- https://github.com/tkvw/grailsIssueDatabasemigration

**Comment by tkvw** [comment]
I think I've figured it out. It's a configuration issue in application.yml. If you define: 

    dataSources:
        dataSource: 
        ...
        other: 
        ...

Grails will create three PlatformTransactionManagers. 

If you specify (as per GORM docs): 

    dataSource:
        ...
    dataSources:
        other: 
        ...

Grails will create two PlatformTransactionManagers. 

Databasemigrations expects all datasources to handle to be in the dataSources block. So the DatabaseMigrationPlugin is at fail and should be updated or you should allow the default datasource in the dataSources config.

**Comment by tkvw** [comment]
I've created a patch for the databasemigration plugin, but it does not work because grails doesn't publish the default datasource using the name "dataSource" in the application context in a multidatasource configuration. Shall I create a new issue for this and close this one?

**Comment by graemerocher** [comment]
@tkvw just change the title of this issue if necessary

**Comment by graemerocher** [comment]
Closing this since the alterations are need in GORM and database migration
