### ISSUE TITLE
UserRole (Spring Security Plugin 3.1.1) not updated properly when Grails version > 3.2.4

### ISSUE THREAD

**Issue by goedef** [grails/grails-core#10487]
Hello,

I have many Grails Web-applications operational and I try to upgrade them on a regular basis. Currently I work with Grails version 3.2.4 and would like to upgrade to 3.2.6. After the upgrade things initially seemed to be fine, but I ran into the a nasty update problem with the UserRole table created by the Spring Security plugin (version 3.1.1).

I can reproduce the problem on a clean install of Grails version 3.2.6 and Spring Security Plugin 3.1.1. The problem is as follows:
When I update a user I use the following code to update the UserRole table:

        user.save flush:true
        UserRole.removeAll(user)
        for (roleId in params.list('roles')){
            Role r = Role.get(roleId)
            UserRole.create(user, r)
        }

In the UserRole domain class I use the standard code generated by the plugin:

	static UserRole create(User user, Role role) {
		def instance = new UserRole(user: user, role: role)
		instance.save()
		instance
	}
When I update the user the UserRole table is not updated properly. I changed instance.save() to instance.save(failOnError: true) and then I get the stacktrace at the end of this message. The UserRole domain class thinks the table still holds the role I thought I removed with UserRole.removeAll(userInstance).

When I downgrade to Grails 3.2.4 everything works fine. So it seems there is a problem as of Grails version 3.2.5.

I could not find a workaround yet, so I cannot upgrade my web-applications to version 3.2.5 or higher now.

Please advise.

Stacktrace:
[_method:PUT, id:2, version:0, password:$2a$10$ycBHPWAtp6u3UNe4ksUiieXoKJKbI18P4IE2q.aPmGrZ0W4eZTSLu, max:, offset:, sort:, order:, username:admin1, password1:, password2:, roles:[1, 2, 3], _accountExpired:, _accountLocked:, _enabled:, enabled:on, _passwordExpired:, controller:user, format:null, action:update]
2017-02-19 16:40:58.911 ERROR --- [nio-8080-exec-9] o.g.web.errors.GrailsExceptionResolver   : ValidationException occurred when processing request: [PUT] /egidia/user/update - parameters:
_method: PUT
id: 2
version: 0
password: $2a$10$ycBHPWAtp6u3UNe4ksUiieXoKJKbI18P4IE2q.aPmGrZ0W4eZTSLu
max: 
offset: 
sort: 
order: 
username: admin1
password1: 
password2: 
roles: 1
roles: 2
roles: 3
_accountExpired: 
_accountLocked: 
_enabled: 
enabled: on
_passwordExpired: 
Validation Error(s) occurred during save():
- Field error in object 'egidia.UserRole' on field 'role': rejected value [Role(authority:ROLE_SUPERADMIN)]; codes [egidia.UserRole.role.validator.error.egidia.UserRole.role,egidia.UserRole.role.validator.error.role,egidia.UserRole.role.validator.error.egidia.Role,egidia.UserRole.role.validator.error,userRole.role.validator.error.egidia.UserRole.role,userRole.role.validator.error.role,userRole.role.validator.error.egidia.Role,userRole.role.validator.error,egidia.UserRole.role.userRole.exists.egidia.UserRole.role,egidia.UserRole.role.userRole.exists.role,egidia.UserRole.role.userRole.exists.egidia.Role,egidia.UserRole.role.userRole.exists,userRole.role.userRole.exists.egidia.UserRole.role,userRole.role.userRole.exists.role,userRole.role.userRole.exists.egidia.Role,userRole.role.userRole.exists,userRole.exists.egidia.UserRole.role,userRole.exists.role,userRole.exists.egidia.Role,userRole.exists]; arguments [role,class egidia.UserRole,Role(authority:ROLE_SUPERADMIN)]; default message [Attribuut [{0}] van entiteit [{1}] met waarde [{2}] is niet geldig]
. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:210)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'egidia.UserRole' on field 'role': rejected value [Role(authority:ROLE_SUPERADMIN)]; codes [egidia.UserRole.role.validator.error.egidia.UserRole.role,egidia.UserRole.role.validator.error.role,egidia.UserRole.role.validator.error.egidia.Role,egidia.UserRole.role.validator.error,userRole.role.validator.error.egidia.UserRole.role,userRole.role.validator.error.role,userRole.role.validator.error.egidia.Role,userRole.role.validator.error,egidia.UserRole.role.userRole.exists.egidia.UserRole.role,egidia.UserRole.role.userRole.exists.role,egidia.UserRole.role.userRole.exists.egidia.Role,egidia.UserRole.role.userRole.exists,userRole.role.userRole.exists.egidia.UserRole.role,userRole.role.userRole.exists.role,userRole.role.userRole.exists.egidia.Role,userRole.role.userRole.exists,userRole.exists.egidia.UserRole.role,userRole.exists.role,userRole.exists.egidia.Role,userRole.exists]; arguments [role,class egidia.UserRole,Role(authority:ROLE_SUPERADMIN)]; default message [Attribuut [{0}] van entiteit [{1}] met waarde [{2}] is niet geldig]

        at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:131)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
        at egidia.UserRole.create(UserRole.groovy:48)
        at egidia.UserController.$tt__update(UserController.groovy:78)
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
        ... 37 common frames omitted

**Comment by graemerocher** [comment]
Probably the same as https://github.com/grails/grails-data-mapping/issues/865

**Comment by goedef** [comment]
Graeme,

I am affraid not. I checked the suggested workarounds and they do not provide a solution.

Fred

Van: Graeme Rocher <notifications@github.com>
Beantwoorden - Aan: grails/grails-core <reply@reply.github.com>
Datum: maandag 20 februari 2017 08:23
Aan: grails/grails-core <grails-core@noreply.github.com>
CC: Fred de Goede <fred@degoede.nu>, Author <author@noreply.github.com>
Onderwerp: Re: [grails/grails-core] UserRole (Spring Security Plugin 3.1.1) not updated properly when Grails version > 3.2.4 (#10487)


Probably the same as grails/grails-data-mapping#865<https://github.com/grails/grails-data-mapping/issues/865>

**Comment by graemerocher** [comment]
As far as I can tell this is not a bug and worked before because of a bug in Grails. Previously `withNewSession` was not working correctly, and was re-using the existing session.

What happens is as follows:

1. On the line `UserRole.removeAll(user)` the user's roles are removed within the current transaction
2. On the line `UserRole.create(user, r)` the `UserRole` is recreated, however `withNewSession` is used to establish of a `UserRole` already exists within a custom validator:

```groovy
UserRole.withNewSession {
	if (UserRole.exists(ur.user.id, r.id)) {
		return ['userRole.exists']
	}
}
```

The `withNewSession` opens a new database connection which has no visibility to the changes that were done in step 1) since the transactions are isolated. Validation therefore fails and an error is returned.

This only happens when you attempt to recreate the same `UserRole` when it already exists.  If I remove the use of `withNewSession` the problem is resolved, since it using the current database connection which has visibility within the transaction.

So as far as I can tell on the Grails side the behaviour is correct. Whether this is a bug in spring security is debatable, but an issue can be reported here if necessary https://github.com/grails-plugins/grails-spring-security-core/issues

I have attached an example that reproduces the problem.
[sec-test.zip](https://github.com/grails/grails-core/files/789929/sec-test.zip)

**Comment by goedef** [comment]
Thanks!

Van: Graeme Rocher <notifications@github.com>
Beantwoorden - Aan: grails/grails-core <reply@reply.github.com>
Datum: dinsdag 21 februari 2017 12:23
Aan: grails/grails-core <grails-core@noreply.github.com>
CC: Fred de Goede <fred@degoede.nu>, Author <author@noreply.github.com>
Onderwerp: Re: [grails/grails-core] UserRole (Spring Security Plugin 3.1.1) not updated properly when Grails version > 3.2.4 (#10487)


As far as I can tell this is not a bug and worked before because of a bug in Grails. Previously withNewSession was not working correctly, and was re-using the existing session.

What happens is as follows:

  1.  On the line UserRole.removeAll(user) the user's roles are removed within the current transaction
  2.  On the line UserRole.create(user, r) the UserRole is recreated, however withNewSession is used to establish of a UserRole already exists within a custom validator:

UserRole.withNewSession {

        if (UserRole.exists(ur.user.id, r.id)) {

               return ['userRole.exists']

        }

}

The withNewSession opens a new database connection which has no visibility to the changes that were done in step 1) since the transactions are isolated. Validation therefore fails and an error is returned.

This only happens when you attempt to recreate the same UserRole when it already exists. If I remove the use of withNewSession the problem is resolved, since it using the current database connection which has visibility within the transaction.

So as far as I can tell on the Grails side the behaviour is correct. Whether this is a bug in spring security is debatable, but an issue can be reported here if necessary https://github.com/grails-plugins/grails-spring-security-core/issues

I have attached an example that reproduces the problem.
sec-test.zip<https://github.com/grails/grails-core/files/789929/sec-test.zip>
