### ISSUE TITLE
Deployed war to Tomcat causes java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by Veeramanikandan1493** [grails/grails-core#10483]
I am having problems with the web profile in grails, when deploying the war file to external tomcat-server.
I get  java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory. 

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. install Grails 3.2.6 & Gradle 3.3
2. install apache-tomcat-8.5.11
3. install Java(TM) SE Runtime Environment (build 1.8.0_111-8u111)
4. grails create-app sampleApp --profile web --features asset-pipeline,json-views,markup-views,MongoDB
5. change: compile "org.springframework.boot:spring-boot-starter-tomcat" in build.gradle to provided
6. ./gradlew clean war for generating war file
7. copy sampleApp-0.1 to apache-tomcat-8.5.11/webapps
8. restart tomcat
9. navigate browser to http://localhost:8080/sampleApp-0.1/

### Expected Behaviour

- Visual of index page

### Actual Behaviour

-  java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory occured while deploying war file.

> 17-Feb-2017 11:06:00.176 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/ard-l012/Libraries/apache-tomcat-8.5.11/temp
17-Feb-2017 11:06:00.176 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
17-Feb-2017 11:06:00.311 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
17-Feb-2017 11:06:00.331 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
17-Feb-2017 11:06:00.334 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
17-Feb-2017 11:06:00.336 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
17-Feb-2017 11:06:00.337 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 756 ms
17-Feb-2017 11:06:00.399 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
17-Feb-2017 11:06:00.399 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.11
**17-Feb-2017 11:06:00.445 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1.war
17-Feb-2017 11:06:08.611 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
17-Feb-2017 11:06:09.209 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/sampleApp-0.1]]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85)
at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
... 10 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
... 17 more
17-Feb-2017 11:06:09.212 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/sampleApp-0.1]]
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
17-Feb-2017 11:06:09.214 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1.war has finished in 8,768 ms**
17-Feb-2017 11:06:09.215 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/ROOT
17-Feb-2017 11:06:09.287 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/ROOT has finished in 71 ms
17-Feb-2017 11:06:09.287 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/examples
17-Feb-2017 11:06:09.558 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/examples has finished in 271 ms
17-Feb-2017 11:06:09.558 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/docs
17-Feb-2017 11:06:09.582 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/docs has finished in 24 ms
17-Feb-2017 11:06:09.583 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/host-manager
17-Feb-2017 11:06:09.633 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/host-manager has finished in 51 ms
17-Feb-2017 11:06:09.633 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/manager
17-Feb-2017 11:06:09.672 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/manager has finished in 39 ms
17-Feb-2017 11:06:09.682 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [http-nio-8080]
17-Feb-2017 11:06:09.696 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [ajp-nio-8009]
17-Feb-2017 11:06:09.701 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 9363 ms

### Environment Information

- **Operating System**: Ubuntu 14.04
- **Grails Version:** 3.2.6
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_111-8u111)
- **Container Version (If Applicable):** apache-tomcat-8.5.11

### Example Application

Follow the steps to create example application

[https://github.com/Veeramanikandan1493/sampleApp](https://github.com/Veeramanikandan1493/sampleApp)

**Comment by Veeramanikandan1493** [comment]
I had included `compile "org.slf4j:slf4j-log4j12"` in build.gradle then while generating the war below shown log occured.  

> SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ard-l012/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.22/3bb94b26c2ad2f8755302aa9bf96f03b23a76639/slf4j-log4j12-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ard-l012/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.9/978cd9fbb43b7abed6379d7b02de052d216e30fc/logback-classic-1.1.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. 
SLF4J: See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
        at org.springframework.beans.BeanUtils.<clinit>(BeanUtils.java:58)
        at grails.views.GenericViewConfiguration$Trait$Helper.findViewConfigPropertyDescriptor(GenericViewConfiguration.groovy:136)
        at grails.plugin.markup.view.MarkupViewConfiguration.findViewConfigPropertyDescriptor(MarkupViewConfiguration.groovy:64)
        at grails.views.GenericViewConfiguration$Trait$Helper.readConfiguration(GenericViewConfiguration.groovy:106)
        at grails.plugin.markup.view.MarkupViewConfiguration.readConfiguration(MarkupViewConfiguration.groovy)
        at grails.views.GenericViewConfiguration$Trait$Helper.readConfiguration(GenericViewConfiguration.groovy:98)
        at grails.plugin.markup.view.MarkupViewConfiguration.readConfiguration(MarkupViewConfiguration.groovy)
        at grails.views.GenericViewConfiguration$readConfiguration.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at grails.views.AbstractGroovyTemplateCompiler.run(AbstractGroovyTemplateCompiler.groovy:101)
        at grails.plugin.markup.view.MarkupViewCompiler.main(MarkupViewCompiler.groovy:41)
Caused by: java.lang.IllegalStateException: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
        at org.slf4j.impl.Log4jLoggerFactory.<clinit>(Log4jLoggerFactory.java:54)
        ... 22 more
:compileGmlViews FAILED

**Comment by jameskleeh** [comment]
Try `compile "org.slf4j:slf4j-api:1.7.22"`

**Comment by Veeramanikandan1493** [comment]
I had included `compile "org.slf4j:slf4j-api:1.7.22"` in build.gradle and war created successfully then while deploying java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory occured.
But I had found following jars in app directory in tomcat  server

> /home/user/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1/WEB-INF/lib/jul-to-slf4j-1.7.22.jar
/home/user/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1/WEB-INF/lib/jcl-over-slf4j-1.7.22.jar
/home/user/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1/WEB-INF/lib/log4j-over-slf4j-1.7.22.jar

**Comment by graemerocher** [comment]
The issue here is the `embedded-mongodb` plugin. It makes the `provided` graph look like:

```
provided - much like compile, but indicates that you expect the JDK or a container to provide it. It is only available on the compilation classpath, and is not transitive.
+--- org.springframework.boot:spring-boot-starter-tomcat: -> 1.4.4.RELEASE
|    +--- org.apache.tomcat.embed:tomcat-embed-core:8.5.11
|    +--- org.apache.tomcat.embed:tomcat-embed-el:8.5.11
|    \--- org.apache.tomcat.embed:tomcat-embed-websocket:8.5.11
|         \--- org.apache.tomcat.embed:tomcat-embed-core:8.5.11
\--- org.grails.plugins:embedded-mongodb:1.0.1
     \--- de.flapdoodle.embed:de.flapdoodle.embed.mongo:1.50.5
          \--- de.flapdoodle.embed:de.flapdoodle.embed.process:1.50.2
               +--- commons-io:commons-io:2.4
               +--- org.apache.commons:commons-lang3:3.1
               +--- net.java.dev.jna:jna:4.0.0 -> 4.2.2
               +--- net.java.dev.jna:jna-platform:4.0.0
               |    \--- net.java.dev.jna:jna:4.0.0 -> 4.2.2
               +--- org.apache.commons:commons-compress:1.10
               \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.22
```

So all of the transitives of `embedded-mongodb` are no longer included in the WAR. The `provided` scope only really seems to work ok for dependencies that don't have transitive dependencies. In this case altering the scope to `testRuntime` fixes the problem:

```
testRuntime "org.grails.plugins:embedded-mongodb:1.0.1"
```

The `mongodb` feature of the `base` profile will need to be updated with this change.

**Comment by jameskleeh** [comment]
Fixed with `provided "org.grails.plugins:embedded-mongodb:1.0.2"`
