### ISSUE TITLE
Rollback annotation in integration test does not work in Grails 3.2.7

### ISSUE THREAD

**Issue by tepsl** [grails/grails-core#10522]
Integration test code such as below always fails;
```
@Integration
@Rollback
@Slf4j
class FooServiceSpec extends Specification {
	long testerId = 12345678
	def setup() {
		User u = new User()
		u.id = testerId
		u.save()
	}
```

The exception, which occurs at `setup` function, whose except of the message is like;
```
org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is rolled back; nested exception is org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Cannot rollback transaction in current status [COMMITTED]

	at org.grails.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:183)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at example.FooServiceSpec.setup(FooServiceSpec.groovy)
```

`@Rollback` is meant for testing and had been working before Grails 3.2.5.
(I haven't tested from Grails 3.2.5 to 3.2.6 because it had default datasource related bugs.)

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by tepsl** [comment]
@graemerocher 
I'm very sorry that providing an example is much more difficult than I expected.
I'm still struggling.
