### ISSUE TITLE
Any grails 3.2.7 task gives: Could not reserve enough space for object heap

### ISSUE THREAD

**Issue by biohazardxxx** [grails/grails-core#10532]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [NOT applicable] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new application with
`grails create-app com.example.myApp`
2. Try to run it with `grails run-app`

### Expected Behaviour

Application should start as expected

### Actual Behaviour

Error message appears:
> C:\GrailsWorkspace\myApp>
> 
> | Resolving Dependencies. Please wait...
> | Error Error initializing classpath: Unable to start the daemon process.
> This problem might be caused by incorrect configuration of the daemon.
> For example, an unrecognized jvm option is used.
> Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.4.1/userguide/gradle_daemon.html
> Please read the following process output to find out more:
> -----------------------
> Error occurred during initialization of VM
> Could not reserve enough space for object heap
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
>  (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
> org.gradle.api.GradleException: Unable to start the daemon process.
> This problem might be caused by incorrect configuration of the daemon.
> For example, an unrecognized jvm option is used.
> Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.4.1/userguide/gradle_daemon.html
> Please read the following process output to find out more:
> -----------------------
> Error occurred during initialization of VM
> Could not reserve enough space for object heap
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> 
>         at org.gradle.launcher.daemon.bootstrap.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:34)
>         at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:152)
>         at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:135)
>         at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:208)
>         at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:130)
>         at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:127)
>         at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:81)
>         at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:59)
>         at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:40)
>         at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
>         at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:34)
>         at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:141)
>         at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:126)
>         at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:208)
>         at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection$CancellableActionRunner.run(CancellableConsumerConnection.java:118)
>         at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:64)
>         at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:59)
>         at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:79)
>         at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
>         at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
>         at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
>         at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
>         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
> | Error Error initializing classpath: Unable to start the daemon process.
> This problem might be caused by incorrect configuration of the daemon.
> For example, an unrecognized jvm option is used.
> Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.4.1/userguide/gradle_daemon.html
> Please read the following process output to find out more:
> -----------------------
> Error occurred during initialization of VM
> Could not reserve enough space for object heap
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.

### Environment Information

- **Operating System**: Windows 10 x64
- **Grails Version:** 3.2.7
- **JDK Version:** 1.8.0
- **Container Version (If Applicable):** default

### Example Application

- TODO: link to github repository with example that reproduces the issue
No need for sample application here I think!

**Comment by biohazardxxx** [comment]
it turned out that my JAVA_HOME was pointing to another path than the java folder in my PATH environment variable. Check at a cmd window with

ECHO %JAVA_HOME%
ECHO %PATH%
