### ISSUE TITLE
NPE during Domain.save()

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10574]
- [ ] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

With grails 3.1.15 everything works well  
Sorry, I can't provide code example now, but it simple save method call in controller action

### Expected Behaviour

Tell us what should happen

### Actual Behaviour

Regularly on production I see following exception. It happens only in one place:  

```
java.lang.NullPointerException: null
at org.hibernate.action.internal.CollectionRecreateAction.execute(CollectionRecreateAction.java:51)
at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:582)
at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:456)
at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1295)
at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.flushSession(AbstractHibernateGormInstanceApi.groovy:279)
at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi$_performSave_closure3.doCall(AbstractHibernateGormInstanceApi.groovy:244)
at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:286)
at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:230)
at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:116)
at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.performSave(AbstractHibernateGormInstanceApi.groovy:241)
at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:158)
at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
```

### Environment Information

- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0.121

gormVersion=6.0.9.RELEASE
compile "org.grails.plugins:hibernate5"
compile "org.hibernate:hibernate-core:5.1.3.Final"
compile "org.hibernate:hibernate-ehcache:5.1.3.Final"

**Comment by demon101** [comment]
@graemerocher I can't reproduce it locally. On production, I can't debug. 

Is it possible to add error log in CollectionRecreateAction.execute method?

Now NPE occurs in line:
`getSession().getPersistenceContext().getCollectionEntry( collection ).afterAction( collection );`

Null can be returned by:
```
getSession()
getSession().getPersistenceContext()
getSession().getPersistenceContext().getCollectionEntry( collection )
```
But I can't find the problem by gaze

**Comment by graemerocher** [comment]
Nope, that is part of Hibernate, which we have no control over. Feel free to report the issue to https://hibernate.atlassian.net/projects/HHH

**Comment by demon101** [comment]
I have code like:
```
def chapter = new Chapter(...)
....      
chapter.save()
def item = new Item(....)
...
item.chapter = chapter
item.save(flush: true)
... 
chapter.addToItems(item)
...
chapter.save(flush: true) // have buisness logic in triggers
```
Chapter has many Items.

The bug was fixed by replacing ugly code 
`chapter.addToItems(item) -> chapter.refresh()`
The bug can be closed
