### ISSUE TITLE
 The current request does not support Async processing

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10585]
In service method, where is a code like

`Domain.async.task {`

It works for grails 3.1.15, but for grails 3.1.16 it fails:

14/04 20:09:01.883 ERROR grails.app.controllers.XXXXController - error during upload
java.lang.IllegalStateException: The current request does not support Async processing
at org.springframework.util.Assert.state(Assert.java:392)
at grails.async.web.AsyncGrailsWebRequest.startAsync(AsyncGrailsWebRequest.groovy:75)
at org.grails.plugins.web.async.WebRequestPromiseDecorator.<init>(WebRequestPromiseDecorator.groovy:42)
at org.grails.plugins.web.async.WebRequestPromiseDecoratorLookupStrategy.findDecorators(WebRequestPromiseDecoratorLookupStrategy.groovy:36)
at grails.async.factory.AbstractPromiseFactory.applyDecorators(AbstractPromiseFactory.groovy:69)
at grails.async.factory.AbstractPromiseFactory.createPromise(AbstractPromiseFactory.groovy:61)
at grails.async.Promises.createPromise(Promises.groovy:153)
at org.grails.datastore.gorm.async.GormAsyncStaticApi.task(GormAsyncStaticApi.groovy:58)
at org.grails.datastore.gorm.async.GormAsyncStaticApi$task.call(Unknown Source)
at XXXX.processXXXX(XXXXService.groovy:55)

- **Operating System**: TODO
- **Grails Version:** 3.1.16
- **Container Version (If Applicable):** Tomcat 8

What wrong? Is it bug of Grails?

**Comment by graemerocher** [comment]
We have an ISSUE_TEMPLATE for a reason, please follow it and provide all of the requested information including a sample application that reproduces the issue.

See https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

**Comment by demon101** [comment]
@graemerocher the bug only reproducible in grails 3.1.16. In Grails 3.1.15 and 3.2.8 everything works well 
If you want, you can reject the issue.

**Comment by demon101** [comment]
@graemerocher this bug was introduced by 
https://github.com/grails/grails-core/commit/067e146e09298e8fad932d99a1b3c1ad9c079eea.

You have added code in WebRequestPromiseDecorator line 42 newWebRequest.startAsync() and it fails (see stacktrace in description)

```
newWebRequest = new AsyncGrailsWebRequest(currentServletRequest, webRequest.currentResponse, webRequest.servletContext,webRequest.applicationContext)
newWebRequest.addParametersFrom(webRequest.params)
asyncManager.setAsyncWebRequest(newWebRequest)
newWebRequest.startAsync()
```

in newWebRequest.startAsync() newWebRequest.request.asyncSupported != true

Is it enough for you for fix it?

**Comment by demon101** [comment]
The error was caused by tomcat valve, by default it has asyncSupported = false
