### ISSUE TITLE
IOException: Thread signal failed on running Grails 3.2.8 integration tests for rest-api profile

### ISSUE THREAD

**Issue by sagrawal31** [grails/grails-core#10594]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided

### Steps to Reproduce

1. Create a Grails 3.2.8 with **rest-api** profile `grails create-app integration-test --profile=rest-api`
2. Create a service with a simple method
3. Create a integration test and call the service method with passing condition
4. Change the `compile` to `provided` in `build.gradle` for `org.springframework.boot:spring-boot-starter-tomcat`
5. Run the tests `grails test-app -integration`

### Expected Behaviour

The test should pass and no exception should be logged.

### Actual Behaviour

The tests are getting passed but an exception is being thrown in the terminal.

### Environment Information

- **Operating System**: MacOS Sierra
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_91
- **Container Version (If Applicable):** N/A

### Example Application

Here is an application that has an integration test that reproduces this problem: https://github.com/wizpanda/integration-thread-exception The 2nd commit https://github.com/wizpanda/integration-thread-exception/commit/93658e74fbb78cd48185e4fe4055c40959874fbb has the actual changes to reproduce the issue.

### Description

I upgraded my application from Grails **3.2.3** to Grails **3.2.8**. When I'm running the integration tests using `grails test-app -integration`, all tests are being executed & passed but I'm seeing additional exception in the console. Full console output as follows:

```java
# shashank @ Shashanks-MBP in ~/Projects/integration-test on git:master o [19:42:32] C:130
$ grails test-app -integration 
✓  Using grails version 3.2.8
| Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL

Total time: 1.486 secs
:compileJava UP-TO-DATE
:compileGroovy
:buildProperties UP-TO-DATE
:processResources UP-TO-DATE
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:compileIntegrationTestJava UP-TO-DATE
:compileIntegrationTestGroovy
:processIntegrationTestResources UP-TO-DATE
:integrationTestClasses
:integrationTest
2017-04-19 19:42:57.411 ERROR --- [       Thread-8] o.a.coyote.http11.Http11NioProtocol      : Failed to stop end point associated with ProtocolHandler ["http-nio-auto-1"]

java.io.IOException: Thread signal failed
        at sun.nio.ch.NativeThread.signal(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.implCloseSelectableChannel(ServerSocketChannelImpl.java:292)
        at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:234)
        at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
        at sun.nio.ch.ServerSocketAdaptor.close(ServerSocketAdaptor.java:137)
        at org.apache.tomcat.util.net.NioEndpoint.unbind(NioEndpoint.java:311)
        at org.apache.tomcat.util.net.AbstractEndpoint.stop(AbstractEndpoint.java:1033)
        at org.apache.coyote.AbstractProtocol.stop(AbstractProtocol.java:633)
        at org.apache.catalina.connector.Connector.stopInternal(Connector.java:1018)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:498)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:814)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:353)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.stopTomcat(TomcatEmbeddedServletContainer.java:238)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.stop(TomcatEmbeddedServletContainer.java:292)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.stopAndReleaseEmbeddedServletContainer(EmbeddedWebApplicationContext.java:306)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onClose(EmbeddedWebApplicationContext.java:155)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1015)
        at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:928)

2017-04-19 19:42:57.420 ERROR --- [       Thread-8] o.apache.catalina.core.StandardService   : Failed to stop connector [Connector[HTTP/1.1-auto-1]]

org.apache.catalina.LifecycleException: Failed to stop component [Connector[HTTP/1.1-auto-1]]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:238)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:498)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:814)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:353)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.stopTomcat(TomcatEmbeddedServletContainer.java:238)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.stop(TomcatEmbeddedServletContainer.java:292)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.stopAndReleaseEmbeddedServletContainer(EmbeddedWebApplicationContext.java:306)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onClose(EmbeddedWebApplicationContext.java:155)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1015)
        at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:928)
Caused by: org.apache.catalina.LifecycleException: Protocol handler stop failed
        at org.apache.catalina.connector.Connector.stopInternal(Connector.java:1020)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        ... 11 common frames omitted
Caused by: java.io.IOException: Thread signal failed
        at sun.nio.ch.NativeThread.signal(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.implCloseSelectableChannel(ServerSocketChannelImpl.java:292)
        at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:234)
        at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
        at sun.nio.ch.ServerSocketAdaptor.close(ServerSocketAdaptor.java:137)
        at org.apache.tomcat.util.net.NioEndpoint.unbind(NioEndpoint.java:311)
        at org.apache.tomcat.util.net.AbstractEndpoint.stop(AbstractEndpoint.java:1033)
        at org.apache.coyote.AbstractProtocol.stop(AbstractProtocol.java:633)
        at org.apache.catalina.connector.Connector.stopInternal(Connector.java:1018)
        ... 12 common frames omitted

:mergeTestReports

BUILD SUCCESSFUL

Total time: 18.088 secs
| Tests PASSED
```

### Additional Informations

1. When I reverted the scope of `org.springframework.boot:spring-boot-starter-tomcat` from `provided` to `compile`, that exception disappeared.
2. This problem is only happening for `rest-api` profile not for the `web` profile (in 3.2.8)

http://stackoverflow.com/questions/43293595/ioexception-thread-signal-failed-on-running-grails-3-2-8-integration-tests

**Comment by graemerocher** [comment]
Can't reproduce this personally, looks like a Gradle issue IMO

**Comment by sagrawal31** [comment]
Oh! I'll try to gather some more information.

**Comment by sagrawal31** [comment]
@graemerocher I think I found the issue. This is because `gradle` is installed globally (using sdkman) in my system with version 3.1 so probably `grails` command is using that gradle installation instead of gradle wrapper available within the repository and Grails 3.2.8 requires Gradle 3.4.1. So difference in Gradle version is causing this issue. As soon as I removed the global installation of gradle, this is no longer the issue.

**Comment by sagrawal31** [comment]
Am I correct? If yes, is there a way to force the `grails` command to use the gradle wrapper if available?

**Comment by HardikModha** [comment]
@sagrawal31 I don't know if we can force grails to use gradle wrapper available but we can use gradle wrapper to run the tests. `./gradlew test`

**Comment by sdelamo** [comment]
`./gradle check` will run both (unit and integration tests)

**Comment by graemerocher** [comment]
Grails uses the version of Gradle configured with SDK man if it is available. See https://github.com/grails/grails-core/blob/master/grails-shell/src/main/groovy/org/grails/cli/gradle/GradleUtil.groovy#L45

If you don't want this you can specify `GRAILS_GRADLE_HOME`
