### ISSUE TITLE
grails 3.2.6 tomcat 8.5 deployment (no problem with standalone app mode deployment) - intermittent NPE when deploying the war

### ISSUE THREAD

**Issue by tyagiakhilesh** [grails/grails-core#10608]
I am facing a null pointer exception while trying to deploy the war into tomcat 8.5.  This is the stack trace.
```
Caused by: java.lang.NullPointerException
    at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.findActionRoles(AnnotationFilterInvocationDefinition.groovy:458)
    at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.findAnnotations(AnnotationFilterInvocationDefinition.groovy:425)
    at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.findAnnotations(AnnotationFilterInvocationDefinition.groovy)
    at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.findControllerAnnotations(AnnotationFilterInvocationDefinition.groovy:382)
    at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.initialize(AnnotationFilterInvocationDefinition.groovy:223)
    at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition$initialize.call(Unknown Source)
    at grails.plugin.springsecurity.SpringSecurityCoreGrailsPlugin.initializeFromAnnotations(SpringSecurityCoreGrailsPlugin.groovy:770)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
I also tried to seek help on SO, but to no avail. This is my [question](http://stackoverflow.com/questions/43594786/gradle-war-vs-gradle-assemble-grails-3-2-6-and-sec-plugin-3-1-2)

Even though, It looks like the problem is coming from Spring Security plugin, but when I did remote debugging of tomcat, I can see that [DefaultGrailsApplication.java#getArtefact(String artefactType, String name)](https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/grails/core/DefaultGrailsApplication.java) is returning null when artifact type is controller and my valid class names. This is happening randomly.

### Task List

- [ ] Steps to reproduce provided
* Build my app using `gradlew clean assemble`
* Deployed it in tomcat 8.5
* Issue is intermittent. But critical for reliability of app. You see what I mean?!

- [ ] Stacktrace (if present) provided
* Provided above.
- [ ] Example that reproduces the problem uploaded to Github
* I have not tried it with any simple example. I have been working with many small samples of grails but mostly with intellij. _**This problem appears only when I am trying to deploy on tomcat. Not as a standalone app.**_

### Expected Behaviour
I should not see this intermittent NPE.
### Actual Behaviour

I see NPE. Also another observation is,  I see spring security grails plugin being loaded twice. And this exception is thrown, when tomcat is trying to refresh the context. First time, it never happens.

### Environment Information

- **Operating System**: CentOS 7
- **Grails Version:** 3.2.6
- **JDK Version:** 1.8.121
- **Container Version (If Applicable):** N/A

### Example Application
Don't have it.

**Comment by tyagiakhilesh** [comment]
I have posted the solution for this [here](http://stackoverflow.com/a/43680964/1229355). Moved cxf plugin above security plugin and I don't see this anymore.
