### ISSUE TITLE
500 error from default REST controller if show(ID) format is invalid

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-core#10612]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the repo
2. grails run-app

The index page of the app redirects to "/test/abc"

### Expected Behaviour

The app should respond with a 400 error, with a message along the lines of "'abc' is not a valid value for params.id"

### Actual Behaviour

HTTP 500 error.

`Caused by: java.lang.IllegalArgumentException: id to load is required for loading
	at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:93)
	at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:63)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2759)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2741)
	at org.hibernate.internal.SessionImpl.get(SessionImpl.java:978)
	at org.grails.orm.hibernate.GrailsHibernateTemplate$2.doInHibernate(GrailsHibernateTemplate.java:349)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:286)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.get(GrailsHibernateTemplate.java:346)
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.get(AbstractHibernateGormStaticApi.groovy:89)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.get(GormEntity.groovy:518)
	at grails.rest.RestfulController.queryForResource(RestfulController.groovy:235)
	at grails.rest.RestfulController.$tt__show(RestfulController.groovy:73)`

_Note: If I explicitly create a RestfulController with show(Long id), the errors collection is populated, but the **rejectedValue** in the error is null, not "abc"._

### Environment Information

- **Operating System**: Win7 x64
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_121-b13

### Example Application

[https://github.com/rmorrise/controller-param-test](https://github.com/rmorrise/controller-param-test)

**Comment by graemerocher** [comment]
Fixed in 3.2.9
