### ISSUE TITLE
replicaSet not working with Grails 3.2.3

### ISSUE THREAD

**Issue by scharanjit** [grails/grails-core#10640]
I've my grails app with below configuration

| Grails Version: 3.2.3
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_121

**Build.gradle** 
 **compile 'org.grails.plugins:mongodb' // Mongo DB plug-in**

application.groovy configuration

grails {
    mongodb {
        replicaSet =  ["mongo-0:27017","mongo-1:27017","mongo-2:27017"]
        username = ""
        password = ""
        databaseName = "mongo-dev"
        encryption {
            enabled = false
        }
    }
}

["mongo-0:27017","mongo-1:27017","mongo-2:27017"] is the cluster of mongo db

**If I'm trying to connect to each database individually, It is working fine.

But with **replicaSet** I'm getting below error**

`

 2017-05-17 08:15:55,226 [localhost-startStop-1] INFO  org.mongodb.driver.cluster  - Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}

2017-05-17 08:15:55,253 [cluster-ClusterId{value='591c3efb2568a341831481ec', description='null'}-127.0.0.1:27017] INFO  org.mongodb.driver.cluster  - Exception in monitor thread while connecting to server 127.0.0.1:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
	... 3 common frames omitted

`

Instead of connecting to mongo cluster of db's, it is trying to connect localhost (i.e. 127.0.0.1:27017)

Please help

**Comment by graemerocher** [comment]
replicaSet is no longer supported by the driver, instead you have to use a connection string. See https://docs.mongodb.com/manual/reference/connection-string/
