### ISSUE TITLE
Creating Spring Beans in Unit Tests (HibernateSpecification) is broken in 3.3.0.M2

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10662]
Take a look at the following [unit test](https://github.com/saw303/grails-issues/blob/grails-3.3.0/src/test/groovy/grails/issues/GameControllerSpec.groovy#L12) which was working in 3.2.x.

```
static doWithSpring = {
        gameService(GameService)
}
```
seems to be broken in 3.3.0.M2

**Comment by jameskleeh** [comment]
Define broken. What isn't working ?

**Comment by jameskleeh** [comment]
I cannot reproduce

**Comment by saw303** [comment]
Well the example is actually attached. The link above points to a Git repository you can use to reproduce the problem. Please pull it and checkout `grails-3.3.0` branch.

The problem is, that the gameService is not injected into the `Game` domain class. 

```
java.lang.NullPointerException: Cannot invoke method verifyAvailableTickets() on null object

	at grails.issues.Game._clinit__closure1$_closure4(Game.groovy:17)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.gorm.validation.constraints.ValidatorConstraint.processValidate(ValidatorConstraint.java:100)
	at org.grails.datastore.gorm.validation.constraints.AbstractConstraint.validate(AbstractConstraint.java:88)
	at grails.gorm.validation.DefaultConstrainedProperty.validate(DefaultConstrainedProperty.groovy:601)
	at grails.gorm.validation.PersistentEntityValidator.validatePropertyWithConstraint(PersistentEntityValidator.groovy:296)
	at grails.gorm.validation.PersistentEntityValidator.validate(PersistentEntityValidator.groovy:73)
	at org.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate_closure1(AbstractHibernateGormValidationApi.groovy:88)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:298)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:242)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:116)
	at org.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:79)
	at org.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:52)
	at org.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:51)
	at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:97)
	at grails.issues.GameController.$tt__saveGame(GameController.groovy:17)
	at grails.issues.GameController.saveGame_closure1(GameController.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at grails.issues.GameControllerSpec.Create a game using the wizard(GameControllerSpec.groovy:29)

```

**Comment by jameskleeh** [comment]
It was not clear to me the file you linked was part of an example project

**Comment by jameskleeh** [comment]
The service is not injected because of this configuration setting

https://github.com/saw303/grails-issues/blob/grails-3.3.0/grails-app/conf/application.yml#L12

**Comment by saw303** [comment]
It changed the `grails.gorm.autowire` to `true`. The test keeps failing with the same exception, since the service is not injected into the domain instance.

**Comment by sdelamo** [comment]
It seems global grails.gorm.autowire = true is broken in 3.3.0.M2

see: 

https://github.com/grails/grails-core/issues/10678

and: 

https://github.com/grails/grails-core/issues/10679
