### ISSUE TITLE
Grails 3.3.0: Some jars missing from maven repository

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-core#10756]
- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. grails create-app test
2. Following the instruction at https://github.com/dsyer/spring-boot-thin-launcher
3. grails package
4. java -jar .\build\libs\test-0.1.war --thin.dryrun=true

### Expected Behaviour

Jars could be fetched from https://repo1.maven.org/maven2.

### Actual Behaviour

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:112)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:81)
Caused by: java.lang.RuntimeException: Could not find artifact org.grails:grails-gsp:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-gsp:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails:grails-web-gsp:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-web-gsp:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails:grails-web-sitemesh:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-web-sitemesh:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:converters:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:converters:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:cache:jar:4.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:cache:jar:4.0.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:hibernate5:jar:6.1.6 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:hibernate5:jar:6.1.6 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:gsp:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:gsp:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact com.bertramlabs.plugins:asset-pipeline-grails:jar:2.14.2 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact com.bertramlabs.plugins:asset-pipeline-grails:jar:2.14.2 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails:grails-gorm-testing-support:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-gorm-testing-support:jar:1.0.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:geb:jar:1.1.1 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:geb:jar:1.1.1 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails:grails-web-testing-support:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-web-testing-support:jar:1.0.0 in central (https://repo1.maven.org/maven2)
        at org.springframework.boot.loader.thin.DependencyResolver.dependencies(DependencyResolver.java:205)
        at org.springframework.boot.loader.thin.PathResolver.extract(PathResolver.java:182)
        at org.springframework.boot.loader.thin.PathResolver.resolve(PathResolver.java:94)
        at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchives(ThinJarLauncher.java:324)
        at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:186)
        at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:139)
        ... 6 more
```

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8

**Comment by jeffbrown** [comment]
Please link to a sample project which demonstrates the problem.

Thanks for the feedback.

**Comment by todoubaba** [comment]
[test-thin.zip](https://github.com/grails/grails-core/files/1185222/test-thin.zip)

run:
```
grails package
java -jar .\build\libs\test-thin-0.1.war --thin.root="d:\repo"
```

**Comment by todoubaba** [comment]
As @dsyer suggested, using maven's settings.xml could workaround this issue. By the way, to make the app running, it should be packaged to a jar (by removing `apply plugin:"war"`).

**Comment by graemerocher** [comment]
I have requested that https://bintray.com/grails/grails-core/grails-testing-support be included in maven central which should resolved this issue once the inclusion request is processed
