### ISSUE TITLE
Shared constraint validation seems to fail in integration tests on Validateable object with Grails 3.3.0

### ISSUE THREAD

**Issue by sarbogast** [grails/grails-core#10782]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to reproduce

In [this project](https://github.com/sarbogast/validateable-test), there is a DTO object that implements `Validateable` with a shared constraint that is validated inside a controller. Then I have an integration test that calls this controller and I get an exception that tells me I'm using a shared constraint that doesn't exist.

```
grails.gorm.validation.exceptions.ValidationConfigurationException: Property [validateable.test.MyDto.name] references shared constraint [nonEmpty:null], which doesn't exist!
	at org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator.applySharedConstraints(DefaultConstraintEvaluator.java:198)
	at org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator.evaluate(DefaultConstraintEvaluator.java:173)
	at grails.validation.Validateable$Trait$Helper.validate(Validateable.groovy:161)
	at grails.validation.Validateable$Trait$Helper.validate(Validateable.groovy:93)
	at validateable.test.ApplicationController.index(ApplicationController.groovy:14)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment Information

- **Operating System**: MacOSX Sierra
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8

### Example Application

https://github.com/sarbogast/validateable-test

**Comment by danielritter** [comment]
I have a similar issue. I get the error message above when I use application.yml instead of application.groovy.

This code snippet in application.yml does not work:

```
grails:
    gorm:
        failOnError: true
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
        # Default constraints.
        default:
            constraints:
                defaultTextInputConstraint:
                    blank: false
                    nullable: true
                    size: 1..128
```


This code snippet in application.groovy works:

```
grails.gorm.default.constraints = {
    defaultTextInputConstraint(blank: false, nullable: true, size: 1..128)
}
```

In my opinion the code snippet in the application.yml version should also work.

**Comment by graemerocher** [comment]
The issue is not the same as this one. Currently default constraints can only be specified in `application.groovy` as they require the Groovy DSL

**Comment by danielritter** [comment]
Should I create a new ticket for that or is not planned to implement this?

**Comment by jameskleeh** [comment]
@danielritter It's not possible

**Comment by tircnf** [comment]
This same issue exists with Units tests. (or at least, unit tests that implement HibernateSpec).

**Comment by frangarcia** [comment]
In case you end up here with the same issue as this ticket for Grails 5.1.8, please move the shared constraints to grails-app/conf/runtime.groovy https://docs.grails.org/5.1.8/guide/single.html#sharingConstraints
