### ISSUE TITLE
On upgrading Grails rest application from 3.1.9 to 3.3.0, it searches for "h2" driver even when I am using MongoDB plugin

### ISSUE THREAD

**Issue by ChiranjibKarn** [grails/grails-core#10781]
My Grails 3.1.9 rest application with spring-security-rest plugin is working fine against Mongo DB 3.4.2 now, but on upgrading the grails version to 3.3.0, it started throwing following error:

> 18.08.2017 11:47:30.973 [main] WARN  o.s.j.d.LazyConnectionDataSourceProxy - Could not retrieve default auto-commit and transaction isolation settings
java.sql.SQLException: No suitable driver found for jdbc:h2:mem:grailsDB;MVCC=TRUE;LOCK_TIMEOUT=10000
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153)
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144)
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)
        at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy.afterPropertiesSet(LazyConnectionDataSourceProxy.java:162)
        at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy.<init>(LazyConnectionDataSourceProxy.java:106)
        at org.grails.datastore.gorm.jdbc.connections.DataSourceConnectionSourceFactory.proxy(DataSourceConnectionSourceFactory.java:95)
        at org.grails.datastore.gorm.jdbc.connections.DataSourceConnectionSourceFactory.create(DataSourceConnectionSourceFactory.java:88)
        at org.grails.datastore.gorm.jdbc.connections.DataSourceConnectionSourceFactory.create(DataSourceConnectionSourceFactory.java:24)
        at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
        at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
        at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
        at org.grails.plugins.datasource.DataSourceConnectionSourcesFactoryBean.afterPropertiesSet(DataSourceConnectionSourcesFactoryBean.groovy:56)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.config.BeanExpressionContext.getObject(BeanExpressionContext.java:56)
        at org.springframework.context.expression.BeanExpressionContextAccessor.read(BeanExpressionContextAccessor.java:42)
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:211)
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94)
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:81)
        at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:51)
        at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:87)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)

Now, on login it generates a token (I can see it in API response) but does not persist in Mongo DB. It seems the token is being persisted in mem-db (h2), hence all other APIs start responding with HTTP status 401. 

### Task List
- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Expected Behaviour

It should not search for h2 driver since am using grails mongodb plugin and
the authentication token should get persisted in Mongo DB, instead of h2.

### Actual Behaviour

On application start-up, it searches for h2 driver and throws "java.sql.SQLException: No suitable driver found for jdbc:h2:mem:grailsDB;MVCC=TRUE;LOCK_TIMEOUT=10000"

### Environment Information

- **Windows 10**: 
- **3,3,0:** 
- **1.8.0_131:** 
- **Tomcat 8:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
I am unable to reproduce this in a new application. Can you check that you do not have `h2` on your class path and otherwise please provide an example that reproduces the issue

**Comment by ChiranjibKarn** [comment]
There is no trace of "h2" in the project.
Also, while upgrading Grails from 3.1.9 to 3.3.0, I was getting following error on application boot:

> java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/FilterRegistrationBean
        at grails.plugin.springsecurity.SpringSecurityCoreGrailsPlugin$_doWithSpring_closure12.doCall(SpringSecurityCoreGrailsPlugin.groovy:196)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
        at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
        at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
        at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:559)
        at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:167)
        at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:171)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at mvp_backend.Application.main(Application.groovy:14)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean

This exception has disappeared on adding compile time dependency of spring-security-core plugin.
Now, I am using both spring-security-rest 2.0.0.M2 and spring-security-core 3.2.0.M1 plugins.

I need some more time to provide you an example.

**Comment by ChiranjibKarn** [comment]
Following are example projects, "example319" is on Grails 3.1.9 which is working fine (authentication token generates and a secure resource can be requested using that token, tested with Post-Man") and "example330" is the same project with updated dependencies on Grails 3.3.0 (I have put the log level INFO for development environment, on startup, this project searches for "h2" driver even when I am not using it anywhere).
Note: This project originally created with "Web" profile, but we are using it for "REST" application.
[example319.zip](https://github.com/grails/grails-core/files/1244173/example319.zip)
[example330.zip](https://github.com/grails/grails-core/files/1244174/example330.zip)

**Comment by graemerocher** [comment]
The reason is because you have the following in `application.groovy`

```
dataSource {
    dbCreate = "update"
    jmxExport = true
    pooled = true
}
```

Since you are not using a SQL data source is this necessary?

**Comment by ChiranjibKarn** [comment]
My bad, that config was there from beginning and I never noticed that, but it is working fine in Grails 3.1.9 with mongo db without any issue.
Removing it solved the issue but it started throwing error 

> o.s.s.c.bcrypt.BCryptPasswordEncoder     : Encoded password does not look like BCrypt
for same password that used to work before.

**Comment by graemerocher** [comment]
Please report the latter issue to https://github.com/grails-plugins/grails-spring-security-core/issues and provide an example

**Comment by ChiranjibKarn** [comment]
Thanks.
I have posted an issue over here
https://github.com/alvarosanchez/grails-spring-security-rest/issues/347
