### ISSUE TITLE
Upgrade from Grails 3.1.8 to 3.3.0 or any version in between causes an error.

### ISSUE THREAD

**Issue by mangelo123** [grails/grails-core#10780]
I am getting a strange error within the GORM classes during execution of unit tests, so I thought this would be  a good time to check the upgrade path since we are on 3.1.8.

I cannot run 'grails set-version' because I get the same error that I will show below. When I 'cd' to my application directory and enter 'grails' to enter command line mode, I immediately get the following (this is with --stacktrace):

```
| Error Error occurred running Grails CLI: startup failed:
script1502995053112803344676.groovy: 1: unable to resolve class [package.name].service.FCUserDetailsService
 @ line 1, column 1.
   import [package.name].service.FCUserDetailsService
   ^

1 error
 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script1502995053112803344676.groovy: 1: unable to resolve class [package.name].service.FCUserDetailsService
 @ line 1, column 1.
   import [package.name].service.FCUserDetailsService
   ^

1 error

        at org.grails.config.CodeGenConfig.loadGroovy(CodeGenConfig.groovy:148)
        at org.grails.cli.GrailsCli.loadApplicationConfig(GrailsCli.groovy:593)
        at org.grails.cli.GrailsCli.initializeApplication(GrailsCli.groovy:292)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:270)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Error occurred running Grails CLI: startup failed:
script1502995053112803344676.groovy: 1: unable to resolve class [package.name].service.FCUserDetailsService
 @ line 1, column 1.
   import [package.name].service.FCUserDetailsService
   ^

1 error
```
The import that it is complaining about is in our application.groovy. I am getting nowhere trying to resolve this. The application runs fine in Grails 3.1.8

**Comment by graemerocher** [comment]
You cannot reference classes directly in `application.groovy` since it is used at build time. Move the configuration that references your classes to `runtime.groovy`
