### ISSUE TITLE
DomainUnitTest fails when using  MappingBuilder in domain class

### ISSUE THREAD

**Issue by nagysz** [grails/grails-core#10790]
In case of domain classes there are - at least - two ways two provide explicit database mapping. Doing it the old way (`static mapping = {}`) works with unit tests. However if I explicitly use `static mapping = orm ({})` (with proper static import) the unit test of the appropriate domain class throws a `ClassCastException`. This prevents unit testing of the domain classes, however the functionality is ok when running the application or using higher level tests.

### Steps to Reproduce

1. create new grails application
2. create domain class
3. add static import to domain class `import static grails.gorm.hibernate.mapping.MappingBuilder.*`
4. add mapping block to domain class: `static mapping = orm ({})`
5. run `grails test-app`
6. modify mapping in the domain class as follows: `static mapping = {}`
7. run `grails test-app`

### Expected Behaviour

The default generated unit test should fail in both runs.

### Actual Behaviour

The first run fails with an exception, the second run works as expected.

`java.lang.ClassCastException: org.grails.datastore.mapping.keyvalue.mapping.config.Family cannot be cast to org.grails.orm.hibernate.cfg.Mapping
	at org.grails.datastore.mapping.config.AbstractGormMappingFactory.createMappedForm(AbstractGormMappingFactory.java:87)
	at org.grails.datastore.mapping.keyvalue.mapping.config.GormKeyValueMappingFactory.createMappedForm(GormKeyValueMappingFactory.java:39)
	at org.grails.datastore.mapping.keyvalue.mapping.config.GormKeyValueMappingFactory.createMappedForm(GormKeyValueMappingFactory.java:28)
	at org.grails.datastore.mapping.keyvalue.mapping.config.KeyValuePersistentEntity.<init>(KeyValuePersistentEntity.java:35)
	at org.grails.datastore.mapping.keyvalue.mapping.config.KeyValueMappingContext.createPersistentEntity(KeyValueMappingContext.java:96)
	at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:274)
	at grails.testing.gorm.DataTest$Trait$Helper.mockDomains(DataTest.groovy:75)
	at org.grails.testing.gorm.spock.DataTestSetupSpecInterceptor.configureDataTest(DataTestSetupSpecInterceptor.groovy:88)
	at org.grails.testing.gorm.spock.DataTestSetupSpecInterceptor.intercept(DataTestSetupSpecInterceptor.groovy:41)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`

### Environment Information

- **Operating System**: Win10
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8.0_141

**Comment by nagysz** [comment]
Hi @jeffbrown , I supposed that it is a really trivial reproduction. But if it need be, I created an easy to grab example: https://github.com/nagysz/grails-mapping-domain-test

I hope it helps! Cheers

**Comment by jeffbrown** [comment]
@nagysz Thanks.  I was just flagging it as not having an example, not suggesting that you needed to provide one.  Often the example is helpful though. For example, the sample at https://github.com/nagysz/grails-mapping-domain-test/blob/master/grails-app/domain/exampleapp/MappedDomain.groovy in your project is doing something different than described in the description above (the description mentions invoking the `orm` method).  I don't yet know if that is relevant but having an executable example is almost always helpful.

Thanks for the feedback.

**Comment by nagysz** [comment]
@jeffbrown Hi Jeff! Sorry, I was in a hurry and just commited the 'working' version, where tests pass. I have pushed the version with the incorrect behaviour. I hope it helps!

Thanks

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/ae0e94733e4ec89f5f0e63dd1de80f9716bbc3ce
