### ISSUE TITLE
Grails application hangs

### ISSUE THREAD

**Issue by skorikovdm** [grails/grails-core#10848]
We have a grails 3.1.7 application аnd it hangs on production once or twice a day
We upgraded groovy jars to 2.4.11, but with no success

Stacktrace (filtered, removed same output):

"qtp791885625-110" #110 prio=5 os_prio=0 tid=0x00007fe7e001d000 nid=0x45b1 waiting on condition [0x00007fe756feb000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000dc0ac950> (a org.codehaus.groovy.util.ManagedConcurrentMap$Segment)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at org.codehaus.groovy.util.LockableObject.lock(LockableObject.java:37)
	at org.codehaus.groovy.util.AbstractConcurrentMapBase$Segment.removeEntry(AbstractConcurrentMapBase.java:174)
	at org.codehaus.groovy.util.ManagedConcurrentMap$Entry.finalizeReference(ManagedConcurrentMap.java:81)
	at org.codehaus.groovy.util.ManagedConcurrentMap$EntryWithValue.finalizeReference(ManagedConcurrentMap.java:115)
	at org.codehaus.groovy.util.ReferenceManager$1.removeStallEntries(ReferenceManager.java:86)
	at org.codehaus.groovy.util.ReferenceManager$1.afterReferenceCreation(ReferenceManager.java:94)
	at org.codehaus.groovy.util.ReferenceManager$2.afterReferenceCreation(ReferenceManager.java:111)
	at org.codehaus.groovy.util.ManagedReference.<init>(ManagedReference.java:36)
	at org.codehaus.groovy.util.ManagedReference.<init>(ManagedReference.java:40)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:53)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:36)
	at org.codehaus.groovy.reflection.CachedClass.getInterfaces(CachedClass.java:255)
	at org.codehaus.groovy.reflection.CachedClass.<init>(CachedClass.java:241)
	at org.codehaus.groovy.reflection.ClassInfo.createCachedClass(ClassInfo.java:352)
	at org.codehaus.groovy.reflection.ClassInfo.access$700(ClassInfo.java:41)
	at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:497)
	at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:488)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:40)
	at org.codehaus.groovy.reflection.ClassInfo.getCachedClass(ClassInfo.java:111)
	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:110)
	at org.codehaus.groovy.reflection.CachedClass$8.initValue(CachedClass.java:212)
	at org.codehaus.groovy.reflection.CachedClass$8.initValue(CachedClass.java:203)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:36)
	at org.codehaus.groovy.reflection.CachedClass.getInterfaces(CachedClass.java:255)
	at org.codehaus.groovy.reflection.CachedClass.<init>(CachedClass.java:241)
	at org.codehaus.groovy.reflection.ClassInfo.createCachedClass(ClassInfo.java:352)
	at org.codehaus.groovy.reflection.ClassInfo.access$700(ClassInfo.java:41)
	at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:497)
	at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:488)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:40)
	at org.codehaus.groovy.reflection.ClassInfo.getCachedClass(ClassInfo.java:111)
	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:110)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:182)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:218)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:230)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:171)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:161)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:144)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:253)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:285)
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.<init>(ClassMetaClassGetPropertySite.java:38)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createClassMetaClassGetPropertySite(AbstractCallSite.java:373)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGetPropertySite(AbstractCallSite.java:325)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.acceptGetProperty(AbstractCallSite.java:312)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at org.grails.web.mime.HttpServletRequestExtension.getMimeTypes(HttpServletRequestExtension.groovy:68)
	at sun.reflect.GeneratedMethodAccessor787.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:64)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at org.grails.web.mime.DefaultMimeTypeResolver.resolveRequestMimeType(DefaultMimeTypeResolver.groovy:53)
	at org.grails.web.mime.DefaultMimeTypeResolver.resolveRequestMimeType(DefaultMimeTypeResolver.groovy:51)
	at grails.web.mime.MimeTypeUtils.resolveMimeType(MimeTypeUtils.groovy:34)
	at grails.web.databinding.DataBindingUtils.resolveMimeType(DataBindingUtils.java:339)
	at grails.web.databinding.DataBindingUtils.getMimeType(DataBindingUtils.java:321)
	at grails.web.databinding.DataBindingUtils.createDataBindingSource(DataBindingUtils.java:308)
	at grails.artefact.Controller$Trait$Helper.initializeCommandObject(Controller.groovy:351)
	at grails.artefact.Controller$Trait$Helper$initializeCommandObject$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at ru.infosysco.fastwater.model.OrderController.initializeCommandObject(OrderController.groovy)

"qtp791885625-108" #108 prio=5 os_prio=0 tid=0x00007fe7db753000 nid=0x45ae waiting on condition [0x00007fe7571ee000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000dc0ac9b0> (a org.codehaus.groovy.util.ManagedConcurrentMap$Segment)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at org.codehaus.groovy.util.LockableObject.lock(LockableObject.java:37)
	at org.codehaus.groovy.util.AbstractConcurrentMap$Segment.put(AbstractConcurrentMap.java:104)
	at org.codehaus.groovy.util.AbstractConcurrentMap$Segment.getOrPut(AbstractConcurrentMap.java:100)
	at org.codehaus.groovy.util.AbstractConcurrentMap.getOrPut(AbstractConcurrentMap.java:38)
	at org.codehaus.groovy.runtime.metaclass.ThreadManagedMetaBeanProperty$ThreadBoundGetter.invoke(ThreadManagedMetaBeanProperty.java:183)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1849)
	at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1155)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3734)
	at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1167)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassGetPropertySite.getProperty(PogoMetaClassGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at ru.infosysco.fastwater.api.AbstractMethod.beforeInterceptor(AbstractMethod.groovy:309)

"qtp791885625-105" #105 prio=5 os_prio=0 tid=0x00007fe76a82a000 nid=0x45ab waiting on condition [0x00007fe7574ef000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000dcc012b8> (a org.codehaus.groovy.util.LockableObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at org.codehaus.groovy.util.LockableObject.lock(LockableObject.java:37)
	at org.codehaus.groovy.reflection.ClassInfo.lock(ClassInfo.java:363)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.setMetaClass(MetaClassRegistryImpl.java:273)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.setMetaClass(MetaClassRegistryImpl.java:296)
	at grails.util.GrailsMetaClassUtils.getExpandoMetaClass(GrailsMetaClassUtils.java:147)
	at grails.artefact.TagLibrary$Trait$Helper.propertyMissing(TagLibrary.groovy:149)
	at grails.artefact.TagLibrary$Trait$Helper$propertyMissing$3.call(Unknown Source)
	at asset.pipeline.grails.AssetsTagLib.propertyMissing(AssetsTagLib.groovy)
	at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaClassImpl.invokeMissingProperty(MetaClassImpl.java:879)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1858)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3734)
	at asset.pipeline.grails.AssetsTagLib.getProperty(AssetsTagLib.groovy)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:324)
	at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:318)
	at groovy.lang.Closure.getProperty(Closure.java:307)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at asset.pipeline.grails.AssetsTagLib$_closure7.doCall(AssetsTagLib.groovy:130)
	
"qtp791885625-104" #104 prio=5 os_prio=0 tid=0x00007fe7bc035800 nid=0x45aa waiting on condition [0x00007fe7575f2000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000dc0ac9e0> (a org.codehaus.groovy.util.ManagedConcurrentMap$Segment)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at org.codehaus.groovy.util.LockableObject.lock(LockableObject.java:37)
	at org.codehaus.groovy.util.AbstractConcurrentMap$Segment.put(AbstractConcurrentMap.java:104)
	at org.codehaus.groovy.util.AbstractConcurrentMap$Segment.getOrPut(AbstractConcurrentMap.java:100)
	at org.codehaus.groovy.util.AbstractConcurrentMap.getOrPut(AbstractConcurrentMap.java:38)
	at org.codehaus.groovy.runtime.metaclass.ThreadManagedMetaBeanProperty$ThreadBoundGetter.invoke(ThreadManagedMetaBeanProperty.java:183)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1849)
	at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1155)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3734)
	at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1167)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassGetPropertySite.getProperty(PogoMetaClassGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at ru.infosysco.fastwater.api.AbstractMethod.printJSON(AbstractMethod.groovy:245)

"qtp791885625-97" #97 prio=5 os_prio=0 tid=0x00007fe7f00b9000 nid=0x459e waiting on condition [0x00007fe757bf8000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000dc0acb90> (a org.codehaus.groovy.util.ManagedConcurrentMap$Segment)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at org.codehaus.groovy.util.LockableObject.lock(LockableObject.java:37)
	at org.codehaus.groovy.util.AbstractConcurrentMapBase$Segment.removeEntry(AbstractConcurrentMapBase.java:174)
	at org.codehaus.groovy.util.ManagedConcurrentMap$Entry.finalizeReference(ManagedConcurrentMap.java:81)
	at org.codehaus.groovy.util.ManagedConcurrentMap$EntryWithValue.finalizeReference(ManagedConcurrentMap.java:115)
	at org.codehaus.groovy.util.ReferenceManager$1.removeStallEntries(ReferenceManager.java:86)
	at org.codehaus.groovy.util.ReferenceManager$1.afterReferenceCreation(ReferenceManager.java:94)
	at org.codehaus.groovy.util.ReferenceManager$2.afterReferenceCreation(ReferenceManager.java:111)
	at org.codehaus.groovy.util.ManagedReference.<init>(ManagedReference.java:36)
	at org.codehaus.groovy.util.ManagedReference.<init>(ManagedReference.java:40)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:53)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:36)
	at org.codehaus.groovy.reflection.CachedClass.getCachedSuperClass(CachedClass.java:251)
	at org.codehaus.groovy.reflection.CachedClass$8.initValue(CachedClass.java:217)
	at org.codehaus.groovy.reflection.CachedClass$8.initValue(CachedClass.java:203)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:36)
	at org.codehaus.groovy.reflection.CachedClass.getInterfaces(CachedClass.java:255)
	at org.codehaus.groovy.reflection.CachedClass.<init>(CachedClass.java:241)
	at org.codehaus.groovy.reflection.stdclasses.CachedClosureClass.<init>(CachedClosureClass.java:30)
	at org.codehaus.groovy.reflection.ClassInfo.createCachedClass(ClassInfo.java:348)
	at org.codehaus.groovy.reflection.ClassInfo.access$700(ClassInfo.java:41)
	at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:497)
	at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:488)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:40)
	at org.codehaus.groovy.reflection.ClassInfo.getCachedClass(ClassInfo.java:111)
	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:110)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:182)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:218)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:230)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.<init>(ClosureMetaClass.java:196)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:169)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:161)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:144)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:253)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:285)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:257)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:881)
	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:34)
	at groovy.lang.Closure.<init>(Closure.java:222)
	at ru.infosysco.fastwater.service.OrderService$_listData_closure10.<init>(OrderService.groovy)

### Environment Information

- **Operating System**: CentOS 7.4
- **Grails Version:** 3.1.7
- **JDK Version:** 1.8.0_74
- **Container Version (If Applicable):** jetty 9.3.7

**Comment by skorikovdm** [comment]
It seems that we modified metaclass without synchronization
