### ISSUE TITLE
GrailsExceptionResolver leads to UrlMappingException for non-url-mapped requests

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#10866]
if requests that are not subject to grails url mapping (but handled by the spring-mvc, i.e. the `DispatcherServlet`) throw an exception, `GrailsExceptionResolver` leads to `UrlMappingException`.

a good example is a request to a spring boot actuator endpoint that throws an exception (see sample app).

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run sample app
2. hit `http://localhost:8080/sample`

### Expected Behaviour

the exception should be resolved by the `GrailsExceptionResolver` without another error / throwing another exception.

### Actual Behaviour

```
grails.web.mapping.exceptions.UrlMappingException: Unable to establish controller name to dispatch for [org.grails.web.mapping.RegexUrlMapping$1@1de26fb9]. Dynamic closure invocation returned null. Check your mapping file is correct, when assigning the controller name as a request parameter it cannot be an optional token!
	at org.grails.web.mapping.DefaultUrlMappingInfo.getControllerName(DefaultUrlMappingInfo.java:188)
	at org.grails.web.mapping.mvc.AbstractGrailsControllerUrlMappings.collectControllerMapping(AbstractGrailsControllerUrlMappings.groovy:198)
	at org.grails.web.mapping.mvc.AbstractGrailsControllerUrlMappings.match(AbstractGrailsControllerUrlMappings.groovy:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy69.match(Unknown Source)
	at org.grails.web.errors.GrailsExceptionResolver.resolveViewOrForward(GrailsExceptionResolver.java:164)
	at org.grails.web.errors.GrailsExceptionResolver.resolveException(GrailsExceptionResolver.java:92)
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1222)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1034)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
```

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 3.3.1
- **JDK Version:** oracle 8u131
- **Container Version (If Applicable):** n/a

### Example Application

- sample app will be referenced in a minute

**Comment by zyro23** [comment]
thx for milestone! i did also ping @sdelamo already if he could take a look.
>11:24 zyro @sergiodelamo if you got a minute to spare a quick look at that issue would be nice. it looks like that behavior may be an unintentional side effect of this change: https://github.com/grails/grails-core/commit/65dd138e3583fefb929348972dd733e4b134abf1#diff-b5fd463d1bb939d26a99171e70a43979R168
