### ISSUE TITLE
wrong BuildSettings.TARGET_DIR for multi-module project

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#10878]
given a multi module project structure like this (`myapp` contains the actual grails application that runs):
```
myapp-root
    myapp
    myapp-plugin
```
evaluating `BuildSettings.BASE_DIR` and `BuildSettings.TARGET_DIR` in `BootStrap`, you can see:

* `BuildSettings.BASE_DIR` is resolved correctly to `myapp-root/myapp`, but
* `BuildSettings.TARGET_DIR` is resolved to `myapp-root/build` instead of `myapp-root/myapp/build`.

i suspect this change: https://github.com/grails/grails-core/commit/877eb553b1d4673baf25500a8ce0f0ba7a9aa6a3 (fixing #10793) to be the cause.

looking at the code, i guess at the time of `BuildSettings.TARGET_DIR`'s static initialization, `BuildSettings.BASE_DIR` is still `null`, so `BuildSettings.TARGET_DIR` gets initialized as `new File(null, "build")` which is not correct for a multi-module project setup like outlined above.
the `static` initializer for `BuildSettings.BASE_DIR` comes later (too late) in the code.

ref. https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.4.2
> 9. Next, execute either the class variable initializers and static initializers of the class, or the field initializers of the interface, in textual order, as though they were a single block. 

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. use multi-module project (layout like describe above, for example)
2. add the following assertion to `BootStrap.init`

```groovy
assert BuildSettings.TARGET_DIR.absolutePath == BuildSettings.BASE_DIR.absolutePath + "/build"
```
### Expected Behaviour

assertion should pass

### Actual Behaviour

```
org.codehaus.groovy.runtime.powerassert.PowerAssertionError: assert BuildSettings.TARGET_DIR.absolutePath == BuildSettings.BASE_DIR.absolutePath + "/build"
                                                                                  |          |            |                |        |            |
                                                                                  build      |            false            |        |            /path/to/myapp-root/myapp/build
                                                                                             |                             |        /path/to/myapp-root/myapp
                                                                                             |                             /path/to/myapp-root/myapp
                                                                                             /path/to/myapp-root/build
    at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:404)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:650)
    at myapp.BootStrap$_closure1.doCall(BootStrap.groovy:14)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
```

this does also lead to an issue with the asset-pipeline-grails cache dir resolution:
* https://github.com/bertramdev/asset-pipeline/blob/rel-2.14.4/asset-pipeline-grails/src/main/groovy/asset/pipeline/AssetPipelineGrailsPlugin.groovy#L105
```
Exception in thread "Thread-15" java.io.FileNotFoundException: /path/to/myapp-root/build/.asscache
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1076)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at asset.pipeline.CacheManager.save(CacheManager.groovy:152)
	at asset.pipeline.CacheManager$save$8.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at asset.pipeline.CachePersister.run(CachePersister.groovy:19)
```

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 3.3.2
- **JDK Version:** oracle 8u131
- **Container Version (If Applicable):** n/a

### Example Application

if a sample app is really needed, i can come up with one. multi-module setup takes a bit of effort..

**Comment by jeffbrown** [comment]
@zyro23 See the project at https://github.com/jeffbrown/issue10878.  The assertion at passes when I run `./gradlew app:bootRun`.  Does that assertion pass for you?

Thanks for the feedback.

**Comment by zyro23** [comment]
thanks for creating a sample app! much appreciated. that sample passes. however i think the difference to my project is that we got a `build.gradle` at the top level and are running `bootRun` from there. ofc, that executes the app subproject but i guess the working dir is different. ill pull-request our setup to your sample app to reproduce.

**Comment by jeffbrown** [comment]
> thanks for creating a sample app! much appreciated.

No problem.  Creating a project like that takes 2 or 3 minutes and helps troubleshoot what is going on.

**Comment by zyro23** [comment]
so there was another thing specific to our project setup. in the `app`s `build.gradle`, we use:
```groovy
bootRun {
    systemProperties System.properties
}
```
to be able to pass systemProperties from the gradlew command to the application.

it seems the underlying behavior has changed - this now leads to the `user.dir` system property being set to the root project dir.

i do not know if something with gradle (i.e. `JavaExec`) has changed or if it is some other part.

debugging into `BuildSettings`, i could observe the static initialization behavior i described above, but in this case, that was not the cause for the wrong directory being picked up.

not merging all system properties (picking them explicitly) or fixing `user.dir` afterwards works (`workingDir` also defaults to the subproject directory - not sure if that was always the case):
```groovy
bootRun {
    systemProperties System.properties
    systemProperty "user.dir", workingDir.path
}
```

as this is somewhat specific to our setup, im completely fine with this issue being closed as "cannot-reproduce", "workaround-available" or whatever fits best.

@jeffbrown thx again for the support.

**Comment by jeffbrown** [comment]
> so there was another thing specific to our project setup

This is why simple sample apps to reproduce odd problems are important.  ;)

Thanks for all of the feedback.
