### ISSUE TITLE
Domain not found in mapping context api when converting as JSON

### ISSUE THREAD

**Issue by mamunsrdr** [grails/grails-core#10883]
[Duplicated post] When I'm trying to convert mongo entity using grails.converter.JSON, it's throwing the following exception `Could not retrieve the respective entity for domain Workspace in the mapping context API`. 
Dependency:
```
//grailsVersion 3.3.1
compile "org.grails.plugins:converters"
compile 'org.grails.plugins:mongodb:6.1.4'
compile "org.mongodb:mongodb-driver:3.5.0"
```

Domain class:
```
class Workspace {
    static mapWith = "mongo"

    ObjectId id
    String name
    List<ObjectId> formIds
    long companyId

    static mapping = {
        collection 'eform_workspace'
    }
}
```
Service code snippet:
```
List<Workspace> workspaces = Workspace.findAll()
String workspaceJson = workspaces as JSON // produces exception
return [
       workspacesJson: workspaceJson
]
```
Stacktrace:
```
Caused by: java.lang.RuntimeException: org.grails.core.exceptions.GrailsConfigurationException: Could not retrieve the respective entity for domain Workspace in the mapping context API
        at org.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:120)
        at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToString(ShortTypeHandling.java:44)
        at com.example.artifact.form.service.EformHomeService$$EQcpF3wG.$tt__getUserWorkspaces(EformHomeService.groovy:14)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReloadedTypeInvoker$2.invoke(ReloadedTypeInvoker.java:133)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1462)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
        at com.example.artifact.form.service.EformHomeService$_getUserWorkspaces_closure1$$EQcpF3wG.doCall(EformHomeService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReloadedTypeInvoker$2.invoke(ReloadedTypeInvoker.java:133)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1462)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at com.example.artifact.form.service.EformHomeService$_getUserWorkspaces_closure1.call(EformHomeService.groovy)
        at groovy.lang.Closure.call(Closure.java:430)
        at com.example.artifact.form.service.EformHomeService$_getUserWorkspaces_closure1.call(EformHomeService.groovy)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at com.example.artifact.form.service.EformHomeService$$EQcpF3wG.getUserWorkspaces(EformHomeService.groovy)
        at com.example.artifact.form.service.EformHomeService$$DQcpF3wG.getUserWorkspaces(Unknown Source)
        at com.example.artifact.form.service.EformHomeService.getUserWorkspaces(EformHomeService.groovy)
        at com.example.artifact.form.service.EformHomeService$getUserWorkspaces$0.call(Unknown Source)
        ... 98 common frames omitted
```

**Comment by jameskleeh** [comment]
Try `compile 'org.grails.plugins:mongodb:6.1.5.BUILD-SNAPSHOT'`

**Comment by mamunsrdr** [comment]
Tried `compile 'org.grails.plugins:mongodb:6.1.5.BUILD-SNAPSHOT'`, still the same exception `Could not retrieve the respective entity for domain Workspace in the mapping context API`. Stacktrace below:
```
Caused by: org.grails.core.exceptions.GrailsConfigurationException: Could not retrieve the respective entity for domain Workspace in the mapping context API
	at org.grails.core.DefaultGrailsDomainClass.verifyContextIsInitialized(DefaultGrailsDomainClass.java:170)
	at org.grails.core.DefaultGrailsDomainClass.initializePersistentProperties(DefaultGrailsDomainClass.java:101)
	at org.grails.core.DefaultGrailsDomainClass.getIdentifier(DefaultGrailsDomainClass.java:260)
	at org.grails.web.converters.marshaller.json.DomainClassMarshaller.marshalObject(DomainClassMarshaller.java:116)
	at org.grails.web.converters.marshaller.json.DomainClassMarshaller.marshalObject(DomainClassMarshaller.java:52)
	at grails.converters.JSON.value(JSON.java:184)
	at grails.converters.JSON.convertAnother(JSON.java:144)
	at org.grails.web.converters.marshaller.json.CollectionMarshaller.marshalObject(CollectionMarshaller.java:41)
	at org.grails.web.converters.marshaller.json.CollectionMarshaller.marshalObject(CollectionMarshaller.java:30)
	at grails.converters.JSON.value(JSON.java:184)
	at grails.converters.JSON.render(JSON.java:119)
	at org.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:118)
	... 45 common frames omitted
```

**Comment by jameskleeh** [comment]
@mamunsrdr Please upload an example application with steps to reproduce

**Comment by mamunsrdr** [comment]
I've uploaded sample project: [https://github.com/mamunsrdr/pwgmongo.git](https://github.com/mamunsrdr/pwgmongo.git). Please change the `grails.mongodb` config in `application.yml` as per your environment. After running the project if you navigate to http://localhost:8080 -> FooController:index(), the exception will occur. However as my temp solution: if you uncomment the JSON Marshaller on `Foo` domain, as expected it works.

**Comment by ibmsoft** [comment]
i have the same error

**Comment by gauravmakkar** [comment]
Same Error

**Comment by sdelamo** [comment]
JSON Views is the recommended way to render JSON. The converters plugin has been split out from core into a separate project and it is facing deprecation. 

I have created a PR showing how you could achieve the same payload using JSON views which is the recommended approach. 

https://github.com/mamunsrdr/pwgmongo/pull/1
