### ISSUE TITLE
Grails 3.3.2 with SpringBoot 1.5.8 On Tomcat

### ISSUE THREAD

**Issue by amarraja123** [grails/grails-core#10896]
I am using Grails 3.3.2 with Spring Boot. The versions are exactly that comes in default.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. grails create-app myapp
2. cd myapp
3. grails run-app -> The app ran fine.
4. grails build -> The war was built. I downloaded apache-tomcat-8.5.24. Put the WAR in the Webapp Dir.

### Expected Behaviour

The war shall be deployed successfully and the server shall respond to the context http://localhost:8080/myapp

### Actual Behaviour

Throws the below mentioned error and context is not up.

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8.0_151

### Example Application

- STACKTRACE:
`26-Dec-2017 19:59:18.183 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Error during ServletContainerInitializer processing
 javax.servlet.ServletException: Failed to instantiate WebApplicationInitializer class
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:155)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.VerifyError: (class: org/grails/plugins/filterpane/test/ApplicationLoader, method: super$2$configure signature: (Lorg/springframework/boot/builder/SpringApplicationB
uilder;)Lorg/springframework/boot/builder/SpringApplicationBuilder;) Illegal use of nonvirtual function call
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:152)`

**Comment by sdelamo** [comment]
I cannot reproduce the issue you described. I downloaded and unzipped apache-tomcat-8.5.24

```
$ cd /apache-tomcat-8.5.24
apache-tomcat-8.5.24 $ grails --version
| Grails Version: 3.3.2
| Groovy Version: 2.4.13
| JVM Version: 1.8.0_152
$ grails create-app demo
| Application created at apache-tomcat-8.5.24/demo
apache-tomcat-8.5.24 $ cd demo/
apache-tomcat-8.5.24/demo$ grails war
| Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL in 10s
Processing File 1 of 26 - skin/database_save.png
Processing File 4 of 26 - skin/information.png
Processing File 3 of 26 - skin/database_edit.png
Processing File 2 of 26 - skin/database_delete.png
Processing File 5 of 26 - skin/house.png
Processing File 7 of 26 - skin/exclamation.png
Processing File 6 of 26 - skin/sorted_asc.gif
Processing File 8 of 26 - skin/database_add.png
Processing File 9 of 26 - skin/sorted_desc.gif
Processing File 10 of 26 - skin/shadow.jpg
Processing File 11 of 26 - skin/database_table.png
Processing File 12 of 26 - favicon.ico
Processing File 13 of 26 - apple-touch-icon.png
Processing File 14 of 26 - spinner.gif
Processing File 15 of 26 - grails.svg
Processing File 16 of 26 - grails-cupsonly-logo-white.svg
Processing File 17 of 26 - apple-touch-icon-retina.png
Processing File 18 of 26 - jquery-2.2.0.min.js
Processing File 19 of 26 - bootstrap.js
Processing File 20 of 26 - application.js
Processing File 21 of 26 - bootstrap.css
Processing File 22 of 26 - errors.css
Processing File 23 of 26 - application.css
Processing File 24 of 26 - grails.css
Processing File 25 of 26 - main.css
Processing File 26 of 26 - mobile.css

> Task :assetCompile 
Finished Precompiling Assets


BUILD SUCCESSFUL in 30s
8 actionable tasks: 8 executed
| Built application to build/libs using environment: production

apache-tomcat-8.5.24/demo $ cd ..
apache-tomcat-8.5.24 $ chmod a+x bin/startup.sh 
apache-tomcat-8.5.24 $ chmod a+x bin/catalina.sh 
apache-tomcat-8.5.24 $ mv demo/build/libs/demo-0.1.war webapps/
apache-tomcat-8.5.24 $ bin/startup.sh 
Using CATALINA_BASE:   /Users/sdelamo/Downloads/apache-tomcat-8.5.24
Using CATALINA_HOME:   /Users/sdelamo/Downloads/apache-tomcat-8.5.24
Using CATALINA_TMPDIR: /Users/sdelamo/Downloads/apache-tomcat-8.5.24/temp
Using JRE_HOME:        /Users/sdelamo/.sdkman/candidates/java/current
Using CLASSPATH:       /Users/sdelamo/Downloads/apache-tomcat-8.5.24/bin/bootstrap.jar:/Users/sdelamo/Downloads/apache-tomcat-8.5.24/bin/tomcat-juli.jar
Tomcat started.
```

I don't get any exception logged in `catalina.out.`

The app starts at: 

http://localhost:8080/demo-0.1/

**Comment by amarraja123** [comment]
Okay, I agree this shall not happen with exactly the default dependencies that come with grails.

Its because of : compile "org.grails.plugins:filterpane:3.0.8"

**Comment by amarraja123** [comment]
https://github.com/Grails-Plugin-Consortium/grails-filterpane/issues/67

**Comment by amarraja123** [comment]
https://github.com/Grails-Plugin-Consortium/grails-filterpane/issues/77

**Comment by amarraja123** [comment]
Its not a grails core issue. So closing the ticket.
