### ISSUE TITLE
Unable to call static methods from a view in a Grails application packaged as a war file

### ISSUE THREAD

**Issue by RobertStroud** [grails/grails-core#10893]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a default Grails application
2. Add a class with a static method - e.g. `Hello.groovy` with 
`static greeting() { return "hello world" }`
3. Add a view that calls the static method - e.g. `hello/index.gsp` with `${Hello.greeting()}`
4. Confirm that everything works as expected when you do `grails prod run-app`
5. Now do `gradle bootRepackage` and run the application from the war file 
`java -jar build/libs/*.war`

### Expected Behaviour

I would expect the behaviour to be identical - if it works in production mode, it should work when I run it from a war file.

### Actual Behaviour

It works in production mode but it crashes when I run it from the war file. The stack trace complains about invoking the static method on a null object, which makes no sense:

`
java.lang.NullPointerException: Cannot invoke method greeting() on null object
	at gsp_TestStatic_helloindex_gsp$_run_closure1.doCall(gsp_TestStatic_helloindex_gsp.groovy:18)
	at org.grails.taglib.TagBodyClosure.executeClosure(TagBodyClosure.java:200)
	at org.grails.taglib.TagBodyClosure.captureClosureOutput(TagBodyClosure.java:102)
	at org.grails.taglib.TagBodyClosure.call(TagBodyClosure.java:213)
	at org.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy:48)
	at org.grails.plugins.web.taglib.SitemeshTagLib$_closure3.doCall(SitemeshTagLib.groovy:156)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:417)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:335)
	at gsp_TestStatic_helloindex_gsp.run(gsp_TestStatic_helloindex_gsp.groovy:21)
	at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
	at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
	at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:76)
	at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
	at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.grails.web.sitemesh.GrailsLayoutView.renderInnerView(GrailsLayoutView.java:150)
	at org.grails.web.sitemesh.GrailsLayoutView.obtainContent(GrailsLayoutView.java:128)
	at org.grails.web.sitemesh.GrailsLayoutView.renderTemplate(GrailsLayoutView.java:63)
	at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
	at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
`

### Environment Information

- **Operating System**: MacOS X 10.11.6
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0_152-ea-b05
- **Container Version (If Applicable):** spring-boot-starter-tomcat

### Example Application

https://github.com/RobertStroud/TestStatic/

**Comment by jeffbrown** [comment]
Invoking static methods from a GSP isn't a good idea and having a class in the default package like that also isn't a good idea, but I built your app and ran the war file as described and it appears to behave as expected.  I am not seeing the problem.  Anyone else able to reproduce?

**Comment by RobertStroud** [comment]
@jeffbrown Thanks for looking into my problem. I wouldn't normally put a class in the default package but why is it not a good idea to invoke static methods from a GSP?

With respect to my issue, I believe I know why you can't reproduce it. Note that the command in step 5 is `gradle bootRepackage` - I am running `gradle` rather than `./gradlew`. This isn't deliberate - it was inadvertent - but it seems to be the cause of the problem.

In particular, I have a copy of Gradle 4.1 installed on my Mac, so if I type `gradle` rather than `./gradlew` I get Gradle 4.1 rather than Gradle 3.4.1. I don't know why this causes things to break, but that is the source of the trouble...

The strange thing is that I normally build the war file for the real application from within my IDE, which is configured to use the Grails wrapper. So it isn't immediately obvious why the war file for my application isn't working since it should have been built using `./gradlew` rather than `gradle`. Indeed, I tried re-building the war file using `./gradlew` and it still didn't work.

However, I think I know what happened. At some point in the past, I built the war file from the command line using the `gradle` command. This corrupted something in the build environment that caused `./gradlew` to stop working - the solution was to run `grails clean` and now everything is working properly again.

Clearly, mixing `gradle` and `./gradlew` is a bad idea, at least for building war files, but is there anything that can be done to detect the problem if it occurs? For example, if the Gradle version number was recorded somewhere in the build environment, it might be possible to detect the conflict.

Thanks.

**Comment by jeffbrown** [comment]
> Clearly, mixing gradle and ./gradlew is a bad idea

It isn't a bad idea if they are configured to use the same version.  There is no good reason to use `gradle` though if `gradlew` is there.
