### ISSUE TITLE
Constraint on multi-column property causes hibernate mapping failure

### ISSUE THREAD

**Issue by longwa** [grails/grails-core#10903]
Upgrading from Grails 2.5.5 to 3.3.2 and domains where we had a constraint on a multi-column property are causing an error on startup.

Hibernate 5.1.9
Gorm 6.1.8
Grails 3.3.2
Java 8

This used to work properly. The nullable constraint would be applied to each of the underlying columns.

For example:
```
import org.jadira.usertype.dateandtime.joda.PersistentDateTimeAndZoneWithOffset
import org.joda.time.DateTime
import org.joda.time.LocalDate

class Author {
	String name
	DateTime testDate

	static constraints = {
		testDate(nullable: true)
	}

	static mapping = {
	    testDate(type: PersistentDateTimeAndZoneWithOffset) {
	        column name: "testDate_datetime"
	        column name: "testDate_offset"
	    }
	}
}
```

Results in:
```
Caused by: java.lang.RuntimeException: Cannot treat multi-column property as a single-column property
        at org.grails.orm.hibernate.cfg.PropertyConfig.checkHasSingleColumn(PropertyConfig.groovy:449)
        at org.grails.orm.hibernate.cfg.PropertyConfig.getScale(PropertyConfig.groovy:425)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGroovyObjectGetProperty(GetEffectivePogoPropertySite.java:68)
        at org.grails.orm.hibernate.cfg.HibernateMappingBuilder$_closure1.doCall(HibernateMappingBuilder.groovy:478)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:574)
        at org.grails.orm.hibernate.cfg.HibernateMappingBuilder.methodMissing(HibernateMappingBuilder.groovy:691)
```
Removing the constraints reference fixes the error, but then both of the properties on the domain object are required and non-nullable.

It's possible this is a by design change, but I can't really find any reference to how the two interact.

**Comment by longwa** [comment]
Oops, meant to open on the data-mapping project. Moving there.
