### ISSUE TITLE
null value in column "date_created" violates not-null constraint error

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10964]
- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce
Following code produce exception with Postgres DB

```
    @Transactional
    def index() {
        def t = new Test()
        t.save()

        t.uid = "dfsdf"
        t.save()
        render "ok"
    }
```

> ERROR:  null value in column "date_created" violates not-null constraint
> DETAIL:  Failing row contains (1, 1, null, 2018-03-14 13:18:16.527, dfsdf).
> STATEMENT:  update test set version=$1, date_created=$2, last_updated=$3, uid=$4 where id=$5 and version=$6
> 2018-03-14 13:18:16.544 ERROR --- [nio-8080-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: null value in column "date_created" violates not-null constraint
>   Detail: Failing row contains (1, 1, null, 2018-03-14 13:18:16.527, dfsdf).
> 2018-03-14 13:18:16.550 ERROR --- [nio-8080-exec-8] org.hibernate.internal.SessionImpl       : HHH000346: Error during managed flush [could not execute statement]
> 2018-03-14 13:18:16.650 ERROR --- [nio-8080-exec-8] o.g.web.errors.GrailsExceptionResolver   : PSQLException occurred when processing request: [GET] /test/index
> ERROR: null value in column "date_created" violates not-null constraint
>   Detail: Failing row contains (1, 1, null, 2018-03-14 13:18:16.527, dfsdf).. Stacktrace follows:
> 
> java.lang.reflect.InvocationTargetException: null
> 	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
> 	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
> 	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
> 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
> 	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
> 	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
> 	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [date_created]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
> 	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:241)
> 	at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:755)
> 	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:590)
> 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
> 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
> 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
> 	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
> 	... 14 common frames omitted
> Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
> 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112)
> 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
> 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
> 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
> 	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3132)
> 	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3011)
> 	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3391)
> 	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:145)
> 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:582)
> 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:456)
> 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
> 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
> 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1295)
> 	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:468)
> 	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3135)
> 	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2352)
> 	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:491)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:147)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
> 	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65)
> 	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:582)
> 	... 18 common frames omitted
> Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "date_created" violates not-null constraint
>   Detail: Failing row contains (1, 1, null, 2018-03-14 13:18:16.527, dfsdf).
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:171)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:138)
> 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
> 	... 37 common frames omitted

### Expected Behaviour

Entity must be saved without errors. dateCreated must be filled

### Actual Behaviour

Exception fails

### Environment Information

- **Operating System**: Ubuntu
- **Grails Version:** 3.2.11
- **JDK Version:** 8
- **Container Version (If Applicable):** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
I was able to verify this happens with Grails 3.3.3 and the latest GORM.

There are 2 available workarounds

1. In the first `.save` call, pass in the option `flush: true`
2. Only call `.save` once

This could be an issue in the postgres driver since it doesn't happen with H2 for example

**Comment by erichelgeson** [comment]
I recently ran into this issue as well in an integration test - I can see that there is a insert (with date created) then an update with dateCreated set to null - I'm not sure where the update is coming from. In my case though there is only 1 explicit call to save.

**Comment by demon101** [comment]
@jameskleeh  workarounds are simple, 
but sometimes really difficult to find the reason in complex business logic. 

I think, the bug related to transaction handling, somewhere in GORM-Hibernate. I hope, @graemerocher will inform us about real reason

**Comment by musketyr** [comment]
I'm just hooking here. I have probably a related problem.  `dateCreated` started to be `null` in the unit tests after upgrading to `3.3.5`

**Comment by demon101** [comment]
One more funny case for this bug:
```
def classAction(SomeEntity a){ // bind new entity
   a.addToBlaBla(someEntityBla)
   a.addToBoBO(someEntityBo) // save happens inside,  
   a.save() // produce validation error
}
```

**Comment by mauracwarner** [comment]
I'm able to replicate the issue in Grails 3.3.5 with Postgres 10.  Another workaround is to manually initialize `dateCreated` on object instantiation, i.e. `Date dateCreated = new Date()`.

**Comment by ilopmar** [comment]
I've been debugging this issue and tried different databases and hibernate versions (5.1.5, 5.1.14 and 5.2.17). The problem only happens with Postgresql. I've tried with both H2 and Mysql and it works correctly.
The issue is when binding the parameters for the update. On both H2 and Mysql the log looks like this:
```
2018-06-28 18:12:42.375 DEBUG --- [nio-8080-exec-1] org.hibernate.SQL                        : insert into test (version, date_created, uid) values (?, ?, ?)
2018-06-28 18:12:42.406 TRACE --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [BIGINT] - [0]
2018-06-28 18:12:42.407 TRACE --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [2] as [TIMESTAMP] - [Thu Jun 28 18:12:42 CEST 2018]
2018-06-28 18:12:42.408 TRACE --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [3] as [VARCHAR] - [null]
2018-06-28 18:12:42.538 DEBUG --- [nio-8080-exec-1] org.hibernate.SQL                        : update test set version=?, date_created=?, uid=? where id=? and version=?
2018-06-28 18:12:42.539 TRACE --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [BIGINT] - [1]
2018-06-28 18:12:42.539 TRACE --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [2] as [TIMESTAMP] - [Thu Jun 28 18:12:42 CEST 2018]
2018-06-28 18:12:42.539 TRACE --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [3] as [VARCHAR] - [dfsdf]
2018-06-28 18:12:42.540 TRACE --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [4] as [BIGINT] - [2]
2018-06-28 18:12:42.540 TRACE --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [5] as [BIGINT] - [0]
```

But with Postgresql the log is:
```
2018-06-28 18:18:29.434 DEBUG --- [nio-8080-exec-2] org.hibernate.SQL                        : insert into test (version, date_created, uid, id) values (?, ?, ?, ?)
2018-06-28 18:18:29.438 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [BIGINT] - [0]
2018-06-28 18:18:29.439 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [2] as [TIMESTAMP] - [Thu Jun 28 18:18:29 CEST 2018]
2018-06-28 18:18:29.440 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [3] as [VARCHAR] - [null]
2018-06-28 18:18:29.440 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [4] as [BIGINT] - [1]
2018-06-28 18:18:29.447 DEBUG --- [nio-8080-exec-2] org.hibernate.SQL                        : update test set version=?, date_created=?, uid=? where id=? and version=?
2018-06-28 18:18:29.447 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [BIGINT] - [1]
2018-06-28 18:18:29.447 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [2] as [TIMESTAMP] - [null] <----- THIS!
2018-06-28 18:18:29.447 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [3] as [VARCHAR] - [dfsdf]
2018-06-28 18:18:29.447 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [4] as [BIGINT] - [1]
2018-06-28 18:18:29.448 TRACE --- [nio-8080-exec-2] o.h.type.descriptor.sql.BasicBinder      : binding parameter [5] as [BIGINT] - [0]
```
As you can see the timestamp field is set to `null` during the update, so somewhere that value is lost. As James suggested maybe the issue is in the postgresql driver. I've also updated it to the latest version (42.2.2) but it still fails.

I'll continue debugging the issue to see where the value is lost.

**Comment by ilopmar** [comment]
I've also though that maybe this issue was because of the isolation level. Postgresql default isolation level is "read committed" and Mysql is "repeteable read". I've done a few tests changing the level for both postgres and mysql but in all the cases it still works in mysql and it still fails in postgres.

**Comment by ilopmar** [comment]
I've been debugging and comparing the execution of Mysql and Postgres until I've found the problem. The bad news is that this is how Hibernate and Postgres work:

Here https://github.com/hibernate/hibernate-orm/blob/5.1.5/hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java#L275 Hibernate builds the `insertAction` that is inserted into the processing queue here https://github.com/hibernate/hibernate-orm/blob/5.1.5/hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java#L306. When executing `source.getActionQueue().addAction( insert );` we reach this method https://github.com/hibernate/hibernate-orm/blob/5.1.5/hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java#L258 and then the key is in https://github.com/hibernate/hibernate-orm/blob/5.1.5/hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java#L273. The method `insert.isEarlyInsert()` returns `true` for Mysql which means that the insert will be executed in `execute(insert)`. From that method this code is called https://github.com/hibernate/hibernate-orm/blob/5.1.5/hibernate-core/src/main/java/org/hibernate/action/internal/EntityIdentityInsertAction.java#L75 and the a `preInsert` event is generated which finally triggers the Grails `AutotimeStampEventListener`. This sets the value in the `dateCreated` field and from here the value is available during the update that fails in postgresql.

If we use Postgresql the execution path is the same until https://github.com/hibernate/hibernate-orm/blob/5.1.5/hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java#L273. Now `insert.isEarlyInsert()` returns `false` because the implementation used is https://github.com/hibernate/hibernate-orm/blob/5.1.5/hibernate-core/src/main/java/org/hibernate/action/internal/EntityInsertAction.java#L65. This is because postgresl uses a sequence for identity generation. Now the `else` branch is executed and instead of executing the insert in this moment (and triggering the `preInsert` event) the `addAction` method is called to queue the insert execution instead of executing it at this moment. After this we go back to GORM code at https://github.com/grails/grails-data-mapping/blob/6.1.x/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/AbstractHibernateGormInstanceApi.groovy#L248 and as `flush` is `false` the session is not flushed and the pre-insert event is not generated. The event is generated later in the execution but the hibernate state is not updated. This means that when we execute the 2nd save (which triggers an update) the value of `dateCreated` is `null` in the hibernate state and this value `null` is used for the update, and, of course, it fails.
I'm not sure if we can force a synchronization of the state in our GORM code. I'll take a look at this now.

In the mean time, there is a workaround that is defining `flush: true` as James mentioned. That would make that here https://github.com/grails/grails-data-mapping/blob/6.1.x/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/AbstractHibernateGormInstanceApi.groovy#L248 `flush` will be `true` and as a result of flushing the session, the queued insert action will be executed and the pre-insert event will be triggered.
Another option is to set globally `hibernate.flush.mode: AUTO` as explained here http://gorm.grails.org/latest/hibernate/manual/index.html#_flush_mode_now_commit_by_default but this could affect the performance of all the application.

**Comment by ilopmar** [comment]
I've found a place in GORM code in which we can synchronize with the hibernate state. If we always execute `synchronizePersisterState(...)` here https://github.com/grails/grails-data-mapping/blob/6.1.x/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/support/ClosureEventListener.java#L263 in the `onPreInsert` handling (removing the `if` check) then everything works as expected.
This change doesn't break any existing test in `grails-data-mapping`, `grails-core` or `grails3-functional-tests` but I'm not sure if there is a performance penalty for trying to synchronize the state in every pre-insert event.
