### ISSUE TITLE
grails create-app => "Method Not Allowed"

### ISSUE THREAD

**Issue by pucojazu** [grails/grails-core#10961]
### Steps to Reproduce

1. Install Grails
2. Run "grails create-app test --stacktrace"

### Expected Behaviour

Grails app should be created.

### Actual Behaviour

Command aborts with error:
```
$ grails create-app test --stacktrace
| Error Error occurred running Grails CLI: Method Not Allowed (405) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.apache.http.client.HttpResponseException: Method Not Allowed (405)
        at org.eclipse.aether.transport.http.HttpTransporter.handleStatus(HttpTransporter.java:466)
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:291)
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:243)
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:217)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:319)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:301)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:293)
        at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:53)
        at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:49)
        at org.grails.cli.profile.repository.MavenProfileRepository.<init>(MavenProfileRepository.groovy:53)
        at org.grails.cli.GrailsCli.createMavenProfileRepository(GrailsCli.groovy:334)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:235)                                                                                                                            
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)                                                                                                                               
| Error Error occurred running Grails CLI: Method Not Allowed (405)            
```

### Environment Information

- **Operating System**: Arch Linux
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8.0_162

**Comment by pucojazu** [comment]
An inactive proxy in my ~/.m2/settings.xml seems to be the cause:
```
<proxies>
  <proxy>
    <active>false</active>
    <protocol>http</protocol>
    <host>proxy.example.com</host>
    <port>80</port>
  </proxy>
</proxies>
```

If I comment out the "proxies" block, Grails works fine.
