### ISSUE TITLE
Unit test domain with multiple datasources

### ISSUE THREAD

**Issue by HeliosRamirez** [grails/grails-core#10966]
Hi,

We have a problem with unit tests.

We have a domain with two datasources, we get the following error.

```
Invalid connection [DEFAULT] configured for class [class multidatasource.sto.User]
org.grails.datastore.mapping.core.exceptions.ConfigurationException: Invalid connection [DEFAULT] configured for class [class multidatasource.sto.User]
	at org.grails.datastore.mapping.simple.SimpleMapDatastore$4.getDatastoreForQualifier(SimpleMapDatastore.java:256)
	at org.grails.datastore.mapping.simple.SimpleMapDatastore$4.getStaticApi(SimpleMapDatastore.java:226)
	at org.grails.datastore.gorm.GormEnhancer.registerEntity(GormEnhancer.groovy:151)
	at org.grails.datastore.mapping.simple.SimpleMapDatastore$3.persistentEntityAdded(SimpleMapDatastore.java:218)
	at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:288)
	at grails.testing.gorm.DataTest$Trait$Helper.mockDomains(DataTest.groovy:78)
	at grails.testing.gorm.DataTest$Trait$Helper.mockDomain(DataTest.groovy:63)
	at grails.testing.gorm.DataTest$Trait$Helper.mockDomain(DataTest.groovy:62)
	at multidatasource.sto.UserServiceSpec.setup(UserServiceSpec.groovy:10)
```

We are implementing DataTest in the Spec class and using mockDomain(User) inside setup.

```
class UserServiceSpec extends Specification implements ServiceUnitTest<UserService>, DataTest

def setup() {
    mockDomain(User)
}
```

Our domain class looks the following way

```
class User {
    String firstName
    String lastName
    static constraints = {
    }
    static mapping = {
        datasources (['DEFAULT', 'stoWrite'])
        id generator: 'sequence', params: [sequence_name: 'seq_user', schema: 'sto']
        table name: "user", schema: "sto"
    }
}
```

We are using a Postgresql 9.6 database for development and production environments.

I have attached a sample project to reproduce the problem

### Environment Information

- **Operating System**: macOS High Sierra
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8.0_31

### Example Application

https://github.com/HeliosRamirez/multiDataSource

**Comment by jameskleeh** [comment]
Dup of https://github.com/grails/grails-core/issues/10888

**Comment by fbarbedette** [comment]
Hi James, 

We already tried to use a real datastore as someone told us in the slack community. 

Basically we followed this manual:
http://gorm.grails.org/latest/hibernate/manual/index.html#testing

And implemented the following "steps":
- make the spec class implements DataTest
- add hibernateDatastore y transactionManager with annotations
- setupSpec method where hibernateDatastore is implemented with the config to connect to DB
- Annotation @Transactional in setup, cleanup and test methods
- Create an instance of the domain class and persist it
- clean the record in the cleanup method

This way we were able to test some of our services (basically the ones that read from the DB). But then testing service method using Gorm save returns an exception:

`No Session found for current thread
org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:117)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:464)
	at org.grails.orm.hibernate.cfg.GrailsHibernateUtil.setObjectToReadWrite(GrailsHibernateUtil.java:328)
	at org.grails.orm.hibernate.HibernateGormInstanceApi.setObjectToReadWrite(HibernateGormInstanceApi.groovy:154)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:137)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:118)
	at org.grails.datastore.gorm.DelegatingGormEntityApi.save(DelegatingGormEntityApi.groovy:44)
	at com.storecheck.iii.UserService.$tt__saveUser(UserService.groovy:61)
	at com.storecheck.iii.UserService.saveUser_closure5(UserService.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at com.storecheck.iii.UserServiceSpec.$tt__$spock_feature_0_1(UserServiceSpec.groovy:55)
	at com.storecheck.iii.UserServiceSpec.test: save user_closure4(UserServiceSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at com.storecheck.iii.UserServiceSpec.test: save user(UserServiceSpec.groovy)`

So we can't test our services that save or updates objects.

I hope I'm being clear on the problem...

thanks for the help.
