### ISSUE TITLE
OSX Native file wacher doesn't load

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#10989]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a fresh app with a version of Grails that has the new OSX file watcher
2. Start app, see
```
2018-04-11 13:55:18.912 ERROR --- [           main] org.grails.io.watch.DirectoryWatcher     : Error Initializing Native OS X File Event Watcher. Add JNA to classpath for Faster File Watching performance.
```
3. Add JNA as instructed in the startup log

### Expected Behaviour

Expect native file watcher to work 

### Actual Behaviour

```
2018-04-11 13:52:27.814  INFO --- [           main] org.grails.io.watch.DirectoryWatcher     : Exception while trying to load WatchServiceDirectoryWatcher (this is probably Java 6 and WatchService isn't available). Falling back to PollingDirectoryWatcher.

java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1076)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlClassNewInstance(ReflectiveInterceptor.java:1062)
        at org.grails.io.watch.DirectoryWatcher.<init>(DirectoryWatcher.java:56)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1076)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
        at grails.boot.GrailsApp.enableDevelopmentModeWatch(GrailsApp.groovy:125)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:93)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:387)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:374)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at foo2234.Application.main(Application.groovy:8)
Caused by: java.lang.NoClassDefFoundError: io/methvin/watchservice/MacOSXListeningWatchService
        at org.grails.io.watch.MacOsWatchServiceDirectoryWatcher.<init>(MacOsWatchServiceDirectoryWatcher.java:39)
        ... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.methvin.watchservice.MacOSXListeningWatchService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 27 common frames omitted
```

### Environment Information

- **Operating System**: OSX
- **Grails Version:** 3.2/3.3 with new file watcher
- **JDK Version:** iu161
- **Container Version (If Applicable):** n/a

### Example Application

n/a

**Comment by erichelgeson** [comment]
Work around here - https://github.com/grails/grails-core/pull/10852#issuecomment-365960515
