### ISSUE TITLE
Error on run-app with grails 3.3.4

### ISSUE THREAD

**Issue by charu-jain89** [grails/grails-core#10994]
Getting:

```
 Caused by: java.lang.NullPointerException: null
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.getTableName(GrailsDomainBinder.java:1202)

```
with mapWith property in domain class.

### Task List

-  Steps to reproduce : 
1) Create a domain class A that extends some other domain Class B.
2) Class C has hasMany relation with class A.
3) Class A has mapWith property set to none in its domain class.
4) Running the application gives Nullpointer on table_name for Class A being null.
5) Commenting mapWith=none makes everything works fine.

- Stacktrace:

Caused by: java.lang.NullPointerException: null
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.getTableName(GrailsDomainBinder.java:1202)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.calculateTableForMany(GrailsDomainBinder.java:1155)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindCollectionTable(GrailsDomainBinder.java:1105)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindCollection(GrailsDomainBinder.java:1052)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder$CollectionType$1.create(GrailsDomainBinder.java:3463)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.createClassProperties(GrailsDomainBinder.java:1872)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindRootPersistentClassCommonValues(GrailsDomainBinder.java:1751)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindRoot(GrailsDomainBinder.java:1391)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.contribute(GrailsDomainBinder.java:165)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:275)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:83)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:418)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:87)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:692)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:276)
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:86)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:39)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:23)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:204)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1076)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 51 common frames omitted

- Example uploaded to Github: https://github.com/charu-jain89/Upgrade 
### Expected Behaviour

No exception on usage of mapWith in domain class.

### Actual Behaviour

NullpointerException as seen in stacktrace.

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.3.5
- **JDK Version:** javac 1.8.0_45

### Example Application

- https://github.com/charu-jain89/Upgrade

Asked the question on stackoverflow: https://stackoverflow.com/questions/49814601/error-on-run-app-with-grails-3-3-4?noredirect=1#comment86710785_49814601

**Comment by charu-jain89** [comment]
Is there any update on this issue?

**Comment by benrhine** [comment]
In looking into this issue this is improper usage of the `mapWith` static property. The issue is not really the `mapWith` property but that you have a `hasMany` on an un-persisted class as that is not supported. 

While this may have worked previously (verified your described behavior works up through 3.2.13 with Gorm 6.0.x) it was not a feature, this does not work in Grails 3.3.x with Gorm 6.1.x as relationships such as `hasMany` will not work with un-persisted classes.

I would suggest you reconsider your relationship mapping and you may not even need `mapWith` when your done.
