### ISSUE TITLE
Grails 3.3 - OneToOne mapping not working

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#11028]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. download and start the example project: https://github.com/jglapa/g335-oneToOne
 * `./gradlew bootRun`
2. navigate to http://localhost:8080/body/create
 * should succeed and create Face and Nose objects in H2 db
3. navigate to http://localhost:8080/body/update
 * will fail:
```
        ... 14 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Parameter "#2" is not set; SQL statement:
select this_.id as y0_ from face this_ where this_.id=? limit ? [90012-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.expression.Parameter.checkSet(Parameter.java:81)
        at org.h2.command.Prepared.checkParameters(Prepared.java:170)
        at org.h2.command.CommandContainer.query(CommandContainer.java:113)
        at org.h2.command.Command.executeQuery(Command.java:202)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
        ... 50 common frames omitted
```

### Expected Behaviour
update operation works

### Actual Behaviour

update operation fails with exception

#### Observation:
 * the `unique` constract for `nose` in `Face` domain seems to be the problem
 * this example is coming from the official  GORM guide : http://gorm.grails.org/6.1.x/hibernate/manual/#gormAssociation - 5.1.1. Many-to-one and one-to-one - Examples C
* the example works fine under Grails `3.2.13`
* the example fails already on `create` operation under Grails `3.3.0`

### Environment Information

- **Operating System**: Ubuntu 18
- **Grails Version:** 3.3.5
- **JDK Version:** 1.8

### Example Application

- https://github.com/jglapa/g335-oneToOne

**Comment by RotatingFans** [comment]
This also occurs in a many to one setup

**Comment by RotatingFans** [comment]
I have done some debugging: it appears that the normal flow is for a Statement, along with query parameters to be set onto a PreparedStatement. For a OneToOne relationship, the OneToOneType is applied to it. To set the value a function of the type is called: nullSafeSet(...).
Here is the declaration for the [nullSafeSet](https://github.com/hibernate/hibernate-orm/blob/6b0ef0a5c4351f7e8801ffcd07bb9c5ef7015fac/hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java#L119) in [OneToOneType](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java) of Hibernate:
```
@Override
	public void nullSafeSet(PreparedStatement st, Object value, int index, boolean[] settable, SharedSessionContractImplementor session) {
		//nothing to do
	}
```

**Comment by jglapa** [comment]
any plans to fix this?
