### ISSUE TITLE
Command 'list-plugins' does not use the proxy settings!

### ISSUE THREAD

**Issue by aadrian** [grails/grails-core#11022]
The command `list-plugins` does not seem to use the proxy settings since it fails for installations behind proxies, even if other parts of Grails work behind the same proxy.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1.  Install Grails 3.3.5 and Gradle
2.  Configure the proxy settings as specified in the [official docs](http://docs.grails.org/latest/guide/single.html#proxyConfig), (so both in Grails and Gradle)
3. Make sure Gradle works with this proxy, e.g. by creating and building a small demo app.
4. Make sure Grails works with this proxy, also e.g. by creating and building a simple webapp
5. Call the 'list-plugins' command --> not working!

### Expected Behaviour
Command 'list-plugins' should work like all other commands, even behind corporate proxies.

### Actual Behaviour
The command 'list-plugins' is not working behind proxies, even if other commands work, and quits with the stacktrace:
```
grails> list-plugins --stacktrace
| Available Plugins
| Error Failed to list plugins (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.net.UnknownHostException: repo.grails.org
        at list-plugins.run(list-plugins.groovy:7)
        at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
        at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:481)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:378)
        at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.doCall(GrailsCli.groovy:469)
        at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.call(GrailsCli.groovy)
| Error Failed to list plugins
```

### Environment Information

- **Operating System**: Windows 7, 8, 8.1, 10
- **Grails Version:** 3.3.5
- **JDK Version:** 1.8.0_162, 1.8.0_172
- **Container Version (If Applicable):** no applicable

### Detailed Stacktrace

```
grails> list-plugins --stacktrace
| Available Plugins
| Error Failed to list plugins (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.net.UnknownHostException: repo.grails.org
        at list-plugins.run(list-plugins.groovy:7)
        at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
        at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:481)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:378)
        at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.doCall(GrailsCli.groovy:469)
        at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.call(GrailsCli.groovy)
| Error Failed to list plugins
grails> list-plugins --stacktrace --verbose
| Available Plugins
| Error Failed to list plugins (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.net.UnknownHostException: repo.grails.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnec
tion.java:200)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1175)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java
:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.configuredInputStream(ResourceGroovyMethods.java:2046)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.newReader(ResourceGroovyMethods.java:2132)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:669)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:632)
        at org.codehaus.groovy.runtime.dgm$964.doMethodInvoke(Unknown Source)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.doMethodInvoke(GeneratedMetaMethod.java:83)
        at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProp
erty.java:76)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.ja
va:63)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
        at list-plugins.run(list-plugins.groovy:7)
        at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
        at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:481)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:378)
        at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.doCall(GrailsCli.groovy:469)
        at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.call(GrailsCli.groovy)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
| Error Failed to list plugins
```

**Comment by ilopmar** [comment]
I'm not able to reproduce the issue. I've downloaded [Charles Proxy](https://www.charlesproxy.com/) and configure my network settings to use a HTTP/HTTPS proxy with a random port (1111) to make sure that nothing can't connect to the internet.
Then I execute:
- `$ export GRAILS_OPTS="-Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8888"`
- `$ grails list-plugins --stacktrace --verbose`
And I can see the request in the proxy:
![charles_proxy](https://user-images.githubusercontent.com/559192/46474838-33c7c080-c7e4-11e8-9b04-299c60597f3a.png)

I've done another test. I've configured an external socks proxy inside Charles Proxy:
![image](https://user-images.githubusercontent.com/559192/46474896-522dbc00-c7e4-11e8-89ab-8cc9d6a8e6ce.png)

I've created a socks proxy with `ssh -D 1080 user@myexternalserver`, so all the traffic goes through it.
Then I execute again `$ grails list-plugins --stacktrace --verbose` and it works and I can see the request in Charles Proxy.
Then I close my ssh connection and this is what I've got:
![image](https://user-images.githubusercontent.com/559192/46475055-c10b1500-c7e4-11e8-90eb-ba964dbb89e8.png)
And this is the error:
```
$ grails list-plugins --stacktrace --verbose
| Available Plugins
| Error Failed to list plugins
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.0 503 Error"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2142)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.configuredInputStream(ResourceGroovyMethods.java:2046)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.newReader(ResourceGroovyMethods.java:2132)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:669)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:632)
	at org.codehaus.groovy.runtime.dgm$964.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.doMethodInvoke(GeneratedMetaMethod.java:83)
	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
	at list-plugins.run(list-plugins.groovy:7)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
	at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:481)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:378)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:351)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:272)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Failed to list plugins
```

**Comment by aadrian** [comment]
Hi,

> I'm not able to reproduce the issue. I've downloaded Charles Proxy and configure  ...

Thank you for your analysis!  Using Charles too on my own infrastructure (where I can controll/configure it) to proxy the traffic, seems to work like in the example you provided :) .

I'm getting the error described in the ticket on some customer's LAN only, where I don't have any control (but other tools seem to work with those proxy settings in the same LAN, except this commando and some in Subversion).

The sources for `list-plugins` look however the same to me like those for the other commandos that work with the same proxy settings. I also can reproduce now this strange behavior with Suversion too, where some commandos work, and some seem to be broken too - so this can't be a Grails issue.

Thank you very much for your detailed support!
