### ISSUE TITLE
Grails 3.3.5 Default method arguments not working with GDK enhancements

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#11029]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. download and start the project: https://github.com/jglapa/g335-serviceDefaultArguments
 * `./gradlew bootRun`
2. navigate to `localhost:8080/test/m1` and `localhost:8080/test/m2`
3. with m2 action you will get the following exception:
```
java.util.Date.clearTime()Ljava/util/Date;. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: java.util.Date.clearTime()Ljava/util/Date;
        at g335.servicedefaultarguments.TestService.serviceMethod2(TestService.groovy:12)
        at g335.servicedefaultarguments.TestController.m2(TestController.groovy:9)
        ... 14 common frames omitted

```

### Expected Behaviour

`m2` invocation works as `m1`

### Actual Behaviour

`m2` invocation fails as if the GDK groovy methods were not available:
```
    def serviceMethod(arg = new Date()) {
        arg
    }

    def serviceMethod2(arg = new Date().clearTime()) {
        arg
    }
```

### Environment Information

- **Operating System**: Ubuntu 18
- **Grails Version:** 3.3.5
- **JDK Version:** 1.5

### Example Application

- TODO: https://github.com/jglapa/g335-serviceDefaultArguments

**Comment by PhilippeRT** [comment]
Hello guys,

Can you tell me the workaround ?
I despair to find it.

Thanks.

**Comment by jamesdh** [comment]
@PhilippeRT try adding `runtime 'org.codehaus.groovy:groovy-dateutil'` to your build.gradle and see if that helps. Also, are you seriously still using JDK 1.5, or is that a typo?

**Comment by jglapa** [comment]
> JDK 1.5, or is that a typo

typo, should 1.8

**Comment by PhilippeRT** [comment]
@jamesdh THANKS A LOT. :-D
I can use minus on java.sql.Timestamp too.

Concerning the environment, I'm using :
- OS : debian 10
- jdk : 1.8.0_222
- grails : 4.0.0

**Comment by jamesdh** [comment]
@PhilippeRT @jglapa Yea, this issue makes sense for Grails 4.x since that uses Groovy 2.5.6, and starting with groovy 2.5.x those Date enhancements were [moved to a separate package that isn't included by default](http://groovy-lang.org/releasenotes/groovy-2.5.html#Groovy2.5releasenotes-Breakingchanges). 

That shouldn't be the case w/ @jglapa since Grails 3.3.5 uses Groovy 2.4.15 but maybe he's got something quirky going on with dependency resolution such that it's pulling in a newer version of `groovy-all` which doesn't contain that `groovy-dateutil` package by default.

**Comment by jglapa** [comment]
obsolete
