### ISSUE TITLE
grails 3.3.6 error when building war (MultiProject)

### ISSUE THREAD

**Issue by miguelabautista** [grails/grails-core#11032]
I migrated the project from 3.3.2 to 3.3.6 and when building the war I got this error.

Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':fatcaone3:bootRepackage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:230)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:227)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
        ... 44 more
Caused by: java.lang.IllegalStateException: invalid entry size (expected 4 but got 3 bytes)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.repackage(RepackageTask.java:238)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.execute(RepackageTask.java:190)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.execute(RepackageTask.java:165)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
        at org.gradle.api.internal.tasks.RealizableTaskCollection.all(RealizableTaskCollection.java:192)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:159)
        at org.springframework.boot.gradle.repackage.RepackageTask.repackage(RepackageTask.java:140)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:692)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:675)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 78 more
Caused by: java.util.zip.ZipException: invalid entry size (expected 4 but got 3 bytes)
        at org.springframework.boot.loader.tools.JarWriter.writeEntry(JarWriter.java:268)
        at org.springframework.boot.loader.tools.JarWriter.writeEntries(JarWriter.java:146)
        at org.springframework.boot.loader.tools.JarWriter.writeEntries(JarWriter.java:126)
        at org.springframework.boot.loader.tools.Repackager.repackage(Repackager.java:285)
        at org.springframework.boot.loader.tools.Repackager.repackage(Repackager.java:262)
        at org.springframework.boot.loader.tools.Repackager.repackage(Repackager.java:194)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.repackage(RepackageTask.java:235)
        ... 98 more

**Comment by ilopmar** [comment]
This is because of the new Spring Boot version. Can you please check if you have any empty - 0 bytes GSP file? @erichelgeson reported this and the issue was because of empty GSP file.

**Comment by ilopmar** [comment]
More information from Grails slack. It may not be a GSP file but another type. Here you have instructions about how to discover the file that is the culprit:

![image](https://user-images.githubusercontent.com/559192/41601549-0b526fb0-73d9-11e8-9df8-4bb9f8d0387c.png)

**Comment by ilopmar** [comment]
Basically execute on the command line `strings file.jar` or `strings file.war` and the last file will be the culprit.

**Comment by erichelgeson** [comment]
Issue is related to a change in the Zip handling in spring-boot 1.5.14 - https://github.com/spring-projects/spring-boot/issues/13525 - remove any small files that may be in your zip (empty gsp/etc)

**Comment by ilopmar** [comment]
The issue has been fixed in Spring Boot and will be included in `1.5.15`

**Comment by aadrian** [comment]
@ilopmar Any workaround for this until 3.3.7 will be released ?

We are getting this issue with single projects too (just using `grails war`)
We have no empty GSP files, but maybe some of the official plug-ins have.

**Comment by ilopmar** [comment]
@aadrian have you tried with the solution Eric proposed in this same issue? Execute `strings my-app.war` and the last file will be the culprit.

**Comment by aadrian** [comment]
@ilopmar of course, but that file isn't empty :( . 
It's small, but it's not empty (small like most of our templates for fields)

**Comment by ilopmar** [comment]
Try to add an empty or few empty lines at the end of the file. Take a look at Mark's comment in the slack screenshot. One of his files wasn't empty but it was really small.

**Comment by HybridProgrammer** [comment]
Here's the find command that might help others with large amounts of empty files. Shockingly the libraries I used had many. Hope this helps others while this is an open issue. 

`find . -type f -empty`

Remove or add a comment to the files.

**Comment by aadrian** [comment]
@HybridProgrammer it's not just empty files, but also those that are small (not sure what's the limit).

@ilopmar Thank you for your help . Unfortunately we have hundreds of small GSP files containing mostly only one or two lines of code ("thanks" to how the Fields plug-in structures stuff). 

We already have much too many workarounds for the various Grails 3 issues (that were not present with Grails 2 https://github.com/aadrian/fieldbugs1 ) , this one however was categorized by other developers as "unacceptable to pollute the sources like that" :) )

It's just strange that such a serious bug is not being higher prioritized (it makes Grails 3.3.6 practically unusable, since WARs can be built because of it :(  )

**Comment by ilopmar** [comment]
@aadrian If you read this thread you'll see that the bug is not because of Grails but because of Spring Boot: https://github.com/spring-projects/spring-boot/issues/13525. They have fixed the bug but SpringBoot 1.5.15 has not been released yet. 
You can also see that we have an issue for upgrading Grails to use that SpringBoot version https://github.com/grails/grails-core/issues/11043 and as soon as they release the version we will use it for next Grails 3.3.7.

**Comment by aadrian** [comment]
> If you read this thread you'll see that the bug is not because of Grails but because of Spring Boot

@ilopmar  Of course: Spring Boot being such a **central** dependency nowadays for so many projects,  it's just strange that breaking issues are not prioritized higher.
