### ISSUE TITLE
MSSQL Grails 3.3.6

### ISSUE THREAD

**Issue by costerutilo** [grails/grails-core#11049]

**Comment by costerutilo** [comment]
After upgrading from Grails 3.2.x to Grails 3.3.6 saving an Object in Database doesn't work.

My database configuration:
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    username: XX
    password: XX
    dbCreate: update
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
environments:
    development:
        dataSource:
            url: jdbc:sqlserver://localhost;database=xxx;port=1433
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

    //JDBC Driver:
    compile 'com.microsoft.sqlserver:mssql-jdbc:6.4.0.jre8'

Whenever I call a *.save(flush:true) method on a domain class I get the error:

Caused by: **com.microsoft.sqlserver.jdbc.SQLServerException: The value is not set for the parameter number 2.**
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.buildParamTypeDefinitions(SQLServerPreparedStatement.java:377)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.buildPreparedStrings(SQLServerPreparedStatement.java:329)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:511)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:401)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)

I used the same configuration on Grails 3.2.x without any problems.

Thank you for your help!

**Comment by ilopmar** [comment]
Please take a look at the Upgrade Notes because some things changed in GORM 6.1.x: http://gorm.grails.org/latest/hibernate/manual/index.html#upgradeNotes

**Comment by costerutilo** [comment]
Thank you ilopmar - I tested everything but found no solution

**Comment by costerutilo** [comment]
I still have not found a solution to the problem. I am also unable to reproduce the problem in a new project. When I activate SQL logging, I get the following error messages:

Hibernate: select TOP(?) this_.id as y0_ from svvkunden this_ where this_.kundennummer=?
TRACE org.hibernate.type.descriptor.sql.BasicBinder.bind 65 - binding parameter [2] as [NUMERIC] - [201604601]
TRACE org.hibernate.type.descriptor.sql.BasicBinder.bind 65 - binding parameter [2] as [NUMERIC] - [201604601]
DEBUG org.hibernate.SQL.logStatement 92 - select TOP(?) this_.id as y0_ from svvkunden this_ where this_.id=?
DEBUG org.hibernate.SQL.logStatement 92 - select TOP(?) this_.id as y0_ from svvkunden this_ where this_.id=?
Hibernate: select TOP(?) this_.id as y0_ from svvkunden this_ where this_.id=?
WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions 129 - SQL Error: 0, SQLState: null
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions 131 - **The value is not set for the parameter number 2.**

**Comment by olavgg** [comment]
It seems like you are executing a query where you are missing the second parameter? I highly recommend that you create an example. It is really difficult to help you with current information.

**Comment by costerutilo** [comment]
After a lot of tests, I found the solution/problem:

If you have a domain class with:

	/** 1:1 Relationship to Test */
	static hasOne = [test:Test]

and the constraint:

    static constraints = {
		test nullable:true, **unique: true**
    }

you get the error "'The value is not set for the parameter number 2"

with 
    static constraints = {
		test nullable:true //_, unique: true_
    }
it works
