### ISSUE TITLE
Problem With HibernateTransactionManager, Multiple Datasources

### ISSUE THREAD

**Issue by jphiloon** [grails/grails-core#11051]
Grails 3.2.5, Quartz plugin 2.0.9

Sql code is run in a quartz job to join unrelated tables, truncate dates for comparison, etc.

        def cfgSvc = grails.util.Holders.applicationContext.getBean('jdeisConfigurationService')
        String x = cfgSvc.getConfigValue('jdeis.assignmentNotifications.disabled', 'false')
 
            def sql = '''
                select * 
                from Object_Notification an
                join Assignment a on a.id = an.object_id
                join Notification n on n.id = an.notification_id
                where ...
            '''

            def mappings = ObjectNotification.withSession { session->
                session.createSQLQuery(sql).addEntity(ObjectNotification).list()
            }

This works fine - until a second database is added, even if no domain object references it.  The stacktrace is:

2018-07-18 13:26:37,357 ERROR grails.plugins.quartz.listeners.ExceptionPrinterJobListener - Exception occurred in job: Grails Job
org.quartz.JobExecutionException: org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is rolled back; nested exception is org.springframework.transaction.IllegalTransactionStateException: Transaction is already completed - do not call commit or rollback more than once per transaction
	at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is rolled back; nested exception is org.springframework.transaction.IllegalTransactionStateException: Transaction is already completed - do not call commit or rollback more than once per transaction
	at org.grails.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:183)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at com.penbaymedia.jdeis5.service.JdeisConfigurationService.getConfigValue(JdeisConfigurationService.groovy)
	at com.penbaymedia.jdeis5.service.JdeisConfigurationService$getConfigValue.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.penbaymedia.jdeis5.job.AssignmentNotificationIntervalJob.execute(AssignmentNotificationIntervalJob.groovy:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:104)
	... 2 common frames omitted
Caused by: org.springframework.transaction.IllegalTransactionStateException: Transaction is already completed - do not call commit or rollback more than once per transaction
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:704)
	at org.grails.transaction.MultiTransactionStatus.commit(MultiTransactionStatus.java:73)
	at org.grails.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:156)
	... 16 common frames omitted

The suspect module is the call into JdeisConfigurationService.  This service is defined with 
    @Transactional(readOnly = true)
    class JdeisConfigurationService { ... }

However, JdeisConfigurationService, as it now stands, makes no database calls at all.  The getConfigValue() method called only reads values from the config Holder and JNDI resources..

Commenting out the @Transactional(readOnly = true) declaration allows the quartz job to run without error.

So, to reproduce:
Define multiple databases in application.yml.  Create a quartz job using withSession {}, call into a transactional service.

**Comment by jphiloon** [comment]
I think this can be cured by rearranging the dataSource definitions in application.yml to have the structure:
    dataSource:
        ..default dataSource
    dataSources:
        ...additional dataSources
