### ISSUE TITLE
Request CONTROLLER_NAME_ATTRIBUTE is ignored, resulting in template lookup failure (3.3.8)

### ISSUE THREAD

**Issue by dlehammer** [grails/grails-core#11075]
These symptoms where uncovered during migration from Grails v2.4.5 to v3.3.6, and is still present in v3.3.8.
The original use-case is generation of a pdf based on the output from another controller, aka. `targetControllerName`, and works during integration-test and runtime in Grails v2.4.5.

The [example application](https://github.com/dlehammer/grails-core-issues-11075) mimics the approach from the application that's being migrated.
In the below success-flow either `SomeController` or `RenderController` plays the part of pdf-controller.

1. pdf-controller -> index (`request.setAttribute(GrailsApplicationAttributes.CONTROLLER_NAME_ATTRIBUTE, targetControllerName)`)
2. render `/some/temp` (some/_temp.gsp) -> `<g:render template="/${targetControllerName}/summary"/>`
3. (other/_summary.gsp) -> `<summary:section template="participant"/>` 
4. (`my.webapp.SummaryTaglibTagLib`) -> (`other/_participant.gsp`)

Step 4 exposes the symptom.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

#### unit-test symptom
1. clone [example application](https://github.com/dlehammer/grails-core-issues-11075) repo
2. evaluate test
```
my-webapp$ ./grailsw test-app --stacktrace --info
```
3. notice `RenderControllerSpec` failed 
![rendercontrollerspec](https://user-images.githubusercontent.com/17439718/44471484-51720980-a62c-11e8-852c-c2b7586531c2.png)

#### runtime symptom
1. clone [example application](https://github.com/dlehammer/grails-core-issues-11075) repo
2. start app
```
my-webapp$ ./grailsw run-app
```
3. Open http://localhost:8080/some/index notice symptom
4. Open http://localhost:8080/other/index or http://localhost:8080/render/index -> Hello world...
![somecontroller_runtime_error](https://user-images.githubusercontent.com/17439718/44471516-5fc02580-a62c-11e8-8c96-c22795802111.png)

### Expected Behaviour

Lookup of template is consistent according to Grails convention, and any resulting error message reflects the actual state.

### Actual Behaviour

Template lookup fails unexpectedly when using `request.setAttribute(GrailsApplicationAttributes.CONTROLLER_NAME_ATTRIBUTE,'other')`.

The [example application](https://github.com/dlehammer/grails-core-issues-11075) contains two examples:

#### 1. `RenderController` unit-test
`RenderControllerSpec` fails during unit-test execution:
```
org.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Error processing GroovyPageView: [views/some/_temp.gsp:1] [views/other/_summary.gsp:1] Template not found for name [participant] and path [/other/_participant.gsp]
	at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.renderViewForTemplate(ResponseRenderer.groovy:599)
	at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.render(ResponseRenderer.groovy:341)
	at my.webapp.RenderController.index(RenderController.groovy:16)
	at org.grails.testing.runtime.support.ActionSettingMethodHandler.invoke(ActionSettingMethodHandler.groovy:29)
	at my.webapp.RenderControllerSpec.test index(RenderControllerSpec.groovy:22)
Caused by: org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/some/_temp.gsp:1] [views/other/_summary.gsp:1] Template not found for name [participant] and path [/other/_participant.gsp]
	at org.grails.web.servlet.view.GroovyPageView.createGroovyPageException(GroovyPageView.java:135)
	at org.grails.web.servlet.view.GroovyPageView.handleException(GroovyPageView.java:112)
	at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:80)
	at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
	at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.renderViewForTemplate(ResponseRenderer.groovy:596)
	... 4 more
Caused by: org.grails.taglib.GrailsTagException: [views/some/_temp.gsp:1] [views/other/_summary.gsp:1] Template not found for name [participant] and path [/other/_participant.gsp]
	at org.grails.gsp.GroovyPage.throwRootCause(GroovyPage.java:469)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:415)
	at home_dleh_tmp_my_webapp_grails_app_views_some__temp_gsp.run(home_dleh_tmp_my_webapp_grails_app_views_some__temp_gsp:15)
	at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
	at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
	at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:76)
	... 8 more
```
#### 2. `SomeController` runtime

```
2018-08-22 16:05:44.723 ERROR --- [nio-8080-exec-8] o.g.web.errors.GrailsExceptionResolver   : GrailsTagException occurred when processing request: [GET] /some/index
[views/some/_temp.gsp:1] [views/other/_summary.gsp:1] Template not found for name [participant] and path [//_participant.gsp]. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.grails.taglib.GrailsTagException: [views/some/_temp.gsp:1] [views/other/_summary.gsp:1] Template not found for name [participant] and path [//_participant.gsp]
	at org.grails.gsp.GroovyPage.throwRootCause(GroovyPage.java:469)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:415)
	at home_dleh_tmp_my_webapp_grails_app_views_some__temp_gsp.run(home_dleh_tmp_my_webapp_grails_app_views_some__temp_gsp:15)
	at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
	at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
	at grails.gsp.PageRenderer.renderViewToWriter(PageRenderer.groovy:122)
	at grails.gsp.PageRenderer.render(PageRenderer.groovy:66)
	at my.webapp.SomeController.index(SomeController.groovy:20)
	... 14 common frames omitted
```
### Environment Information

- **Operating System**: Ubuntu v16.04 (64-bit)
- **Grails Version:** 3.3.8
- **JDK Version:** OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)
- **Container Version (If Applicable):** N/A

### Example Application

- https://github.com/dlehammer/grails-core-issues-11075

**Comment by jeffbrown** [comment]
> 1. clone example application repo

Where is that repo?

**Comment by dlehammer** [comment]
> Where is that repo?

Should be there now.
It's a bit of chicken and egg problem, as I prefer the repository to reflect the issue :)

**Comment by dlehammer** [comment]
I've done a little bit of digging, and debugging has revealed the source(s) of the symptom.

As far as I can tell the `URI` is generated atleast two times by different logic. This causes the symptom where the lookup fails and the path included in the error-message is different from the actual lookup state...

As an example I'm using the `RenderController` that is expected to end up rendering `other/_participant.gsp`.

`GrailsConventionGroovyPageLocator:274` notice how `templateURI` contains `render/_participant.gsp`, this lookup fails...
![grailsconventiongroovypagelocator_templateuri](https://user-images.githubusercontent.com/17439718/44472044-9e0a1480-a62d-11e8-82b9-5e98e96f7b2d.png)

`GroovyPagesTemplateRenderer:130` notice how `uri` contains `other/_participant.gsp`, this lookup should succeed, but the URI is instead used for caching and error-message...
![groovypagestemplaterenderer_uri](https://user-images.githubusercontent.com/17439718/44472059-acf0c700-a62d-11e8-8893-73cca5aa6795.png)


The optimal solution encapsulates Grails template convention `URI` generation in a single place, in-order to enforce consistent behavior and error-messages.
(Grails could benefit from this re-factoring as this should eliminate duplicate code)

**Comment by jeffbrown** [comment]
There may be some opportunity to make some of the implementation more efficient but separate from that, I don't think setting `CONTROLLER_NAME_ATTRIBUTE` in your controller is a good idea.  That is monkeying with a detail that is likely to create a number of problems.

**Comment by dlehammer** [comment]
@jeffbrown I agree, the approach in the application that surfaced the symptom maybe sub-optimal.

I have no strong opinion on which approach that best adheres to the Grails template convention as I'm no expert on the matter.
My main focus is the inconsistent implementation, as it took a while to untangle the root cause for the symptom, my goal with this issue is to help Grails, as a framework, to be more predictable and developer-friendly.

What I recommend is stream-lining the lookup approach in-order to enforce consistency and predictability.
Side-effects might include higher efficiency and maintainability :)

**Comment by niravassar** [comment]
I have not looked into this issue other than reading the description above. However by scanning your screenshots this is around the same code involved with #11087. I will be checking this out.

**Comment by niravassar** [comment]
From what I have surmised, you have attempted to use `request.setAttribute(GrailsApplicationAttributes.CONTROLLER_NAME_ATTRIBUTE,'other')` to influence the base path in the statement `<summary:section template="participant"/>`. 

This attribute is used in `grails-web-common` and is grails implementation detail. Grails as a framework doesn't espouse to influence view rendering in this way, so I don't think this in itself is a bug.  However, your interrogation into the code may have exposed some duplicate logic, which I think can be examined in another context I suppose.
	
In order to make the rendering of `<summary:section template="participant"/>` work, I believe you could pass in a model attribute of the class name in this statement `<g:render template="/${targetControllerName}/summary"/>`, (that is if i understand your intent correctly.) Thanks for digging in!
