### ISSUE TITLE
Certificate at https://repo.grails.org has expired 

### ISSUE THREAD

**Issue by lthuangiang** [grails/grails-core#11082]
The certificate at https://repo.grails.org has expired and is failing our builds.
<img width="1123" alt="screen shot 2018-08-28 at 7 42 51 pm" src="https://user-images.githubusercontent.com/1841367/44723607-add89b80-aafa-11e8-9730-bec179fe9c02.png">

**Comment by lthuangiang** [comment]
> Could not resolve net.minidev:json-smart:[1.3.1,2.3].
               > Failed to list versions for net.minidev:json-smart.
                  > Unable to load Maven meta-data from https://repo.grails.org/grails/core/net/minidev/json-smart/maven-metadata.xml.
                     > Could not GET 'https://repo.grails.org/grails/core/net/minidev/json-smart/maven-metadata.xml'.
                        > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

**Comment by jeffbrown** [comment]
We are working on it.  Thanks for the feedback.

**Comment by dularion** [comment]
How is it going? 
we need to update our production environment and we cant right now because neither the tests nor the assemble will run

**Comment by jeffbrown** [comment]
> How is it going?

It is going fine.  We are working with the folks at JFrog and will have the issue addressed as quickly as we can.  At the moment I don't know how long that is going to take though.

**Comment by jeffbrown** [comment]
For now are you able to resolve whatever grails artifacts you need from jcenter?

**Comment by jeffbrown** [comment]
Using http instead of https as a temporary solution will work for some folks who are comfortable doing that.

We will have the new cert in place asap.

**Comment by rirl-spireon** [comment]
Any update on an ETA for those of us who cannot use http?

**Comment by jeffbrown** [comment]
No.  We are waiting for JFrog to put the new cert in place.  Could be any minute but I don't know.

**Comment by mindspin311** [comment]
Is there a way to use http instead of https? Can't seem to find a way to override that at the project level as I can't find `repo.grails.org`

**Comment by jeffbrown** [comment]
```groovy
maven { url "http://repo.grails.org/grails/core" }
```

**Comment by jeffbrown** [comment]
> Has jfrog actually been in contact as of yet?

Yes. As I said above... We are working with the folks at JFrog.

**Comment by mindspin311** [comment]
Can't seem to find where to put that in the `BuildConfig.groovy`. Does not appear to be changing it.

**Comment by mindspin311** [comment]
Ok, wanted 
`mavenRepo "http://repo.grails.org/grails/plugins/"`

Put that in here:

```
grails.project.dependency.resolution = {
...
...
    repositories {
...
...
        mavenRepo "http://repo.grails.org/grails/plugins/"
```

**Comment by dlehammer** [comment]
Is this issue identical to the below error?
Using Grails v3.3.8.


```
$ grails create-app my-webapp --stacktrace

| Error Error occurred running Grails CLI: NotAfter: Tue Aug 28 14:00:00 CEST 2018 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.security.cert.CertificateExpiredException: NotAfter: Tue Aug 28 14:00:00 CEST 2018
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:436)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:287)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:243)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:217)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:318)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:300)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:292)
	at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:54)
	at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:50)
	at org.grails.cli.profile.repository.MavenProfileRepository.<init>(MavenProfileRepository.groovy:53)
	at org.grails.cli.GrailsCli.createMavenProfileRepository(GrailsCli.groovy:334)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:235)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
```

**Comment by jeffbrown** [comment]
> Is this issue identical to the below error?

Yes

**Comment by jeffbrown** [comment]
Fixed.

**Comment by lthuangiang** [comment]
Thanks @jeffbrown

**Comment by haleylanebrown** [comment]
@jeffbrown This seems to be happening again. Trying to run "grails create-app" and receiving the following error: "Error occurred running Grails CLI: NotAfter: Sat May 30 04:48:38 MDT 2020". Any thoughts?

**Comment by apolczyk** [comment]
Me too just now :((
```
$ grails -version
| Grails Version: 4.0.4
| JVM Version: 1.8.0_25

$ grails create-app my-app --stacktrace
| Error Error occurred running Grails CLI: NotAfter: Sat May 30 11:48:38 BST 2020 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.security.cert.CertificateExpiredException: NotAfter: Sat May 30 11:48:38 BST 2020
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:570)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:554)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:415)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:164)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:296)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:252)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:453)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:360)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:261)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:192)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:539)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:522)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:411)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:353)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:256)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:307)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:293)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:277)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:269)
	at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:54)
	at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:50)
	at org.grails.cli.profile.repository.MavenProfileRepository.<init>(MavenProfileRepository.groovy:53)
	at org.grails.cli.GrailsCli.createMavenProfileRepository(GrailsCli.groovy:333)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:234)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Error occurred running Grails CLI: NotAfter: Sat May 30 11:48:38 BST 2020
```

**Comment by apolczyk** [comment]
Ah, okay... if anyone else is having this issue take a look at https://github.com/grails/grails-core/issues/11594 ;)

**Comment by AshokKumarSharma** [comment]
Hi Team,

I am facing problem while downloading maven plugins. below is the screen shot 
"Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.grails.plugins:tomcat:pom:7.0.52.1 from/to repo_grails_org_grails_plugins (https://repo.grails.org/grails/plugins): peer not authenticated"

![image](https://user-images.githubusercontent.com/67033363/122005167-dfc06700-cde7-11eb-872d-e29f58cc01d0.png)

For the reference i have put below thing sin buildconfig.groovy and using TLSv1.2

grailsPlugins()
        grailsHome()
        mavenLocal()
        //grailsCentral()
        mavenRepo "https://repo1.maven.org/maven2/"
        mavenRepo "https://repo.grails.org/grails/plugins"
        mavenCentral()
	mavenRepo "https://code.lds.org/nexus/content/groups/main-repo"

for creating the war i am using below command by github actions 

./grailsw war -Dhttps.protocols=TLSv1.3 -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true --stacktrace --verbose.

It will be really apricated if anyone have solution of this or experience same
