### ISSUE TITLE
redirect & foward do not work for dynamic mappings when a parameter has $

### ISSUE THREAD

**Issue by jdaugherty** [grails/grails-core#11144]
When domain objects have a natural key, and that key has a '$' in it, a url mapping error is thrown.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Start application
2. Visit http://localhost:8080
3. Click on Book Controller

### Expected Behaviour

Page should render

### Actual Behaviour

Exception is thrown: Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/book/index.gsp:21] Error executing tag <f:table>: [views/templates/_fields/_table.gsp:14] Error executing tag <g:link>: No group 1

```
java.lang.IndexOutOfBoundsException: No group 1
        at java.util.regex.Matcher.start(Matcher.java:375)
        at java.util.regex.Matcher.appendReplacement(Matcher.java:880)
        at java.util.regex.Matcher.replaceFirst(Matcher.java:1004)
        at java.lang.String.replaceFirst(String.java:2178)
        at org.grails.web.mapping.RegexUrlMapping.createURLInternal(RegexUrlMapping.java:326)
        at org.grails.web.mapping.RegexUrlMapping.createURLInternal(RegexUrlMapping.java:466)
        at org.grails.web.mapping.RegexUrlMapping.createRelativeURL(RegexUrlMapping.java:498)
        at org.grails.web.mapping.UrlCreatorCache$CachingUrlCreator.createRelativeURL(UrlCreatorCache.java:110)
        at org.grails.web.mapping.DefaultLinkGenerator.link(DefaultLinkGenerator.groovy:265)
        at org.grails.web.mapping.CachingLinkGenerator.link(CachingLinkGenerator.java:76)
        at org.grails.plugins.web.taglib.ApplicationTagLib.doCreateLink(ApplicationTagLib.groovy:382)
        at org.grails.plugins.web.taglib.ApplicationTagLib$_closure9.doCall(ApplicationTagLib.groovy:359)
        at org.grails.taglib.TagOutput.captureTagOutput(TagOutput.java:64)
        at org.grails.plugins.web.taglib.ApplicationTagLib$_closure7.doCall(ApplicationTagLib.groovy:225)
        at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:446)
        at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)
        at gsp_fields_templates__fields_table_gsp.run(gsp_fields_templates__fields_table_gsp.groovy:41)
        at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
        at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
        at org.grails.web.gsp.GroovyPagesTemplateRenderer.makeTemplate(GroovyPagesTemplateRenderer.java:232)
        at org.grails.web.gsp.GroovyPagesTemplateRenderer.render(GroovyPagesTemplateRenderer.java:113)
        at org.grails.plugins.web.taglib.RenderTagLib$_closure7.doCall(RenderTagLib.groovy:367)
        at org.grails.taglib.TagOutput.captureTagOutput(TagOutput.java:78)
        at grails.artefact.gsp.TagLibraryInvoker$Trait$Helper.methodMissing(TagLibraryInvoker.groovy:88)
        at grails.plugin.formfields.FormFieldsTagLib$_closure4.doCall(FormFieldsTagLib.groovy:239)
        at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:446)
        at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)

```

### Environment Information

- **Operating System**: Mac
- **Grails Version:** 3.3.8
- **JDK Version:** Java 8, Build 181
- **Container Version (If Applicable):** N/A

### Example Application

https://github.com/jdaugherty/grails-issue-regexmapping

**Comment by jdaugherty** [comment]
In grails 4, this now affects redirects.  I've adjusted the title of this ticket to better reflect the problem.
