### ISSUE TITLE
Grails 4 run-app command not working

### ISSUE THREAD

**Issue by niravassar** [grails/grails-core#11214]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a grails 4 application: `grails create-app sample-grails-upgrade`
2. run `grails run-app`
3. Get the error: 

```
| Error Command [run-app] error: Profile [org.grails.profiles:base:3.3.1] declares an invalid dependency on parent profile [org.grails.profiles:base:3.3.1]
java.lang.IllegalStateException: Profile [org.grails.profiles:base:3.3.1] declares an invalid dependency on parent profile [org.grails.profiles:base:3.3.1]
        at org.grails.cli.profile.AbstractProfile$_getExtends_closure4.doCall(AbstractProfile.groovy:360)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:427)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3540)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3525)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3625)
        at org.grails.cli.profile.AbstractProfile.getExtends(AbstractProfile.groovy:357)
        at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:440)
        at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:130)
        at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:468)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:377)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:350)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Command [run-app] error: Profile [org.grails.profiles:base:3.3.1] declares an invalid dependency on parent profile [org.grails.profiles:base:3.3.1]
```

### Expected Behaviour

The app should load normally

### Actual Behaviour

Breaks as it might be a command issue in the CLI

### Environment Information

    Operating System: Win 10
    Grails Version: 4.0.0.BUILD-SNAPSHOT
    JDK Version: 1.8.0_191
    Container Version (If Applicable): none

**Comment by graemerocher** [comment]
I couldn't reproduce this with master

**Comment by niravassar** [comment]
I tried this again and it now works. Must have been fixed through a CLI change
