### ISSUE TITLE
Bootstrapping Tenant aware Domain

### ISSUE THREAD

**Issue by pleonar3** [grails/grails-core#11279]
### Steps to Reproduce
1. Create a new grails app, setting up multi tenancy for gorm and adding multiple datasources.
2. Create a tenant aware domain.
3. Add bootstrapping code for the tenant aware domain, and run the application.

### Expected Behaviour

When using the @WithoutTenant annotation, I expect the domain to behave as if it weren't tenant aware, and add records to the global database.

### Actual Behaviour

You get an error, saying tenant cannot be resolved outside a web request.

        org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException: Tenant could 
          not be resolved outside a web request
        at org.grails.datastore.mapping.multitenancy.web.SubDomainTenantResolver.resolveTenantIdentifier(SubDomainTenantResolver.groovy:43)
        at grails.gorm.multitenancy.Tenants.currentId(Tenants.groovy:73)
        at org.grails.datastore.gorm.GormEnhancer.findTenantId(GormEnhancer.groovy:273)
        at org.grails.datastore.gorm.GormEnhancer.findInstanceApi(GormEnhancer.groovy:317)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.currentGormInstanceApi(GormEntity.groovy:1364)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper$save.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at app.Book.save(Book.groovy)
        at app.Book.save(Book.groovy)
        at org.grails.datastore.gorm.GormEntity$save.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at app.BootStrap$_closure1.doCall(BootStrap.groovy:9)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1099)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:541)
        at grails.util.Environment.executeForEnvironment(Environment.java:534)
        at grails.util.Environment.executeForCurrentEnvironment(Environment.java:510)
        at org.grails.web.servlet.boostrap.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:74)
        at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:65)
        at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:53)
        at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:263)
        at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:146)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at app.Application.main(Application.groovy:8)

### Environment Information

- **Operating System**: Ubuntu 18
- **Grails Version:** 3.3.9
- **JDK Version:** openjdk version "1.8.0_172"

### Example Application

- [github](https://github.com/pleonar3/grails-bootstrapping-tenant-aware)

**Comment by erichelgeson** [comment]
Related issue https://github.com/grails/grails-data-mapping/issues/1124 - it does work on a method level, not a class.

**Comment by pleonar3** [comment]
> Related issue [grails/grails-data-mapping#1124](https://github.com/grails/grails-data-mapping/issues/1124) - it does work on a method level, not a class - though it should work on a class.

I just updated the repo, and put the object creation to a method with the @WithoutTenant annotation. Same result.

**Comment by graemerocher** [comment]
Move the logic into a service

**Comment by pleonar3** [comment]
> Move the logic into a service

@graemerocher , Just tried moving the logic to a service, nothing has changed, still receiving the same error. Updated the [repo](https://github.com/pleonar3/grails-bootstrapping-tenant-aware).

**Comment by pleonar3** [comment]
The solution for now is to use the groovy sql class to bootstrap the data.
This works fine, but is less than an efficient way to write the code.

**Comment by puneetbehl** [comment]
It should be fixed with PR grails/grails-data-mapping#1242
