### ISSUE TITLE
Grails 4 with datastore-rest-client dependency still fails

### ISSUE THREAD

**Issue by niravassar** [grails/grails-core#11288]
### Task List

- [ x] Steps to reproduce provided
- [ x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. grails-core in the gradle plugin has a bug fix to not bring in datastore-rest-client 7.0.0 
2. grails 4 app with datastore rest client dependency has integration tests (these tests work in grails 3)
3. Run the tests and get a `NoSuchMethodError:`

### Expected Behaviour

The tests should run the same and pass given the depenency is brought in correctly. 

### Actual Behavior

- The dependency is brought in by gradle correctly, but the execution of the test throws this error:

```
java.lang.NoSuchMethodError: org.springframework.http.MediaType.getCharSet()Ljava/nio/charset/Charset;
	at org.grails.datastore.gorm.rest.client.utils.NullSafeStringHttpMessageConverter.getCharSetForMediaType(NullSafeStringHttpMessageConverter.groovy:45)
	at org.grails.datastore.gorm.rest.client.utils.NullSafeStringHttpMessageConverter.readInternal(NullSafeStringHttpMessageConverter.groovy:36)
	at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:199)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:111)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:995)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:978)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:737)
```

### Environment Information

- **Operating System**: Win 10
- **Grails Version:** 4.0.0.SNAPSHOT
- **JDK Version:** 1.8
- **Container Version (If Applicable):** TODO

### Example Application

- branch for the fix of the gradle plugin
https://github.com/grails/grails-core/tree/gradle-plugin-datastore-rest-client-removal

- branch for the sample project
https://github.com/grails-guides/grails-mock-logging-slf4j-test/commits/grails-4-datastore-rest-client

**Comment by niravassar** [comment]
- the MediaType is in spring-web:4.3.16 and charset is is on MimeType in spring-core:4.3.16 is charSet uppercase
- in the new version of MimeType getCharset() is there and the uppercase has been taken out. This is in spring 5.1.5 where its has charset lowecasre, while in spring 4.3.16 charSet is there with lowercase
