### ISSUE TITLE
[Grails 3.3.9] - Execution failed for task ':compileGsonViews'

### ISSUE THREAD

**Issue by eugenio1590** [grails/grails-core#11295]
### Steps to Reproduce

1. Create a web project with grails '3.3.9' and views-gradle:'1.2.10'
2. Ran the task `compileGmlViews`

### Expected Behaviour

Successful compilation

### Actual Behaviour

````
> Task :compileJava NO-SOURCE
> Task :compileGroovy UP-TO-DATE
> Task :buildProperties UP-TO-DATE
> Task :processResources
> Task :classes
> Task :pathingJar UP-TO-DATE

> Task :compileGsonViews FAILED
Exception in thread "main" org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
TestApp_profile_update_gson: 1: unable to resolve class model.Profile
 @ line 1, column 1.
   import model.Profile
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:981)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:575)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at org.codehaus.groovy.control.CompilationUnit$compile$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at grails.views.AbstractGroovyTemplateCompiler.compile(AbstractGroovyTemplateCompiler.groovy:71)
	at grails.views.AbstractGroovyTemplateCompiler$compile$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at grails.views.AbstractGroovyTemplateCompiler.run(AbstractGroovyTemplateCompiler.groovy:120)
	at grails.plugin.json.view.JsonViewCompiler.main(JsonViewCompiler.groovy:41)

FAILURE: Build failed with an exception.
````

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.3.9
- **JDK Version:** openjdk version "1.8.0_201"

**Comment by jameskleeh** [comment]
Please upload a sample application
