### ISSUE TITLE
4.0.0.RC1, Structured Data Binding Editors Not Working

### ISSUE THREAD

**Issue by puneetbehl** [grails/grails-core#11315]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new application using `grails create-app example.sturct-demo`
2. Create a domain class `Shape` with property `int area`
3. Create another domain class `Gadget` with properties `expandedShape` and `compressedShape` of type Shape.
4. Register a structured editor as:

_src/main/groovy/example/converters/StructuredShapeEditor.groovy_
```
package example.converters

import example.Shape

import org.grails.databinding.converters.AbstractStructuredBindingEditor

class StructuredShapeEditor extends AbstractStructuredBindingEditor<Shape> {

    public Shape getPropertyValue(Map values) {
        def width = values.width as int
        def height = values.height as int
        def area = width * height
        new Shape(area: area)
    }
}
```
5. Register with the Spring application context:

_grails-app/conf/spring/resources.groovy_
```
beans = {
    shapeEditor example.converters.StructuredShapeEditor
    // ...
}
```
6. Create a controller DemoController.groovy as:

_grails-app/controllers/example/DemoController.groovy_
```
package example

import grails.converters.JSON

class DemoController {

    def createGadget(Gadget gadget) {
        render(["ES": gadget.expandedShape.area, "CS": gadget.compressedShape.area] as JSON)
    }
}
```
7. Submit the form to `/demo/createGadget` with following:
```
expandedShape:struct
expandedShape_width:80
expandedShape_height:30
compressedShape:struct
compressedShape_width:10
compressedShape_height:3
```

### Expected Behaviour
 With the request parameters `/demo/createGadget?expandedShape=struct&expandedShape_width=80&expandedShape_height=30&compressedShape=struct&compressedShape_width=10&compressedShape_height=3` gadget.expandedShape.area would be 2400 and gadget.compressedShape.area would be 30

### Actual Behaviour

Error 500: Internal Server Error with exception stactrace:
```
Cannot get property 'area' on null object. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Cannot get property 'area' on null object
	at example.DemoController.createGadget(DemoController.groovy:17)
	... 13 common frames omitted
```

### Environment Information

- **Operating System**: macOS Mojave
- **Grails Version:** 4.0.0.RC1
- **JDK Version:** 1.8

### Example Application

- [Sample Application.zip](https://github.com/grails/grails-core/files/3130487/hello-binder.zip)

**Comment by jeffbrown** [comment]
Per conversation with @puneetbehl this morning, he says this can be closed.
