### ISSUE TITLE
Grails 4 autoImport false not working

### ISSUE THREAD

**Issue by alexandresaura** [grails/grails-core#11344]
### Introduction

I created a simple application with two domains located in different packages but having the same class name. Mapping either one of them (or even both, as documented in [here](https://docs.grails.org/latest/ref/Database%20Mapping/autoImport.html)) with `autoImport false` doesn't seem to be working:

```
package foo

class Country {
    Long id

    static mapping = {
        autoImport false
        table "TABLE_1"
        id column: "test", generator: "assigned"
        version false
    }
}

```

```
package bar

class Country {
    Long id

    static mapping = {
        autoImport false
        table "TABLE_2"
        id column: "test", generator: "assigned"
        version false
    }
}

```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the repository from [https://github.com/alexandresaura/autoImport.git](https://github.com/alexandresaura/autoImport.git)
2. Run the application
`grails run-app`

### Expected Behaviour

Application should start without errors.

### Actual Behaviour

Application throws the following error:
```
Caused by: org.hibernate.DuplicateMappingException: The [bar.Country] and [foo.Country] entities share the same JPA entity name: [Country] which is not allowed!
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.addEntityBinding(InFlightMetadataCollectorImpl.java:305)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindRoot(GrailsDomainBinder.java:1408)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.contribute(GrailsDomainBinder.java:161)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:284)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:84)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:474)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:689)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:287)
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:86)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:39)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:23)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:200)
	at jdk.internal.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)

```
### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 4.0.0.RC2
- **JDK Version:** 11

### Example Application

- [https://github.com/alexandresaura/autoImport.git](https://github.com/alexandresaura/autoImport.git)

**Comment by jameskleeh** [comment]
I don't think the `autoImport` flag documentation says it allows multiple entities with the same name. It only talks about importing of domains into HQL statements.

@graemerocher Can you confirm this should be allowed?
