### ISSUE TITLE
Grails 4 app fails to resolve transitive dependencies of Grails 3 plugin

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#11345]
## Description

Trying to use a Grails 3 plugin such as Grails Rendering plugin in a Grails 4 application fails to resolve transitive dependencies of the plugin. 

Expected to be able to use: 

```
... 
dependencies {
  ...
  compile("com.lowagie:itext:2.1.0")
}
```

Need to add the [transitive dependencies of Grails rendering plugin](https://github.com/gpc/rendering/blob/master/build.gradle#L57-L58) directly: 

```
... 
dependencies {
  ...
  compile 'org.grails.plugins:rendering:2.0.3'
  compile("org.xhtmlrenderer:core-renderer:R8")
  compile("com.lowagie:itext:2.1.0")
}
```

## Steps to reproduce
———

In a Grails 3 app: 

```
grails --version
3.3.10
```

`$ grails create-app example.grails.grailsthree `
`$ cd grailsthree`
`$ touch grails-app/controllers/example/grails/HomeController.groovy`

```
package example.grails

class HomeController {

    def index() { 
        renderPdf(template: "/pdfs/report", model: [:], filename: 'sample.pdf')
    }
}
```

`$ mkdir -p grails-app/views/pdfs`

`$ touch grails-app/views/pdfs/_report.gsp`

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
</head>
<body>
</body>
</html>
```

`$ vi grails-app/controllers/example/grails/UrlMappings.groovy`

replace

```
...
   static mappings = {
            "/"(controller: "home")
   }
```

Add [Grails Rendering plugin](http://plugins.grails.org/plugin/grails/rendering)

`$ vi build.gradle`

```
... 
dependencies {
  ...
  compile 'org.grails.plugins:rendering:2.0.3'
  runtime "org.springframework:spring-test:4.2.1.RELEASE" // Workaround to: https://github.com/gpc/rendering/issues/42
}
```

Start the app and go to the home page 

`$ gradle bootRun`

Go to localhost:8080 and a blank PDF is downdloaded. 

---

In a Grails 4 app: 

```
grails --version
4.0.0.RC2
```

`$ grails create-app example.grails.grailsfour `
`$ cd grailsfour`
`$ touch grails-app/controllers/example/grails/HomeController.groovy`

```
package example.grails

class HomeController {

    def index() { 
        renderPdf(template: "/pdfs/report", model: [:], filename: 'sample.pdf')
    }
}
```

`$ mkdir -p grails-app/views/pdfs`

`$ touch grails-app/views/pdfs/_report.gsp`

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
</head>
<body>
</body>
</html>
```

`$ vi grails-app/controllers/example/grails/UrlMappings.groovy`

replace

```
...
   static mappings = {
            "/"(controller: "home")
   }
```

Add [Grails Rendering plugin](http://plugins.grails.org/plugin/grails/rendering)

`$ vi build.gradle`

```
... 
dependencies {
  ...
  compile 'org.grails.plugins:rendering:2.0.3'
}
```

Start the app and go to the home page 

`$ gradle bootRun`

Go to localhost:8080 and an exception is thrown: 

```
General error during instruction selection: java.lang.NoClassDefFoundError: Unable to load class grails.plugins.rendering.image.ImageRenderingService due to missing dependency org/xhtmlrenderer/simple/Graphics2DRenderer

java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class grails.plugins.rendering.image.ImageRenderingService due to missing dependency org/xhtmlrenderer/simple/Graphics2DRenderer
	at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1118)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1098)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:645)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:623)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:600)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:179)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:57)
	at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:80)
	at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:68)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:86)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Unable to load class grails.plugins.rendering.image.ImageRenderingService due to missing dependency org/xhtmlrenderer/simple/Graphics2DRenderer
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:409)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:280)
	at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:376)
	at org.codehaus.groovy.ast.ClassNode.declaresInterface(ClassNode.java:1001)
	at org.codehaus.groovy.ast.ClassNode.implementsInterface(ClassNode.java:981)
	at org.codehaus.groovy.transform.stc.StaticTypeCheckingVisitor.getResultType(StaticTypeCheckingVisitor.java:4108)
	at org.codehaus.groovy.transform.stc.StaticTypeCheckingVisitor.visitBinaryExpression(StaticTypeCheckingVisitor.java:832)
	at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:49)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:120)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:197)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:110)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:121)
	at org.codehaus.groovy.transform.stc.StaticTypeCheckingVisitor.visitConstructorOrMethod(StaticTypeCheckingVisitor.java:2079)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:132)
	at org.codehaus.groovy.transform.stc.StaticTypeCheckingVisitor.startMethodInference(StaticTypeCheckingVisitor.java:2453)
	at org.codehaus.groovy.transform.stc.StaticTypeCheckingVisitor.visitMethod(StaticTypeCheckingVisitor.java:2411)
	at org.codehaus.groovy.transform.sc.StaticCompilationVisitor.visitMethod(StaticCompilationVisitor.java:224)
	at org.codehaus.groovy.transform.sc.StaticCompileTransformation.visit(StaticCompileTransformation.java:78)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:145)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:189)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1084)
	... 32 more
```

*Workaround*: Add the [transitive dependencies of Grails rendering plugin](https://github.com/gpc/rendering/blob/master/build.gradle#L57-L58) directly: 

```
... 
dependencies {
  ...
  compile 'org.grails.plugins:rendering:2.0.3'
  compile("org.xhtmlrenderer:core-renderer:R8")
  compile("com.lowagie:itext:2.1.0")
}
```

Start the app and go to the home page 

`$ gradle bootRun`

Go to localhost:8080 and a blank PDF is downloaded. 

## Causes

I assume this is a Gradle 5 change. 

Found a couple of references to dependency related breaking changes:

[Separation of compile and runtime dependencies when consuming POMs](https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:pom_compile_runtime_separation)
[Gradle now honors implicit wildcards in Maven POM exclusions](https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel4.8:pom_wildcard_exclusions)

Attached sample app both Grails 3 and Grails 4. 

[issuerendering.zip](https://github.com/grails/grails-core/files/3279796/issuerendering.zip)

**Comment by graemerocher** [comment]
If it is the Gradle change there is nothing we can do about it. The plugin needs updating

**Comment by erichelgeson** [comment]
Even though there's nothing we can do about it this needs to be highlighted in a guide/blogpost/upgrade guide/etc/etc - as it's a confusing change.

**Comment by graemerocher** [comment]
The section on upgrading to Gradle 5 seems to be an appropriate location http://docs.grails.org/latest/guide/upgrading.html

**Comment by ZacharyKlein** [comment]
Documented in https://github.com/grails/grails-doc/commit/071ef0e4ad38e395c2c5333d536720a4ae347bac

**Comment by zyro23** [comment]
affected are plugin versions that are published with older versions of gradle/grails. those expose their transitive dependencies in the `pom` file with `<scope>runtime</scope>`. 

when an affected plugin is (re-)built/published with gradle-5/grails-4, it gets fixed, i.e. `<scope>compile</scope>` and resolution works again properly.

**Comment by GEARWELL** [comment]
I have the issue with spring security plugin 4.0.1
And solved by creating a new proyect and then adding dependecies

	runtime 'org.springframework:spring-test:4.2.1.RELEASE'
	runtime 'org.grails.plugins:rendering:2.0.3'
		compile 'org.grails.plugins:spring-security-core:4.0.3'

Hope this helps

**Comment by GEARWELL** [comment]
The best way to find libraries is to add to build.gradle

compile group: 'org.xhtmlrenderer', name: 'flying-saucer-core', version: '9.1.6' //class org.xhtmlrenderer.simple.Graphics2DRenderer
compile group: 'io.github.msalaslo', name: 'flying-saucer-pdf', version: '9.1.20' //class org/xhtmlrenderer/pdf/ITextRenderer

thanks to the web site
https://jar-download.com/artifacts/org.xhtmlrenderer/flying-saucer-core/9.1.8/source-code/org/xhtmlrenderer/simple/Graphics2DRenderer.java
