### ISSUE TITLE
4.0.0.RC2 - IllegalStateException on rendering some gsp's after devtools restart

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#11358]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run sample app
2. http://localhost:8080/dummy/create -> create one -> show view is rendered without errors
3. trigger a devtools restart (e.g. just appending a space somewhere in `DummyController` is enough)
4. http://localhost:8080/dummy/create - again create one -> error rendering the show view

note that:
* the order is important - if the affected gsp was not rendered before the restart, it works after the restart... caching?
* error does not happen for all views. maybe its related to using precompiled gsps (fields plugin in the sample app, used by scaffolding)

### Expected Behaviour

views should render properly after devtools restart as they do on fresh `bootRun`.

### Actual Behaviour

```
java.lang.IllegalStateException: The resources may not be accessed if they are not currently started
	at org.springframework.web.context.support.ServletContextResource.exists(ServletContextResource.java:103)
	at org.grails.gsp.io.DefaultGroovyPageLocator.findResource(DefaultGroovyPageLocator.java:398)
	at org.grails.gsp.io.DefaultGroovyPageLocator.findResourceScriptPathForSearchPaths(DefaultGroovyPageLocator.java:384)
	at org.grails.gsp.io.DefaultGroovyPageLocator.findResourceScriptSource(DefaultGroovyPageLocator.java:326)
	at org.grails.gsp.io.DefaultGroovyPageLocator.findPageInBinding(DefaultGroovyPageLocator.java:178)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator.access$001(CachingGrailsConventionGroovyPageLocator.java:38)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator$1.call(CachingGrailsConventionGroovyPageLocator.java:50)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator$1.call(CachingGrailsConventionGroovyPageLocator.java:48)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator.lookupCache(CachingGrailsConventionGroovyPageLocator.java:100)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator.findPageInBinding(CachingGrailsConventionGroovyPageLocator.java:58)
	at org.grails.gsp.io.DefaultGroovyPageLocator.findPageInBinding(DefaultGroovyPageLocator.java:132)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator.access$201(CachingGrailsConventionGroovyPageLocator.java:38)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator$2.call(CachingGrailsConventionGroovyPageLocator.java:67)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator$2.call(CachingGrailsConventionGroovyPageLocator.java:65)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator.lookupCache(CachingGrailsConventionGroovyPageLocator.java:100)
	at org.grails.web.gsp.io.CachingGrailsConventionGroovyPageLocator.findPageInBinding(CachingGrailsConventionGroovyPageLocator.java:75)
	at org.grails.web.gsp.io.GrailsConventionGroovyPageLocator.findTemplateInBinding(GrailsConventionGroovyPageLocator.java:274)
	at org.grails.web.gsp.GroovyPagesTemplateRenderer.findAndCacheTemplate(GroovyPagesTemplateRenderer.java:130)
	at org.grails.web.gsp.GroovyPagesTemplateRenderer.render(GroovyPagesTemplateRenderer.java:108)
	at org.grails.plugins.web.taglib.RenderTagLib$_closure7.doCall(RenderTagLib.groovy:367)
	at org.grails.taglib.TagOutput.captureTagOutput(TagOutput.java:78)
	at org.grails.taglib.TagLibraryMetaUtils$_registerMethodMissingForTags_closure1.doCall(TagLibraryMetaUtils.groovy:49)
	at grails.plugin.formfields.FormFieldsTagLib$_closure8.doCall(FormFieldsTagLib.groovy:332)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:446)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)
	at Byte_array_resource__view_____dummy_show_$_run_closure2.doCall(Byte_array_resource__view_____dummy_show_:59)
	at org.grails.taglib.TagBodyClosure.executeClosure(TagBodyClosure.java:200)
	at org.grails.taglib.TagBodyClosure.captureClosureOutput(TagBodyClosure.java:102)
	at org.grails.taglib.TagBodyClosure.call(TagBodyClosure.java:213)
	at org.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy:48)
	at org.grails.plugins.web.taglib.SitemeshTagLib$_closure3.doCall(SitemeshTagLib.groovy:156)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:446)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)
	at Byte_array_resource__view_____dummy_show_.run(Byte_array_resource__view_____dummy_show_:76)
	at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
	at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
	at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:76)
	at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
	at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	at org.grails.web.sitemesh.GrailsLayoutView.renderInnerView(GrailsLayoutView.java:150)
	at org.grails.web.sitemesh.GrailsLayoutView.obtainContent(GrailsLayoutView.java:128)
	at org.grails.web.sitemesh.GrailsLayoutView.renderTemplate(GrailsLayoutView.java:63)
	at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
	at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1370)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1116)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

### misc

spent a few hours trying to find the real cause but no luck :(

in the debugger, i can see that if the error occurs after a devtools restart, `org.grails.taglib.TagLibraryMetaUtils$_registerMethodMissingForTags_closure1` references the "old" `gspTagLibraryLookup` (the instance prior to the restart).

that again references the old `RenderTagLib` -> `GroovyPagesTemplateRenderer` -> `DefaultGroovyPageLocator` -> `ResourceLoader` -> `ServletContext` (`service.state` = `DESTROYED`).

but looking at the `TagLibraryMetaUtils` code, all metaclass modifications should happen on instance level and not survive a restart of the application context?

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 4.0.0.RC2
- **JDK Version:** oracle 8u121
- **Container Version (If Applicable):** n/a

### Example Application

sample app will be referenced asap

**Comment by zyro23** [comment]
think i found the cause: a missing `developmentMode` guard in `TagLibraryInvoker`.

will move this over to grails/grails-gsp and send a pr for review.
