### ISSUE TITLE
Auto reload throws an error after modifying a method of a service

### ISSUE THREAD

**Issue by mangelo123** [grails/grails-core#11418]
Modifying controllers seems to work fine. Once a service is modified, I get the following stacktrace:

File C:\Users\mangelo\IdeaProjects\sandbox4\grails-app\services\sandbox4\CustomerService.groovy changed, recompiling...
Exception in thread "Thread-26" BUG! exception in phase 'semantic analysis' in source unit 'C:\Users\mangelo\IdeaProjects\sandbox4\grails-app\services\sandbox4\CustomerService.groovy' unexpected NullpointerException
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1089)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:645)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:623)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:600)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at grails.boot.GrailsApp.compileGroovyFile(GrailsApp.groovy:383)
	at grails.boot.GrailsApp.recompile(GrailsApp.groovy:369)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:310)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at groovy.lang.Closure.run(Closure.java:486)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.grails.datastore.gorm.services.implementers.AbstractDetachedCriteriaServiceImplementor.doImplement(AbstractDetachedCriteriaServiceImplementor.groovy:79)
	at org.grails.datastore.gorm.services.implementers.AbstractReadOperationImplementer.implement(AbstractReadOperationImplementer.groovy:62)
	at org.grails.datastore.gorm.services.transform.ServiceTransformation.visitAfterTraitApplied(ServiceTransformation.groovy:278)
	at org.grails.datastore.gorm.transform.AbstractTraitApplyingGormASTTransformation.visit(AbstractTraitApplyingGormASTTransformation.groovy:52)
	at org.grails.datastore.gorm.transform.AbstractTraitApplyingGormASTTransformation.visit(AbstractTraitApplyingGormASTTransformation.groovy:42)
	at org.grails.datastore.gorm.transform.AbstractGormASTTransformation.visit(AbstractGormASTTransformation.groovy:59)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:145)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:189)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1084)
	... 29 more

1. Startup app
2. Go to localhost:8080/customer/1 - should work 
3. Modify controller method 'show':
   respond customerService.getOne()
4. Again go to localhost:8080/customer/1 - should work
5. Modify CustomerService.getOne() to get a different id (1-3) - this will cause the exception

This project can be found at: https://github.com/mangelo123/sandbox4.git

**Comment by jeffbrown** [comment]
FYI... I expect this is related to the class implementing an interface and I think the following probably would not show the same error:

```groovy
package sandbox4

import grails.gorm.services.Service

@Service(Customer)
abstract class CustomerService  {

    List<Customer> findAll() {
        println 'here again'
        return Customer.findAll()
    }

    Customer getOne() {
        return Customer.get(1)
    }
    abstract Customer get(Serializable id)

    abstract List<Customer> list(Map args)

    abstract Long count()

    abstract void delete(Serializable id)

    abstract Customer save(Customer customer)
}
```

Side notes:

There is no good reason to call `return Customer.findAll()` inside of a GORM Data Service class.  You would just add that as an abstract method.    Same with `Customer.get(1)`.
