### ISSUE TITLE
upgrade from grails 2.4.4 to 3.0.17

### ISSUE THREAD

**Issue by wimedko** [grails/grails-core#11455]
Hey Guys i am trying to upgrade my web app from grails 2.4.4 to 3.0. 17. after downloading dependencies and compiling i am having these errors. i followed the upgrade-guid but still having these problems

**i am using :

Gradle 2.3 groovy 2.4.5 JVM: 1.8.0_232**

General error during class generation:` java.lang.reflect.MalformedParameterizedTypeException`

```
java.lang.reflect.MalformedParameterizedTypeException
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
        at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
        at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:364)
        at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:265)
        at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:360)
        at org.codehaus.groovy.ast.ClassNode.declaresInterface(ClassNode.java:976)
        at org.codehaus.groovy.ast.ClassNode.implementsInterface(ClassNode.java:956)
        at org.codehaus.groovy.ast.ClassNode.isDerivedFromGroovyObject(ClassNode.java:946)
        at org.codehaus.groovy.classgen.AsmClassGenerator.isGroovyObject(AsmClassGenerator.java:1043)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitPropertyExpression(AsmClassGenerator.java:998)
        at org.codehaus.groovy.ast.expr.PropertyExpression.visit(PropertyExpression.java:57)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.makeCallSite(CallSiteWriter.java:303)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCachedCall(InvocationWriter.java:307)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:392)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:104)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeInvokeMethodCall(InvocationWriter.java:88)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:459)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:767)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:66)
        at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.evaluateEqual(BinaryExpressionHelper.java:316)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitDeclarationExpression(AsmClassGenerator.java:633)
        at org.codehaus.groovy.ast.expr.DeclarationExpression.visit(DeclarationExpression.java:89)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeExpressionStatement(StatementWriter.java:607)
        at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeExpressionStatement(OptimizingStatementWriter.java:357)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitExpressionStatement(AsmClassGenerator.java:620)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:84)
        at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeBlockStatement(OptimizingStatementWriter.java:158)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitBlockStatement(AsmClassGenerator.java:566)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:104)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:115)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitStdMethod(AsmClassGenerator.java:430)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructorOrMethod(AsmClassGenerator.java:387)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:126)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethod(AsmClassGenerator.java:507)
        at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1086)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:53)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:233)
        at org.codehaus.groovy.control.CompilationUnit$16.call(CompilationUnit.java:813)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1055)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:591)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:525)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:122)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:47)
        at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**and this is my buil.gradle**

```
runtime "mysql:mysql-connector-java:5.1.36"//checked
    runtime 'net.sourceforge.jtds:jtds:1.2.6'//ckecked
    runtime 'com.github.groovy-wslite:groovy-wslite:1.1.3'//checked
    runtime 'net.jodah:expiringmap:0.5.8' // Belongs to lab service //checked
    testRuntime 'net.sourceforge.htmlunit:htmlunit:2.35.0'
    testRuntime 'org.seleniumhq.selenium:selenium-htmlunit-driver:2.44.0'//checked
    testCompile "org.grails.plugins:geb"
    testRuntime 'net.sourceforge.htmlunit:htmlunit:2.35.0'
    testCompile "org.seleniumhq.selenium:htmlunit-driver:2.35.1"
    testCompile "org.seleniumhq.selenium:selenium-remote-driver:3.141.59"
    testCompile "org.seleniumhq.selenium:selenium-api:3.141.59"
    testCompile "org.seleniumhq.selenium:selenium-support:3.141.59"
    testRuntime "org.seleniumhq.selenium:selenium-chrome-driver:3.141.59"
    testRuntime "org.seleniumhq.selenium:selenium-firefox-driver:3.141.59"
    testCompile "org.spockframework:spock-grails-support:0.7-groovy-2.0"
    compile 'org.grails.plugins:geb:2.0.0.RC1'
    compile "org.gebish:geb-junit4:$gebVersion"
    testCompile( "com.github.detro.ghostdriver:phantomjsdriver:1.1.0" ) {
        transitive = false
    }
    runtime "org.springframework:spring-test:4.2.1.RELEASE"
    compile "org.apache.httpcomponents:httpcore:4.3.2"
    compile "org.apache.httpcomponents:httpclient:4.3.2"
    compile 'fr.exanpe.grails:exa-datatables:2.0.1'
    compile 'cglib:cglib:3.1'
    runtime "org.grails:grails-web-jsp:3.3.2"
    testCompile "org.grails:grails-datastore-test-support:1.0-grails-2.4"
    compile 'commons-io:commons-io:2.6'
    compile 'org.grails.plugins:scaffolding:4.0.0.RC1'
    compile "org.grails.plugins:hibernate5:6.1.12"
    compile "org.hibernate:hibernate-core:5.1.5.Final"
    compile "org.hibernate:hibernate-ehcache"
    compile 'org.grails.plugins:ajaxdependancyselection:1.3'
    compile 'fr.exanpe.grails:exa-datatables:2.0.1'
    compile 'com.bertramlabs.plugins:coffee-asset-pipeline:3.0.11'
    compile 'org.grails.plugins:spring-security-jaxrs:3.0.1'
    compile "org.grails.plugins:quartz:2.0.0"
    provided "org.springframework.boot:spring-boot-starter-tomcat"
    compile 'org.grails.plugins:build-test-data:3.3.1'
    compile 'org.grails.plugins:joda-time:2.1.0'
    compile 'org.grails.plugins:greenmail:2.0.0.RC2'    compile 'org.grails.plugins:spring-security-core:3.1.2'
    compile "org.grails.plugins:spring-security-ui:3.0.2"
    compile group: 'org.codehaus.groovy.modules.http-builder', name: 'http-builder', version: '0.7.1'
    compile 'com.github.groovy-wslite:groovy-wslite:1.1.3'
    compile 'org.grails.plugins:mail:3.0.0'
    compile 'org.grails.plugins:http-builder-helper:1.1.0'
    compile group: 'org.ghost4j', name: 'ghost4j', version: '1.0.0'
    compile group: 'org.grails', name: 'grails-datastore-gorm-async', version: '6.1.0.RC2'
```

**Comment by puneetbehl** [comment]
@wimedko please share a sample application replicating the problem. I tried with the above dependencies but could not replicate it. Also, I would suggest trying to update to latest Grails 3 version.

**Comment by puneetbehl** [comment]
Closed due to a lack of feedback.
