### ISSUE TITLE
DomainClassMarshaller and domain classes with composite key

### ISSUE THREAD

**Issue by dflynn100** [grails/grails-core#11450]
The DomainClassMarshaller in Grails 4.0.1 no longer seems to support rendering JSON from domain objects that map the id attribute to a composite key.  Our current thought is that at some point, the DomainClassMarshaller was updated to reference the id attribute of the domain class.  Since the id of a composite key is remapped, the DomainClassMarshaller throws a null pointer exception when referencing it.

Note that we are upgrading from 2.5.4, so we don't know when this issue was introduced.

Errors are thrown whether using code such as:
```groovy
static responseFormats = ['json', 'html']
...
respond myDomainClassWithCompositeKey
```

or when using a JSON View such as:
```groovy
model {
    MyDomainClassWithCompositeKey dc
}
json g.render([mydata:dc])
```

Beginning of stack trace:
```
java.lang.NullPointerException: null
        at org.grails.web.converters.marshaller.json.DomainClassMarshaller.extractValue(DomainClassMarshaller.java:283)
        at org.grails.web.converters.marshaller.json.DomainClassMarshaller.asShortObject(DomainClassMarshaller.java:264)
        at org.grails.web.converters.marshaller.json.DomainClassMarshaller.marshalObject(DomainClassMarshaller.java:220)
        at org.grails.web.converters.marshaller.json.DomainClassMarshaller.marshalObject(DomainClassMarshaller.java:59)
        at grails.converters.JSON.value(JSON.java:184)
        at grails.converters.JSON.convertAnother(JSON.java:144)
        at org.grails.web.converters.marshaller.json.MapMarshaller.marshalObject(MapMarshaller.java:45)
        at org.grails.web.converters.marshaller.json.MapMarshaller.marshalObject(MapMarshaller.java:30)
        at grails.converters.JSON.value(JSON.java:184)
        at grails.converters.JSON.convertAnother(JSON.java:144)
        at org.grails.web.converters.marshaller.json.CollectionMarshaller.marshalObject(CollectionMarshaller.java:41)
        at org.grails.web.converters.marshaller.json.CollectionMarshaller.marshalObject(CollectionMarshaller.java:30)
        at grails.converters.JSON.value(JSON.java:184)
        at grails.converters.JSON.render(JSON.java:119)
        at org.grails.web.converters.AbstractConverter.writeTo(AbstractConverter.java:110)
```

Environment:  local environment running Docker with latest Ubuntu image, Java 8

**Comment by jchharris** [comment]
We have the same issue with rendering the UserRole class from the the SpringSecurityCore plugin.

It works fine in Grails 3.3.11 but is broken in 4.0.1
` List<UserRole> roles = UserRole.list()

        roles.each { role ->
            println (role as JSON).toString()
        }`

`      java.lang.NullPointerException
            at org.grails.web.converters.marshaller.json.DomainClassMarshaller.marshalObject(DomainClassMarshaller.java:141)
            at org.grails.web.converters.marshaller.json.DomainClassMarshaller.marshalObject(DomainClassMarshaller.java:59)
            at grails.converters.JSON.value(JSON.java:184)
            at grails.converters.JSON.render(JSON.java:119)
            at org.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:118)`
