### ISSUE TITLE
Grails 4.0.2 test execution fails when defining GORM settings in application.groovy

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#11491]
After upgrading from Grails 4.0.1 to 4.0.2 I ran into the following issue when executing my unit test with `./gradlew test`.

```java
io.micronaut.context.exceptions.ConfigurationException: Exception occurred reading configuration [application]: startup failed:
Script1.groovy: 2: [Static type checking] - Cannot find matching method Script1#cache(boolean). Please check if the declared type is correct and if the method exists.
 @ line 2, column 5.
       cache true
       ^

Script1.groovy: 3: [Static type checking] - Cannot find matching method Script1#id(java.util.LinkedHashMap <java.lang.String, java.lang.String>). Please check if the declared type is correct and if the method exists.
 @ line 3, column 5.
       id generator : 'uuid2'
       ^

2 errors

	at io.micronaut.context.env.groovy.GroovyPropertySourceLoader.processInput(GroovyPropertySourceLoader.java:53)
	at io.micronaut.context.env.AbstractPropertySourceLoader.read(AbstractPropertySourceLoader.java:112)
	at io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(AbstractPropertySourceLoader.java:97)
	at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:73)
	at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:59)
	at io.micronaut.context.env.PropertySourceLoader.load(PropertySourceLoader.java:51)
	at io.micronaut.context.env.DefaultEnvironment.loadPropertySourceFromLoader(DefaultEnvironment.java:608)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(DefaultEnvironment.java:541)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:675)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:463)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:324)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:647)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:617)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:228)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
	at org.grails.testing.GrailsApplicationBuilder.createMainContext(GrailsApplicationBuilder.groovy:142)
	at org.grails.testing.GrailsApplicationBuilder.build(GrailsApplicationBuilder.groovy:58)
	at org.grails.testing.GrailsUnitTest$Trait$Helper.getGrailsApplication(GrailsUnitTest.groovy:68)
	at org.grails.testing.GrailsUnitTest$Trait$Helper.defineBeans(GrailsUnitTest.groovy:94)
	at org.grails.testing.gorm.spock.DataTestSetupSpecInterceptor.setupDataTestBeans(DataTestSetupSpecInterceptor.groovy:38)
	at org.grails.testing.gorm.spock.DataTestSetupSpecInterceptor.configureDataTest(DataTestSetupSpecInterceptor.groovy:66)
	at org.grails.testing.gorm.spock.DataTestSetupSpecInterceptor.intercept(DataTestSetupSpecInterceptor.groovy:31)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 2: [Static type checking] - Cannot find matching method Script1#cache(boolean). Please check if the declared type is correct and if the method exists.
 @ line 2, column 5.
       cache true
       ^

Script1.groovy: 3: [Static type checking] - Cannot find matching method Script1#id(java.util.LinkedHashMap <java.lang.String, java.lang.String>). Please check if the declared type is correct and if the method exists.
 @ line 3, column 5.
       id generator : 'uuid2'
       ^

2 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1102)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:645)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:623)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:600)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:540)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:552)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:532)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:597)
	at io.micronaut.context.env.groovy.ConfigurationEvaluator.evaluate(ConfigurationEvaluator.groovy:80)
	at io.micronaut.context.env.groovy.ConfigurationEvaluator.evaluate(ConfigurationEvaluator.groovy:53)
	at io.micronaut.context.env.groovy.GroovyPropertySourceLoader.processInput(GroovyPropertySourceLoader.java:48)
	... 43 more

```

I created a small Grails 4.0.2 app that demonstrates the issue when running `./gradlew test`. 
The demo app contains the default `application.yml` and an additional `application.groovy` in order to set global GROM id generator setting.

```groovy
grails.gorm.default.mapping = {
    cache true
    id generator : 'uuid2'
}
```
Please find the demo app at https://github.com/saw303/grails-4.0.2-test-bug

Beside of that I was wondering if it is possible to convert that `application.groovy` to YAML but I struggle with the conversion of `id generator : 'uuid2'` to YAML? 

```yml
grails:
   gorm:
      default:
          mapping:
              cache: true
              id: # how to continue here?
```

**Comment by puneetbehl** [comment]
@saw303 It seems to be working fine, please see the sample application https://github.com/puneetbehl/grailsDslConfigraution

**Comment by puneetbehl** [comment]
Also, please verify that the version of micronaut-runtime-groovy dependency is 1.1.2 by running the command:
```
./gradlew -q dependencyInsight --configuration compile --dependency micronaut-runtime-groovy
```

**Comment by deroffal** [comment]
Hi,

I have the same issue creating an application with Grails 4.0.2 : 
https://github.com/deroffal/grails_4.0.2_bug

I run a `grails create-app demo` and I just add an [aplication.groovy](https://github.com/deroffal/grails_4.0.2_bug/blob/master/grails-app/conf/application.groovy) configuration.

I run `grails run-app` and :

```
io.micronaut.context.exceptions.ConfigurationException: Exception occurred reading configuration [application]: No such property: key for class: Script1
	at io.micronaut.context.env.groovy.GroovyPropertySourceLoader.processInput(GroovyPropertySourceLoader.java:53)
	at io.micronaut.context.env.AbstractPropertySourceLoader.read(AbstractPropertySourceLoader.java:112)
	at io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(AbstractPropertySourceLoader.java:97)
	at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:73)
	at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:59)
	at io.micronaut.context.env.PropertySourceLoader.load(PropertySourceLoader.java:51)
	at io.micronaut.context.env.DefaultEnvironment.loadPropertySourceFromLoader(DefaultEnvironment.java:608)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(DefaultEnvironment.java:541)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:675)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:463)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:324)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:647)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:617)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:228)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
	at grails.boot.GrailsApp.createApplicationContext(GrailsApp.groovy:156)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:97)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:458)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:445)
	at demo.Application.main(Application.groovy:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: groovy.lang.MissingPropertyException: No such property: key for class: Script1
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at Script1$_run_closure1.doCall(Script1.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:369)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:316)
	at org.codehaus.groovy.runtime.dgm$827.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:223)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at Script1.run(Script1.groovy:4)
	at io.micronaut.context.env.groovy.ConfigurationEvaluator.evaluate(ConfigurationEvaluator.groovy:81)
	at io.micronaut.context.env.groovy.ConfigurationEvaluator.evaluate(ConfigurationEvaluator.groovy:53)
	at io.micronaut.context.env.groovy.GroovyPropertySourceLoader.processInput(GroovyPropertySourceLoader.java:48)
	... 25 common frames omitted
```

**Comment by puneetbehl** [comment]
@deroffal Did you check the sample application shared in my previous comment?

**Comment by deroffal** [comment]
`$ ./gradlew -q dependencyInsight --configuration compile --dependency micronaut-runtime-groovy`
```
io.micronaut:micronaut-runtime-groovy:1.1.2 (selected by rule)
   variant "runtime" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-runtime (not requested)
      org.gradle.component.category = library (not requested)
   ]

io.micronaut:micronaut-runtime-groovy:1.1.2
\--- org.grails:grails-plugin-databinding:4.0.2
     \--- compile (requested org.grails:grails-plugin-databinding)

A web-based, searchable dependency report is available by adding the --scan option.
```

And I used the grails 4.0.2 cli to create the application so I have the default configuration.

**Comment by puneetbehl** [comment]
It looks like this issue is unrelated to the one shared by @saw303

**Comment by deroffal** [comment]
OK I will create a new issue.

**Comment by puneetbehl** [comment]
@deroffal As a workaround, you could change the `collect` as:
```
collect([] as List) { entry ->
        $/"${entry.key}": "${entry.value}"/$
    }.join(', ')
```

**Comment by saw303** [comment]
@puneetbehl here is what I get when I run the dependencyInsight task 

```bash
➜  grails-4.0.2-test-bug git:(master) ./gradlew -q dependencyInsight --configuration compile --dependency micronaut-runtime-groovy
io.micronaut:micronaut-runtime-groovy:1.1.2 (selected by rule)
   variant "runtime" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-runtime (not requested)
      org.gradle.component.category = library (not requested)
   ]

io.micronaut:micronaut-runtime-groovy:1.1.2
\--- org.grails:grails-plugin-databinding:4.0.2
     \--- compile (requested org.grails:grails-plugin-databinding)

```

So 1.1.2 is selected. Looks good so far.

Have you tried to run my example Grails 4.0.2 project at https://github.com/saw303/grails-4.0.2-test-bug ? Does `./gradlew test` work for you?

The difference between your project and mine is that mine **contains a unit test** that uses GORM (see https://github.com/saw303/grails-4.0.2-test-bug/blob/master/src/test/groovy/ch/silviowangler/grails/PersonServiceSpec.groovy). And I think this might be causing the problem in Grails 4.0.2.

**Comment by puneetbehl** [comment]
@saw303 ok, I think the problem is with `GrailsUnitTest`. As a workaround,  please set the following System property in the test Gradle Task:
```
tasks.withType(Test) {
    ...
    systemProperty "micronaut.groovy.config.compileStatic", "false"
}
```
