### ISSUE TITLE
4.0.3.BUILD-SNAPSHOT Micronaut configuration not mapped from camel case to kebab case

### ISSUE THREAD

**Issue by jjelliott** [grails/grails-core#11507]
In 4.0.3, config keys in application.groovy are not converted from camel case to kebab case, causing resolution to fail.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define an http service in application.groovy:
```groovy
micronaut {
    http {
        services{
            blogService{
                url = "http://localhost:8081"
                path = "/blog"
            }
        }
    }
}
```
2. Declare a client using the service
```groovy
@Client("blogService") // or @Client("blog-service")
interface BlogClient {

    @Get
    List<BlogPost> list();
}
```
3. Attempt to call list on BlogClient

### Expected Behaviour

`blogService` should map to `blog-service` and BlogClient should be initialized

### Actual Behaviour

Micronaut is unable to resolve the kebab case version of the service name

Stacktrace
```
2020-03-22 12:07:38.663 ERROR --- [nio-8080-exec-8] o.g.web.errors.GrailsExceptionResolver   : NoAvailableServiceException occurred when processing request: [GET] /test/index
No available services for ID: blog-service. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.micronaut.discovery.exceptions.NoAvailableServiceException: No available services for ID: blog-service
	at io.micronaut.http.client.loadbalance.AbstractRoundRobinLoadBalancer.getNextAvailable(AbstractRoundRobinLoadBalancer.java:50)
	at io.micronaut.core.async.publisher.Publishers$1.doOnNext(Publishers.java:142)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:52)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredSetOnce(SubscriptionHelper.java:202)
	at io.reactivex.internal.subscribers.StrictSubscriber.onSubscribe(StrictSubscriber.java:87)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14885)
	at io.micronaut.core.async.publisher.Publishers.lambda$map$2(Publishers.java:133)
	at io.micronaut.core.async.publisher.Publishers.lambda$map$2(Publishers.java:133)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.blockingFirst(Flowable.java:5698)
	at io.micronaut.http.client.DefaultHttpClient$3.exchange(DefaultHttpClient.java:528)
	at io.micronaut.http.client.BlockingHttpClient.retrieve(BlockingHttpClient.java:136)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.lambda$intercept$14(HttpClientIntroductionAdvice.java:566)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.handleBlockingCall(HttpClientIntroductionAdvice.java:580)
	at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.intercept(HttpClientIntroductionAdvice.java:565)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:73)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at service.test.TestController.index(TestController.groovy:11)
	... 13 common frames omitted
```

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 4.0.3.BUILD-SNAPSHOT
- **JDK Version:** 8

### Example Application

[jjelliott/grails-micronaut-config-issue](https://github.com/jjelliott/grails-micronaut-config-issue)

### Workaround

Map services as strings:
```groovy
micronaut {
    http {
        services{
            "blog-service"{
                url = "http://localhost:8081"
                path = "/blog"
            }
        }
    }
}
```

**Comment by puneetbehl** [comment]
It looks like the problem is with [MicronautGroovyPropertySourceLoader.groovy](https://github.com/grails/grails-core/blob/4.0.x/grails-core/src/main/groovy/org/grails/core/cfg/MicronautGroovyPropertySourceLoader.groovy#L44-L46) in the following lines:
```
def configObject = configSlurper.parse(input.getText("UTF-8"))
def propertySource = new NavigableMap()
propertySource.merge(configObject, false)
finalMap.putAll(propertySource)
```

If we replace the above as:
```
finalMap.putAll(configObject.flatten())
``` 
Then, I think it would solve this problem. However, I am not sure about the impact of this change as we were using `NavigableMap` in Grails 3.3.x while reading configuration from `application.groovy`.
