### ISSUE TITLE
Attempting to call .toFlatConfig() on a config key that doesn't exist fails

### ISSUE THREAD

**Issue by sjrd218** [grails/grails-core#11514]
### Description
Attempting to call .toFlatConfig() on a config key that doesn't exist fails.

### Steps to Reproduce

Attempt to use `.toFlatConfig()` on a config key that does not exist.
e.g. `grailsApplication.config.thiskeydoesnotexist.toFlatConfig()`

### Expected Behaviour

I expect the NullSafeNavigator that is returned by the grails Config class to have a .toFlatConfig() that does the right thing.

I'm not sure if it should return an empty map or a null. Either would be fine.

### Actual Behaviour

NullSafeNavigator doesn't have a .toFlatConfig() method.

```
groovy.lang.MissingMethodException: No signature of method: static org.grails.config.NavigableMap.toFlatConfig() is applicable for argument types: () values: []
Possible solutions: toFlatConfig()
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1525)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1511)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:985)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
        at org.grails.config.NavigableMap$NullSafeNavigator.methodMissing(NavigableMap.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:82)
        at configbug.BootStrap$_closure1.doCall(BootStrap.groovy:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1099)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:594)
        at grails.util.Environment.executeForEnvironment(Environment.java:587)
        at grails.util.Environment.executeForCurrentEnvironment(Environment.java:563)
        at org.grails.web.servlet.boostrap.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:74)
        at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:83)
        at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:56)
        at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:269)
        at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:96)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:456)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:443)
        at configbug.Application.main(Application.groovy:11)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

### Workaround

Use Groovy meta-programming to insert a `toFlatConfig()` method onto the NullSafeNavigator.

```
def toFlatConfig = {
    if(delegate.isEmpty()) return [:]
    else return delegate.parent.toFlatConfig()
}
toFlatConfig.resolveStrategy = Closure.DELEGATE_FIRST
NavigableMap.NullSafeNavigator.metaClass.toFlatConfig = toFlatConfig
```

### Environment Information

- **Operating System**: any
- **Grails Version:** 4.0.3 all the way back to 3.3.x
- **JDK Version:** any

### Example Application

https://github.com/sjrd218/ConfigBug

**Comment by niravassar** [comment]
in speaking with @sjrd218 in grails 3.3.x a null value would return NullSafeNavigator  and NavigableMap, now in grails 4.0.3, the configuration is read and just returns a "" if null. Therefore `toFlatConfig()` results a MissingMethodException.

**Comment by puneetbehl** [comment]
@sjrd218 A `NullSafeNavigator` is not `NavigableMap` it only implements `Map<String, Object>` so it would not have methods from `NavigableMap`. Also, I am not sure if flattening a parent would make sense.

**Comment by sjrd218** [comment]
Since the `NullSafeNavigator` is a nested class of `NavigableMap` and seems to be the substitution when the config cannot be found, it seems reasonable for a dev to assume the `NullSafeNavigator` would have the same methods as `NavigableMap`. 

We have a use case where a set of config properties can be supplied by a user in a .properties file. We want to ref the parent key and call toFlatConfig() to get all the subproperties in a flat map that we pass to our code.

**Comment by gschueler** [comment]
i'm not sure this is a bug in NullSafeNavigator, this may be due to a behavior change in the conversion of yaml file to config object.  E.g. i ran into this same error with another grails plugin converted from grails 3 to 4.  This was the (paraphrased) affected code:

```groovy
Map conf = config.a?.b?.c?.toFlatConfig()
```
This was the `plugin.yml` from the plugin:

```yaml
a:
    b:
        c:
```

In grails 4, this causes an error, because it seems the `c:` is essentially `c: ""`  (i.e. a blank string) and so `.toFlatConfig()` is an error. But in grails3 the value of `c` was treated as missing or null (perhaps it was just checking the "groovy truth" of the value), allowing the NavigableMap to return the NullSafeNavigator.

Being explicit about the map content for the yaml value fixed it for me:


```yaml
a:
    b:
        c: {}
```

**Comment by sjrd218** [comment]
If the leaf of a property graph return `null` for an unset property the issue would be avoided entirely. 

A call to `config.a?.b?.c?.toFlatConfig()` would then return a predictable value without having to change the `NullSafeNavigator`. 

The Grails 4 behavior of return a blank string for a non-defined value seems suboptimal.

**Comment by niravassar** [comment]
We filed this ticket which i think demos the issue
https://github.com/grails/grails-core/issues/11524
