### ISSUE TITLE
grails `run app` crashes due to unverifiable bytecode

### ISSUE THREAD

**Issue by DanHeidinga** [grails/grails-core#11528]
### Steps to Reproduce

See https://github.com/AdoptOpenJDK/openjdk-support/issues/92

### Expected Behaviour

Grails should run without specifying `-Xverify:none`.

See https://github.com/grails/grails-core/blob/6658f864c0a6287d0ed5f60b5ac67c370c45fdcb/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsExtension.groovy#L79 for where it adds it by default.

### Actual Behaviour

Segfault as shown in https://github.com/AdoptOpenJDK/openjdk-support/issues/92

Removing the `-Xverify:none` results in the following `java.lang.VerifyError`:
```
:bootRunError: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=grails/boot/config/GrailsAutoConfiguration, method=<clinit>()V, pc=0
Exception Details:
  Location:
    grails/boot/config/GrailsAutoConfiguration.<clinit>()V @0: JBldc
  Reason:
    A stackmap frame is expected at branch target 65.
  Exception Handler Table:
    bci [0, 65] => handler: 65
    bci [0, 65] => handler: 74
    bci [65, 67] => handler: 74
        at java.lang.J9VMInternals.prepareClassImpl(Native Method)
        at java.lang.J9VMInternals.prepare(J9VMInternals.java:304)
        at java.lang.Class.getMethodHelper(Class.java:1247)
        at java.lang.Class.getMethod(Class.java:1191)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
 FAILED
```
### Environment Information

- **Operating System**: Linux/x64
- **Grails Version:** grails-3.3.6
- **JDK Version:**
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200416_608 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - cfa47e66cd5 based on jdk8u252-b09)
```
- **Container Version (If Applicable):** NA

**Comment by jdaugherty** [comment]
Later versions of grails use the Gradle bootRun task and do not have verify specified as a default argument.  Closing this ...
