### ISSUE TITLE
Custom URL protocol handlers work in dev mode but not compiled war

### ISSUE THREAD

**Issue by sjrd218** [grails/grails-core#11545]
I want to use a custom protocol handler in a pre Java 9 app. I register a custom protocol handler and it works in dev mode. I compile the app to a war and my custom protocol cannot be found by java.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a custom protocol handler by putting a `Handler.java` class in a package named: `sun.net.www.protocol.greatness`
2. In BootStrap.groovy open a URL connection using the `greatness` protocol.
`new URL("greatness://acheive").openConnection()`
3. Fire up dev mode and see that it works fine
4. Compile Grails App to war
5. Try to launch the war. See the failure

### Expected Behaviour

I should be able to use my custom protocol handler in prod mode

### Actual Behaviour

Stacktrace telling me my custom protocol is not found.

```
java.net.MalformedURLException: unknown protocol: greatness
	at java.net.URL.<init>(URL.java:607)
	at java.net.URL.<init>(URL.java:497)
	at java.net.URL.<init>(URL.java:446)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at protocolhandlerbug.BootStrap$_closure1.doCall(BootStrap.groovy:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1099)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:594)
	at grails.util.Environment.executeForEnvironment(Environment.java:587)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:563)
	at org.grails.web.servlet.boostrap.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:74)
	at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:83)
	at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:56)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:269)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:96)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:456)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:443)
	at protocolhandlerbug.Application.main(Application.groovy:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
```

### Environment Information

- **Operating System**: MacOS Catalina
- **Grails Version:** 4.0.3 back to 3.3.x
- **JDK Version:** jdk 1.8.0_222

### Example Application

https://github.com/sjrd218/ProtocolHandlerBug

**Comment by niravassar** [comment]
The issue seems to be with how the Custom `Handler` class is loaded into the `URL.java` instance. In the `BootStrap`, no Handler is passed in so a `ClassLoader` loads classes by a protocol name and eventually classname. See `URL.getURLStreamHandler`. In the bootRun scenario all the application classes are loaded so the connection is handled.  In the `gradlew assemble`, then `java -jar` execution scenario, the `ClassLoader` does not load the application classes and `Handler` is not created.  The ClassLoaders are controlled by spring boot. On debugging, it seems to load classes such `org.springframework.boot.loader.Launcher`, `WarLauncher` etc. The root of this issue seems to be how Spring Boot uses class loaders with different environments, and I think would be outside of grails. 

A workaround I used was simply use this in the `Bootstrap.groovy`, which will explicitly pass the handler in and no longer rely on the ClassLoader. 
```
URL u = new URL(null, "greatness://a/great/resource", new Handler())
```

**Comment by niravassar** [comment]
@puneetbehl please let me know if this requires further research, thanks

**Comment by bobbywarner** [comment]
As mentioned in the comment above, this is something that would have to be addressed within Spring Boot as opposed to Grails.  There is nothing to fix in `grails-core` for the issue.  So closing and we can discuss further if required.
