### ISSUE TITLE
Grails 4.1.0.M1 fails to run-app with Java 8

### ISSUE THREAD

**Issue by puneetbehl** [grails/grails-core#11557]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new Grails 4.1.0.M1 application.
2. Execute `./gradlew run-app`

### Expected Behaviour

The application should run fine.

### Actual Behaviour

The following exception is thrown:
```

| Running application...
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalAccessError: tried to access method grails.boot.GrailsApp.configureDirectoryWatcher(Lorg/grails/io/watch/DirectoryWatcher;Ljava/lang/String;)V from class grails.boot.GrailsApp$configureDirectoryWatcher$0
        at grails.boot.GrailsApp$configureDirectoryWatcher$0.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
        at grails.boot.GrailsApp.enableDevelopmentModeWatch(GrailsApp.groovy:236)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:106)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:456)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:443)
        at example.Application.main(Application.groovy:11)
        ... 5 more
<==========---> 83% EXECUTING [1m 5s]
```

### Environment Information

- **Operating System**: macOS 10.15.4
- **Grails Version:** 4.1.0.M1
- **JDK Version:** 1.8.252.hs-adpt

**Comment by puneetbehl** [comment]
It seems to be a Groovy bug with `for` loop where it is creating a class `grails.boot.GrailsApp$configureDirectoryWatcher$0` for the following code:

_GrailsApp.groovy_
```
List<File> watchBaseDirectories
for(File dir in watchBaseDirectories) {
                configureDirectoryWatcher(directoryWatcher, dir.absolutePath)
            }
```
See [GrailsApp.groovy](https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/grails/boot/GrailsApp.groovy#L235) for complete code.

It would work fine, if I use `each` instead of `for` as:
```
for(File dir in watchBaseDirectories) {
                configureDirectoryWatcher(directoryWatcher, dir.absolutePath)
            }
```

**Comment by paulk-asert** [comment]
I'll take a look.

**Comment by paulk-asert** [comment]
Looks like this is related:
https://github.com/grails/grails-core/pull/11525

**Comment by puneetbehl** [comment]
I believe #11525 is not the solution to this problem. As it would happen at other places too. Here is another place where it happens in asset-pipeline:

```
java.lang.IllegalAccessError: tried to access method asset.pipeline.fs.AbstractAssetResolver.resolveAsset(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Lasset/pipeline/AssetFile;Ljava/lang/String;)Lasset/pipeline/AssetFile; from class asset.pipeline.fs.AbstractAssetResolver$resolveAsset
	at asset.pipeline.fs.FileSystemAssetResolver.getAsset(FileSystemAssetResolver.groovy:79)
	at asset.pipeline.fs.FileSystemAssetResolver.getAsset(FileSystemAssetResolver.groovy:85)
	at asset.pipeline.AssetHelper.fileForUri(AssetHelper.groovy:51)
	at asset.pipeline.AssetPipeline.getDependencyList(AssetPipeline.groovy:80)
	at asset.pipeline.grails.AssetsTagLib.element(AssetsTagLib.groovy:103)
	at asset.pipeline.grails.AssetsTagLib$_closure2.doCall(AssetsTagLib.groovy:48)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:439)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)
	at private_tmp_helloworld_grails_app_views_layouts_main_gsp$_run_closure1.doCall(private_tmp_helloworld_grails_app_views_layouts_main_gsp:36)
	at org.grails.taglib.TagBodyClosure.executeClosure(TagBodyClosure.java:200)
	at org.grails.taglib.TagBodyClosure.captureClosureOutput(TagBodyClosure.java:102)
	at org.grails.taglib.TagBodyClosure.call(TagBodyClosure.java:213)
	at org.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy:48)
	at org.grails.plugins.web.taglib.SitemeshTagLib$_closure1.doCall(SitemeshTagLib.groovy:124)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:446)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)
	at private_tmp_helloworld_grails_app_views_layouts_main_gsp.run(private_tmp_helloworld_grails_app_views_layouts_main_gsp:41)
	at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
	at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
	at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:76)
	at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
	at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	at org.grails.web.sitemesh.SpringMVCViewDecorator.render(SpringMVCViewDecorator.java:69)
	at org.grails.web.sitemesh.GrailsLayoutView.renderTemplate(GrailsLayoutView.java:83)
	at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
	at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1373)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-05-22 17:00:28.402 ERROR --- [nio-8080-exec-1] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] threw exception
```

**Comment by wureka** [comment]
so, can I Java12 ?

**Comment by erichelgeson** [comment]
Java 12 was EoL Sept 2019 - Try Java 11 as it's the current long term support version.

**Comment by rkimaoui** [comment]
> ### Task List
> * [x]  Steps to reproduce provided
> * [x]  Stacktrace (if present) provided
> * [ ]  Example that reproduces the problem uploaded to Github
> * [x]  Full description of the issue provided (see below)
> 
> ### Steps to Reproduce
> 1. Create a new Grails 4.1.0.M1 application.
> 2. Execute `./gradlew run-app`
> 
> ### Expected Behaviour
> The application should run fine.
> 
> ### Actual Behaviour
> The following exception is thrown:
> 
> ```
> 
> | Running application...
> Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
> Caused by: java.lang.IllegalAccessError: tried to access method grails.boot.GrailsApp.configureDirectoryWatcher(Lorg/grails/io/watch/DirectoryWatcher;Ljava/lang/String;)V from class grails.boot.GrailsApp$configureDirectoryWatcher$0
>         at grails.boot.GrailsApp$configureDirectoryWatcher$0.callCurrent(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
>         at grails.boot.GrailsApp.enableDevelopmentModeWatch(GrailsApp.groovy:236)
>         at grails.boot.GrailsApp.run(GrailsApp.groovy:106)
>         at grails.boot.GrailsApp.run(GrailsApp.groovy:456)
>         at grails.boot.GrailsApp.run(GrailsApp.groovy:443)
>         at example.Application.main(Application.groovy:11)
>         ... 5 more
> <==========---> 83% EXECUTING [1m 5s]
> ```
> 
> ### Environment Information
> * **Operating System**: macOS 10.15.4
> * **Grails Version:** 4.1.0.M1
> * **JDK Version:** 1.8.252.hs-adpt

I have the same error when creating a new fresh app with java 8, Java 11, Java 12.
Did you find a fix ?

**Comment by davydotcom** [comment]
@paulk-asert should we submit a JIRA For this issue? Trying to reproduce with a TestClass.groovy with little luck.

**Comment by puneetbehl** [comment]
I have created the following issue in Groovy JIRA:
https://issues.apache.org/jira/browse/GROOVY-9613

**Comment by paulk-asert** [comment]
Can you try with the latest 3.0.5-SNAPSHOT snapshot?

**Comment by bobbywarner** [comment]
@paulk-asert I tried `3.0.5-SNAPSHOT` on Grails `master` and it does not compile.  The following exception is thrown:

```
Execution failed for task ':grails-web-databinding:compileGroovy'.
> BUG! exception in phase 'class generation' in source unit '/Users/bobby/workspace/grails/grails-core/grails-web-databinding/src/main/groovy/grails/web/databinding/GrailsWebDataBinder.groovy' At line 541 column 33
  On receiver: obj with message: getAt and arguments: propName
  This method should not have been called. Please try to create a simple example reproducing
  this error and file a bug report at https://issues.apache.org/jira/browse/GROOVY

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':grails-web-databinding:compileGroovy'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: BUG! exception in phase 'class generation' in source unit '/Users/bobby/workspace/grails/grails-core/grails-web-databinding/src/main/groovy/grails/web/databinding/GrailsWebDataBinder.groovy' At line 541 column 33
On receiver: obj with message: getAt and arguments: propName
This method should not have been called. Please try to create a simple example reproducing
this error and file a bug report at https://issues.apache.org/jira/browse/GROOVY
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:277)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:67)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:98)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:77)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

**Comment by bobbywarner** [comment]
@paulk-asert Grails `master` now builds with Groovy `3.0.5-SNAPSHOT`, but the `java.lang.IllegalAccessError` still happens when trying to run an app with JDK 8.

**Comment by puneetbehl** [comment]
It is working now! I tested this locally with REST API and Web Profile with Java 8 and Java 11.

**Comment by puneetbehl** [comment]
I will do a few more tests before closing this issue.

**Comment by sagrawal31** [comment]
Thanks for constant effort @puneetbehl
