### ISSUE TITLE
One of the root or intermediate certificates of https://repo.grails.org has expired

### ISSUE THREAD

**Issue by denychen** [grails/grails-core#11561]
Our builds are failing with

```
01-Jun-2020 09:22:33	> Could not resolve all dependencies for configuration ':classpath'.
01-Jun-2020 09:22:33	   > Could not resolve org.grails.plugins:database-migration:2.0.1.
01-Jun-2020 09:22:33	     Required by:
01-Jun-2020 09:22:33	         project :
01-Jun-2020 09:22:33	      > Could not resolve org.grails.plugins:database-migration:2.0.1.
01-Jun-2020 09:22:33	         > Could not get resource 'https://repo.grails.org/grails/core/org/grails/plugins/database-migration/2.0.1/database-migration-2.0.1.pom'.
01-Jun-2020 09:22:33	            > Could not GET 'https://repo.grails.org/grails/core/org/grails/plugins/database-migration/2.0.1/database-migration-2.0.1.pom'.
01-Jun-2020 09:22:33	               > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
```

See https://www.sslshopper.com/ssl-checker.html#hostname=https://repo.grails.org.
```
Common name: COMODO RSA Certification Authority
Organization: COMODO CA Limited
Location: Salford, Greater Manchester, GB
Valid from May 30, 2000 to May 30, 2020
Serial Number: 2766ee56eb49f38eabd770a2fc84de22
Signature Algorithm: sha384WithRSAEncryptionIssuer: AddTrust External CA Root
```
and
```
Common name: AddTrust External CA Root
Organization: AddTrust AB Org. Unit: AddTrust External TTP Network
Location: SE
Valid from May 30, 2000 to May 30, 2020
Serial Number: 1 (0x1)
Signature Algorithm: sha1WithRSAEncryption
Issuer: AddTrust External CA Root
```

**Comment by erichelgeson** [comment]
https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

I believe it's because your certificate store is out of date. If you apply security updates or update your store it should resolve.

**Comment by denychen** [comment]
We'll look into doing that, and I'll update the issue afterwards. Thanks for the quick reply.

**Comment by atharvafulay** [comment]
I am also running into this issue. I tried to create a new project `grails create-app sampleapp --stacktrace`

but I am seeing this error 

`| Error Error occurred running Grails CLI: NotAfter: Sat May 30 03:48:38 PDT 2020 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.security.cert.CertificateExpiredException: NotAfter: Sat May 30 03:48:38 PDT 2020
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:570)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:554)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:415)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:164)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:296)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:252)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:453)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:360)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:261)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:192)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:539)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:522)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:411)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:353)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:256)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:307)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:293)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:277)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:269)
	at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:54)
	at org.grails.cli.boot.GrailsDependencyVersions.<init>(GrailsDependencyVersions.groovy:50)
	at org.grails.cli.profile.repository.MavenProfileRepository.<init>(MavenProfileRepository.groovy:53)
	at org.grails.cli.GrailsCli.createMavenProfileRepository(GrailsCli.groovy:333)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:234)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Error occurred running Grails CLI: NotAfter: Sat May 30 03:48:38 PDT 2020
`

Unfortunately, I don't know enough about SSL and certificates to make use of this. Any advise would be appreciated!

**Comment by denychen** [comment]
It turns out that our build server was running an older JDK version: jdk1.8.0_31. Updating the JDK to jdk1.8.0_251 fixed the issue for us.

**Comment by atharvafulay** [comment]
^ This was my issue as well. Updated it and now it works as well
