### ISSUE TITLE
4.0.4: compileWebappGroovyPages fails with  CreateProcess error=206, The filename or extension is too long

### ISSUE THREAD

**Issue by jchharris** [grails/grails-core#11589]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

You need to have a project with substantial number of dependencies.  What occurs is that the command line for java has a very large -cp element as it lists all of the individual jars.:

```
Task ':core:core-framework:compileWebappGroovyPages' is not up-to-date because:
  The type of task ':core:core-framework:compileWebappGroovyPages' has changed from 'org.grails.gradle.plugin.web.gsp.GroovyPageCompileTask_Decorated' to 'org.grails.gradle.plugin.web.gsp.Groov
yPageForkCompileTask_Decorated'.
All input files are considered out-of-date for incremental task ':core:core-framework:compileWebappGroovyPages'.
Starting process 'command 'C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin\java.exe''. Working directory: C:\dev\di\workspace\048_DataIgnition_Framework_grails4\core\framework Command:
C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin\java.exe -Dfile.encoding=UTF-8 -Duser.country=AU -Duser.language=en -Duser.variant -cp C:\dev\di\.gradle\caches\modules-2\files-2.1\org.grails\grails-plugin-interceptors\4.0.4\40092049aa3c26e8d2514302fb8d5ae61
2161e79\grails-plugin-interceptors-4.0.4.jar;C:\dev\di\.gradle\caches\modules-2\files-2.1\org.grails\grails-plugin-url-mappings\4.0.4\9fc5deee02707edc547894c6170aaf1de4b47e2b\grails-plugin-url-
mappings-4.0.4.jar;C:\dev\di\.gradle\caches\modules-2\files-2.1\org.grails.plugins\async\4.0.0\41a4a5a76032ae71d77ce7a9722986ae5a42af04\async-4.0.0.jar;C:\dev\di\.gradle\caches\modules-2\files-
2.1\org.grails\grails-plugin-controllers\4.0.4\c1eba24fdfc5df44729e5587dee403984fd51a05\grails-plugin-controllers-4.0.4.jar and on and on....
```

### Expected Behaviour

compilation should complete successfully as it does on Grails 4.0.3

### Actual Behaviour

Below exception

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:core-framework:compileWebappGroovyPages'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin\java.exe''
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:237)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:214)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:364)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        ... 3 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin\java.exe'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
        ... 4 more
Caused by: java.io.IOException: Cannot run program "C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin\java.exe" (in directory "C:\dev\di\workspace\048_DataIgnition_Framework_grails4\core\
framework"): CreateProcess error=206, The filename or extension is too long
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 8 more
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        ... 9 more
```
### Environment Information

- **Operating System**: Window 10
- **Grails Version:** 4.0.4
- **JDK Version:** Adopt OpenJDK 11

**Comment by davydotcom** [comment]
Do you have the pathingJar enabled?

**Comment by davydotcom** [comment]
The forking process code is the exact same as the grails-views for gson. Wondering if you are using grails views or have in the past in the project as this issue may have shown up in past grails versions

**Comment by puneetbehl** [comment]
I believe it only happens on Windows. It seems related to https://github.com/grails/grails-core/issues/10630 and should be fixed as what @davydotcom suggested with `pathingJar` enabled.

**Comment by jchharris** [comment]
Hi,  I do have pathingJar enabled.  I had the same issue (at least the same error but can't recall at what build task it failed at) when we moved to Grails 3 which is is why I added pathingJar.  The build works fine for Grails 4.0.3.

**Comment by davydotcom** [comment]
I'm wondering if grails-views plugin has the same issue as that's where I sourced the forked process logic

**Comment by davydotcom** [comment]
Fixed for 4.0.5 in PR #11593

**Comment by jchharris** [comment]
awesome!  Does a similar fix need to be applied for grails-views?

**Comment by davydotcom** [comment]
It was already applied in the Abstract Task which I did not notice. So should be good there.
