### ISSUE TITLE
Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain

### ISSUE THREAD

**Issue by rorbla** [grails/grails-core#11585]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

grails create-app otroTest
cd .\otroTest\
grails run-app -port=8085

### Expected Behaviour

run the application 

### Actual Behaviour
```
Error: Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain
Caused by: java.lang.ClassNotFoundException: worker.org.gradle.process.internal.worker.GradleWorkerMain
Could not write standard input to Gradle Worker Daemon 1.
java.io.IOException: Se estß cerrando la canalizaci¾n
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:67)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:52)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
If I try to run through Intellij 2020.1.3:

```
"C:\Program Files\Java\jdk-11.0.2\bin\java.exe" -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:CICompilerCount=3 -Djline.WindowsTerminal.directConsole=false -Dfile.encoding=UTF-8 @C:\Users\Rubén\AppData\Local\Temp\idea_arg_file102377509 org.grails.cli.GrailsCli run-app --plain-output
Error: Could not find or load main class org.grails.cli.GrailsCli
Caused by: java.lang.ClassNotFoundException: org.grails.cli.GrailsCli
```

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 4.03
- **JDK Version:** 11.0.7 (Fails with 11.0.2 too)

**Comment by puneetbehl** [comment]
I tested with Grails 4.0.3 and Windows 10 inside Virtual Box. It seems to be working fine.

**Comment by puneetbehl** [comment]
Please try with `./grailsw.bat run-app` and also you should use `-Dserver.port=8085`.
