### ISSUE TITLE
Url mappings "linear" syntax inconsistence

### ISSUE THREAD

**Issue by markoong** [grails/grails-core#11584]
I've found some difference between the "block" and the "linear" syntax specifying url mappings (static mappings).

Reading the docs I'd assume the following two mappings to be equivalent:

linear:
```groovy
"/timeline/chuck_norris"(controller: "post", action: "timeline", id: "chuck_norris")
```

block:
```groovy
"/timeline/chuck_norris" {
            controller = "post"
            action = "timeline"
            id = "chuck_norris"
        }
```

But a test like the following fails with the first version, while passes in the other case:

```groovy
class UrlMappingsSpec extends Specification implements UrlMappingsUnitTest<UrlMappings> {

    def setup() {
        mockController(PostController)
    }

    def cleanup() {
    }

    @Unroll
    void "Ensure basic mapping operations for user permalink"() {
        expect:
            assertForwardUrlMapping(url, controller: expectCtrl, action: expectAction) {
                id = expectId
            }

        where:
            url                  | expectCtrl | expectAction | expectId
        '/users/glen'            | 'post'     | 'timeline'   | 'glen'
        '/timeline/chuck_norris' | 'post'     | 'timeline'   | 'chuck_norris'
    }
}
```

```
Condition failed with Exception:

assertForwardUrlMapping(url, controller: expectCtrl, action: expectAction) { id = expectId }
|                       |                |                   |
|                       |                post                timeline
|                       /timeline/chuck_norris
junit.framework.ComparisonFailure: Url mapping id assertion for '/timeline/chuck_norris' failed expected:<chuck_norris> but was:<null>

Condition failed with Exception:

assertForwardUrlMapping(url, controller: expectCtrl, action: expectAction) { id = expectId }
|                       |                |                   |
|                       |                post                timeline
|                       /timeline/chuck_norris
junit.framework.ComparisonFailure: Url mapping id assertion for '/timeline/chuck_norris' failed expected:<chuck_norris> but was:<null>

	at UrlMappingsSpec.Ensure basic mapping operations for user permalink(UrlMappingsSpec.groovy:19)
Caused by: junit.framework.ComparisonFailure: Url mapping id assertion for '/timeline/chuck_norris' failed expected:<chuck_norris> but was:<null>
	at grails.testing.web.UrlMappingsUnitTest$Trait$Helper.checkForwardUrlMapping_closure2$_closure5(UrlMappingsUnitTest.groovy:319)
	at groovy.lang.Closure.call(Closure.java:405)
	at grails.testing.web.UrlMappingsUnitTest$Trait$Helper.checkForwardUrlMapping_closure2(UrlMappingsUnitTest.groovy:313)
	at grails.testing.web.UrlMappingsUnitTest$Trait$Helper.checkForwardUrlMapping(UrlMappingsUnitTest.groovy:276)
	at grails.testing.web.UrlMappingsUnitTest$Trait$Helper.assertForwardUrlMapping(UrlMappingsUnitTest.groovy:336)
	... 1 more


```

Reading the documentation I'd expect the two syntax-es to be functionally equivalent and the test to pass in both cases, but it seems something is wrong with the `id` parameter in the first case.

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 4.0.1
- **JDK Version:** 1.8.2

**Comment by puneetbehl** [comment]
This does not work because `id` is not a named parameter. See https://github.com/grails/grails-core/blob/v4.0.1/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultUrlMappingsHolder.java#L147

The correct way would be:

```
 "/timeline/chuck_norris"(controller: "post", action: "timeline") {
            id = "chuck_norris"
  }
```
