### ISSUE TITLE
4.1.0.M3 - grails console is not working

### ISSUE THREAD

**Issue by mengu** [grails/grails-core#11699]
Hi everyone,

I wanted to visit Grails after a few years of break. I do have a Grails project (initially generated with 4.0.6) that is 4.1.0.M3. `grails run-app` does not have any problems however `grails console` has an issue. In 4.0.6 console wasn't even starting and it was throwing a Swing error which appears to be fixed with 4.1.0.M3. Whenever I run anything in the Grails console, I get the following error:

```
 
Exception thrown

groovy.lang.MissingMethodException: No signature of method: grails.ui.console.support.GroovyConsoleWebApplicationContext.getConsoleId() is applicable for argument types: () values: []
	at grails.ui.console.support.GroovyConsoleWebApplicationContext.this$dist$invoke$6(GroovyConsoleWebApplicationContext.groovy)
	at grails.ui.console.support.GroovyConsoleWebApplicationContext$1.methodMissing(GroovyConsoleWebApplicationContext.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Grails application running at http://localhost:0 in environment: development
```

This is how my gradle.properties look like:
```
grailsVersion=4.1.0.M3
gorm.version=7.1.0.M5
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M
```

### Steps to Reproduce

1. Generate a project with 4.1.0.M3
2. Run `grails console`
3. Console shows up.
4. Run a Groovy statement.
5. Fail.

### Expected Behaviour

Console should be working.

### Actual Behaviour

Console is throwing exception.

### Environment Information

- **Operating System**: macOS Mojave
- **Grails Version:** 4.1.0.M3
- **JDK Version:**  
* OpenJDK:
> java version "12.0.1" 2019-04-16
> Java(TM) SE Runtime Environment (build 12.0.1+12)
> Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
* GraalVM:
> openjdk version "1.8.0_272"
> OpenJDK Runtime Environment (build 1.8.0_272-b10)
> OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 25.272-b10-jvmci-20.3-b06, mixed mode)

**Comment by mengu** [comment]
also, i'd like to note that `grails url-mappings-report` throws this exception:

```
| Error Command [url-mappings-report] error: null (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.AbstractMethodError
	at org.grails.cli.gradle.commands.GradleTaskCommandAdapter.handle(GradleTaskCommandAdapter.groovy:65)
	at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:482)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:377)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:350)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Command [url-mappings-report] error: null
```

```bash
bash-3.2$ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```

**Comment by puneetbehl** [comment]
Please try with Grails 4.1.0.M5

**Comment by mengu** [comment]
hi @puneetbehl, i still get an error:

```
groovy> println("Hello World") 
 
Exception thrown

groovy.lang.MissingMethodException: No signature of method: grails.ui.console.support.GroovyConsoleWebApplicationContext.getConsoleId() is applicable for argument types: () values: []
	at grails.ui.console.support.GroovyConsoleWebApplicationContext.this$dist$invoke$6(GroovyConsoleWebApplicationContext.groovy)
	at grails.ui.console.support.GroovyConsoleWebApplicationContext$1.methodMissing(GroovyConsoleWebApplicationContext.groovy)
```

![Screen Shot 2021-01-23 at 19 00 07 (2)](https://user-images.githubusercontent.com/113091/105607007-6cbd4200-5dad-11eb-9590-df57666db7f1.png)


`grails url-mappings-report` command is also failing with:

```
| Error Command [url-mappings-report] error: null
java.lang.AbstractMethodError
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at org.grails.cli.gradle.commands.GradleTaskCommandAdapter.handle(GradleTaskCommandAdapter.groovy:65)
	at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:482)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:377)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:350)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Command [url-mappings-report] error: null
```

**Comment by puneetbehl** [comment]
I am not able to reproduce the above error with `./grailsw console`. Could you please share a sample application?

Also, I do not see error `java.lang.AbstractMethodError` with url-mappings-report. However, there is some other error due to a different reason.

**Comment by mengu** [comment]
hi @puneetbehl, indeed i will.

**Comment by puneetbehl** [comment]
Please reopen this is issue once you are able to replicate with Grails 5.0.0.M1 in a sample application.

**Comment by pvidasoftware** [comment]
I tested with grails 5.0.0.M1 (and some 4.0.x) and the error hapens if the profile is "vue", don't know with others profiles except "web". If the application is created using the "web" profile the console works as expected

I reviewed dependencies for console profile in both cases but couldn't find any difference between them, so don't know where the problem comes

**Comment by skomorokh** [comment]
FWIW I'm also finding this on the current release version 4.0.12: I get a `MissingMethodException` on `GroovyConsoleWebApplicationContext.getConsoleId` when I run `./grailsw console` immediately after creating a fresh app with `grails create-app somename --profile rest-api` whereas the console works fine when I create one with `--profile web`. 

My specific environment is Grails 4.0.12 and Groovy 3.0.9 from SDKMAN with OpenJDK 11.0.11 from Ubuntu 21.04.

**Comment by puneetbehl** [comment]
@skomorokh Please note that Grails 4 is not compatible with Groovy 3, use Grails 5 instead.

**Comment by skomorokh** [comment]
@puneetbehl thanks for the heads up, I'd been blindly letting sdkman just go with releases and the combination worked well enough that I'd not yet noticed the incompatibility. Unfortunately, creating a fresh app with `--profile rest-api` with Groovy 2.5.14 and Grails 4.0.12 still results in that same error when attempting to make use of the console.
