### ISSUE TITLE
cant convert arraylist as json ?  

### ISSUE THREAD

**Issue by cookiedesert** [grails/grails-core#11819]
### Task List
i have one `ArrayList` in code ,and i use `as JSON`, then it throw  exception
```
Exception in thread "main" org.grails.web.converters.exceptions.ConverterException: Unconvertable Object of class: java.util.ArrayList
	at grails.converters.JSON.value(JSON.java:182)
	at grails.converters.JSON.render(JSON.java:119)
	at org.grails.web.converters.AbstractConverter.writeTo(AbstractConverter.java:110)
	at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:535)
	at groovy.lang.GString.writeTo(GString.java:198)
	at groovy.lang.GString.toString(GString.java:154)
	at org.codehaus.groovy.reflection.stdclasses.StringCachedClass.coerceArgument(StringCachedClass.java:48)
	at org.codehaus.groovy.reflection.ParameterTypes.coerceArgumentsToClasses(ParameterTypes.java:152)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:211)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at common.AliApiGatewayClient.main(AliApiGatewayClient.groovy:147)
```
### Steps to Reproduce

1.  def  a =  []
2.  a as json

### Expected Behaviour

Tell us what should happen

### Actual Behaviour

Tell us what happens instead

### Environment Information

- **Operating System**: MAC OS
- **Grails Version:   3.3.8
- **JDK Version: 1.8
- **Container Version (If Applicable):** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by puneetbehl** [comment]
Could you please verify that if it is an issue with Grails 3 only or Grails 4 as well? because based on that I would be able to prioritise the same.

**Comment by cookiedesert** [comment]
only test  Grails 3。maybe on grails4 ? i don't know.... who knows?

**Comment by jeffbrown** [comment]
The project at https://github.com/jeffbrown/issue11819 contains a Grails 4.0.10 app:

[grails-app/controllers/issue11819/DemoController.groovy](https://github.com/jeffbrown/issue11819/blob/b89050581da75550271db4e74e3e3c53765519b9/grails-app/controllers/issue11819/DemoController.groovy)

```
package issue11819

import grails.converters.JSON

class DemoController {

    def emptyListAsJSON() {
        def a = []
        render a as JSON
    }
    def listAsJSON() {
        def a = [42, 'Hello', [name: 'Jeff', town: 'STL']]
        render a as JSON
    }
}
```


[src/test/groovy/issue11819/DemoControllerSpec.groovy](https://github.com/jeffbrown/issue11819/blob/b89050581da75550271db4e74e3e3c53765519b9/src/test/groovy/issue11819/DemoControllerSpec.groovy)

```
package issue11819

import grails.testing.web.controllers.ControllerUnitTest
import spock.lang.Specification

class DemoControllerSpec extends Specification implements ControllerUnitTest<DemoController> {

    void "test empty list"() {
        when:
        controller.emptyListAsJSON()

        then:
        response.text == '[]'
    }

    void "test populated list"() {
        when:
        controller.listAsJSON()

        then:
        response.text == '[42,"Hello",{"name":"Jeff","town":"STL"}]'
    }
}
```

That test passes.

**Comment by jeffbrown** [comment]
@cookiedesert Can you share some more code which demonstrates the problematic scenario, and/or send a PR to the project I linked above to help us reproduce the problem?  Thanks for any feedback.

**Comment by cookiedesert** [comment]
ok。so it work on grails 4 . thanks
