### ISSUE TITLE
Deploying G5 to Heroku: no main manifest attribute

### ISSUE THREAD

**Issue by jadelomeiri** [grails/grails-core#11940]
### Steps to Reproduce

1. Create new Grails 5 app (provided)
2. Create new Heroku app
3. Set in Heroku `heroku config:set GRADLE_TASK="build"`
4. Deploy to Heroku as per https://devcenter.heroku.com/articles/git

### Expected Behaviour

Application should be running in Heroku.
It works with previous Grails versions (G4 & G3 tested)

### Actual Behaviour

We get an error, the app crashes & doesn't run.

Erorrs as seen in Heroku logs:
```
2021-08-03T09:50:20.111964+00:00 heroku[web.1]: Starting process with command `java -Dserver.port=35720 $JAVA_OPTS -jar build/libs/*.war`
2021-08-03T09:50:22.036294+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2021-08-03T09:50:22.039994+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 
2021-08-03T09:50:22.120619+00:00 app[web.1]: no main manifest attribute, in build/libs/build_41ae25b0-0.1-plain.war
2021-08-03T09:50:22.185426+00:00 heroku[web.1]: Process exited with status 1
2021-08-03T09:50:22.347492+00:00 heroku[web.1]: State changed from starting to crashed
```

### Environment Information

- **Operating System**:  Heroku-20 stack, based on Ubuntu 20.04 https://devcenter.heroku.com/articles/heroku-20-stack
- **Grails Version:** 5.0.0.M2
- **JDK Version:** tied with both 8 & 15
- **Container Version (If Applicable):** Not sure

### Example Application

https://github.com/jadelomeiri/g5-heroku

**Comment by jadelomeiri** [comment]
Hey @puneetbehl I previously mentioned an issue with deploying G5 to Heroku.
I finally had time to create an example app and an issue for it.
Please let me know if anything's unclear or needs to be added.

**Comment by puneetbehl** [comment]
The error is not clear to me from the logs. I think the problem maybe related to `Xmx` settings. Did you try increasing it?

See https://devcenter.heroku.com/articles/java-memory-issues for more information on configuring `Xmx`

**Comment by jadelomeiri** [comment]
Hi @puneetbehl you can actually ignore that line.
The problem is more with:
`no main manifest attribute, in build/libs/build_41ae25b0-0.1-plain.war`

**Comment by puneetbehl** [comment]
Thanks, I will take a look tomorrow.

**Comment by jadelomeiri** [comment]
Cheers @puneetbehl
Let me know if there's anything I can do to help!

**Comment by jadelomeiri** [comment]
Hey @puneetbehl 
Do you think G5 final release would have this issue fixed?
Is there anything I can do to help with?
Many thanks ✌

**Comment by xqliu** [comment]
@jadelomeiri  I was using the bootJar gradle task as the build stage for heroku and it works with the jar file

**Comment by jadelomeiri** [comment]
Oh wow, that's awesome news! Thank you so much @xqliu !
Will give it a try then 🤞

**Comment by jadelomeiri** [comment]
Hey @xqliu 
If you don't mind, could please share your build.gradle and Procfile?
Been trying by trial and error, and getting different errors each time. I would be so grateful!

**Comment by xqliu** [comment]
Hi this is the related parts  in build.gradle, as by default, heroku uses a build task called `stage` to build during heroku CI, so we defined a task called stage, which depends on bootJar.

```
task stage(dependsOn: ['bootJar'])

tasks.stage.doLast() {
  delete fileTree(dir: "build/distributions")
  delete fileTree(dir: "build/assetCompile")
  delete fileTree(dir: "build/distributions")
  delete fileTree(dir: "build/libs", exclude: "*.jar")
}

jar {
  exclude "test/**"
  exclude "test/**/**"
}

build.mustRunAfter clean

gradle.taskGraph.whenReady {
  taskGraph ->
    if (taskGraph.hasTask(stage)) {
      test.enabled = false
    }
}

bootJar {
  enabled = true
  classifier = 'boot'
  exclude "test/**"
  exclude "test/**/**"
}
```

Here is our Procfile
```
web: java -Dgrails.env=$ENV -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/*.jar
```

Hope could help you.

**Comment by jadelomeiri** [comment]
Thanks a lot @xqliu for sharing and for adding the comments!
Unfortunately, I still get the same error I was getting since I tried bootJar when you first mentioned it.

Not sure if you've come across the same:
`2021-09-20T12:02:21.430909+00:00 app[web.1]: javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
2021-09-20T12:02:21.430909+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1377)
2021-09-20T12:02:21.430910+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1142)
2021-09-20T12:02:21.430910+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
2021-09-20T12:02:21.430910+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
2021-09-20T12:02:21.430911+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
2021-09-20T12:02:21.430911+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
2021-09-20T12:02:21.430912+00:00 app[web.1]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
2021-09-20T12:02:21.430912+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
2021-09-20T12:02:21.430912+00:00 app[web.1]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
2021-09-20T12:02:21.430912+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
2021-09-20T12:02:21.430913+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2021-09-20T12:02:21.430913+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
2021-09-20T12:02:21.430914+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2021-09-20T12:02:21.430914+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2021-09-20T12:02:21.430914+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
2021-09-20T12:02:21.430915+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2021-09-20T12:02:21.430915+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2021-09-20T12:02:21.430915+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
2021-09-20T12:02:21.430916+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2021-09-20T12:02:21.430916+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2021-09-20T12:02:21.430916+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
2021-09-20T12:02:21.430916+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
2021-09-20T12:02:21.430917+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)
2021-09-20T12:02:21.430917+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
2021-09-20T12:02:21.430918+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:390)
2021-09-20T12:02:21.430918+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:249)
2021-09-20T12:02:21.430918+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:344)
2021-09-20T12:02:21.430918+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
2021-09-20T12:02:21.430919+00:00 app[web.1]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2021-09-20T12:02:21.430919+00:00 app[web.1]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2021-09-20T12:02:21.430920+00:00 app[web.1]: 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
2021-09-20T12:02:21.430920+00:00 app[web.1]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
2021-09-20T12:02:21.430921+00:00 app[web.1]: 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
2021-09-20T12:02:21.430921+00:00 app[web.1]: 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2021-09-20T12:02:21.430921+00:00 app[web.1]: 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
2021-09-20T12:02:21.430921+00:00 app[web.1]: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
2021-09-20T12:02:21.430922+00:00 app[web.1]: 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2021-09-20T12:02:21.430922+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
2021-09-20T12:02:21.430922+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
2021-09-20T12:02:21.430923+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2021-09-20T12:02:21.430923+00:00 app[web.1]: 	at java.base/java.lang.Thread.run(Thread.java:832)
2021-09-20T12:02:21.430923+00:00 app[web.1]: 
2021-09-20T12:02:21.433681+00:00 heroku[router]: at=info method=GET path="/" host=grails5.herokuapp.com request_id=125e49dd-f8b9-42c9-a140-995113eaf532 fwd="159.205.84.15" dyno=web.1 connect=0ms service=11ms status=500 bytes=699 protocol=https`

Note: I'm trying with a fresh G5 app (no plugins, no custom code...)
Note 2: I've seen some other people coming across the same error, but not sure if the root problem is the same. Their solutions didn't work for me.
