### ISSUE TITLE
create-app fails with Grails 5 RC4

### ISSUE THREAD

**Issue by fernando88to** [grails/grails-core#12120]
### Steps to Reproduce

```
grails --version
| Grails Version: 5.0.0-RC4
| JVM Version: 11.0.11

grails create-app apppp --stacktrace

| Warning Unrecognized flag: stacktrace.
Resolving dependencies..
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:base:jar:5.0.0-RC6 in grailsCentral (https://repo.grails.org/grails/core) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.grails.profiles:base:jar:5.0.0-RC6 in grailsCentral (https://repo.grails.org/grails/core)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:408)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:293)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:116)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:108)
	at org.grails.cli.profile.repository.MavenProfileRepository.resolveProfile(MavenProfileRepository.groovy:87)
	at org.grails.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:72)
	at org.grails.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:80)
	at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:231)
	at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:369)
	at org.grails.cli.GrailsCli.executeCommandWithArgumentValidation(GrailsCli.groovy:286)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:262)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:base:jar:5.0.0-RC6 in grailsCentral (https://repo.grails.org/grails/core)


```

### Expected Behaviour

The application was created.

### Actual Behaviour

It crashes on application creation command

### Environment Information

- **Operating System**: Ubuntu 20.04.3 LTS
- **Grails Version:** 5.0.0-RC4
- **JDK Version:** openjdk version "11.0.11" 2021-04-20

**Comment by codeconsole** [comment]
I think it just takes time for the dependences to propagate in the repo.  
`craete-app` now works, but `create-domain-class` does not.

```
grails create-domain-class Sample
Error initializing classpath: Could not find org.grails.plugins:hibernate5:7.1.0-RC4.
```

@puneetbehl Any way to hold off on releasing until all the deps are available in the future? I think people see the release announcement in sdkman and just install. 

I also don't see that the hibernate RC4 plugin has been released

https://github.com/grails/gorm-hibernate5/tags

https://repo.grails.org/ui/native/core/org/grails/plugins/hibernate5

**Comment by puneetbehl** [comment]
Yes, it takes some time to propagate. It should work now.
