### ISSUE TITLE
JDK 17 Support / Gradle 7.3.0

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#12152]
Gradle 7.3.0 will soon be released (Currently RC3) and will support [JDK 17](https://github.com/gradle/gradle/issues/16857)

JDK is [the new](https://dev.java/download/releases/) LTS and was released in September.

JDK 17 requires [asm 9.1](https://asm.ow2.io/versions.html#9.1) and [Groovy 3.0.8](https://github.com/apache/groovy/commit/d27994ea1f516894423980c958b65c8c02fb9395) is the first version to support it.

Fortunately, Grails 5.0.0 introduced `groovyVersion` in `gradle.properties` and can be updated to Groovy 3.0.8+, so now is the time to start planning for JDK 17 support once Gradle 7.3.0 is released.

[Current Gradle Computability Matrix](https://docs.gradle.org/current/userguide/compatibility.html)

**Comment by codeconsole** [comment]
This will probably depend on Groovy 4.x support
https://github.com/grails/grails-core/issues/12373

**Comment by codeconsole** [comment]
I can confirm Grails 5.1.7 working with JDK 17 using Groovy 3.0.11-SNAPSHOT
I had to use `gradle bootRun`

However, the grails cli does not work.

```
% grails
| Error Failed to compile CreateFunctionalTest.groovy: startup failed:
General error during conversion: Unsupported class file major version 61

java.lang.IllegalArgumentException: Unsupported class file major version 61
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:189)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:170)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:156)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:277)
	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:79)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:70)
	at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:49)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lambda$createMethodNode$1(DecompiledClassNode.java:230)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.createMethodNode(DecompiledClassNode.java:236)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:203)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:122)
	at org.codehaus.groovy.ast.ClassNode.tryFindPossibleMethod(ClassNode.java:1283)
	at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:251)
	at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:133)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:108)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:66)
	at org.codehaus.groovy.control.StaticImportVisitor.visitConstructorOrMethod(StaticImportVisitor.java:108)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructor(ClassCodeVisitorSupport.java:101)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1089)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
	at org.codehaus.groovy.control.CompilationUnit.lambda$addPhaseOperations$3(CompilationUnit.java:209)
	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:288)
	at org.grails.cli.profile.commands.factory.GroovyScriptCommandFactory.readCommandFile(GroovyScriptCommandFactory.groovy:50)
	at org.grails.cli.profile.commands.factory.GroovyScriptCommandFactory.readCommandFile(GroovyScriptCommandFactory.groovy)
	at org.grails.cli.profile.commands.factory.ResourceResolvingCommandFactory.findCommands(ResourceResolvingCommandFactory.groovy:44)
	at org.grails.cli.profile.commands.CommandRegistry.findCommands(CommandRegistry.groovy:86)
	at org.grails.cli.profile.commands.CommandRegistry.findCommands(CommandRegistry.groovy)
	at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:432)
	at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:130)
	at org.grails.cli.profile.AbstractProfile.getCompleters(AbstractProfile.groovy:362)
	at org.grails.cli.GrailsCli.setupCompleters(GrailsCli.groovy:420)
	at org.grails.cli.GrailsCli.handleInteractiveMode(GrailsCli.groovy:402)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:273)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)

1 error
 (Use --stacktrace to see the full trace)
| Error Error occurred running Grails CLI: Cannot invoke "org.grails.cli.profile.commands.script.GroovyScriptCommand.setProfile(org.grails.cli.profile.Profile)" because "data" is null (Use --stacktrace to see the full trace)
```

**Comment by codeconsole** [comment]
The only JDK 17 issues that seem to be remaining are grails cli issues.

```
% grails -v
| Grails Version: 5.1.8
| JVM Version: 17.0.3
% grails create-app grails4bugs
| Application created at /grails4bugs
% cd grails4bugs
| Resolving Dependencies. Please wait...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 4s
| Error Failed to compile CreateFunctionalTest.groovy: startup failed:
General error during conversion: Unsupported class file major version 61

java.lang.IllegalArgumentException: Unsupported class file major version 61
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:189)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:170)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:156)

```

**Comment by codeconsole** [comment]
FYI JDK 17 is version 61 so the CLI is not supporting compiling itself

**Comment by codeconsole** [comment]
This seems like an issue being enforced by the framework

https://github.com/grails/grails-spring-security-core/issues/767
https://github.com/grails-plugins/grails-spring-security-ui/issues/127
https://github.com/grails/grails-spring-security-core/issues/737

**Comment by codeconsole** [comment]
https://github.com/codeconsole/grails4bugs

**Comment by fernando88to** [comment]
I ran grails 5.2.2 with jdk 17 by ./gradlew bootRun and it worked normally.

**Comment by codeconsole** [comment]
I can confirm JDK 17 is now working

**Comment by agre1981** [comment]
Hello, can we announce official support for java 17?
Now documentation says: "We have tested most Grails projects up to JDK 14."
https://docs.grails.org/5.2.x/guide/single.html#whatsNew

**Comment by DJViking** [comment]
Has the fix for JDK17 been released into the latest Grails 5.2.5 release?

When using Grails 5.2.5 with JDK17, I am unable to build.
It did not help changing the Gradle Wrapper from 7.2 to 7.3, or 7.6

`./gradlew bootRun` and `grails run-app` Works fine, but `./gradlew build` fails like this.
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':configureChromeDriverBinary'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
Caused by: java.lang.IllegalAccessException: module jdk.proxy4 does not open jdk.proxy4 to unnamed module @32464a14
        ... 134 more
```
This comes from a project created with `grails create-app helloworld`.

**Comment by agre1981** [comment]
Grails forge build works fine (https://start.grails.org/)
Grails: 5.2.5
Java: 11.0.15 (Windows 10)

12:02:40 PM: Executing 'clean build'...
> Task :clean
> Task :check UP-TO-DATE
> Task :build
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
BUILD SUCCESSFUL in 20s
13 actionable tasks: 12 executed, 1 up-to-date
12:03:00 PM: Execution finished 'clean build'.

**Comment by agre1981** [comment]
Yes, you are right, `build` doesn't work in 5.2.5, at least for me )

Looks this relates to the issue: https://github.com/erdi/webdriver-binaries-gradle-plugin/issues/30

```
Caused by: java.lang.IllegalAccessException: module jdk.proxy4 does not open jdk.proxy4 to unnamed module @20e2cbe0
	... 139 more
```

**Comment by agre1981** [comment]
Adding this to dependencies fixes the issue

```
buildscript {
    dependencies {
        classpath "org.ysb33r.gradle:grolifant50:2.0.0-alpha.6"    
    }
```
