### ISSUE TITLE
GrailsApp cannot resolve ConfigurableApplicationContext to MicronautApplicationContext when running in Tomcat

### ISSUE THREAD

**Issue by raniemi** [grails/grails-core#12156]
NOTE: I haven't been able to get a simple example working that demonstrates this issue, but I will try to continue to do so.  I'm creating this issue now just so that if there's something obvious for me to try then hopefully someone can chime in.

I'm currently working on upgrading a large Grails 2.x application to Grails 5.0.0. Most of the upgrade has already been done using Grails 5.0.0 RC1 and this issue only surfaced after upgrading to Grails 5.0.0 GA.

I first reported the issue on the slack channel: https://grails.slack.com/archives/C07M0GTDE/p1634592012409300

After upgrading to Grails 5.0.0 GA, I found that my GrailsApp is able to resolve the MicronautApplicationContext bean when it is executed using:

* `./grailsw run-app -https`
* `java -jar` - bootWar (embedded Tomcat)

For example:

```
2021-10-21 20:15:07.154 DEBUG --- [           main] io.micronaut.context.DefaultBeanContext  : Finding candidate beans for type: ConfigurableApplicationContext
2021-10-21 20:15:07.154 DEBUG --- [           main] io.micronaut.context.DefaultBeanContext  : Resolved bean candidates [Definition: io.micronaut.spring.context.MicronautApplicationContext] for type: ConfigurableApplicationContext
```

But the bean is not found when deploying:

* the plain war on Tomcat (non-embedded service)
* the boot war on Tomcat (non-embedded service)

For example: 

```
2021-10-22 00:03:32.337 DEBUG --- [           main] io.micronaut.context.DefaultBeanContext  : Finding candidate beans for type: ConfigurableApplicationContext
2021-10-22 00:03:32.337 DEBUG --- [           main] io.micronaut.context.DefaultBeanContext  : Resolved bean candidates [] for type: ConfigurableApplicationContext
```

The twist: When I created a new (`web`) application using the generator to reproduce this issue, I was able to run the war (no modifications) on the same Tomcat stack (i.e. non-embedded service) without issue.

### Environment Information

- **Operating System**: OSX/Windows
- **Grails Version:** 5.0.0
- **Tomcat Version:** 9.0.53
- **JDK Version:** 15.0.3

### Exception

```
java.lang.IllegalStateException: Error starting child
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1185)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1933)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1095)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:477)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
	... 37 common frames omitted
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [org.springframework.context.ConfigurableApplicationContext] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2698)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:824)
	at grails.boot.GrailsApp.createApplicationContext(GrailsApp.groovy:185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
	at org.grails.boot.context.web.GrailsAppServletInitializer.createRootApplicationContext(GrailsAppServletInitializer.groovy:57)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5219)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	... 38 common frames omitted
```

**Comment by raniemi** [comment]
@Taack I haven't tried with JDK 11 - since we're now using 15.  The application has already been built into a war multiple times (in a clean environment) and deployed to Tomcat just as many times - so I don't think it's compile time related.

The problem seems to be exclusively runtime and only when the war is running in a Tomcat install -- it appears that the Micronaut application context isn't fully instantiated by the time the GrailsApp does it's look up. 

Micronaut still seems pretty magical to me since I'm not sure how the bean load order is being enforced.  I tried declaring the application context in my resources.groovy file, but the behavior is still the same.

In the meantime, I may end up using the fat jar for our first production release and revisit this after wards.

**Comment by raniemi** [comment]
Since I've also been having some problems with HTTP/2 using Tomcat, I ended up swapping Tomcat for Jetty. Once I did that this particular issue went away. 

In light of this recent development, I don't see myself going back to Tomcat any time soon and so I'm going to close this issue for now.
