### ISSUE TITLE
Deploying war to tomcat fails for grails 5.1.2

### ISSUE THREAD

**Issue by qvarnis** [grails/grails-core#12352]
### Expected Behavior

Expecting that the war should deploy to tombat without errors.
This did not work in version 5.1.1 either.

### Actual Behaviour
```
20-Jan-2022 12:59:35.530 ALLVARLIG [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/Gradle___se_su_it___vfuportalen_war]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1141)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'groovyPagesTemplateEngine': Cannot resolve reference to bean 'classLoader' while setting bean property 'classLoader'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'classLoader' available
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
	at org.grails.boot.context.web.GrailsAppServletInitializer.createRootApplicationContext(GrailsAppServletInitializer.groovy:58)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'classLoader' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:872)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
	... 32 more
```

### Environment Information

Mac OS Monterey and and our ci-system running Debian Linux
Java 1.8
Tomcat 8.5.27

### Version

5.1.2

**Comment by qvarnis** [comment]
We still have this problem from 5.1.1 even though the issues were closed with fix.

**Comment by puneetbehl** [comment]
I am not sure if Grails 5 support Tomcat 8. Could you please try with Tomcat 9?

**Comment by qvarnis** [comment]
I will try it, in the meantime refering to grails documentation https://docs.grails.org/5.1.2/guide/single.html see the text "Grails is built against Tomcat 8 APIs by default." section  2.10.

**Comment by qvarnis** [comment]
It's the same problem with tomcat 9.0.58

**Comment by qvarnis** [comment]
Stuff that may help solve this issue:
1. If i remove the line apply plugin:"org.grails.grails-gsp" from our build.gradle i dont receive the same problem that was reported. I get a new one as below.

=======================================
21-Jan-2022 10:34:40.839 ALLVARLIG [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/Gradle___se_su_it___vfuportalen_war]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1736)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:482)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [org.springframework.context.ConfigurableApplicationContext] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2795)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:888)
	at grails.boot.GrailsApp.createApplicationContext(GrailsApp.groovy:185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:299)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 44 more

21-Jan-2022 10:34:40.841 ALLVARLIG [RMI TCP Connection(2)-127.0.0.1] org.apache.tomcat.util.modeler.BaseModelMBean.invoke Exception invoking method manageApp
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/Gradle___se_su_it___vfuportalen_war]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1736)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:482)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
=======================================

**Comment by puneetbehl** [comment]
Please share a sample application. Here is an example: https://github.com/puneetbehl/bookstore

**Comment by qvarnis** [comment]
I've used your example bookstore app and updated the build stuff and dependencies that we use.
You will find the example app here - https://github.com/qvarnis/bookstore

artifact-name: vfuportalen.war
java 1.8
tomcat 8.5.27 & tomcat 9.0.58

It fails with the above error int both versions when deploying the war.

**Comment by fernando88to** [comment]
I made an example application, it only worked with jdk 11.

Grails 5.1.12

https://github.com/fernando88to/Issue12352

**Comment by davidkron** [comment]
Maybe this can help as well, as it seems to be a similar or the same problem:
https://github.com/grails/grails-core/issues/12343

Although the ticket is closed, as I stated in my last comment, I do not believe that the fundamental problem is really fixed and the suggested "solution" of using `testImplementation` doesn't actually work as expected (Tomcat should NOT be present in resulting artifact).

**Comment by qvarnis** [comment]
@puneetbehl are you the only one working/supporting the grails community now adays?

**Comment by Dirk-27** [comment]
Our application is deployed and running when build with grails 4.0.13. After migrating to grails 5.1.4 it runs with grails run-app and the war file is build without error with grails build. But the tomcat 9.0.59 didn't start. The error is:

```
25-Mar-2022 13:58:05.032 SCHWERWIEGEND [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Fehler beim deployen des Web-Applikationsarchivs [C:\xampp\tomcat\webapps\neomatt-filecard-backend.war]
	java.lang.IllegalStateException: Error starting child
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:757)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/neomatt-filecard-backend]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
		... 9 more
	Caused by: java.lang.NullPointerException
		at org.springframework.boot.cli.app.SpringApplicationWebApplicationInitializer.getSources(SpringApplicationWebApplicationInitializer.java:61)
		at org.springframework.boot.cli.app.SpringApplicationWebApplicationInitializer.onStartup(SpringApplicationWebApplicationInitializer.java:47)
		at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5221)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 10 more
```

Even after exluding the dependency org.springframework.boot:spring-boot-starter-tomcat (which we verify with the dependency-report) the error is shown. (see https://docs.grails.org/latest/guide/deployment.html#deploymentContainer)

After we see this note *"THIS IS A BROKEN RELEASE, WHICH CONFLICTS WITH PREVIOUS RELEASE OF 5.0.0. PLEASE USE VERSION 5.0.1 WITH GRAILS 4 AND VERSION 6.0.0 WITH GRAILS 5"* at grails-cache (https://github.com/grails/grails-cache/releases/tag/v5.0.0) and there was no grails-cache version 6 at the maven repo we switched back to grails 4.0.13.

**Comment by puneetbehl** [comment]
[@qvarnis](https://github.com/qvarnis) I tried the same application shared by you and found multiple problems. 

- You are using a very old version of Grails views-gradle plugin.
-  The Dockerfile does not work so I made changes to fix that.
- I am not sure how Gradle `providedCompile` works but adding it seems to be the root cause. So, if you are planning to run the application on Standalone Tomcat then I would suggest to remove the spring-boot-starter-tomcat dependency from the classpath. 

Also, I have already shared a [sample application](https://github.com/grails/grails-core/issues/12352#issuecomment-1018344480) with you which works with standalone tomcat. I would appreciate if you could isolate the problem moving forward as it easier for me to quickly debug/fix the root cause and save me a lot of time. In this case, it does not seem to be the problem with Grails Core. I have sent the PR to you example application https://github.com/qvarnis/bookstore/pull/1

**Comment by aulea** [comment]
I had to exclude also module 'grails-shell' from dependencies. Because it includes spring-boot-cli which has own WebApplicationInitializer and usually it will start war from from it, not from GrailsAppServletInitializer.

**Comment by scottlollman** [comment]
```
Caused by: java.lang.NullPointerException
		at org.springframework.boot.cli.app.SpringApplicationWebApplicationInitializer.getSources(SpringApplicationWebApplicationInitializer.java:61)
```
@Dirk-27 I was running into this root cause when using `gradle war` deployed to tomcat.  I traced the issue to `developmentOnly` dependencies being included in the war.  According to [this spring boot documentation](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#reacting-to-other-plugins), the spring boot gradle plugin now defines `productionRuntimeClasspath` for this purpose.  In `org.springframework.boot.gradle.plugin.WarPluginAction` you can see the plugin removing `developmentOnly` dependencies from the `war` classpath.  

I added a block similar to this to my build file and no longer have issues with `developmentOnly` dependencies in my `war` file.  
```
war {
	def springBootCLI = classpath.find { it.name.contains("spring-boot-cli-") }//known problem package
	if( springBootCLI ) {
		// org.springframework.boot.gradle.plugin.WarPluginAction
		logger.warn("WAR classpath contains developmentOnly packages.  removing")
		classpath = classpath.minus(
			configurations.developmentOnly.minus(
				configurations.productionRuntimeClasspath
			)
		)
	} else {
		logger.trace("WAR classpath fine")
	}
}
```

**Comment by logantracyo** [comment]
We have been having the same problem as @Dirk-27 (with a very similar stacktrace) after upgrading several apps to Grails 5, but @scottlollman's solution didn't work out.  Finally found a similar solution [here](https://github.com/grails/grails-database-migration/issues/353) that did the trick for us:

Using that solution (updating the plugin call to `implementation ('org.grails.plugins:database-migration:4.2.1') { exclude module: 'spring-boot-cli' }`) excludes the troublesome spring-boot-cli, allowing startup and migrations to proceed normally.
