### ISSUE TITLE
Grails 5.1.2 LogbackException... should be either .groovy or .xml

### ISSUE THREAD

**Issue by mtgleeson** [grails/grails-core#12358]
### Expected Behavior

Running grails test-app should run without throwing ch.qos.logback.core.LogbackException.

### Actual Behaviour

Running grails test-app throws the folllowing exception:
```> Task :common:compileTestGroovy
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
ch.qos.logback.core.LogbackException: Unexpected filename extension of file [file:/<path to grails app>/build/resources/main/logback.groovy]. Should be either .groovy or .xml
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:67)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:140)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at io.micronaut.context.env.AbstractPropertySourceLoader.<clinit>(AbstractPropertySourceLoader.java:46)
        at grails.util.Metadata$_loadFromDefault_closure1.doCall(Metadata.groovy:133)
        at grails.util.Metadata$_loadFromDefault_closure1.call(Metadata.groovy)
        at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1184)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1897)
        at grails.util.Metadata.loadFromDefault(Metadata.groovy:132)
        at grails.util.Metadata.<init>(Metadata.groovy:61)
        at grails.util.Metadata.getCurrent(Metadata.groovy:118)
        at grails.util.Environment.resolveCurrentEnvironment(Environment.java:295)
        at grails.util.Environment.cacheCurrentEnvironment(Environment.java:321)
        at grails.util.Environment.getCurrent(Environment.java:288)
        at grails.util.Environment.<clinit>(Environment.java:132)
        at org.grails.compiler.injection.GlobalGrailsClassInjectorTransformation.visit(GlobalGrailsClassInjectorTransformation.groovy:73)
        at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:337)
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:610)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:262)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:97)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

### Steps To Reproduce

grails create-app grails512-restapi --profile rest-api
grails create-controller Test
grails test-app

### Environment Information

Mac OS 11.6
Java 8
Grails 5.1.2

### Version

5.1.2

**Comment by mtgleeson** [comment]
Ah, I just read logback.groovy is no longer supported. https://github.com/grails/grails-core/releases/tag/v5.1.2

I'll switch back to using logback.version=1.2.7.

Is there a way to achieve this using logback.xml (per environment configuration):

```
if ((Environment.isDevelopmentMode() {

}
```

**Comment by puneetbehl** [comment]
No, I think you can try logback-development.xml

**Comment by mtgleeson** [comment]
Thank @puneetbehl 
For anyone else migrating to logback.xml, I ended up with this in my application.yml to get per environment configuration working:

```
environments:
    development:
        logging:
            config: classpath:logback-development.xml
    production:
        logging:
            config: classpath:logback-prod.xml
    #test only seems to work via /src/test/resources/logback.xml
```

**Comment by puneetbehl** [comment]
Logback 1.2.9 dropped the support for Groovy file.

**Comment by arixmkii** [comment]
There is some sort of conditional configs supported in xml with `<if condition=` constructs.

**Comment by puneetbehl** [comment]
@arixmkii Thank you for pointing it out, please checkout https://logback.qos.ch/manual/configuration.html#conditional for more information

**Comment by ppazos** [comment]
@puneetbehl it seems Grails 5.x documentation wasn't updated to reflect the groovy config is not longer supported

https://docs.grails.org/5.3.2/guide/single.html#logging

"Since Grails 3.0, logging is handled by the [Logback logging framework](http://logback.qos.ch/) and can be configured with the grails-app/conf/logback.groovy file. If you prefer XML you can replace the logback.groovy file with a logback.xml file instead."
