### ISSUE TITLE
Stop Grails 5 JDK 11 output errors. 

### ISSUE THREAD

**Issue by arjangch** [grails/grails-core#12377]
### Expected Behavior

Grails 5, JDK 11 app should stop without any error. 

### Actual Behaviour

Stopping app produces error 

```| Error Failed to start server
java.util.concurrent.ExecutionException: org.gradle.internal.UncheckedException: java.lang.InterruptedException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java_util_concurrent_Future$get.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at run-app.run(run-app.groovy:98)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:153)
	at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:475)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:377)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:350)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
Caused by: org.gradle.internal.UncheckedException: java.lang.InterruptedException
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.internal.concurrent.ManagedExecutorImpl.stop(ManagedExecutorImpl.java:93)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$TrackedManagedExecutor.stop(DefaultExecutorFactory.java:80)
	at org.gradle.internal.concurrent.ManagedExecutorImpl.stop(ManagedExecutorImpl.java:77)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.stop(DefaultAsyncConsumerActionExecutor.java:47)
	at org.gradle.tooling.internal.consumer.DefaultProjectConnection.close(DefaultProjectConnection.java:48)
	at org.grails.cli.gradle.GradleUtil.withProjectConnection(GradleUtil.groovy:86)
	at org.grails.cli.gradle.GradleUtil.runBuildWithConsoleOutput(GradleUtil.groovy:92)
	at org.grails.cli.gradle.GradleInvoker.invokeMethod(GradleInvoker.groovy:50)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
	at org.grails.cli.gradle.GradleAsyncInvoker$_invokeMethod_closure2.doCall(GradleAsyncInvoker.groovy:57)
	at org.grails.cli.gradle.GradleAsyncInvoker$_invokeMethod_closure2.doCall(GradleAsyncInvoker.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
	at org.gradle.internal.concurrent.ManagedExecutorImpl.stop(ManagedExecutorImpl.java:87)
	... 29 more
| Error Failed to start server
```

### Steps To Reproduce

1. User JDK 11, Grails 5 
2. Create a new app
3. run app
4. stop app 

Output this error 
 | Error Failed to start server

Repeat the same but with JDK 8 does not produce any error.

### Environment Information

java=11.0.14-zulu
gradle=7.2
groovy=3.0.7
grails=5.1.2

### Example Application

An empty app creates this error 

### Version

5.1.2

**Comment by jeffscottbrown** [comment]
On what OS are you seeing that?

I have tried to reproduce on macOs and cannot.

Thank you for the feedback!

**Comment by rvachtl** [comment]
I've tried this with empty application on Windows 10, Oracle JDK 11.0.11 and Grails 5.0.3 and I'm getting "Error Application not running":
```

| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
grails> run-app
| Running application...
Grails application running at http://localhost:8080 in environment: development
<=======<<=====<===========--> 85% EXECUTING [27s]
> :bootRun
grails> stop-app
| Shutti<=<===========--> 85% EXECUTING [1m 2s]
| Error Application not running.
```

**Comment by jeffscottbrown** [comment]
@rvachtl I believe that may be a separate issue than the one reported in the original issue above.

**Comment by rainboyan** [comment]
I submit a PR https://github.com/grails-profiles/base/pull/99, this issue should be fixed now. I only test it on mac OS, please build and test it on windows 10, thank you. @rvachtl

**Comment by puneetbehl** [comment]
With Grails 6, the Grails CLI is completely rewritten from the scratch. We have removed commands such as `run-app`, `stop-app`, and encourage you to use Gradle build system.
