### ISSUE TITLE
GrailsCompileStatic could not take parameters now. 

### ISSUE THREAD

**Issue by gaolei8888** [grails/grails-core#12507]
### Expected Behavior

@GrailsCompileStatic suppose to take parameters as TypeCheckingMode.SKIP or TypeCheckingMode.PASS, It will do type checking or do not depends on these two parameters value. 

### Actual Behaviour

With Grails 5.1.7, This feature broke. It will throw compilation errors.  Something as 

```
 Index 0 out of bounds for length 0
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:265)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
        at org.gradle.api.internal.tasks.c
```

### Steps To Reproduce

1. Create  a Grails 5.1.7 project.
2. Create a Controller say, TestController.groovy
3. Add a methods test() ....., Annotated it with @GrailsStaticCompile(TypeCheckingMode.SKIP)
4. Run "gradle build -x test"
5. 

### Environment Information

- Windows 11
- JDK 11
- Grails 5.1.7

### Version

5.1.7

**Comment by gaolei8888** [comment]
This is a duplicated issue as #12440
