### ISSUE TITLE
grails migration 4.x to 5.x Task :compileGroovy FAILED No map entry allowed at this place

### ISSUE THREAD

**Issue by JJAM2014** [grails/grails-core#12506]
### Issue description

Hi ,
I have migrated from grails version 4.0.3 to version 5.x but when it reaches the build step compileGroovy this error appears

```
> Task :compileGroovy FAILED
startup failed:
General error during conversion: No map entry allowed at this place
. At [61:27] 

org.codehaus.groovy.syntax.RuntimeParserException: No map entry allowed at this place
. At [61:27] 
	at org.codehaus.groovy.classgen.VerifierCodeVisitor.visitListExpression(VerifierCodeVisitor.java:66)
	at org.codehaus.groovy.ast.expr.ListExpression.visit(ListExpression.java:62)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBinaryExpression(CodeVisitorSupport.java:202)
	at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:58)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitMethodCallExpression(CodeVisitorSupport.java:184)
	at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:76)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:117)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.codehaus.groovy.classgen.Verifier.visitMethod(Verifier.java:632)
	at org.codehaus.groovy.ast.ClassNode.visitMethods(ClassNode.java:1099)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1092)
	at org.codehaus.groovy.classgen.Verifier.visitClass(Verifier.java:251)
	at org.codehaus.groovy.tools.javac.JavaStubGenerator$1.visitClass(JavaStubGenerator.java:204)
	at org.codehaus.groovy.tools.javac.JavaStubGenerator.printClassContents(JavaStubGenerator.java:292)
	at org.codehaus.groovy.tools.javac.JavaStubGenerator.generateStubContent(JavaStubGenerator.java:173)
	at org.codehaus.groovy.tools.javac.JavaStubGenerator.generateFileStub(JavaStubGenerator.java:151)
	at org.codehaus.groovy.tools.javac.JavaStubGenerator.generateClass(JavaStubGenerator.java:131)
	at org.codehaus.groovy.tools.javac.JavaAwareCompilationUnit.lambda$new$2(JavaAwareCompilationUnit.java:103)
	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:610)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:262)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
	at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:97)
	at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
	at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
	at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

1 error
```
please could anybody tell me one clue what happend?

thanks very much in advance

best regards

**Comment by JJAM2014** [comment]
Java  openjdk 11

grailsVersion=5.1.7
grailsGradlePluginVersion=5.1.3
groovyVersion=3.0.7
gorm.version=7.2.1
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

**Comment by jeffscottbrown** [comment]
I tried to reproduce that and cannot.  Can you link to sample project which demonstrates the issue?

Thank you for your feedback!

**Comment by JJAM2014** [comment]
Dear Jeff
Thanks for your answer, I guess the problem will be in the change of version of groovy from 2.x to 3.x and in the use of annotations like @CompileStatic

best regards

José Juan

**Comment by jeffscottbrown** [comment]
It would be helpful to see what is around `[61:27]` in the class that won't compile.

**Comment by jeffscottbrown** [comment]
>  I guess the problem will be in the change of version of groovy from 2.x to 3.x and in the use of annotations like @CompileStatic

@JJAM2014 If you can help us by providing some more information about how to recreate the problem we can help investigate.

**Comment by JJAM2014** [comment]
Dear Jeff,

I am so sorry, but the software belongs to the client and I cannot show it. I can tell you that I generate a project in the grails 5 and gradle 7 version and it works fine and when I add classes from the project that I want to migrate I get the error and I can't find the point where it is because it is possibly a class that has a map that is generated in execution, I tried to do the migration with other project and did not get this problema.
thanks you very much in advance,
 best  regards,
José

**Comment by JJAM2014** [comment]
Dear Jeff,
I would like to tell you , that I solved the problem, I looked for inside of classes and I saw this 
 ` variableBoolean?[result:variableBoolean] as JSON :null`
This works for Groovy 2.x compiler , but It does not work for Groovy 3.x  compiler
thanks you very much for your interest
best regards,
José

**Comment by jeffscottbrown** [comment]
Thank you.  That feedback is helpful.  I have verified that a newly created 5.1.7 app will fail compilation with the following code...

```
boolean variableBoolean = true
def result = variableBoolean?[result:variableBoolean] as JSON :null
```

**Comment by jeffscottbrown** [comment]
FYI... I believe this works:

```
boolean variableBoolean = true
def result = variableBoolean?([result:variableBoolean] as JSON) :null
```
