### ISSUE TITLE
groovy.lang.GroovyRuntimeException: Cannot read write-only property: name

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#12678]
### Expected Behavior

Version should save without problems.

### Actual Behaviour

See full context on StackOverflow https://stackoverflow.com/questions/73444833/grails-3-saving-complex-model-throws-cannot-read-write-only-property-name?noredirect=1#comment129797768_73444833

```
2022-08-22 08:40:45.558 ERROR --- [nio-8080-exec-4] o.g.web.errors.GrailsExceptionResolver   : GroovyRuntimeException occurred when processing request: [GET] /version/testCreate
Cannot read write-only property: name. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: groovy.lang.GroovyRuntimeException: Cannot read write-only property: name
        at grails.validation.ValidationErrors.<init>(ValidationErrors.groovy:29)
        at grails.web.databinding.DataBindingUtils.bindObjectToDomainInstance(DataBindingUtils.java:387)
        at grails.web.databinding.DataBindingUtils.bindObjectToDomainInstance(DataBindingUtils.java:208)
        at org.grails.plugins.web.controllers.api.ControllersDomainBindingApi.initialize(ControllersDomainBindingApi.java:64)
        at com.cabolabs.ehrserver.openehr.common.change_control.VersionController.testCreate(VersionController.groovy:40)
        ... 14 common frames omitted
```

### Steps To Reproduce

git clone https://github.com/ppazos/grails_3_3_10_tests.git
cd grails_3_3_10_tests
grails run-app
browse: http://localhost:8080/version/testCreate

@jeffbrown noted this as relevant to this issue https://github.com/grails/grails-core/blob/f05fd73bd24f63fa95c0f5dbd74ad31526aa53e9/grails-core/src/main/groovy/grails/validation/ValidationErrors.groovy#L29

### Environment Information

$ grails -version
| Grails Version: 3.3.10
| JVM Version: 1.8.0_302

### Example Application

https://github.com/ppazos/grails_3_3_10_tests.git

### Version

3.3.10

**Comment by puneetbehl** [comment]
Could you please verify if this is also reproducible in the higher Grails versions? 

Grails 3 is EOL, and it is very unlikely to receive any updates. Please read about Grails Support Schedule [here](https://grails.org/support-schedule.html)

**Comment by ppazos** [comment]
@puneetbehl I can't, sorry, I'm maintaining a grails 3.3.10 app, and it can't be updated in the short term.

**Comment by puneetbehl** [comment]
Please reopen once it is verified that it is still an issue with Grails 5.

**Comment by ppazos** [comment]
@puneetbehl I"m not working on Grails 5, sorry.
