### ISSUE TITLE
Error establishing whether path is a directory: /application.yml  java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by maiconandsilva** [grails/grails-core#12829]
### Expected Behavior

Running the generated war shouldn't bring up a NoSuchFileException on the configuration file. 

### Actual Behaviour

Unable to read configuration file application.yml while starting generated war with command :

```
DefaultClassPathResourceLoader : Error establishing whether path is a directory: /application.yml

java.nio.file.NoSuchFileException: /application.yml
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:702)
        at jdk.zipfs/jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:815)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:252)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
        at io.micronaut.core.io.scan.DefaultClassPathResourceLoader.getResourceAsStream(DefaultClassPathResourceLoader.java:126)
        at io.micronaut.context.env.DefaultEnvironment.getResourceAsStream(DefaultEnvironment.java:327)
        at io.micronaut.context.env.AbstractPropertySourceLoader.readInput(AbstractPropertySourceLoader.java:127)
        at io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(AbstractPropertySourceLoader.java:96)
        at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:68)
        at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:55)
        at io.micronaut.context.env.DefaultEnvironment.loadPropertySourceFromLoader(DefaultEnvironment.java:601)
        at io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(DefaultEnvironment.java:534)
        at io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(DefaultEnvironment.java:520)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:790)
        at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:408)
        at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:270)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:765)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:734)
        at io.micronaut.context.LifeCycle.refresh(LifeCycle.java:71)
        at grails.boot.GrailsApp.loadPluginConfigurationsToMicronautContext(GrailsApp.groovy:137)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:106)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:485)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:472)
        at test.war.applicationyml.Application.main(Application.groovy:11)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
```

### Steps To Reproduce

1. Change log level to debug
2. Generate war: `grails war`
3. Run war:  `java -jar <path to war>`

### Environment Information

Ubuntu 22.04.1 LTS jammy

openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)

### Example Application

https://github.com/maiconandsilva/test-issue-grails-war-applicationyml

### Version

5.2.4

**Comment by msaubier** [comment]
Any update on this issue?  I'm seeing the same thing in our current Grails v5.3.2 application and in a Grails v6.0.0 application we are working on upgrading to.

**Comment by guillermocalvo** [comment]
This problem is most likely caused by https://github.com/micronaut-projects/micronaut-core/issues/7654
