### ISSUE TITLE
JDK 18 Support / Grails 5.3.2 / Gradle 7.6.1

### ISSUE THREAD

**Issue by akash-saha-jmh** [grails/grails-core#12931]
### Expected Behavior

The grails application should be compiling or supporing with JDK or JAVA_Version 18 and 19, as latest gradle supports those, But it is failing on compile-groovy step. But it is successfully compiling with JAVA 17 and below.

### Actual Behaviour

When I try to generate war using Gradle 7.6.1 it is failing on  compile Groovy step. It is not supporting any JDK above 17.

### Steps To Reproduce

1. When I ran the command "gradle clean war" with JDK 18 as a JAVA_HOME path variable, it is failing.

```
> Task :compileGroovy FAILED
startup failed:
General error during conversion: Unsupported class file major version 62
java.lang.IllegalArgumentException: Unsupported class file major version 62
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
        at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:869)
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:505)
        at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1430)
        at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:261)
        at org.codehaus.groovy.tools.javac.JavaAwareCompilationUnit.lambda$new$0(JavaAwareCompilationUnit.java:91)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:610)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:271)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:97)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:87)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:56)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Compilation failed; see the compiler error output for details.
```

### Environment Information

OS: Windows
JDK: 18
Gradle: 7.6.1
Grails: 5.3.2

### Version

5.3.2

**Comment by arixmkii** [comment]
@akash-saha-jmh Grails 5.3.2 has groovy version set to 3.0.11 (according to this https://github.com/grails/grails-core/issues/12931), which is pretty old and could not support latest JDKs. You can try overriding groovy version to 3.0.16, but this can bring on other incompatibilities, so, YMMV.

**Comment by akash-saha-jmh** [comment]
Hi @arixmkii , I tried the same as per your comment override groovy with 'implementation "org.codehaus.groovy:groovy-all:**3.0.16**"' in gradle.build file and tried to build with JDK 18 and 19 both, but it is giving same error like below for both of the cases,

> Task :compileGroovy FAILED
startup failed:
General error during conversion: Unsupported class file major version 63

java.lang.IllegalArgumentException: Unsupported class file major version 63
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
        at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:869)
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:505)
        at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1430)
        at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:261)
        at org.codehaus.groovy.tools.javac.JavaAwareCompilationUnit.lambda$new$0(JavaAwareCompilationUnit.java:91)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)

**Comment by arixmkii** [comment]
You should try with dependency overrides, something like:
```
configurations.all {
  resolutionStrategy {
    eachDependency { DependencyResolveDetails details ->
      // groovy updated
      if (details.requested.name.startsWith('groovy') && details.requested.group == 'org.codehaus.groovy') {
        details.useTarget "${details.requested.group}:${details.requested.name}:$groovyVersion"
      }
   }
 }
}
```

Where groovyVersion is defined in gradle.properties

I don't have a codebase to test it, but I could recall there was a problem to override this version. If this doesn't help, then it is better to wait for the response from Grails team on how this could be fixed.

**Comment by chrisbitmead** [comment]
I'm getting this problem also with Java 17 and a grails 5.3.2 app.

[arixmkii](https://github.com/arixmkii) what evidence is there that 5.0.11 groovy is too old for Java 17 and it causes this problem? And I tried changing it in gradle.properties to 3.0.18 and it didn't make any difference.

[arixmkii](https://github.com/arixmkii) I don't understand what your build.gradle (presumably?) snippet is supposed to do.

**Comment by chrisbitmead** [comment]
Actually looks like I made a silly mistake, upgrading groovyVersion=3.0.18 in gradle.properties does actually help.

**Comment by puneetbehl** [comment]
Grails 5 does not support Java 17 or Java 18 yet. It might work in some cases by following the suggestion from https://github.com/grails/grails-core/issues/12931#issuecomment-1476023846

We are planning to support Apache Groovy 4 with next major Grails update which should support Java 17.
