### ISSUE TITLE
The run-script command does not work with Groovy 2.5.7 or newer if grails.codegen.defaultPackage is set

### ISSUE THREAD

**Issue by douglyuckling** [grails/grails-core#12953]
### Expected Behavior

The `run-script` command should function properly when using Groovy 2.5.7+ and the `grails.codegen.defaultPackage` property is specified.

### Actual Behaviour

The application context initializes successfully, but the script never actually runs. The JVM just sits there idle:
```
$ ./grailsw run-script scripts/hello-world.groovy

> Task :runScript
Grails application running at http://localhost:0 in environment: development
<===========--> 85% EXECUTING [5m 16s]
> :runScript
```
If we run the script directly via the Gradle task, we can see that an exception has been thrown when Grails was preparing to run the script:
```
$ ./gradlew runScript -Pargs='scripts/hello-world.groovy'

> Task :runScript
Grails application running at http://localhost:0 in environment: development
Exception in thread "main" java.lang.UnsupportedOperationException
        at org.codehaus.groovy.control.CompilerConfiguration$1.addCompilationCustomizers(CompilerConfiguration.java:173)
        at grails.ui.script.GrailsApplicationScriptRunner.run(GrailsApplicationScriptRunner.groovy:61)
        at grails.ui.script.GrailsApplicationScriptRunner.main(GrailsApplicationScriptRunner.groovy:122)
<===========--> 85% EXECUTING [11s]
> :runScript
```

This is happening because Grails is attempting to apply compilation customizers to `CompilerConfiguration.DEFAULT`, but [as of Groovy 2.5.7 the implementation of `CompilerConfiguration` provided by `CompilerConfiguration.DEFAULT` is immutable](https://github.com/apache/groovy/commit/9a57f31f64720e3dcba190d03ca5ee50541d2a5f).

### Steps To Reproduce

1. Create a new default Grails project, and ensure that it defines a value for the `grails.codegen.defaultPackage` property (which it should by default).
2. Create a simple Grails script. The content of the script doesn't matter—a Groovy file containing a `println` is sufficient.
3. Try to run the script via `grails run-script` and observe that it doesn't actually run.
4. Comment out or delete the lines in `grails-app/conf/application.yml` that set `grails.codegen.defaultPackage`, then try running the script again and observe that it succeeds.

### Environment Information

This problem will manifest itself in any OS or JRE, but I happen to be on MacOS 11.7.6 using AdoptOpenJDK 11.0.8+10.

### Example Application

https://github.com/douglyuckling/grails-run-script-bug-repro

### Version

4.1.0 through at least 5.3.2

**Comment by greggobridges** [comment]
I get this also in grails 5 + groovy 3. Commenting out the  property did not help because something else then set the defaultPackage to a different value.

My workaround was to implement my own script runner that didn't attempt to modify the immutable CompilerConfiguration.

**Comment by douglyuckling** [comment]
I ran into this again today, and commenting out `grails.codegen.defaultPackage` in my project didn't help because some plugins we're using also define a value for that property.

But I found a decent workaround. There are two pieces to it:

1. Add some logic to `onStartup()` in your main `Application` class to delete/remove `grails.codegen.defaultPackage` from the `Config` object when a specific custom property (called `hack.suppressGrailsCodegenDefaultPackage` here) is enabled:

       @Override
       void onStartup(Map<String, Object> event) {
           Config config = Holders.grailsApplication.config

           // Workaround for https://github.com/grails/grails-core/issues/12953
           if (config.getProperty('hack.suppressGrailsCodegenDefaultPackage', Boolean.class)) {
               config.remove('grails.codegen.defaultPackage')
               config.get('grails')?.remove('codegen')
           }
       }

2. In `build.gradle`, configure tasks of type `ApplicationContextScriptTask` (which is the type of the Gradle task that provides the `run-script` functionality) to enable the custom property recognized above:

       tasks.withType(org.grails.gradle.plugin.commands.ApplicationContextScriptTask) {
           systemProperties([
                   // Workaround for https://github.com/grails/grails-core/issues/12953
                   'hack.suppressGrailsCodegenDefaultPackage': true,

                   // Bonus tip: Disable devtools when running scripts, because otherwise it interferes with
                   // successful shutdown and causes Gradle to report a build failure even when the script
                   // ran fine.
                   'spring.devtools.restart.enabled'           : false,
           ])
       }

**Comment by jdaugherty** [comment]
This appears to be an issue only with 5.x.  Performing the requested steps in a 7.0 snapshot seem to work as expected.  An example project is available here: https://github.com/jdaugherty/grails-core-issue-12953 

<img width="661" alt="Image" src="https://github.com/user-attachments/assets/7d7a3108-4db5-44ef-a8e3-446e06a923c1" />
