### ISSUE TITLE
Grails 6.0.0 - unexpected issue deploying to Tomcat 10 webapps-javaee folder - "GrailsVersion snapshot is not in the expected format"

### ISSUE THREAD

**Issue by boardbloke** [grails/grails-core#13080]
### Expected Behavior

I'm not sure if a Grails 6.0.0 application should be deployable to Tomcat10 in the webapps-javaee but given its a boot with extra smarts I thought it should do.

For context we have a number of Spring Boot and Grails apps.  We are in the process of all the vanilla Boot apps to Boot 3.1 as Boot 2.x is EOL in November I believe.  Boot 3.1 is Tomcat 10 and JDK 17 minimum.

We would ideally like to be able to run Grails 6.0.0 apps on Tomcat 10 by migrating using the  webapps-javaee capability provided by Tomcat so that we don't have to maintain different Tomcat versions for different components.

Presently we can't get past this issue (which I think may be minor) to see whether anything more significant comes up.

### Actual Behaviour

Tomcat 10 did the migration and produced a war file, however on trying to deploy Grails reported an error:

```java.lang.IllegalArgumentException: GrailsVersion snapshot is not in the expected format
        at org.grails.datastore.mapping.core.grailsversion.Snapshot.<init>(Snapshot.groovy:49)
        at org.grails.datastore.mapping.core.grailsversion.GrailsVersion.<init>(GrailsVersion.groovy:56)
        at org.grails.datastore.mapping.core.grailsversion.GrailsVersion.getCurrent(GrailsVersion.groovy:147)
        at org.grails.datastore.mapping.core.grailsversion.GrailsVersion.isAtLeastMajorMinor(GrailsVersion.groovy:77)
        at org.grails.orm.hibernate.support.HibernateDatastoreConnectionSourcesRegistrar.postProcessBeanDefinitionRegistry(HibernateDatastoreConnectionSourcesRegistrar.groovy:40)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:142)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4875)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:713)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:975)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1949)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:776)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1705)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1102)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1301)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1305)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1283)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)```

The error seems to be that HibernateDatastoreConnectionSourcesRegistrar is expecting to be able to find a instantiated GrailsVersion instance to decide whether to do some stuff, and one doesn't exist.



### Steps To Reproduce

Proceeded as follows:
* Created a minimal Grails 6.0.0 app created using grails create-app
* Created a war using gradlew war
* Deployed to the "webapps-javaee" (legacy webapps) folder in Tomcat10


### Environment Information

Temurin JDK 17
WSL2


### Example Application

_No response_

### Version

6.0.0

**Comment by puneetbehl** [comment]
Grails 6 is not compatible with Tomcat 10. The support for Tomcat 10 is scheduled for next major release alongwith Spring Boot 3.
