### ISSUE TITLE
Issue with Spring Security plugin in 5.3.4

### ISSUE THREAD

**Issue by lynchie14** [grails/grails-core#13250]
### Expected Behavior

Upgrade grailsVersion from 5.3.3 to 5.3.4 and spring security plugin should work

### Actual Behaviour

Failure when loading spring security plugin.

```
Configuring Spring Security Core ...
2023-11-30 20:00:46.267 ERROR --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NullPointerException: Cannot invoke method resolveType() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at grails.plugin.springsecurity.SpringSecurityCoreGrailsPlugin.classFor(SpringSecurityCoreGrailsPlugin.groovy:1101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at grails.plugin.springsecurity.SpringSecurityCoreGrailsPlugin$_doWithSpring_closure12.doCall(SpringSecurityCoreGrailsPlugin.groovy:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
	at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
	at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
	at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:545)
	at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:166)
	at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:178)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:142)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:458)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:445)
	at g533.Application.main(Application.groovy:11)
```

### Steps To Reproduce

Checkout https://github.com/lynchie14/spring_security_issue and run the app.

Drop version to 5.3.3 and re-run and it starts up fine.

For some reason in 5.3.4 the assignment of 

`beanTypeResolver = beanTypeResolverClass.newInstance(conf, grailsApplication)`

is not being set even though the evaluation of the right hand side in a debugger is instantiating the class.

### Environment Information

Windows 

Tested with jdk 11 / groovy 3.0.11 and jdk 17 with groovy 3.0.18 

### Example Application

https://github.com/lynchie14/spring_security_issue

### Version

5.3.4

**Comment by guillermocalvo** [comment]
The root cause of this issue is that `DefaultGrailsPlugin` closure's resolve strategy [was changed to `DELEGATE_FIRST`](https://github.com/grails/grails-core/pull/13150/files#diff-2226701447a270b094a7eb52800a92b7d818d10fac64927e709efd4206294bcfR544) recently.

This rendered the assignment [`beanTypeResolver = beanTypeResolverClass.newInstance(conf, grailsApplication)`](https://github.com/grails/grails-spring-security-core/blob/5.3.x/plugin/src/main/groovy/grails/plugin/springsecurity/SpringSecurityCoreGrailsPlugin.groovy#L215) void, because now it's intercepted by [`BeanBuilder.setProperty`](https://github.com/grails/grails-core/blob/5.3.x/grails-spring/src/main/groovy/grails/spring/BeanBuilder.java#L771) and then discarded because `currentBeanConfig` is `null`:

```groovy
public void setProperty(String name, Object value) {
  if (currentBeanConfig != null) {
    setPropertyOnBeanConfig(name, value);
  }
}
```

@puneetbehl I've prepared a PR that fixes the problem by using strategy `OWNER_FIRST`, but I'm not sure what's the specific problem that we were trying to solve in https://github.com/grails/grails-core/pull/13150. Could you please take a look at my PR and confirm that it makes sense?
- https://github.com/grails/grails-core/pull/13257

**Comment by puneetbehl** [comment]
Even with `DELEGATE_FIRST` is should also look into the `OWNER` if it is unable to find in the `delegate`. Also, I believe it should be `DELEGATE_FIRST` when we are explicitly setting the delegate.

**Comment by guillermocalvo** [comment]
@puneetbehl 

> Even with `DELEGATE_FIRST` is should also look into the `OWNER` if it is unable to find in the `delegate`.

A closure with `DELEGATE_FIRST` will only try to set the owner's property [if the delegate throws an exception](https://github.com/groovy/groovy-core/blob/master/src/main/groovy/lang/Closure.java#L388). However, `BeanBuilder` doesn't throw any exceptions: `setProperty` simply ignores the request to update the property if `currentBeanConfig` is `null`.

**Comment by lynchie14** [comment]
Any chance of getting a 5.3.5 released with this fix as 5.3.4 is unusable otherwise?

**Comment by LukaszGrzesik** [comment]
Also tried to upgrade from 5.3.3 to 5.3.4 - getting the same error (linux/java11/groovy seems not matter).
@guillermocalvo 
@puneetbehl 
Is there any timeline this will be resolved?

**Comment by amondel2** [comment]
I can confirm that the mail plugin is also impacting by this issue and moving to 5.3.5-snapshot did resolve the issue

**Comment by lynchie14** [comment]
Working in 5.3.5 release
