### ISSUE TITLE
Exception thrown when running grailsw in stock Grails 5.3.5

### ISSUE THREAD

**Issue by Erando89** [grails/grails-core#13327]
### Expected Behavior

`grailsw` runs without any problems, e.g. `grailsw -version`.

### Actual Behaviour

```
user@Latitude-7440:~/Downloads/grails-5.3.5/bin/Dummy$ chmod +x ./grailsw
user@Latitude-7440:~/Downloads/grails-5.3.5/bin/Dummy$ ./grailsw
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at grails.init.Start.main(Start.java:111)
Caused by: java.lang.NoClassDefFoundError: io/micronaut/context/env/PropertySourcePropertyResolver
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:869)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:979)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:967)
        at grails.util.Environment.resolveCurrentEnvironment(Environment.groovy:286)
        at grails.util.Environment.cacheCurrentEnvironment(Environment.groovy:312)
        at grails.util.Environment.getCurrent(Environment.groovy:278)
        at grails.util.Environment.<clinit>(Environment.groovy:127)
        at org.grails.build.parsing.CommandLineParser.<clinit>(CommandLineParser.java:44)
        at org.grails.cli.GrailsCli.<init>(GrailsCli.groovy:109)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:157)
        at org.grails.cli.GrailsCli$main.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at grails.init.RunCommand.main(RunCommand.groovy:40)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: io.micronaut.context.env.PropertySourcePropertyResolver
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:869)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:979)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:967)
        ... 29 more

```

### Steps To Reproduce

1. Download [grails-5.3.5.zip](https://github.com/grails/grails-core/releases/download/v5.3.5/grails-5.3.5.zip) (https://github.com/grails/grails-core/releases/tag/v5.3.5)
2. Unpack
3. `cd bin/`
4. `./grails create-app Dummy`
5. `cd Dummy/`
6. `chmod +x ./grailsw`
7. `./grailsw`

### Environment Information

- Ubuntu 22.04.3 LTS
- openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

### Version

5.3.5

**Comment by jamesfredley** [comment]
This issue impacted Grails 5.3.4+.

The updated grails-wrapper.jar for Grails 5.3.4+ can be found on:
https://github.com/grails/grails-wrapper/releases/tag/v3.1.0

The updated grails-wrapper.jar for Grails 6.0.0+ can be found on:
https://github.com/grails/grails-wrapper/releases/tag/v4.0.0
