### ISSUE TITLE
Getting error when running the tests task in Gradle.  Grails 6.1.2

### ISSUE THREAD

**Issue by dgeiselmanMOO** [grails/grails-core#13382]
### Expected Behavior

Tests should run successfully

### Actual Behaviour

I'm getting an error on 13 of my unit tests
java.lang.NoClassDefFoundError: org/springframework/beans/factory/config/InstantiationAwareBeanPostProcessorAdapter
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.grails.testing.GrailsApplicationBuilder.registerBeans_closure1(GrailsApplicationBuilder.groovy:199)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovy.lang.Closure.call(Closure.java:406)
	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
	at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
	at org.grails.testing.GrailsApplicationBuilder.defineBeans(GrailsApplicationBuilder.groovy:183)
	at org.grails.testing.GrailsApplicationBuilder.registerBeans(GrailsApplicationBuilder.groovy:189)
	at org.grails.testing.GrailsApplicationBuilder.registerGrailsAppPostProcessorBean_closure2(GrailsApplicationBuilder.groovy:213)
	at org.grails.testing.GrailsApplicationBuilder.registerGrailsAppPostProcessorBean_closure2(GrailsApplicationBuilder.groovy)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovy.lang.Closure.call(Closure.java:406)
	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
	at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
	at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:211)
	at org.grails.testing.GrailsApplicationBuilder$TestRuntimeGrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationBuilder.groovy:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:148)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:788)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:606)
	at org.grails.testing.GrailsApplicationBuilder.createMainContext(GrailsApplicationBuilder.groovy:156)
	at org.grails.testing.GrailsApplicationBuilder.build(GrailsApplicationBuilder.groovy:61)
	at org.grails.testing.GrailsUnitTest$Trait$Helper.getGrailsApplication(GrailsUnitTest.groovy:73)

Not sure what I am missing for a class not to be found.   The spring-beans class is on the classpath

### Steps To Reproduce

Happened after upgrading to JDK17, Grails 6.1.2, Spring Boot 3.2.2, Spring 6.1.3, Apache Camel 4.3.0

### Environment Information

JDK 17 Windows 10

### Version

6.1.2

**Comment by dgeiselmanMOO** [comment]
Changing to supported versions resolved this issue.

**Comment by gtorreblancaluna** [comment]
hello @dgeiselmanMOO . what version are compatibles? i have same error.

**Comment by jdaugherty** [comment]
Spring Boot 3 is what's in the 7.x branch and currently under development.  Spring boot 2.x is what's running on Grails 6.   You can see the version #'s in the gradle properties file here (for 6.2.x):  https://github.com/grails/grails-core/blob/6.2.x/gradle.properties
