### ISSUE TITLE
Grails 6.1.2 - Service injection not working on Command Object

### ISSUE THREAD

**Issue by gsartori** [grails/grails-core#13411]
### Expected Behavior

Injecting a Service into a Command Object should make it available for use

### Actual Behaviour

The Service instance is null

### Steps To Reproduce

1. Download the project -> https://github.com/gsartori/service-injection-not-working-in-command-objects
2. The project will only work with `Java 17`
3. Run the application (`bootRun`)
4. Login with username 'super' password 'super'
5. Click on 'Books' on the left side menu
6. Try adding a new book

The following Exception is thrown:

groovy.lang.MissingPropertyException: No such property: bookService for class: com.dueuno.BookValidator
Possible solutions: bookService
	at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1963)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1938)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3843)
	at org.grails.datastore.gorm.validation.constraints.builder.ConstrainedPropertyBuilder.getProperty(ConstrainedPropertyBuilder.java:74)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:194)
	at groovy.lang.Closure.getProperty(Closure.java:298)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:194)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:320)
	at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:314)
	at groovy.lang.Closure.getProperty(Closure.java:304)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at com.dueuno.BookValidator$__clinit__closure1$_closure2.doCall(BookController.groovy:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.grails.datastore.gorm.validation.constraints.ValidatorConstraint.processValidate(ValidatorConstraint.java:100)
	at org.grails.datastore.gorm.validation.constraints.AbstractConstraint.validate(AbstractConstraint.java:88)
	at grails.gorm.validation.DefaultConstrainedProperty.validate(DefaultConstrainedProperty.groovy:601)
	at grails.validation.Validateable$Trait$Helper.doValidate(Validateable.groovy:211)
	at grails.validation.Validateable$Trait$Helper.validate(Validateable.groovy:182)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
	at com.dueuno.BookValidator.validate(BookController.groovy)
	at grails.validation.Validateable$Trait$Helper.validate(Validateable.groovy:105)
	at grails.validation.Validateable$Trait$Helper$validate$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at com.dueuno.BookValidator.validate(BookController.groovy)
	at com.dueuno.BookController.onCreate(BookController.groovy)
	... 87 common frames omitted

### Environment Information

- OS: macOs
- Java 17

### Example Application

https://github.com/gsartori/service-injection-not-working-in-command-objects

### Version

6.1.2

**Comment by matrei** [comment]
The validator runs in a static context (`this` is not the `BookValidator` instance) so you cannot call `bookService` directly.
Do this instead:
```groovy
class BookValidator implements Validateable {

    def bookService

    String title
    String author

    static constraints = {
        title validator: { String title, BookValidator cmd, Errors errors ->
            if (cmd.bookService.getByTitle(title)) {
                errors.rejectValue('title', 'unique')
                return true
            }
            return false
        }
    }
}
```

**Comment by gsartori** [comment]
Thank you and sorry for the burden, I guess my fast reading got too 'fast' and not enough 'reading'...

Let's close this before I realize how much time I've spent on it :)
