### ISSUE TITLE
Grails 6.2.0: Application not starting in Tomcat 9

### ISSUE THREAD

**Issue by DKPillo** [grails/grails-core#13547]
### Expected Behavior

We are currently migrating some Grails Applications from 5.x.x to 6.2.0.
We build the war file using `gradle war`, which generates the `{appName}-{version}-plain.war` file as expected.
We deploy the war file into a tomcat (docker image: `tomcat:9.0.90-jre17`).
The application should start normally.

### Actual Behaviour

When the `{appName}-{version}-plain.war` is deployed the application startup beginns but crashes with the following output:

```
16-Jul-2024 19:15:10.840 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.90
16-Jul-2024 19:15:10.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 14 2024 14:45:13 UTC
16-Jul-2024 19:15:10.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.90.0
16-Jul-2024 19:15:10.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
16-Jul-2024 19:15:10.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.146.1-microsoft-standard-WSL2
16-Jul-2024 19:15:10.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
16-Jul-2024 19:15:10.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
16-Jul-2024 19:15:10.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           17.0.11+9
16-Jul-2024 19:15:10.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
16-Jul-2024 19:15:10.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
16-Jul-2024 19:15:10.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
16-Jul-2024 19:15:10.855 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
16-Jul-2024 19:15:10.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
16-Jul-2024 19:15:10.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
16-Jul-2024 19:15:10.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
16-Jul-2024 19:15:10.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
16-Jul-2024 19:15:10.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
16-Jul-2024 19:15:10.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
16-Jul-2024 19:15:10.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xdebug
16-Jul-2024 19:15:10.857 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
16-Jul-2024 19:15:10.857 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
16-Jul-2024 19:15:10.857 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
16-Jul-2024 19:15:10.857 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -agentlib:jdwp=transport=dt_socket,address=*:6000,server=y,suspend=y
16-Jul-2024 19:15:10.857 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
16-Jul-2024 19:15:10.857 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
16-Jul-2024 19:15:10.857 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
16-Jul-2024 19:15:10.858 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
16-Jul-2024 19:15:10.861 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.3.0] using APR version [1.7.0].
16-Jul-2024 19:15:10.861 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
16-Jul-2024 19:15:10.861 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
16-Jul-2024 19:15:10.864 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.2 15 Mar 2022]
16-Jul-2024 19:15:11.146 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
16-Jul-2024 19:15:11.168 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-0.0.0.0-8009"]
16-Jul-2024 19:15:11.169 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [509] milliseconds
16-Jul-2024 19:15:11.215 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
16-Jul-2024 19:15:11.215 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.90]
16-Jul-2024 19:15:11.229 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
16-Jul-2024 19:15:11.241 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-0.0.0.0-8009"]
16-Jul-2024 19:15:11.245 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [75] milliseconds
16-Jul-2024 19:15:31.246 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
16-Jul-2024 19:15:35.964 INFO [Catalina-utility-2] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
16-Jul-2024 19:25:00.191 SEVERE [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
        java.lang.IllegalStateException: Error starting child
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:602)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:571)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:603)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1014)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1866)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
                at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:816)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:468)
                at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1633)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:109)
                at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:973)
                at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1172)
                at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1176)
                at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1154)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
                at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
                at java.base/java.lang.Thread.run(Unknown Source)
        Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:402)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:179)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:599)
                ... 24 more
        Caused by: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "sources" is null
                at org.springframework.boot.cli.app.SpringApplicationWebApplicationInitializer.getSources(SpringApplicationWebApplicationInitializer.java:61)
                at org.springframework.boot.cli.app.SpringApplicationWebApplicationInitializer.onStartup(SpringApplicationWebApplicationInitializer.java:47)
                at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4438)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                ... 25 more
16-Jul-2024 19:25:00.194 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [568,947] ms
```

Additional Information:
We are using the [Database Migration Plugin](https://github.com/grails/grails-database-migration) Version 4.2.1, therefor we have `org.grails:grails-shell:6.1.2` included as a dependency.
Before the error occurs, the database migration is executed successfully.

Some Thoughts:
The exception occurs when `SpringApplicationWebApplicationInitializer` tries to read the `Spring-Application-Source-Classes` from the `/META-INF/MANIFEST.MF` file inside the war. In the plain war the manifest is empty. I have compared the manifest with a war built with Grails 5.3.3 which is successfully deployed to `tomcat:9.0.70-jre17`. There the manifest is empty, too. So this seams to be correct.
Now, if I understand the usage of `SpringApplicationWebApplicationInitializer` correctly, then this code should only be executed in the standalone war file. This i could successfully test by running the war file built with `gradle bootWar` via cli.

### Steps To Reproduce

1. `gradle war`
2. deploy to tomcat

### Environment Information

- Operating System: Debian/Ubuntu
- Tomcat: 9.0.90
- JDK: 17.0.11 (Temurin)
- Grails: 6.2.0

### Version

6.2.0

**Comment by rainboyan** [comment]
@DKPillo 
Remove the dependency grails-shell when packaging the war, grails-shell should not be on the runtime classpath because database-migration depends on it

```
configurations {
    developmentOnly
    runtimeClasspath {
        // Excludes from database-migration
        exclude group: 'org.grails', module: 'grails-shell'
    }
}
```

https://www.linen.dev/s/grails/t/16366221/i-m-running-into-another-issue-upgrading-from-5-to-6-1-2-rel#6fa78446-9201-48c2-97c6-4d22186bf75e

**Comment by DKPillo** [comment]
@rainboyan
Thank you for your quick answer.
This fixed the problem and the deployment works wine with this.

**Comment by fernando88to** [comment]
Thank you very much too

**Comment by rkrishnas81** [comment]
Do you have hello world app
Can you share so helpful

**Comment by jamesfredley** [comment]
@rkrishnas81 https://start.grails.org/
