### ISSUE TITLE
Fix stop-app in grails cli

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13695]
https://github.com/grails-profiles/base/blob/7.0.x/commands/stop-app.groovy

**Comment by codeconsole** [comment]
https://github.com/grails-profiles/base/issues/31

**Comment by codeconsole** [comment]
`management-agent.jar` was removed after java 1.8 and this code should be removed/refactored

https://github.com/grails-profiles/base/blob/6294515794b8ac8ae4eeb6a3da7ff40e5f132bb8/commands/stop-app.groovy#L31

**Comment by codeconsole** [comment]
https://github.com/grails-profiles/base/blob/6294515794b8ac8ae4eeb6a3da7ff40e5f132bb8/commands/stop-app.groovy#L76-L98

Perhaps there is a better way to stop the app similar to how `quit` works 
https://github.com/grails/grails-core/blob/ab9fdf3921f6a04f355d3b8282b9b29d16b98dab/grails-shell/src/main/groovy/org/grails/cli/GrailsCli.groovy#L665-L672

**Comment by arjangch** [comment]
I think this is the same bug.  
`java=21.0.8-zulu
gradle=8.14.3
groovy=4.0.28
grails=7.0.0-RC1
`

How to reproduce: Create a new app.  Start your app with 
`grails> run-app`
then try to stop it 
`grails> stop-app --stacktrace`
will output 
`java.io.FileNotFoundException: http://localhost:8080/actuator/shutdown
	at stop-app.run(stop-app.groovy:87)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:156)
	at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:478)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:364)
	at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.doCall(GrailsCli.groovy:455)
	<===========--> 90% EXECUTING [2m 45s]mandWithCancellationSupport_closure6.call(GrailsCli.groovy)
| Error Application not running.`

It says application is not running. But it is actually running. 
Now if you exit grails> with control-c then it will kill the app.

**Comment by jdaugherty** [comment]
The base profile includes a command  "stop-app.groovy" which is what you're invoking in the Grails console.  Here's why it doesn't work:

       What the code does:
        1. JMX first (lines 52–73): Uses com.sun.tools.attach.VirtualMachine to find the running JVM, attach to it, load the management agent, and call mbean.shutdown() on name=shutdownEndpoint,type=Endpoint.
        2. HTTP fallback (lines 76–98): POSTs to /actuator/shutdown — this is where your error comes from.

        Why you're getting FileNotFoundException:

        FileNotFoundException from Java's URL.openConnection() means HTTP 404. The actuator shutdown endpoint is disabled by default. You need both:

        # application.yml
        management:
          endpoint:
            shutdown:
              enabled: true
          endpoints:
            web:
              exposure:
                include: shutdown  # only needed for HTTP fallback

        Why JMX fallback likely silently failed:

        The JMX path (line 46) catches Throwable silently. Common reasons it fails:
        - com.sun.tools.attach.VirtualMachine not on classpath (requires JDK, not JRE, or the jdk.attach module)
        - MainClassFinder.findMainClass() returns null or doesn't match the running process's display name
        - Java 9+ module restrictions on management-agent.jar (line 31–32 tries to load it, but that jar was removed in Java 9+)
        
        Bottom line: Even if you fix the HTTP endpoint, the JMX approach is the more reliable one — but it requires management.endpoint.shutdown.enabled=true too (that's what registers the MBean). The
        management-agent.jar loading at line 31–32 is a Java 8-era approach that breaks on Java 9+.

**Comment by jdaugherty** [comment]
@matrei we recently talked about why the actuator was required and how I was confused it wasn't included by default anymore - it was actually to support stopping the app in dev ... (but requires configuration)

**Comment by matrei** [comment]
> we recently talked about why the actuator was required and how I was confused it wasn't included by default anymore - it was actually to support stopping the app in dev ... (but requires configuration)

This does not seem like a viable solution. It is very intrusive and impacts running in production for the sake of `stop-app` in development.
