### ISSUE TITLE
"Context failed to load: null" error with command grails run-script in grails 5.3.6

### ISSUE THREAD

**Issue by joelBrun** [grails/grails-core#13821]
### Expected Behavior

script success with message : 
> hello app536 !

### Actual Behaviour

Script fails with message :
> Task :runScript
Grails application running at http://localhost:0 in environment: development
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.UnsupportedOperationException
        at org.codehaus.groovy.control.CompilerConfiguration$1.addCompilationCustomizers(CompilerConfiguration.java:195)
        at grails.ui.script.GrailsApplicationScriptRunner.run(GrailsApplicationScriptRunner.groovy:61)
        at grails.ui.script.GrailsApplicationScriptRunner.main(GrailsApplicationScriptRunner.groovy:122)
        ... 5 more
Context failed to load: null

> Task :runScript FAILED

### Steps To Reproduce

grails create-app app536
cd app536
mkdir scripts
echo 'println "hello app536 !"' > scripts/hello.groovy
./gradlew runScript -Pargs="scripts/hello.groovy"

### Environment Information

Operating System: WSL2 Ubuntu 24
Grails Version: 5.3.6
JVM Version: 1.8.0_362

### Version

5.3.6

**Comment by jeffscottbrown** [comment]
Not a dup but related to #12953.

**Comment by joelBrun** [comment]
thanks Jeff for sharing the related ticket https://github.com/grails/grails-core/issues/12953.

it fixes the exception  UnsupportedOperationException
```
Exception in thread "main" java.lang.UnsupportedOperationException
        at org.codehaus.groovy.control.CompilerConfiguration$1.addCompilationCustomizers(CompilerConfiguration.java:195)
        at grails.ui.script.GrailsApplicationScriptRunner.run(GrailsApplicationScriptRunner.groovy:61)
        at grails.ui.script.GrailsApplicationScriptRunner.main(GrailsApplicationScriptRunner.groovy:122)
```

but the script execution never complete. still waiting after 30min
```
<===========--> 87% EXECUTING [36m 53s]
> :runScript
```

**Comment by joelBrun** [comment]
Is the support command "run-script" still supported ?

**Comment by jamesfredley** [comment]
This is resolved in 7.0.0-M5 and 7.0.0-SNAPSHOT.  See https://github.com/apache/grails-core/issues/12953#issuecomment-2780270055
