### ISSUE TITLE
Restore implements ContainerRenderer<C, T> on AbstractJsonViewContainerRenderer<C,T>

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-core#14199]
The interface XXX cannot be implemented more than once with different arguments.

implements ContainerRenderer<C, T> was causing Render to be implement more than once. It is currently removed from class AbstractJsonViewContainerRenderer<C,T>

https://github.com/grails/grails-views/pull/581/files#diff-b2646b6110b34798952582e9a501678112c0ed5d810ac556902857099652a31e

The way it worked historically would still require Groovy allowing classes to extend multiple interfaces with different generics.  Groovy allowed this for traits to support Grails 7, but would not allow it for interfaces, since Java does not allow that.  https://issues.apache.org/jira/browse/GROOVY-11508
https://issues.apache.org/jira/browse/GROOVY-5106
https://github.com/apache/groovy/commit/9d0d67197eb8cd333e973b08d4d0f4b7f3f41475

**Comment by jamesfredley** [comment]
This would require changes to ContainerRenderer in grails-core.

A start:  https://github.com/grails/grails-core/compare/7.0.x...convert-ContainerRender-to-trait

which resulted in a deeper rabbit hole with Groovy Traits called from Java:

```
                Caused by:
                java.lang.NoClassDefFoundError: grails/web/mime/MimeTypeProvider$Trait$Helper
                    at org.grails.plugins.databinding.DataBindingConfiguration.xmlDataBindingSourceCreator(DataBindingConfiguration.java:68)
                    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:171)
                    ... 45 more
                    Caused by:
                    java.lang.ClassNotFoundException: grails.web.mime.MimeTypeProvider$Trait$Helper
                        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
                        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
                        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
                        ... 47 more (edited) 
```

**Comment by jdaugherty** [comment]
I looked into this one.  It's tough.  It's Java code `DataBindingUtils.java` calling the groovy code that's failing.  

Here's the grails-views code before 7.0 code: 

	abstract class AbstractJsonViewContainerRenderer<C,T> extends DefaultJsonRenderer<T> implements ContainerRenderer<C, T>


By specifying both interfaces, it means there are 2 identical methods returning different values.  This isn't supported by Groovy 4.  It's only supported by traits and loading the Groovy Object from Java code is failling.  In groovy 3, it would have picked just the last interface when a method conflicts.  

Maybe we shouldn't use generics, that's how others like this are working:

        class AtomCollectionRenderer extends AtomRenderer implements ContainerRenderer

**Comment by jamesfredley** [comment]
`AbstractJsonViewContainerRenderer` used to implement `ContainerRenderer<C,T>` and that is used in org.grails.plugins.web.rest.render.DefaultRendererRegistry#addRenderer as a marker.

**Comment by sbglasius** [comment]
Relates to #15228
