### ISSUE TITLE
GRAILS-11070: list-plugin-updates throws NPE

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#2454]
Original Reporter: donal
Environment: Mac OS X, Linux, Windows
Version: 2.3.5
Migrated From: http://jira.grails.org/browse/GRAILS-11070

When you run {code}grails list-plugin-updates --stacktrace{code} you get the following error

{code}
| Error Error executing script ListPluginUpdates: java.lang.NullPointerException: Cannot get property 'plugin' on null object (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.NullPointerException: Cannot get property 'plugin' on null object
	at ListPluginUpdates$_run_closure1_closure5_closure6.doCall(ListPluginUpdates.groovy:28)
	at ListPluginUpdates$_run_closure1_closure5_closure6.doCall(ListPluginUpdates.groovy)
	at ListPluginUpdates$_run_closure1_closure5.doCall(ListPluginUpdates.groovy:27)
	at ListPluginUpdates$_run_closure2_closure9.doCall(ListPluginUpdates.groovy:67)
	at ListPluginUpdates$_run_closure2.doCall(ListPluginUpdates.groovy:66)
	at ListPluginUpdates$_run_closure1.doCall(ListPluginUpdates.groovy:26)
	at ListPluginUpdates$_run_closure1.doCall(ListPluginUpdates.groovy)
	at ListPluginUpdates$_run_closure4.doCall(ListPluginUpdates.groovy:85)
{code}

You can reproduce this issue simply by creating a new (empty) application and then running this script on it. The NPE is thrown from the line indicated below

{code}
def getAvailablePluginVersions = {
    def plugins = [:]
    eachRepository {repo, url ->
        use(DOMCategory) {

            /////////////////////////////////////////////////////
            // NPE thrown here because pluginsList is null
            /////////////////////////////////////////////////////
            pluginsList.'plugin'.each {plugin ->
                def name = plugin.'@name'
                def version
                if (plugin.'@latest-release') {
                    version = plugin.'@latest-release'
                }
                else if (plugin.'release'.size() > 0) {
                    // determine latest release by comparing version names in lexicografic order
                    version = plugin.'release'[0].'@version'
                    plugin.'release'.each {
                        if (!"${it.'@version'}".endsWith("SNAPSHOT") && "${it.'@version'}" > version) {
                            version = "${it.'@version'}"
                        }
                    }
                }
                plugins."$name" = version
            }
        }
    }
    return plugins
}
{code}

**Comment by graemerocher** [comment]
Couldn't reproduce this is master, but added a null check to avoid the error
