### ISSUE TITLE
Error Could not checkout tag for Grails release [3.0.1]

### ISSUE THREAD

**Issue by rawi2** [grails/grails-core#597]
Kubuntu 14.04, java version 1.8.0_40
Grails 3.0.1 installed from ZIP

~/work/grails$ grails --stacktrace --verbose create-app test
| Error Could not checkout tag for Grails release [3.0.1]: Ref v3.0.1 can not be resolved
org.eclipse.jgit.api.errors.RefNotFoundException: Ref v3.0.1 can not be resolved
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:244)
        at org.grails.cli.profile.git.GitProfileRepository.checkoutTagForRelease(GitProfileRepository.groovy:128)
        at org.grails.cli.profile.git.GitProfileRepository.createOrUpdateRepository(GitProfileRepository.groovy:116)
        at org.grails.cli.profile.git.GitProfileRepository.getProfile(GitProfileRepository.groovy:56)
        at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:70)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:173)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Could not checkout tag for Grails release [3.0.1]: Ref v3.0.1 can not be resolved
| Application created at /home/radu/work/grails/test

**Comment by bobbywarner** [comment]
@rawi2 This should no longer be an issue as the tag for 3.0.1 has now been added to the profile repository.  Can you please retry and verify it works for you now?

**Comment by jeffbrown** [comment]
Thanks for the feedback.

**Comment by rawi2** [comment]
Now is everything OK!
What's this for a quick voodoo?
You are awesome, thanks!

**Comment by yemurai** [comment]
I am getting this error 

grails --stacktrace --verbose create-app test
| Error Problem updating profiles from origin git repository
org.eclipse.jgit.api.errors.TransportException: https://github.com/grails/grails-profile-repository: cannot open git-upload-pack
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
        at org.grails.cli.profile.git.GitProfileRepository.fetchAndRebaseIfExpired(GitProfileRepository.groovy:140)
        at org.grails.cli.profile.git.GitProfileRepository.createOrUpdateRepository(GitProfileRepository.groovy:109)
        at org.grails.cli.profile.git.GitProfileRepository.getProfile(GitProfileRepository.groovy:56)
        at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:70)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:173)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/grails/grails-profile-repository: cannot open git-upload-pack
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:524)
        at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:309)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1115)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        ... 6 more
Caused by: java.net.UnknownHostException: github.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:176)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
        at java.net.Socket.connect(Socket.java:579)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:607)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:388)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:483)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:278)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:335)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:971)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1296)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:98)
        at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:168)
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:475)
        ... 11 more
| Error Problem updating profiles from origin git repository
| Error Could not checkout tag for Grails release [3.0.1]: Ref v3.0.1 can not be resolved
org.eclipse.jgit.api.errors.RefNotFoundException: Ref v3.0.1 can not be resolved
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:244)
        at org.grails.cli.profile.git.GitProfileRepository.checkoutTagForRelease(GitProfileRepository.groovy:128)
        at org.grails.cli.profile.git.GitProfileRepository.createOrUpdateRepository(GitProfileRepository.groovy:116)
        at org.grails.cli.profile.git.GitProfileRepository.getProfile(GitProfileRepository.groovy:56)
        at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:70)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:173)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Could not checkout tag for Grails release [3.0.1]: Ref v3.0.1 can not be resolved
| Error Cannot find profile web
