### ISSUE TITLE
Grails 3.0.2: With JDK8, grails run-app returns an InvocationTargetException, when modifying a controller

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#599]
Everytime I save a controller on Linux I get this exception from Spring Loaded, on OSX everything is working fine though.

```java
ERROR org.springsource.loaded.agent.Watcher - FileWatcher caught serious error, see cause
java.lang.IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4b672daa has been closed already
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:940) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:961) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.BeanFactory$getBean$1.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) ~[groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) ~[groovy-2.4.3.jar:2.4.3]
        at org.grails.plugins.web.GroovyPagesGrailsPlugin.onChange(GroovyPagesGrailsPlugin.groovy:322) ~[grails-plugin-gsp-3.0.0.jar:3.0.0]
        at org.grails.plugins.DefaultGrailsPlugin.notifyOfEvent(DefaultGrailsPlugin.java:768) ~[grails-core-3.0.0.jar:3.0.0]
        at grails.plugins.DefaultGrailsPluginManager.informObservers(DefaultGrailsPluginManager.java:225) ~[grails-core-3.0.0.jar:3.0.0]
        at org.grails.plugins.DefaultGrailsPlugin.notifyOfEvent(DefaultGrailsPlugin.java:792) ~[grails-core-3.0.0.jar:3.0.0]
        at org.grails.plugins.AbstractGrailsPluginManager.informOfClassChange(AbstractGrailsPluginManager.java:385) ~[grails-core-3.0.0.jar:3.0.0]
        at org.grails.dev.support.GrailsSpringLoadedPlugin.reloadEvent(GrailsSpringLoadedPlugin.java:40) ~[grails-core-3.0.0.jar:3.0.0]
        at org.springsource.loaded.TypeRegistry.fireReloadEvent(TypeRegistry.java:1794) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:417) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.]ELEASE
        at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

System information:
Ubuntu x64 14.10 ext4 (default mount options)
Oracle JDK 8 40
OpenJDK 8 40

Steps to reproduce:
```bash
grails create-app bugapp
grails create-controller Default
grails run-app
```

Then modify the DefaultController.groovy and save the file so spring loaded kicks in.

**Comment by olavgg** [comment]
Note: I also tried a clean install of Ubuntu 15.04 with VirtualBox, and got the same exception.

**Comment by volnei** [comment]
The same occurs in Windows.

**Comment by daptordarattler** [comment]
I also have this issue

**Comment by graemerocher** [comment]
I was able to reproduce with 3.0.1, but I have tested with 3.0.2 snapshot and it works, using Ubuntu Linux and JDK 1.8 u45

**Comment by gilinykh** [comment]
Controller modification still fails with 3.0.2 (with slightly different error):

```
Grails application running at http://localhost:8080 in environment: development
File C:\Projects\testTemplate\grails-app\controllers\testtemplate\TestController.groovy changed, recompiling...
hash=99162322 size=0
ERROR org.springsource.loaded.agent.Watcher - FileWatcher caught serious error, see cause
org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class testtemplate.TestController] of type [class org.grails.core.DefaultGrailsControllerClass]: InvocationTargetE
xception
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:169) ~[grails-core-3.0.2.jar:3.0.2]
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:784) ~[grails-core-3.0.2.jar:3.0.2]
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:480) ~[grails-core-3.0.2.jar:3.0.2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166) ~[groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68) ~[groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) ~[groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) ~[groovy-2.4.3.jar:2.4.3]
        at org.grails.plugins.web.controllers.ControllersGrailsPlugin.onChange(ControllersGrailsPlugin.groovy:184) ~[grails-plugin-controllers-3.0.2.jar:3.0.2]
        at org.grails.plugins.DefaultGrailsPlugin.notifyOfEvent(DefaultGrailsPlugin.java:791) ~[grails-core-3.0.20.2]:3.
        at org.grails.plugins.AbstractGrailsPluginManager.informOfClassChange(AbstractGrailsPluginManager.java:385) ~[grails-core-3.0.2.jar:3.0.2]
        at org.grails.dev.support.GrailsSpringLoadedPlugin.reloadEvent(GrailsSpringLoadedPlugin.java:41) ~[grails-core-3.0.2.jar:3.0.2]
        at org.springsource.loaded.TypeRegistry.fireReloadEvent(TypeRegistry.java:1794) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:417) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_40]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_40]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1002) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:160) ~[grails-core-3.0.2.jar:3.0.2]
        ... 23 common frames omitted
Caused by: java.lang.IllegalArgumentException: Cannot find method public java.lang.Object testtemplate.TestController.hello()
        at org.springframework.cglib.reflect.FastMethod.helper(FastMethod.java:35) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.cglib.reflect.FastMethod.<init>(FastMethod.java:24) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.cglib.reflect.FastClass.getMethod(FastClass.java:99) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at testtemplate.TestController$$FastClassByCGLIB$$5adb8110.getMethod(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
        at org.grails.core.DefaultGrailsControllerClass.methodStrategy(DefaultGrailsControllerClass.java:100) ~[grails-core-3.0.2.jar:3.0.2]
        at org.grails.core.DefaultGrailsControllerClass.<init>(DefaultGrailsControllerClass.java:61) ~[grails-core-3.0.2.jar:3.0.2]
        ... 29 common frames omitted
> Building 83% > :bootRun

C:\Projects\testTemplate>
| Grails Version: 3.0.2
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_40
```

**Comment by olavgg** [comment]
I get a similar error too, on both Linux and OSX, but it's only related to controllers.
```
ERROR org.springsource.loaded.agent.Watcher - FileWatcher caught serious error, see cause
org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class com.example.administration.ProjectController] of type [class org.grails.core.DefaultGrailsControllerClass]: InvocationTargetException
	at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:169) ~[grails-core-3.0.2.jar:3.0.2]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:784) ~[grails-core-3.0.2.jar:3.0.2]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:480) ~[grails-core-3.0.2.jar:3.0.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) ~[groovy-2.4.3.jar:2.4.3]
	at org.grails.plugins.web.controllers.ControllersGrailsPlugin.onChange(ControllersGrailsPlugin.groovy:184) ~[grails-plugin-controllers-3.0.2.jar:3.0.2]
	at org.grails.plugins.DefaultGrailsPlugin.notifyOfEvent(DefaultGrailsPlugin.java:791) ~[grails-core-3.0.2.jar:3.0.2]
	at org.grails.plugins.AbstractGrailsPluginManager.informOfClassChange(AbstractGrailsPluginManager.java:385) ~[grails-core-3.0.2.jar:3.0.2]
	at org.grails.dev.support.GrailsSpringLoadedPlugin.reloadEvent(GrailsSpringLoain.java:41) ~[grails-core-3.0.2.jar:3.0.2]
	at org.springsource.loaded.TypeRegistry.fireReloadEvent(TypeRegistry.java:1794) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:417) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1002) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:160) ~[grails-core-3.0.2.jar:3.0.2]
	... 21 common frames omitted
Caused by: java.lang.IllegalAccessError: tried to access method org.springframework.cglib.reflect.FastClass.getSignatureWithoutReturnType(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/String; from class com.example.administration.ProjectController$$FastClassByCGLIB$$9b6eafb6$$EPFzwLxI
	at com.example.administration.ProjectController$$FastClassByCGLIB$$9b6EPFzwLxI.getIndex(<generated>) ~[na:na]
	at com.example.administration.ProjectController$$FastClassByCGLIB$$9b6eafb6$$DPFzwLxI.getIndex(Unknown Source) ~[na:na]
	at com.example.administration.ProjectController$$FastClassByCGLIB$$9b6eafb6.getIndex(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.cglib.reflect.FastMethod.helper(FastMethod.java:28) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.cglib.reflect.FastMethod.<init>(FastMethod.java:24) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.cglib.reflect.FastClass.getMethod(FastClass.java:99) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at com.example.administration.ProjectController$$FastClassByCGLIB$$9b6eafb6.getMethod(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.grails.core.DefaultGrailsControllerClass.methodStrategy(DefaultGrailsControllerClass.java:100) ~[grails-core-3.0.2.jar:3.0.2]
	at org.grails.core.DefaultGrailsControllerClass.<init>(DefaultGrailsControllerClass.java:61) ~[grails-```

**Comment by ikakara** [comment]
I'm running Windows 8.1 w/ JDK8u45 and Grails 3.0.2 - and fails for me too.

I went ahead tried the latest spring-loaded from https://github.com/grails/grails-core/issues/619 - to no avail.

**Comment by ikakara** [comment]
@olavgg - can you update the issue title, to read: "Grails 3.0.2: With JDK8, grails run-app returns an InvocationTargetException, when modifying a controller"

I tried w/ JDK7, and it works fine.  Something changed between JDK7 and JDK8 to cause this issue.

**Comment by olavgg** [comment]
Sure, and thank you for telling me about JDK7.

**Comment by DanishKhakwani** [comment]
Getting the same error with JDK7_79 while modifying the controller.

**Comment by olavgg** [comment]
I just tested these changes from the snapshot build today, and I've had no weird compile errors yet :-) Thank you for quick fix!

**Comment by barcelona23** [comment]
I still have same problem. this only happens in OSx, using same project in windows works ok.

Grails Version: 3.1.11
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_102

Any idea somebody?
