### ISSUE TITLE
Grails 3.0.1 redirect from interceptor broken

### ISSUE THREAD

**Issue by mgkimsal** [grails/grails-core#625]
I've got an interceptor in which I'm trying to redirect() and getting the following error

```
ERROR org.grails.web.errors.GrailsExceptionResolver - HibernateException occurred when processing request: [GET] /
No Session found for current thread. Stacktrace follows:
org.hibernate.HibernateException: No Session found for current thread
	at grails.web.mapping.ResponseRedirector.redirectResponse(ResponseRedirector.groovy:101) ~[grails-web-url-mappings-3.0.1.jar:3.0.1]
	at grails.web.mapping.ResponseRedirector.redirect(ResponseRedirector.groovy:79) ~[grails-web-url-mappings-3.0.1.jar:3.0.1]
	at grails.artefact.controller.support.ResponseRedirector$Trait$Helper.redirect(ResponseRedirector.groovy:119) ~[grails-plugin-controllers-3.0.1.jar:3.0.1]
	at ncvpsgr3.GeneralInterceptor.before(GeneralInterceptor.groovy:21) ~[main/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]

```

Line 79 above looks to be

```
        redirectResponse(linkGenerator.getServerBaseURL(), linkGenerator.link(arguments), request, response, permanent)
```

which leads to (right below it)

```groovy
   private void redirectResponse(String serverBaseURL, String actualUri, HttpServletRequest request, HttpServletResponse response, boolean permanent) {
        if(log.isDebugEnabled()) {
            log.debug "Method [redirect] forwarding request to [$actualUri]"
            log.debug "Executing redirect with response [$response]"
        }

        String processedActualUri = processedUrl(actualUri, request);
        String absoluteURL = processedActualUri.contains("://") ? processedActualUri : serverBaseURL + processedActualUri
        String redirectUrl = useJessionId ? response.encodeRedirectURL(absoluteURL) : absoluteURL
        int status = permanent ? HttpServletResponse.SC_MOVED_PERMANENTLY : HttpServletResponse.SC_MOVED_TEMPORARILY

        response.status = status
        response.setHeader HttpHeaders.LOCATION, redirectUrl

        if (redirectListeners) {
            for (redirectEventListener in redirectListeners) {
                redirectEventListener.responseRedirected redirectUrl
            }
        }

        request.setAttribute GRAILS_REDIRECT_ISSUED, processedActualUri
    }
```

line 101 is "redirectEventListener.responseRedirected redirectUrl"

which seems to trigger the "org.hibernate.HibernateException: No Session found for current thread" (but maybe I'm looking in the wrong files?)

Interceptor code

```groovy
class GeneralInterceptor {

    GeneralInterceptor() {
        matchAll().excludes(controller:"user", action:"login")
    }

    boolean before() {
			log.info(session.id)
			log.info("controllerName=$controllerName")
			if(session && !session.isLoggedIn)
			{
				if(controllerName=="user" && (actionName=="login" || actionName=="loginProcess"))
				{ } else {
					log.info("REDIRECTING")
					redirect(uri:"/")
					return false
				}
			}
			log.info("controller="+controllerName)
			session.start = System.currentTimeMillis()
			log.info("before = "+session.start)
			true
    }
}
```

If the answer is "you're not supposed to redirect from an interceptor" I'll be really bummed.

**Comment by olavgg** [comment]
I have the same problem with this code!

    boolean before() {
        if(session["id"]){
            true
        }
        log.debug 'no user_id session found'
        redirect controller: "auth", action: "login"
    }

**Comment by mgkimsal** [comment]
Glad I'm not the only one @olavgg :)

**Comment by jeffbrown** [comment]
Thanks for the feedback.  We will get it straightened out.

**Comment by jeffbrown** [comment]
I haven't debugged it but my first suspicion is that the problem is problem coming out of `FlushOnRedirectEventListener` from grails-data-mapping.

**Comment by btboys** [comment]
I also met the same problem, what time can send the new version to solve?

**Comment by ikakara** [comment]
FYI - redirect (from an interceptor) works in grails 2.5.0, so problem is specific to grails 3

**Comment by graemerocher** [comment]
Duplicates #600
