### ISSUE TITLE
GormEntity trait is not applied when mapping external domain classes via hibernate.cfg.xml

### ISSUE THREAD

**Issue by ckalan** [grails/grails-core#633]
GormEntity trait is applied during compilation phase to domain artefacts so external Java domain classes can not have this trait. 

This causes GORM methods to call HibernateGormInstanceApi methods directly. And some of these methods ( like AbstractGormInstanceApi#save ) throws errors because they assume that first the GormEntity method is called. 

AbstractGormInstanceApi#save method for instance, does not check arguments parameter's nullability and causes NullPointerException when called without arguments.

```groovy
Person p = new Person()
p.save()
```

A workaround is to fix AbstractGormInstanceApi bugs but in any case, depending on compile time injected traits in such a way seems to create inconsistent behavior which is hardly traceable.

**Comment by jeffbrown** [comment]
We will soon settle on a plan for handling entities that have not been compile time enhanced.  Thanks for the feedback.

**Comment by ckalan** [comment]
Great. Do you recommend a workaround for now ? Does it help to annotate external classes with @Artefact(value="Domain") and compile with grails-core in classpath ?

**Comment by jeffbrown** [comment]
I don't think there is any good reason to use something like `@Artefact(value="Domain")`.  `@Artefact('Domain')` or `@grails.persistence.Entity` probably makes more sense.  None of that is going to help if this is a Java domain class.  If it is a Groovy domain class then I think `@Entity` will get you what you need.  Give that a spin and let me know if that works.

**Comment by jeffbrown** [comment]
Annotate your class with `@Entity` and then confirm that the generated class does implement `GormEntity`.  You shouldn't have to mention `GormEntity` in your source code, the compiler should add that.  If your compile time class path is setup correctly, I think it will.

**Comment by ckalan** [comment]
When annotated with @Entity, hibernate schema export complains because of injected validation properties.

```
Caused by: org.hibernate.MappingException: Could not determine type for: org.springframework.validation.Errors, at table: role, for columns: [org.hibernate.mapping.Column(org_grails_datastore_gorm_gorm_validateable__errors)]
        at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:336) ~[hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:310) ~[hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.hibernate.mapping.Property.isValid(Property.java:241) ~[hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:496) ~[hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.hibernate.mapping.RootClass.validate(RootClass.java:270) ~[hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.hibernate.cfg.Configuration.validate(Configuration.java:1360) ~[hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1851) ~[hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.grails.orm.hibernate.cfg.GrailsAnnotationConfiguration.buildSessionFactory(GrailsAnnotationConfiguration.java:390) ~[grails-datastore-gorm-hibernate4-4.0.0.RELEASE.jar:na]
        at org.grails.orm.hibernate.ConfigurableLocalSessionFactoryBean.doBuildSessionFactory(ConfigurableLocalSessionFactoryBean.java:479) ~[grails-datastore-gorm-hibernate4-4.0.0.RELEASE.jar:na]
        at org.grails.orm.hibernate.ConfiguralSessionFactoryBean.buildSessionFactory(ConfigurableLocalSessionFactoryBean.java:473) ~[grails-datastore-gorm-hibernate4-4.0.0.RELEASE.jar:na]
        at org.grails.orm.hibernate.ConfigurableLocalSessionFactoryBean.afterPropertiesSet(ConfigurableLocalSessionFactoryBean.java:387) ~[grails-datastore-gorm-hibernate4-4.0.0.RELEASE.jar:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        ... 40 common frames omitted
```

I tried putting   static transients = ['errors'] . But it did not work.

**Comment by ckalan** [comment]
Any progress on this ?

**Comment by graemerocher** [comment]
We will not be supporting entities that are not compile time enhanced. In your case you should move your entity out of `grails-app/domain` and into `src/groovy` and ensure that it is not annotated with `@Entity`

**Comment by ckalan** [comment]
This issue should not be closed I guess. What is described in Grails documentation chapter 20 says that JPA domain classes can be uses with Gorm dynamic methods. 

And if you just create a new app and do exactly what that page says, and try to save a Book like

`new Book(...).save()`

You get "No signature of method: Book.save()". Even though hibernate recognizes the entity and creates the tables, Grails does not enhance the class with Gorm methods. 

I am using Grails 3.1.3 but reproduced it with all 3.x versions. 

So if I don't put the Grails @Entity annotation, how does Grails enhance the class with Gorm api ? And if I put that annotation, then problems I described above occurs. 

So if Grails does not support JPA domain objects with GORM any more, I think this must be documented.

**Comment by kranthiboinpally** [comment]
Is there any progress on this issue?
