### ISSUE TITLE
File watcher duplicate items with same file causes applicationContext refresh

### ISSUE THREAD

**Issue by ckalan** [grails/grails-core#636]
In GrailsApp class, when more than 1 file have been changed, applicationContext is refreshed. Intellij IDEA ( and maybe other IDEs) makes a file change to trigger both onChange and onNew at the same time which unintentionally refreshes the applicationContext.

**Comment by mTatai** [comment]
I can confirm this. I have observed this in the debugger, and the `changedFiles` collection contains the same file twice, so the reloading logic takes the route which has the comment `// more than one change, recompile and restart`.
This triggers the whole applicationContext reload, which also fails for me the second time (not the first time, intrestingly), when it tries starting the embedded container again, because the port is 'already taken'.

I am using a brand new grails application and a single controller with a single index action.
```
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_25
| Ubuntu 14.04.2 LTS 
```

The stack trace is : 
```
java.lang.IllegalStateException: Tomcat connector in failed state	at org.springsource.loaded.ri.
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:157)
ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-2.4.3.jar:2.4.3]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-2.4.3.jar:2.4.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207) [groovy-2.4.3.jar:2.4.3]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130) [groovy-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:180) [grails-core-3.0.1.jar:3.0.1]

	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy) [grails-core-3.0.1.jar:3.0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at grails.boot.GrailsApp.super$2$run(GrailsApp.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1276)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:180)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at groovy.lang.Closure.call(Closure.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at groovy.lang.Closure.call(Closure.java:417)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at groovy.lang.Closure.run(Closure.java:504)
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-2.4.3.jar:2.4.3]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) [groovy-2.4.3.jar:2.4.3]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) [groovy-2.4.3.jar:2.4.3]
	at groovy.lang.Closure.call(Closure.java:423) [groovy-2.4.3.jar:2.4.3]
	at groovy.lang.Closure.call(Closure.java:417) [groovy-2.4.3.jar:2.4.3]
	at groovy.lang.Closure.run(Closure.java:504) [groovy-2.4.3.jar:2.4.3]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

```

**Comment by graemerocher** [comment]
Thanks for the pull request
