### ISSUE TITLE
Grails 3.0.0: Starting Grails with -https enabled leads to CNFE on some JVMs

### ISSUE THREAD

**Issue by ikakara** [grails/grails-core#648]
Environment: 
Java 8.1.8.0_45
Grails: 3.0.1

When I run grails run-app -https, I get the following error:
| Generating SSL certificate
| Error Failed to start server (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.ClassNotFoundException: com.ibm.crypto.tools.KeyTool
        at run-app.getKeyToolClass(run-app.groovy:87)
        at run-app.createSSLCertificate(run-app.groovy:67)
        at run-app.run(run-app.groovy:34)
        at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:146)
        at org.grails.cli.profile.DefaultProfile.handleCommand(DefaultProfile.groovy:177)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:235)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:216)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:194)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)

**Comment by graemerocher** [comment]
Which JDK? Open JDK? Sun JDK?

**Comment by ikakara** [comment]
Using Windows 8.1 and Oracle JDK

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-profile-repository/commit/be669a5854d65ee6518a2f7e41cce09f4dea6438
