### ISSUE TITLE
Unable to start Grails 3.0.1 on Windows 7x64

### ISSUE THREAD

**Issue by busches** [grails/grails-core#656]
I'm able to run `grails create-app test` but when I do a `cd test` `grails run-app` I get the following:

```
| Error Error initializing classpath: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.gradle.api.GradleException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

        at org.gradle.launcher.daemon.bootstrap.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:35)
        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:112)
        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:93)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:105)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:82)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:115)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:75)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:42)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:62)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:107)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:101)
        at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:171)
        at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection$CancellableActionRunner.run(CancellableConsumerConnection.java:105)
        at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:60)
        at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:57)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
| Error Error initializing classpath: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Versions:
```
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.7.0_71
| Windows: 7x64
```

Debug command path:
```
"C:\Program Files (x86)\Java\jdk1.7.0_71/bin/java.exe" "-XX:+TieredCompilation" "-XX:TieredStopAtLevel=1" "-XX:CICompilerCount=3"    -classpath....
```
The classpath is large and cuts off, but clearly works, since `grails create-app` runs.

I've tried clearing `.gradle` and `.grails` and the same issue occurs. I've also set  `-Xmx1024M` and `-XX:MaxPermSize=1024m` and same error.

**Comment by graemerocher** [comment]
Related to https://issues.gradle.org/browse/GRADLE-1420

**Comment by Mutley5000** [comment]
What was the solution to this as I have hit this same problem?  Thank you.

**Comment by busches** [comment]
Newer versions of Grails use newer versions of Gradle, which solved the problem.

**Comment by Mutley5000** [comment]
Ok thank you.
