### ISSUE TITLE
Cannot create a grails project by calling 'grails create-app PROJECTNAME'

### ISSUE THREAD

**Issue by TobiasKranz** [grails/grails-core#658]
I installed grails 3.0.1 via gvm and tried to create a new grails project by calling

# grails create-app myproject
| Error Error occurred running Grails CLI: org.yaml.snakeyaml.Yaml.loadAs(Ljava/io/InputStream;Ljava/lang/Class;)Ljava/lang/Object; (Use --stacktrace to see the full trace)
The complete error message reads as follows:

# grails --verbose --stacktrace create-app myproject 
| Error Error occurred running Grails CLI: org.yaml.snakeyaml.Yaml.loadAs(Ljava/io/InputStream;Ljava/lang/Class;)Ljava/lang/Object;
java.lang.NoSuchMethodError: org.yaml.snakeyaml.Yaml.loadAs(Ljava/io/InputStream;Ljava/lang/Class;)Ljava/lang/Object;
at org.grails.cli.profile.DefaultProfile$_initialize_closure5.doCall(DefaultProfile.groovy:207)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
at groovy.lang.Closure.call(Closure.java:423)
at groovy.lang.Closure.call(Closure.java:439)
at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1204)
at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1642)
at org.grails.cli.profile.DefaultProfile.initialize(DefaultProfile.groovy:206)
at org.grails.cli.profile.DefaultProfile.create(DefaultProfile.groovy:59)
at org.grails.cli.profile.git.GitProfileRepository.getProfile(GitProfileRepository.groovy:61)
at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:70)
at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:173)
at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Error occurred running Grails CLI: org.yaml.snakeyaml.Yaml.loadAs(Ljava/io/InputStream;Ljava/lang/Class;)Ljava/lang/Object;
(The same error occurs with grails 3.0.0. The error persist when using java 1.8.0_45 instead of 1.8.0_31.)

Any ideas?

Some useful information of my system:

# java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

# grails -version
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_31

# uname -a
Darwin <anonymous>.edu 14.3.0 Darwin Kernel Version 14.3.0: Wed Apr  8 03:17:44 PDT 2015; root:xnu-2782.20.48~13/RELEASE_X86_64 x86_64

See discussion on stackoverflow: http://stackoverflow.com/questions/29767040/cannot-create-a-grails-project-by-calling-grails-create-app-projectname

**Comment by graemerocher** [comment]
There appear to be 2 conflicting versions of snakeyml on your classpath for some reason, probably an environment specific issue. You can maybe debug this by using:

      export GRAILS_OPTS=-verbose

And monitoring the class loading to see where and which version of snakeyml is being loaded.
