### ISSUE TITLE
Grails 2.5.0: Running H2 in prod mode results in Feature not supported: "isWrapperFor"

### ISSUE THREAD

**Issue by zaccak** [grails/grails-core#700]
When running an app in prod mode using H2 on G2.5.0 it fills up the db.trace file with constant errors:

05-12 07:56:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Feature not supported: "isWrapperFor" [50100-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:215)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:395)
	at org.h2.jdbc.JdbcStatement.isWrapperFor(JdbcStatement.java:1076)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.isTypeOf(ResultSetReturnImpl.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2066)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1863)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839)
	at org.hibernate.loader.Loader.doQuery(Loader.java:910)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
	at org.hibernate.loader.Loader.doList(Loader.java:2554)
	at org.hibernate.loader.Loader.doList(Loader.java:2540)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
	at org.hibernate.loader.Loader.list(Loader.java:2365)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:126)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1682)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)
	at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:402)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormStaticApi$3.doInHibernate(HibernateGormStaticApi.groovy:239)
	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:188)
	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:132)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormStaticApi.count(HibernateGormStaticApi.groovy:234)
	at allerganfis.Settings.count(Settings.groovy)
	at allerganfis.Settings$count.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
	at BootStrap$_closure1.doCall(BootStrap.groovy:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1121)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1121)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I've tried to downgrade the H2 version to the previous to this and the same errors occur. I've tried to upgrade to the latest H2 (beta) and a different error occurs.

**Comment by zaccak** [comment]
This looks like the same issue:
https://github.com/rundeck/rundeck/issues/1175

**Comment by gschueler** [comment]
I think this is only an issue using hibernate 4 with h2 1.3, so upgrading h2, or use hibernate3 might solve it

**Comment by zaccak** [comment]
I've downgraded and upgraded H2 and still it happens. I was hoping to stay on Hibernate4 but looks like I might have to downgrade.

**Comment by gschueler** [comment]
I did test using h2 1.4.187, and it seemed to fix the issue for me

**Comment by zaccak** [comment]
You are correct, once I fix the absolute path, H2 1.4.187 beta seems to resolve the issue.
