### ISSUE TITLE
NPE when running profile commands behind a proxy

### ISSUE THREAD

**Issue by andmart** [grails/grails-core#704]
grails -version
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_45

WINDOWS 7

grails create_app tarefas --stacktrace

Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this releas
e.
Usage:
         create-app [NAME] --profile=web
         create-plugin [NAME] --profile=web-plugin

| Error Error occurred running Grails CLI: null (NOTE: Stack trace has been filt
ered. Use --verbose to see entire trace.)
java.lang.NullPointerException
        at org.grails.cli.profile.git.GitProfileRepository.getAllProfiles(GitPro
fileRepository.groovy:72)
        at org.grails.cli.profile.commands.ListProfilesCommand.handle(ListProfil
esCommand.groovy:43)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:173)
        at org.grails.cli.GrailsCli.getBaseUsage(GrailsCli.groovy:118)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:177)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Error occurred running Grails CLI: null

**Comment by graemerocher** [comment]
Probably related to your proxy configuration, have you correctly configured your proxy?

**Comment by andmart** [comment]
I had to configure ~/.grail/ProxySettings.groovy manually like this:


    currentProxy='myproxy'
    myproxy=["http.proxyHost":"localhost", "http.proxyPort":"3128"]

because, 

    grails add-proxy "myproxy" "--host=localhost" "--port=3128"

gives following error

| Error Error occurred running Grails CLI: null (NOTE: Stack trace has been filt
ered. Use --verbose to see entire trace.)
java.lang.NullPointerException
        at org.grails.cli.profile.git.GitProfileRepository.getAllProfiles(GitPro
fileRepository.groovy:72)
        at org.grails.cli.profile.commands.ListProfilesCommand.handle(ListProfil
esCommand.groovy:43)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:173)
        at org.grails.cli.GrailsCli.getBaseUsage(GrailsCli.groovy:118)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:177)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Error occurred running Grails CLI: null

**Comment by graemerocher** [comment]
Duplicates #594
