### ISSUE TITLE
Grails 3.0.1 Error executing tag <f:all>

### ISSUE THREAD

**Issue by bodiam** [grails/grails-core#711]
In Grails 3.0.1, I have a domain class like this:

    import java.time.LocalDate
    class Person {
         LocalDate birthDate
    }

When I do a generate-all, run the app, and try to create a new instance of the person, the following error occurs:

````
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/conference/create.gsp:35] Error executing tag <g:form>: [views/conference/create.gsp:30] Error executing tag <f:all>: null] with root cause
java.lang.NullPointerException: null
	at grails.plugin.formfields.FormFieldsTagLib$_renderDefaultField_closure13.doCall(FormFieldsTagLib.groovy:370) ~[fields-2.0.1.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib.renderDefaultField(FormFieldsTagLib.groovy:363) ~[fields-2.0.1.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib$_closure3.doCall(FormFieldsTagLib.groovy:133) ~[fields-2.0.1.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib$_closure2.doCall(FormFieldsTagLib.groovy:79) ~[fields-2.0.1.jar:na]
	at Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp$_run_closure2$_closure24.doCall(Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp:73) ~[na:na]
	at Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp$_run_closure2.doCall(Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp:78) ~[na:na]
	at Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp.run(Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp:81) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
````

**Comment by jeffbrown** [comment]
We can fix this for `java.time.LocalDate` in particular but more generally we should decide how to handle property types that are not recognized.  We could throw an exception that describes the problem.  Maybe a better idea is to log a warning and just generate a text input field.

**Comment by bodiam** [comment]
Well, an error like: could not find custom template "/templates/_LocalDate.gsp" or something would already be much better than the current approach. However, the same is true for List<String>, which I assumed would be supported (since it is in the DB mapping), but it seems not like it.

**Comment by graemerocher** [comment]
Duplicates #8982

**Comment by graemerocher** [comment]
I pushed a fix for the NPE here https://github.com/grails3-plugins/fields/commit/e042dee24253b3029075e664dba2127b0e590d58

It now just doesn't render anything if no widget is found, as for `List` being supported, a list of primitive types has never been supported, in fact your example fails with Hibernate (I assume you are using MongoDB) with a mapping exception.

**Comment by bodiam** [comment]
Hi Graeme, I'm not sure why this would be a mapping exception. In my Spring Boot application I have a similar approach, and it works there. I'm not sure what Grails does different to create a mapping exception.

**Comment by graemerocher** [comment]
I was actually referring to the example in #8982 where you define a List which is not a supported type for mapping in Hibernate (you get an unmapped type exception) and yes this would happen in Spring Boot as well. I'm not sure why the topic of Boot is being raised, since this about the fields plugin as far as I understood, which doesn't exist for Boot.

**Comment by bodiam** [comment]
This bug was about the LocalDate not being rendered. 
You said it would my example fails with a mapping exception. 
I have the same mapping in Spring Boot, which doesn't fail.

I'm not sure why we talk here about a code example from #8982 , that's a bit confusing to me.
