### ISSUE TITLE
Grails 3.0.1 doesn't start

### ISSUE THREAD

**Issue by bodiam** [grails/grails-core#714]
When trying to run `java -jar name-of-war.war`, I get the following error on my Linux machine:

````
erikp@manyconf:~$ java -Dgrails.env=prod -jar grails-admin-0.1.war
ERROR grails.boot.GrailsApp - Application startup failed
java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    grails/web/mime/MimeType.<init>(Ljava/lang/String;)V @119: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 05bd 0004 5903 2b12 4fb8 009c 5359 0403
    0x0000010: bd00 04b8 003d c000 8e12 8eb8 009c 5359
    0x0000020: 10ff 1202 b800 a02a 5fab 0000 0000 00a3
    0x0000030: 0000 0004 a159 6e5c 0000 002b aad3 b1ff
    0x0000040: 0000 0054 b7d2 0ba6 0000 0067 e925 fa09
    0x0000050: 0000 0086 5f5a 5903 32b8 006d c000 4f5f
    0x0000060: 5904 32b8 006d c000 4f5f 5905 3212 8eb8
    0x0000070: 005d c000 8e5f 57b7 002e a700 5c5f 5a59
    0x0000080: 0332 b800 6dc0 004f 5f57 b700 a2a7 0049
    0x0000090: 5f5a 5903 32b8 006d c000 4f5f 5904 3212
    0x00000a0: 8eb8 005d c000 8e5f 57b7 00a4 a700 2a5f
    0x00000b0: 5a59 0332 b800 6dc0 004f 5f59 0432 b800
    0x00000c0: 6dc0 004f 5f57 b700 a7a7 000d bb00 a959
    0x00000d0: 12ab b700 acbf 57b1
  Stackmap Table:
    full_frame(@84,{UninitializedThis,Object[#79]},{Object[#89],UninitializedThis})
    full_frame(@125,{UninitializedThis,Object[#79]},{Object[#89],UninitializedThis})
    full_frame(@144,{UninitializedThis,Object[#79]},{Object[#89],UninitializedThis})
    full_frame(@175,{UninitializedThis,Object[#79]},{Object[#89],UninitializedThis})
    full_frame(@204,{UninitializedThis,Object[#79]},{Object[#89],UninitializedThis})
    full_frame(@214,{Object[#2],Object[#79]},{Object[#89]})

	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:1.8.0_20]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658) ~[na:1.8.0_20]
	at java.lang.Class.getDeclaredConstructors(Class.java:2007) ~[na:1.8.0_20]
	at org.codehaus.groovy.reflection.CachedClass$2$1.run(CachedClass.java:71) ~[groovy-2.4.3.jar!/:2.4.3]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_20]
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:68) ~[groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66) ~[groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46) ~[groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33) ~[groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:265) ~[groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:215) ~[groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:225) ~[groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:168) ~[groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:158) ~[groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:141) ~[groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:250) ~[groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:282) ~[groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.<init>(ClassMetaClassGetPropertySite.java:35) ~[groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createClassMetaClassGetPropertySite(AbstractCallSite.java:370) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGetPropertySite(AbstractCallSite.java:322) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.acceptGetProperty(AbstractCallSite.java:309) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:293) [groovy-2.4.3.jar!/:2.4.3]
	at org.grails.plugins.web.mime.MimeTypesGrailsPlugin$_doWithSpring_closure1.doCall(MimeTypesGrailsPlugin.groovy:39) ~[grails-plugin-mimetypes-3.0.1.jar!/:3.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) ~[groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) ~[groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.Closure.call(Closure.java:423) ~[groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.Closure.call(Closure.java:417) ~[groovy-2.4.3.jar!/:2.4.3]
	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:754) ~[grails-spring-3.0.1.jar!/:3.0.1]
	at grails.spring.BeanBuilder.beans(BeanBuilder.java:584) ~[grails-spring-3.0.1.jar!/:3.0.1]
	at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:527) ~[grails-spring-3.0.1.jar!/:3.0.1]
	at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:548) ~[grails-core-3.0.1.jar!/:3.0.1]
	at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:172) ~[grails-core-3.0.1.jar!/:3.0.1]
	at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:142) ~[grails-core-3.0.1.jar!/:3.0.1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:119) ~[spring-context-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606) ~[spring-context-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462) ~[spring-context-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) ~[spring-boot-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:49) [grails-core-3.0.1.jar!/:3.0.1]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:254) [grails-core-3.0.1.jar!/:3.0.1]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:243) [grails-core-3.0.1.jar!/:3.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-2.4.3.jar!/:2.4.3]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) [groovy-2.4.3.jar!/:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122) [groovy-2.4.3.jar!/:2.4.3]
	at grails.admin.Application.main(Application.groovy:8) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [grails-admin-0.1.war:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.VerifyError: Bad <init> method call from inside of a branch
````

Java version:

````
erikp@manyconf:~$ java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
````

Same as this issue, but that one is solved: https://github.com/grails/grails-core/issues/608

**Comment by bodiam** [comment]
This workaround works (for me):

`java -noverify -jar name-of-war.war`

**Comment by graemerocher** [comment]
Probably an issue with the JDK you are using otherwise a Groovy bug, please report in the Groovy issue tracker

**Comment by bodiam** [comment]
Hi Graeme,

I upgraded my JVM (thought I was already on the newest, but I needed to add a custom PPA repository), but running on 1.8.0_45 now, and that works, also without `-noverify`.
