### ISSUE TITLE
grails 2.4.5 FileSystemWatcher Exceptions

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#722]
After upgrading to Grails 2.4.5 (from 2.3.8) I started seing the following exceptions after each change I made when hot reloading kicks in.
An exception like below is thrown for each Filter I have and for each changelog I have in grails-app/migrations directory.
The hot reload appears to be working fine but getting all those exception each time is an issue.

I've worked the problem around by moving the migrations directory out of the grails-app directory. 
As for the filters I had a slightly different setup. All the filter classes were stored under a directory which name was `com.comp.filters`. After breaking the directory name into proper sub-directories structure the problem went away.

Similar issue here: https://jira.grails.org/browse/GRAILS-10134

OS: Linux
JAVA: OpenJDK 1.7.0_79
IDE: Intellij IDEA 14.0.3
GRAILS: 2.4.5

```
2015-05-27 10:02:12,767 [Thread-15] INFO  compiler.GrailsProjectWatcher  - File [/home/user/comp/proj/grails-app/controllers/com/comp/controller/test/DevController.groovy] added. Applying changes to application.
......
|Compiling 42 source files
  [groovyc] Compiling 42 source files to /home/user/comp/proj/target/classes
2015-05-27 10:02:26,581 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "changelog-1/4-api$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,583 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "changelog-1/4-fixed-tags$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,585 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "changelog-1/4$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
................
................
................
................
	2015-05-27 10:02:26,824 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "com/comp/filters/SecurityFilters$_closure1_closure4_closure8$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,825 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "com/comp/filters/SecurityFilters$_closure1_closure5$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,827 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "com/comp/filters/SecurityFilters$_closure1_closure5_closure9$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,829 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "com/comp/filters/SecurityFilters$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,830 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "com/comp/filters/SentryFilters$_closure1$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,832 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "com/comp/filters/SentryFilters$_closure1_closure2$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,833 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "com/comp/filters/SentryFilters$_closure1_closure2_closure3$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
2015-05-27 10:02:26,835 [FileSystemWatcher: files=#1641 cl=java.net.URLClassLoader@80b4d4d] ERROR agent.Watcher  - FileWatcher caught serious error, see cause
java.lang.LinkageError: loader (instance of  org/springsource/loaded/ChildClassLoader): attempted  duplicate class definition for name: "com/comp/filters/SentryFilters$$DPDs0qvI"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:37)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1116)
	at org.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:111)
	at org.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:99)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:396)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by graemerocher** [comment]
but upload an example to github with steps to reproduce and provide information regarding your JDK, OS, and environment

**Comment by hugoriar** [comment]
Solution that works for me:

1) Versions:
IDE: Intellij IDEA 14.1.3
JDK: jdk1.7.0_25
GRAILS: 2.5.0 

2) On BuildConfig.groovy: 
grails.reload.enabled = true
grails.project.fork = [
        test: false,
        run: false,
]

3) Originally, my code was compiled on grails 2.4.4, so I upgraded to 2.5.0. I had no problems with the version change with plugins or anything. My guess is this works because it uses later versions of spring-loaded. Steps:
3.1) set-grails-version 2.5.0
3.2) clean
3.3) delete directory work (just to be sure, I don't really know if this is good practice)
3.4) compile and/or go to number 4

4) Debug Idea with this configuration: run-app -reloading

------------------------------------------------------------------------------------------

Works perfect, no forked debug, reloading enabled, no console error after reload and all breakpoints working even after code changes!

Hope this helps anyone, I can extend my answer if you need more help.

**Comment by graemerocher** [comment]
Closing due to lack of feedback
