### ISSUE TITLE
Grails 2.5: Cannot run any grails command on a grails plugin w/ compile 'org.jaitools:jt-utils:1.3.1' in BuildConfig.groovy, results in java.lang.NoSuchFieldError: fRecognizedFeatures

### ISSUE THREAD

**Issue by ikakara** [grails/grails-core#8966]
Environment:
----------------------------
Windows 8.1
Oracle JDK 8u45
Grails 2.5

To reproduce:
-----------------------------
> grails create-plugin any-name 
Update BuildConfig.groovy w/

```
  dependencies {
    compile 'org.jaitools:jt-utils:1.3.1' // this works w/ a grails app, but not w/ grails plugin

    compile ('org.jaitools:jt-utils:1.3.1') { // this doesn't work either
      excludes "xerces" // I've tried excluding potential conflicting dependencies
    }
  }
```
> grails clean

Entire Error:
------------------------------
| Error Error executing script Clean: fRecognizedFeatures (NOTE: Stack trace has been filtered. Use --verbose to see ent
ire trace.)
java.lang.NoSuchFieldError: fRecognizedFeatures
        at org.apache.xerces.parsers.BasicParserConfiguration.<init>(Unknown Source)
        at org.apache.xerces.parsers.DTDConfiguration.<init>(Unknown Source)
        at org.apache.xerces.parsers.StandardParserConfiguration.<init>(Unknown Source)
        at org.apache.xerces.parsers.IntegratedParserConfiguration.<init>(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.<init>(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.<init>(Unknown Source)
        at org.apache.xerces.util.ObjectFactory.newInstance(Unknown Source)
        at org.apache.xerces.util.ObjectFactory.findJarServiceProvider(Unknown Source)
        at org.apache.xerces.util.ObjectFactory.createObject(Unknown Source)
        at org.apache.xerces.util.ObjectFactory.createObject(Unknown Source)
        at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
        at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParser(Unknown Source)
        at org.apache.tools.ant.util.JAXPUtils.newSAXParser(JAXPUtils.java:215)
        at org.apache.tools.ant.util.JAXPUtils.getNamespaceXMLReader(JAXPUtils.java:172)
        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:273)
        at org.apache.tools.ant.helper.ProjectHelper2.parseUnknownElement(ProjectHelper2.java:131)
        at org.apache.tools.ant.helper.ProjectHelper2.parseAntlibDescriptor(ProjectHelper2.java:111)
        at org.apache.tools.ant.taskdefs.Antlib.createAntlib(Antlib.java:91)
        at org.apache.tools.ant.taskdefs.Definer.loadAntlib(Definer.java:440)
        at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:292)
        at org.apache.tools.ant.ComponentHelper.checkNamespace(ComponentHelper.java:877)
        at org.apache.tools.ant.ComponentHelper.getDefinition(ComponentHelper.java:308)
        at org.apache.tools.ant.ComponentHelper.createComponent(ComponentHelper.java:285)
        at org.apache.tools.ant.ComponentHelper.createComponent(ComponentHelper.java:264)
        at org.apache.tools.ant.UnknownElement.makeObject(UnknownElement.java:417)
        at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:163)
        at org.codehaus.gant.GantBuilder.invokeMethod(GantBuilder.java:99)
        at org.codehaus.gant.GantBinding.initializeGantBinding(GantBinding.groovy:108)
        at org.codehaus.gant.GantBinding.<init>(GantBinding.groovy:42)
| Error Error executing script Clean: fRecognizedFeatures

**Comment by ikakara** [comment]
Maybe related to https://github.com/grails/grails-core/issues/8817

**Comment by jeffbrown** [comment]
Instead of `excludes "xerces"`, I think `excludes "xercesImpl"` probably makes the problem go away.  That isn't a fix, but may be a workaround pending a real fix.

There are a lot of reports of this problem out there in different contexts.  Googling for `fRecognizedFeatures` finds a lot of them.

**Comment by ikakara** [comment]
Thanks Jeff!  That worked ...
```
    compile ('org.jaitools:jt-utils:1.3.1') {
      excludes "xercesImpl"
    }
```
