### ISSUE TITLE
Error on install-templates script

### ISSUE THREAD

**Issue by rserranon** [grails/grails-core#8970]
## Grails 3.0.1

**This is the error I get when calling the script:**
grails> install-templates
| Copying fields templates
| Error Caught exception /Users/proyectoweb/Documents/RSN/grails_apps/vivanyServer/src/templates/scaffolding (No such file or directory) (Use --stacktrace to see the full trace)

**Here is the call with --stacktrace:**
grails> install-templates --stacktrace
| Copying fields templates
| Error Caught exception /Users/proyectoweb/Documents/RSN/grails_apps/vivanyServer/src/templates/scaffolding (No such file or directory) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.io.FileNotFoundException: /Users/proyectoweb/Documents/RSN/grails_apps/vivanyServer/src/templates/scaffolding (No such file or directory)
	at org.grails.io.support.SpringIOUtils.copy(SpringIOUtils.java:175)
	at org.grails.cli.profile.commands.io.FileSystemInteractionImpl.copy(FileSystemInteractionImpl.groovy:142)
	at org.grails.cli.profile.commands.io.FileSystemInteractionImpl.copyAll(FileSystemInteractionImpl.groovy:123)
	at org.grails.cli.profile.commands.io.FileSystemInteractionImpl.copy(FileSystemInteractionImpl.groovy:90)
	at org.grails.cli.profile.commands.io.FileSystemInteractionImpl.copy(FileSystemInteractionImpl.groovy)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.copy(GroovyScriptCommand.groovy:57)
	at org.grails.cli.profile.commands.io.FileSystemInteraction$copy.callCurrent(Unknown Source)
	at InstallTemplates.run(InstallTemplates.groovy:20)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:146)
	at org.grails.cli.profile.DefaultProfile.handleCommand(DefaultProfile.groovy:177)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:235)
	at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure4.doCall(GrailsCli.groovy:305)
	at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure4.call(GrailsCli.groovy)
| Error Caught exception /Users/proyectoweb/Documents/RSN/grails_apps/vivanyServer/src/templates/scaffolding (No such file or directory)

**Comment by graemerocher** [comment]
A workaround is the make the directory manually before running the command:

   $ mkdir -p src/templates/scaffolding
