### ISSUE TITLE
"No Session found for current thread" in Interceptor

### ISSUE THREAD

**Issue by cedWetzel** [grails/grails-core#8975]
I have created an Interceptor for handling my security. 
Checking the session attributes causes the following error:

ERROR org.grails.web.errors.GrailsExceptionResolver - HibernateException occurred when processing request: [GET] /auth
No Session found for current thread. Stacktrace follows:
org.hibernate.HibernateException: No Session found for current thread
	at grails.web.mapping.ResponseRedirector.redirectResponse(ResponseRedirector.groovy:101) ~[grails-web-url-mappings-3.0.1.jar:3.0.1]
	at grails.web.mapping.ResponseRedirector.redirect(ResponseRedirector.groovy:79) ~[grails-web-url-mappings-3.0.1.jar:3.0.1]
	at grails.artefact.controller.support.ResponseRedirector$Trait$Helper.redirect(ResponseRedirector.groovy:119) ~[grails-plugin-controllers-3.0.1.jar:3.0.1]
	at myserver.SecurityInterceptor$$EPEM6YBE.before(SecurityInterceptor.groovy:12) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_67]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_67]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]

This is my Interceptor:

class SecurityInterceptor {

    SecurityInterceptor() {
        matchAll().excludes(namespace: 'v1')
    }

    boolean before() {
        if (!session.user) {
            redirect(controller: 'auth')
            false
        }
        true
    }

    boolean after() { true }

    void afterView() {
        // no-op
    }

Checking the session in my controller works fine. 
I am using Grails 3.0.1

**Comment by zyro23** [comment]
related/possible duplicate: #600
