### ISSUE TITLE
StackOverflow when extending a class that extends restfulcontroller

### ISSUE THREAD

**Issue by mtj8033** [grails/grails-core#9005]
Followed the suggestion from here:

https://jira.grails.org/browse/GRAILS-11958

but still hitting an error. Setup is as follows:
```
class BasicFilteringRestfulController<DT> extends RestfulController<DT> {

    BasicFilteringRestfulController(Class resource) {
        super(resource, false)
        println "Inside constructor class"
    }

    BasicFilteringRestfulController(Class resource, boolean readOnly) {
        super(resource,readOnly)
    }

    @Override
    def index(Integer max) {
          ...
    }

    def save() {
       ....
    }
}
```
Then my actual controllers extend that, this one gets no errors (note i had to change def index(Integer max) to public Object index()) :
```
class FormFieldController extends BasicFilteringRestfulController<FormField> {
    static responseFormats = ['json', 'xml']
    FormFieldController() {
        super(FormField)
    }

    @Override
    public Object index() {
        log.debug("Index params: "+ params)
        JSON.use('deep')
        // TODO Auto-generated method stub
        return super.index()
    }
}
```
however this one hits a stackoverflow:

```
    def index(Integer max) {
        println "HERE"
        JSON.use('deep')
        // TODO Auto-generated method stub
        return super.index()
    }
```
	at grails.rest.RestfulController.$tt__index(RestfulController.groovy)
	at com.thomsonreuters.formauthoring.rest.BasicFilteringRestfulController.$tt__index(BasicFilteringRestfulController.groovy)
	at com.thomsonreuters.formauthoring.backend.FormFieldTypeController.$tt__index(FormFieldTypeController.groovy)
	at grails.rest.RestfulController$_index_closure10.doCall(RestfulController.groovy)
	at sun.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1121)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:90)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:87)
	at grails.rest.RestfulController.index(RestfulController.groovy)
	at com.thomsonreuters.formauthoring.rest.BasicFilteringRestfulController.index(BasicFilteringRestfulController.groovy)
	at com.thomsonreuters.formauthoring.backend.FormFieldTypeController.super$2$index(FormFieldTypeController.groovy)
	at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)

**Comment by jeffbrown** [comment]
I haven't tested this but I may know what is going wrong here.

When you write an action like this:

    def index(Integer max) {
        // your code goes here
    }

The compiler generates code as if you had written something like this:

    def index() {
        index(params.int('max'))
    }

    def index(Integer max) {
        // your code goes here
    }

So in your subclass when you call `super.index()` from the subclass' `def index(Integer max)` you are calling a method in the parent class that is going to in turn invoke your `def index(Integer max)` method so that will go on until the stack is overflown.
    
Instead of this...

    def index(Integer max) {
        println "HERE"
        JSON.use('deep')
        // TODO Auto-generated method stub
        return super.index()
    }

Can you do this?...

def index(Integer max) {
        println "HERE"
        JSON.use('deep')
        // TODO Auto-generated method stub
        return super.index(max)
    }

**Comment by jeffbrown** [comment]
I have built a simple test and verified what I suspected.

    class BasicFilteringRestfulController {

        def index(Integer max) {
            render 'BasicFilteringRestfulController.index(Integer)'
        }
    }

    class FormFieldController extends BasicFilteringRestfulController {

        def index(Integer max) {
            // this will overflow the stack...
            super.index()

            // this works...
            super.index(max)
        }
    }

@mtj8033 Can you please confirm that you see the same?

**Comment by mtj8033** [comment]
Yep that was it, thanks!
