### ISSUE TITLE
GORM HQL query fails when referencing ENUMS

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#9053]
This query doesn't work:
```java
Person.findAll("""
        FROM Person p
        WHERE p.deactivated = false
        AND p.role = :role
    """,
            [role: Role.BASIC]
)

```

Error:
```java
ERROR org.grails.web.errors.GrailsExceptionResolver - GrailsQueryException occurred when processing request: [GET] /person/index
Invalid query [
            FROM Person p
            WHERE p.deactivated = false
            AND p.role = :role
        ] for domain class [hqlerror.Person]. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: org.grails.orm.hibernate.exceptions.GrailsQueryException: Invalid query [
            FROM Person p
            WHERE p.deactivated = false
            AND p.role = :role
        ] for domain class [hqlerror.Person]
        at hqlerror.PersonController.index(PersonController.groovy:10) ~[main/:na]
        ... 3 common frames omitted

```

The same error with a List of enums
```java
Person.findAll("""
        FROM Person p
        WHERE p.deactivated = false
        AND p.role IN (:roles)
    """,
            [roles: [Role.BASIC, Role.MANAGER]]
)  
```

Using findAllBy* works fine though

```java
Person.findAllByDeactivatedAndRole(false, Role.BASIC)
Person.findAllByDeactivatedAndRoleInList(
        false, 
        [Role.BASIC, Role.MANAGER]
)   
```

I've created an example here: https://github.com/olavgg/hqlerror

**Comment by driverpt** [comment]
The error you're getting has nothing to do with the queries. I just cloned your project and if i put the queries in a simple single-line String, they work properly.

This is related to a very old issue with Multi-line Strings as you can see here https://jira.grails.org/browse/GRAILS-10313

**Comment by graemerocher** [comment]
@driverpt Thanks for verifying this

**Comment by driverpt** [comment]
@graemerocher I created a [pull request](https://github.com/grails/grails-data-mapping/pull/544) that addresses this issue.
