### ISSUE TITLE
Problem with Database Migration Plugin after upgrade to grails 2.5.0

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#9061]
This is a bug submission based on a post I've created some time but never got any response. I've prepared an example project where I can reproduce the error I'm getting (https://groups.google.com/forum/#!topic/grails-dev-discuss/a8ZIb5-EGJQ)

To reproduce:
```
git clone git@github.com:jglapa/grails-bug-projects.git
cd grails-bug-projects/grails250-dbMigration-plugin-bug/
gvm u grails 2.4.5
grails clean-all
grails compile
grails dbm-status --plain-output
--all good you should see the list of changesets to applye

gvm u grails 2.5.0
grails set-grails-version 2.5.0
grails clean-all
grails compile
grails dbm-status --plain-output
--fails
```

Pasting the content here:

I'm not really sure if the problem is with Grails 2.5, DB Migration Plugin(1.3.8) or with Groovy 2.4.

I initially wanted to upgrade from grails 2.3.6 to 2.5.0 directly but because of this problem I managed to upgrade only to 2.4.5 (nothing like below happens on 2.4.5)

I'm getting the following exception upon start:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplication' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is org.codehaus.groovy.grails.exceptions.GrailsConfigurationException: Class not found loading Grails application: changelog-1.1
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:736)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:71)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
........
Caused by: org.codehaus.groovy.grails.exceptions.GrailsConfigurationException: Class not found loading Grails application: changelog-1.1
	at org.codehaus.groovy.grails.commons.DefaultGrailsApplication.<init>(DefaultGrailsApplication.java:126)
	at org.codehaus.groovy.grails.commons.GrailsApplicationFactoryBean.afterPropertiesSet(GrailsApplicationFactoryBean.java:99)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1625)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
	... 22 more
Caused by: java.lang.ClassNotFoundException: changelog-1.1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:676)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:786)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:774)
	at org.codehaus.groovy.grails.commons.DefaultGrailsApplication.<init>(DefaultGrailsApplication.java:124)
	... 25 more
```

my changelog files look like that:
>ls grails-app/migrations
...
changelog.groovy
changelog-0.9.3.groovy
changelog-0.9.8.groovy
changelog-1.0.groovy
changelog-1.1.groovy
...

There's nothing special about changelog-1.1.groovy. if I remove it a I'm getting similar exception for a different changelog file.

So I had a look at the target/classes folder and it turns out that between releases the changelog classes are compiled differently:
2.3.6 and 2.4.5:
```
>ls target/classes | grep changelog
...
changelog-0/
changelog-1/
changelog.class
changelog$_run_closure1.class
changelog$_run_closure1_closure2.class
initial-changelog.class
...
```

```
>ls target/classes/changelog-0/
...
0.class
0$_run_closure1.class
0$_run_closure1_closure10.class
0$_run_closure1_closure10_closure16.class
0$_run_closure1_closure2.class
0$_run_closure1_closure2_closure11.class
0$_run_closure1_closure3.class
...
```

2.5.0:
```
>ls target/classes | grep changelog
.....
changelog-1_0.class
changelog-1_0$_run_closure1.class
changelog-1_0$_run_closure1$_closure10.class
changelog-1_0$_run_closure1$_closure9.class
changelog-1_1.class
changelog-1_1$_run_closure1.class
changelog-1_1$_run_closure1$_closure3$_closure6.class
...
```

Looks like a dot in a class name in version prior to 2.5.0 caused a directory to be created so changelog-1.0.groovy is changelog_1/1.class (also dash is converted to underscore)
In grails 2.5.0 dots are converted to underscores: changelog-1.0.groovy becomes changelog-1_0.class (dash stays as it is)

Where is the issue then?
* groovy 2.4 compiles classes differently (grails or db migration plugin doesn't know how to load them?
* grails 2.5.0
* db migration plugin (1.3.8, I'm using hibernate 3)

OpenJDK1.7
Ubuntu 14.10

Thanks,
Jakub

**Comment by ClemensSchneider** [comment]
I ran into a similar issue and I resolved it by using valid class-names for my changelog-scripts. A dot (as contained in 'changelog-1.0.groovy') is not a valid part of a Java classname and thus should not be used when naming groovy-scripts.

So replace 'changelog-1.0.groovy' -> 'changelog-1_0.groovy' and you should be fine (except that liquibase now tries to re-apply the contained changes because the script-name is part of the changelog-entries checksum).

**Comment by jglapa** [comment]
Yes databasechangelog filename column would need to get manually updated and probably the md5sum would have to be reset:/

So the `.` was handled incorrectly so far? I think I started versioning this changesets in this manner b/c of the dbmigration plugin documentation (http://grails-plugins.github.io/grails-database-migration/docs/manual/guide/gettingStarted.html#autobase)

**Comment by ClemensSchneider** [comment]
Seems like the Groovy-Compiler changed its behavior when converting script-names to class-names. I think it should be updated accordingly in the database-migration docs. @burtbeckwith ?

**Comment by zaccak** [comment]
That workaround to change the . to _ doesn't work because it will try and run the old scripts on the DB again.

**Comment by ClemensSchneider** [comment]
You could try to mark all changes as run via `dbm-changelog-sync`?
