### ISSUE TITLE
grails doc command not found in Grails 3.0.2

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-core#9067]
I was trying to use grails doc command and got this
```
| Error Command not found doc
Did you mean: create-domain-class?
```

Has this command been removed? Or the syntax been changed? 

Also where is the source for the commands? So that I can lookup that in the future before raising a bug.

**Comment by graemerocher** [comment]
You have to apply a Gradle plugin now:

     apply plugin: "org.grails.grails-doc"

Then run

     gradle docs

**Comment by anshbansal** [comment]
Is there anything else that needs to be done? I added that plugin and got a NoClassDef error
```
18:13:23.504 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'itext.jar (com.lowagie:itext:2.0.8)' in resolver cache: /home/aseem/.gradle/caches/modules-2/files-2.1/com.lowagie/itext/2.0.8/3734dd08e513c321d2121f2b3a7498300c596fe3/itext-2.0.8.jar
18:13:23.505 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'jcl-over-slf4j.jar (org.slf4j:jcl-over-slf4j:1.7.10)' in resolver cache: /home/aseem/.gradle/caches/modules-2/files-2.1/org.slf4j/jcl-over-slf4j/1.7.10/ce49a188721bc39cb9710b346ae9b7ec27b0f36b/jcl-over-slf4j-1.7.10.jar
18:13:23.506 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'grails-gdoc-engine.jar (org.grails:grails-gdoc-engine:1.0.1)' in resolver cache: /home/aseem/.gradle/caches/modules-2/files-2.1/org.grails/grails-gdoc-engine/1.0.1/9233083da1943dcffdc20dc87f7ac821d82ee51f/grails-gdoc-engine-1.0.1.jar
18:13:23.507 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'core-renderer.jar (org.xhtmlrenderer:core-renderer:R8)' in resolver cache: /home/aseem/.gradle/caches/modules-2/files-2.1/org.xhtmlrenderer/core-renderer/R8/88e6306a7c88e3c3082ae548999025cb14002f1/core-renderer-R8.jar
18:13:23.507 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'jsoup.jar (org.jsoup:jsoup:1.7.3)' in resolver cache: /home/aseem/.gradle/caches/modules-2/files-2.1/org.jsoup/jsoup/1.7.3/92568d7167ce1bf9eb1fd815b022d5a2c113547a/jsoup-1.7.3.jar
18:13:23.508 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'bcmail-jdk14.jar (bouncycastle:bcmail-jdk14:138)' in resolver cache: /home/aseem/.gradle/caches/modules-2/files-2.1/bouncycastle/bcmail-jdk14/138/14ff2dfec8578f5f6838c4d6a77a86789afe5382/bcmail-jdk14-138.jar
18:13:23.510 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'bcprov-jdk14.jar (bouncycastle:bcprov-jdk14:138)' in resolver cache: /home/aseem/.gradle/caches/modules-2/files-2.1/bouncycastle/bcprov-jdk14/138/de366c3243a586eb3c0e2bcde1ed9bb1bfb985ff/bcprov-jdk14-138.jar
18:13:23.511 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'slf4j-api.jar (org.slf4j:slf4j-api:1.7.10)' in resolver cache: /home/aseem/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.10/5b338f206827d88acd890739f400a9b7664e5984/slf4j-api-1.7.10.jar
18:13:23.525 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':docs' (up-to-date check took 0.25 secs) due to:
  No history is available.
18:13:23.526 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':docs'.
18:13:25.254 [ERROR] [system.err] Failed to instantiate SLF4J LoggerFactory
18:13:25.256 [ERROR] [system.err] Reported exception:
18:13:25.257 [ERROR] [system.err] java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
18:13:25.257 [ERROR] [system.err] 	at java.lang.ClassLoader.defineClass1(Native Method)
18:13:25.258 [ERROR] [system.err] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
18:13:25.258 [ERROR] [system.err] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
18:13:25.259 [ERROR] [system.err] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
18:13:25.259 [ERROR] [system.err] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
18:13:25.259 [ERROR] [system.err] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
18:13:25.259 [ERROR] [system.err] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
18:13:25.260 [ERROR] [system.err] 	at java.security.AccessController.doPrivileged(Native Method)
18:13:25.260 [ERROR] [system.err] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
18:13:25.260 [ERROR] [system.err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
18:13:25.260 [ERROR] [system.err] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
18:13:25.261 [ERROR] [system.err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
```

**Comment by droggo** [comment]
@anshbansal did you solve problem with `NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder` ? A can generate documentation using `gradlew docs` but not using `gradle docs` although both have the same version
