### ISSUE TITLE
Integration tests fail with an IllegalStateException in grails 3.0.2

### ISSUE THREAD

**Issue by tony75** [grails/grails-core#9072]
Hi,

When running the integration tests, I get the following exception : 
```
java.lang.IllegalStateException: Method on class [User] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
java.lang.RuntimeException: java.lang.IllegalStateException: Method on class [User] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
	at org.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:111)
	at AnnotationMarshallerSpec.toJsonAndBack(AnnotationMarshallerSpec.groovy:22)
	at AnnotationMarshallerSpec.Marshaller should serialize properties explicitly belonging to the requested API(AnnotationMarshallerSpec.groovy:30)
Caused by: java.lang.IllegalStateException: Method on class [User] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.currentGormInstanceApi(GormEntity.groovy:52)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.ident(GormEntity.groovy:172)
	at json.annotations.marshaller.AnnotationMarshaller.marshalObject_closure3(AnnotationMarshaller.groovy:79)
	at json.annotations.marshaller.AnnotationMarshaller.marshalObject_closure3(AnnotationMarshaller.groovy)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:143)
	at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:64)
	at grails.converters.JSON$Builder.execute(JSON.java:488)
	at grails.converters.JSON.build(JSON.java:166)
	at json.annotations.marshaller.AnnotationMarshaller.marshalObject(AnnotationMarshaller.groovy:78)
	at grails.converters.JSON.value(JSON.java:202)
	at grails.converters.JSON.render(JSON.java:134)
	at org.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:109)
	... 2 more
```

For example, this integration test class does not work : https://github.com/tony75/grails3-json-annotations-marshaller/blob/master/src/test/groovy/AnnotationMarshallerSpec.groovy

**Comment by graemerocher** [comment]
Will investigate but it is likely something to do with this particular test

**Comment by graemerocher** [comment]
@tony75 The test linked to doesn't exist?

**Comment by tony75** [comment]
Sorry I have updated the package. 
Here it is : 
https://github.com/tony75/grails3-json-annotations-marshaller/blob/master/src/test/groovy/org/grails/json/annotations/AnnotationMarshallerSpec.groovy

**Comment by graemerocher** [comment]
Integration tests must go in the `src/integration-test/groovy` directory

**Comment by tony75** [comment]
I know, but when I put integrations tests in that folder I can't launch them, intellij give me an error : 
No tests found for given includes: [AnnotationMarshallerSpec]

When I run them from the test/groovy folder I can launch them via intellij but I get the error above

**Comment by salex772** [comment]
I have the same problem. Does anybody know the solution?

**Comment by salex772** [comment]
Solution - add testCompile "org.grails.plugins:hibernate" to build.gradle
