### ISSUE TITLE
Problem in dependencies of grails doc with Gradle 2.4

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-core#9074]
There is some issue with the dependencies of grails docs. 

I have been trying to build the documentation for [quartz plugin](https://github.com/anshbansal/quartz) but keep on getting errors for dependencies not being found. 

```
Caused by: java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:142)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:121)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:332)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:275)
	at org.radeox.util.i18n.ResourceManager.<clinit>(ResourceManager.java:39)
	at org.radeox.engine.context.BaseInitialRenderContext.<init>(BaseInitialRenderContext.java:48)
	at grails.doc.DocPublisher.initialize(DocPublisher.groovy:497)
	at grails.doc.DocPublisher.catPublish(DocPublisher.groovy:134)
	at grails.doc.DocPublisher.this$2$catPublish(DocPublisher.groovy)
	at grails.doc.DocPublisher$_publish_closure1.doCall(DocPublisher.groovy:129)
	at grails.doc.DocPublisher$_publish_closure1.doCall(DocPublisher.groovy)
	at grails.doc.DocPublisher.publish(DocPublisher.groovy:128)
	at grails.doc.DocPublisher$publish.call(Unknown Source)
```

Added the dependencies for log4j but still happening. Was not sure whether compile or runtime so tried combinations. Still getting errors. 
```  
runtime 'org.slf4j:slf4j-log4j12:1.7.12'
runtime 'log4j:log4j:1.2.17'
```

**Comment by anshbansal** [comment]
The problem is reproducible at https://github.com/anshbansal/test-grails-doc-command/tree/da1d13f3bb6f256152b136db92adb2bca68f48a8

**Comment by anshbansal** [comment]
I debugged a bit more and found that this is happening with gradle 2.4. On gradle 2.3 it is working fine.

**Comment by rlovtangen** [comment]
Still an issue in Grails 3.1.1. Works with Gradle 2.3 but not 2.4 or newer (tried with 2.11).
