### ISSUE TITLE
gradle docs throws exception when used with default application.yml

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-core#9077]
I create a new application with Grails 3.0.2. I have uploaded it on this [github Repository](https://github.com/anshbansal/test-grails-doc-command/tree/69940c4de1356d89f3fb5486bac926bf30867000).  

An exception is thrown when gradle docs is run.

```
Caused by: expected a single document in the stream
 in 'reader', line 2, column 1:
    grails:
    ^
but found another document
 in 'reader', line 16, column 1:
    ---
    ^

	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:110)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
	at grails.doc.DocPublisher$_initialize_closure23.doCall(DocPublisher.groovy:480)
	at grails.doc.DocPublisher.initialize(DocPublisher.groovy:479)
	at grails.doc.DocPublisher.catPublish(DocPublisher.groovy:134)
	at grails.doc.DocPublisher.this$2$catPublish(DocPublisher.groovy)
	at grails.doc.DocPublisher$_publish_closure1.doCall(DocPublisher.groovy:129)
	at grails.doc.DocPublisher$_publish_closure1.doCall(DocPublisher.groovy)
	at grails.doc.DocPublisher.publish(DocPublisher.groovy:128)
	at grails.doc.DocPublisher$publish.call(Unknown Source)
	at grails.doc.DocPublisher$publish.call(Unknown Source)
	at org.grails.gradle.plugin.doc.PublishGuideTask.compile(PublishGuideTask.groovy:97)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
```

I am able to get past this exception if I change the application.yml to have single document. Just rearranging the properties and removing `---`. 

Then https://github.com/grails/grails-core/issues/9074 occurs.

**Comment by anshbansal** [comment]
The change that I did was 
https://github.com/anshbansal/test-grails-doc-command/commit/da1d13f3bb6f256152b136db92adb2bca68f48a8
