### ISSUE TITLE
stop-app not working with parameters

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-core#9109]
Tried on Grails 3.0.3

```
>> grails stop-app --port=9001 --stacktrace
| Error Error occurred running Grails CLI: Cannot cast object '9001' with class 'java.lang.String' to class 'java.lang.Integer' (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '9001' with class 'java.lang.String' to class 'java.lang.Integer'
	at stop-app.run(stop-app.groovy:9)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
	at org.grails.cli.profile.DefaultProfile.handleCommand(DefaultProfile.groovy:177)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:239)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:220)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:198)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Error occurred running Grails CLI: Cannot cast object '9001' with class 'java.lang.String' to class 'java.lang.Integer'
```

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-profile-repository/commit/d91c4871ad6d5a053c6b5b2de8fcf4a162f4d150
