### ISSUE TITLE
Found Connection leak Bug : DataSource Connection don't Close after forward and Broken pipe

### ISSUE THREAD

**Issue by laizhenhai88** [grails/grails-core#9127]
I found a connection leak bug, but don't know how to fix it. I use Grails2.5.0
1、I write a DownloadController to read file in the server and write to client
```
def path = FilePath.get(1) // do some query here,so it will get datasource connection
def file = new File(path.realpath)
response.outputStream << new BufferedInputStream(new FileInputStream(file))
```
but, if the file is big and the client shutdown connection(such as close brower) when transferring, it will throw SocketException, and the datasource connection will close after SocketException;

2、I write another Controller and Action, forward to DownloadController
```
    def attachment(){
        forward(controller: 'download',action: 'index')
    }
```
at this time, client shutdown connection when transferring, the datasource connection will not close, and the current thread will block

3、I delete the query in DownloadController, and still forward to it
<del>def path = FilePath.get(1)</del> // delete this line so that the DownloadController need not to get datasource connection
```
response.outputStream << new BufferedInputStream(new FileInputStream(file))
```
at this time, client shutdown connection when transferring, current Thread will throw SocketException;
and then, when another request come, the same Thread handle this request in any action which need query, it will get datasource connection and don't close it, the Thread will block

here is the log when client shutdown:
```
2015-07-23 12:10:11,194 [http-bio-80-exec-1] ERROR errors.GrailsExceptionResolver  - SocketException occurred when processing request: [GET] /common/main/attachment/asdf.rar
Broken pipe. Stacktrace follows:
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at back.tool.DownloadController.index(DownloadController.groovy:48)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at common.MainController.attachment(MainController.groovy:411)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
2015-07-23 12:10:11,229 [http-bio-80-exec-1] ERROR errors.GrailsExceptionResolver  - IllegalStateException occurred when processing request: [GET] /common/main/attachment/asdf.rar
getOutputStream() has already been called for this response. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at common.MainController.attachment(MainController.groovy:411)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at java.io.FilterWriter.flush(FilterWriter.java:100)
	... 8 more
2015-07-23 12:10:11,238 [http-bio-80-exec-1] WARN  simple.MemoryPageFragmentCachingFilter  - Throwable thrown during doFilter on request with URI: /grails/download/index.dispatch and Query: prefix=%2Fcommon%2Fmain%2Fattachment : Request processing failed; nested exception is org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at common.MainController.attachment(MainController.groovy:411)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
	... 8 more
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at java.io.FilterWriter.flush(FilterWriter.java:100)
	... 8 more
2015-07-23 12:10:11,245 [http-bio-80-exec-1] ERROR errors.GrailsExceptionResolver  - IllegalStateException occurred when processing request: [GET] /common/main/attachment/asdf.rar
getOutputStream() has already been called for this response. Stacktrace follows:
java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at java.io.FilterWriter.flush(FilterWriter.java:100)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at common.MainController.attachment(MainController.groovy:411)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
2015-07-23 12:10:11,247 [http-bio-80-exec-1] ERROR servlet.GrailsDispatcherServlet  - Internal server error - problem rendering error view
java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by linhere20** [comment]
kill 0 reply!
Don't say thank you, please call me red scarfer!

**Comment by graemerocher** [comment]
@laizhenhai88 Please upload an example that reproduces the problem to github

**Comment by laizhenhai88** [comment]
@graemerocher here is the example https://github.com/laizhenhai88/forwardBug
if I request /download/index , the datasource connection will close
if I request /forward/index , the datasource connection will not close

**Comment by laizhenhai88** [comment]
@linhere20 thanks

**Comment by laizhenhai88** [comment]
@graemerocher here is the example https://github.com/laizhenhai88/forwardBug
could you please help me to fix this bug as quickly as possible? I have 4 online project face this problem.
Thank you very much!
