### ISSUE TITLE
Grails not starting! after trying to install a plugin in build.gradle

### ISSUE THREAD

**Issue by rserranon** [grails/grails-core#9128]
**Grails 3.0.3 in Mac OS X yosemite**

I tried to intall the Fields plugin including: compile "org.grails.plugins:fields-2.0.2" in my build.gradle file and got this error:

>grails> 
FAILURE: Build failed with an exception.

>* What went wrong:
A problem occurred configuring root project 'vivanyServer'.
> Could not open buildscript class cache for build file '/Users/proyectoweb/Documents/RSN/grails_apps/vivanyServer/build.gradle' (/Users/proyectoweb/.gradle/caches/2.3/scripts/build_80hc9xoom31vg2u17hb7uaao/ProjectScript/buildscript).
   > Timeout waiting to lock buildscript class cache for build file '/Users/proyectoweb/Documents/RSN/grails_apps/vivanyServer/build.gradle' (/Users/proyectoweb/.gradle/caches/2.3/scripts/build_80hc9xoom31vg2u17hb7uaao/ProjectScript/buildscript). It is currently in use by another Gradle instance.
     Owner PID: unknown
     Our PID: 86860
     Owner Operation: unknown
     Our operation: Initialize cache
     Lock file: /Users/proyectoweb/.gradle/caches/2.3/scripts/build_80hc9xoom31vg2u17hb7uaao/ProjectScript/buildscript/cache.properties.lock

>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

So I deleted the line for the plugin in my build.gradle file and tried to restart Grails with the following response:

proyectoweb:~/Documents/RSN/grails_apps/vivanyServer(develop) $ grails --stacktrace

BUILD SUCCESSFUL

>Total time: 3.324 secs
| Error Error initializing classpath: Unsupported method: GrailsClasspath.getError().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model. (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: GrailsClasspath.getError().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.
	at org.gradle.tooling.model.internal.Exceptions.unsupportedMethod(Exceptions.java:33)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$InvocationHandlerImpl.invoke(ProtocolToModelAdapter.java:240)
	at com.sun.proxy.$Proxy7.getError(Unknown Source)
	at org.grails.cli.GrailsCli$1.readFromGradle(GrailsCli.groovy:370)
	at org.grails.cli.GrailsCli$1.readFromGradle(GrailsCli.groovy)
	at org.grails.cli.gradle.cache.CachedGradleOperation$_call_closure1.doCall(CachedGradleOperation.groovy:64)
	at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure2.doCall(GradleUtil.groovy:89)
	at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure2.call(GradleUtil.groovy)
	at grails.io.support.SystemOutErrCapturer.withNullOutput(SystemOutErrCapturer.groovy:64)
	at org.grails.cli.gradle.GradleUtil.withProjectConnection(GradleUtil.groovy:88)
	at org.grails.cli.gradle.cache.CachedGradleOperation.call(CachedGradleOperation.groovy:64)
	at org.grails.cli.GrailsCli.populateContextLoader(GrailsCli.groovy:361)
	at org.grails.cli.GrailsCli.initializeProfile(GrailsCli.groovy:348)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:196)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Error initializing classpath: Unsupported method: GrailsClasspath.getError().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

**Any suggestions to be able to start Grails again?**

**Comment by graemerocher** [comment]
Try run
  
     gradle --stop

To stop the Gradle daemon and then try again

**Comment by rserranon** [comment]
If someone have the same issue. I managed to make it work copying /gradle directory from a new clean project and deleting /.gradle & /build directories, restarting Grails, build and run-app. I will no longer try the plugin for now.

**Comment by rserranon** [comment]
For some reason It seems that Grails still looks for some components of the plugin. Any idea on how to fix it?

grails> run-app 
| Running application...
objc[2990]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Grails application running at http://localhost:8080 in environment: development
grails> ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/person/index.gsp:21] Error executing tag <f:table>: [views/templates/_fields/_table.gsp:18] Error executing tag <f:display>: Cannot get property 'id' on null object] with root cause
java.lang.NullPointerException: Cannot get property 'id' on null object
	at grails.plugin.formfields.FormFieldsTagLib.displayAssociation(FormFieldsTagLib.groovy:576) ~[fields-2.0.2.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib.renderDefaultDisplay(FormFieldsTagLib.groovy:532) ~[fields-2.0.2.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib.renderForDisplay(FormFieldsTagLib.groovy:279) ~[fields-2.0.2.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib$_closure6.doCall(FormFieldsTagLib.groovy:221) ~[fields-2.0.2.jar:na]
	at gsp_fields_templates__fields_table_gsp.run(gsp_fields_templates__fields_table_gsp.groovy:53) ~[fields-2.0.2.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib$_closure5.doCall(FormFieldsTagLib.groovy:184) ~[fields-2.0.2.jar:na]
	at Users_proyectoweb_Documents_RSN_grails_apps_vivanyServer_grails_app_views_person_index_gsp$_run_closure2.doCall(Users_proyectoweb_Documents_RSN_grails_apps_vivanyServer_grails_app_views_person_index_gsp:53) ~[na:na]
	at Users_proyectoweb_Documents_RSN_grails_apps_vivanyServer_grails_app_views_person_index_gsp.run(Users_proyectoweb_Documents_RSN_grails_apps_vivanyServer_grails_app_views_person_index_gsp:58) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]

**Comment by graemerocher** [comment]
@rserranon This error seems unrelated to the problem you originally posted and seems to be a data / query issue as you are trying to render a domain object which is null. I'm closing this as the general issue has been solved at the user end.
