### ISSUE TITLE
JSON Grails converter replaces null references to JSONObject.NULL references causing all kind of havoc

### ISSUE THREAD

**Issue by aruizca** [grails/grails-core#9129]
I am not the first to report this issue, but this week it was my turn to deal with this nonsense. The base problem is that JSON null references should be kept as they are. But to avoid regressions, maybe it would be enough by just fixing the toString() method implementation of the JSONObject.NULL inner class, which is really really dumb and has cause enough headaches and grief to the Grails community:
```java
        /**
         * Get the "null" string value.
         * @return The string "null".
         */
        @Override
        public String toString() {
            return "null";
        }
```
I might be wrong but I think just returning and empty String would solve most of the problems thanks to the Groovy truth:
```java
        /**
         * Get the "" string value.
         * @return An empty String "".
         */
        @Override
        public String toString() {
            return "";
        }
```
This way you can safely cast this object to String and evaluate it within a logical expression. It has to be explicitly cast though

To fix this in an existing version of Grails, just copy the class `org.codehaus.groovy.grails.web.json.JSONObject` to your `/src/java` folder and make the suggested change there. Next time, the classloader will choose this class instead of the one packaged in the Grails dependencies.

Make sure you keep the same package as the original.

P.S: I tried using meta-programming:
```
JSONObject.NULL.metaClass.toString= {-> ""}
```
but it did not work.

**Comment by jeffbrown** [comment]
@aruizca 

> who the f#$? wants that?

Thanks for the bug report and we will get it straightened out but the colorful commentary isn't helpful.

**Comment by aruizca** [comment]
Sorry @jeffbrown 
Please don't take it personally. I just let my frustration out :-) This issue cost me a lot of time and there are reports of this that date 2011. I was surprised that an issue as significant as this was still there. Specially now that we tend to expose everything with REST web services using JSON payloads.
My apologies if that offended you. I will remove it.
IMO the ideal solutions would be one were the JSONObject.NULL inner class is removed completely.
Thanks for your work mate!

**Comment by anshbansal** [comment]
I heard from someone a few days back that he is sending null value and getting a "null" String. I was surprised about how could this happen. He was working with angular and probably using Grails REST services.

**Comment by aruizca** [comment]
@anshbansal Same here :-)

**Comment by jeffbrown** [comment]
I am not sure how to get "...all kind of havoc" to manifest.  I am trying to decide if the method should return an and empty string  (`""`) or it should return `null` (as opposed to the String `"null"`).  @graemerocher had suggested `null`.  Can you describe how to trigger the mal behavior and/or submit a simple failing unit test as a PR so we can fix it?

Thanks for the feedback.

**Comment by aruizca** [comment]
Hi @jeffbrown 
Here are some test cases: https://gist.github.com/8ceaaabfbea8ad8f03bf.git

My workaround is only to palliate the first test case in existing versions of Grails. The reason for choosing `""` over `null` as the returned value in the `toString()` method is to avoid regressions.  And the outcome is the same for all effects AFAIK.

The ideal solution for new versions of Grails is to remove the JSONObject.NULL and replace it with `null`

**Comment by jeffbrown** [comment]
> Here are some test cases: https://gist.github.com/8ceaaabfbea8ad8f03bf.git

That link isn't currently working.

**Comment by aruizca** [comment]
Ups! Edited :-)

**Comment by jeffbrown** [comment]
Thanks.  I will take a look.

**Comment by jeffbrown** [comment]
That test appears to describe the current behavior, not the desired behavior.  Is that correct?

**Comment by jeffbrown** [comment]
Is this the desired behavior?...

    
    def "test parsing null value"() {
        expect:
        JSON.parse("{'myList':null}").myList == null
    }

**Comment by aruizca** [comment]
Correct! to both :-)

**Comment by jeffbrown** [comment]
I don't think having the `toString()` method return `null` or an empty String will satisfy that.

**Comment by aruizca** [comment]
You are right. As I said my fix is not a full solution, but at least it allows you to work with Strings as you would expect in existing versions of Grails. If you were expecting anything that is not a String (eg: Integer, Array, ...), the casting will fail miserably as shown in second test case.

**Comment by aruizca** [comment]
I think we should aim to remove the JSONObject.NULL inner class and replace all the occurrences with `null`

**Comment by jeffbrown** [comment]
I think the proposed interim change just results in the ability to assign the value to a `String` reference and have the result of that assignment be an empty `String`.  Is that correct or am I misunderstanding?  Just trying to clarify.

Thanks for the feedback.

**Comment by aruizca** [comment]
I have proposed and interim change/workaround for existing versions of Grails that does not fully solve the problem:
```
        @Override
        public String toString() {
            return "";
        }
```
and a full solution for new versions of Grails:
> remove the JSONObject.NULL inner class and replace all the occurrences with `null`

**Comment by jeffbrown** [comment]
> I have proposed and interim change/workaround for existing versions of Grails that does not fully solve the problem

I know what you are proposing.  Please reread my question.  I am trying to clarify the expectation of making the change.

**Comment by jeffbrown** [comment]
One thing that will help for some cases is adding something like this to the `Null` class:

    
        public Object asType(Class c) {
            return null;
        }

That will allow things like the following:

    def "test parsing null value"() {
        when:
        def obj =  JSON.parse("{'myList':null}")

        then:
        (obj.myList as String) == null
        (obj.myList as Integer) == null
        (obj.myList as AnyClass) == null
    }

**Comment by jeffbrown** [comment]
I am hesitant to change `toString()` to return an empty String.  I see why it is helpful for a particular use case, but I think it only accidentally helps that situation and may be problematic in other ways.  I think I may be alone in that thought though so maybe we will end up doing it.  I think @graemerocher is in favor of having it return `null`, but that seems wrong to me too.  I will probably end up having to be the odd man out and just let it be one of those things.  For now I will leave it and ask Graeme to weigh in tomorrow.

Thanks again for the feedback.  We appreciate it.

**Comment by aruizca** [comment]
Adding the asType method is a nice addition to my workaround, but it should not be needed in the final fix for this.
In terms of expectations, I think the desired behavior should allow something like this: 
```
    def "test parsing null value with no explicit casting provided"() {
        given:
        def obj =  JSON.parse("{'myKey':null}")

        when:
        String stringValue = obj.mykey
        then:
        stringValue == null
        (true && stringValue) == false

        when:
        Integer integerValue = obj.mykey
        then:
        integerValue == null
        (true && integerValue) == false

        when:
        List list = obj.mykey
        then:
        list == null
        (true && list) == false
    }
```
The same for any class that has a JSON type correspondence

**Comment by jeffbrown** [comment]
I think I agree with all of that.

When the test does something like this:

    then:
    stringValue == null
    (true && stringValue) == false

What is the value of the 2nd assertion?

**Comment by aruizca** [comment]
I guess I am bit paranoid at this point XD I was probably thinking in terms of the JSONObject.NULL implementation which in some very old Grails distribution, it does not have an `asBoolean()` method implemented.

**Comment by aruizca** [comment]
For my workaround now I have the following three methos inside the `JSONObject.NULL` inner class:
```
...
        /**
         * Null in JSON should evaluate to false
         *
         * @return false
         */
        public boolean asBoolean() {
            return false;
        }

        /**
         * Get an empty string value.
         *
         * @return The string "".
         */
        @Override
        public String toString() {
            return "";
        }

        /**
         * Converts JSONObject.NULL to null
         * @param c Type conversion
         * @return
         */
        public Object asType(Class c) {
            return null;
        }
...
```

**Comment by jeffbrown** [comment]
I think rather than change things so something like `JSON.parse("{'myList':null}").myList` evaluates to an object whose `toString()` returns null or returns an empty String, I think it probably makes more sense for `JSON.parse("{'myList':null}").myList` to evaluate to null.

**Comment by jeffbrown** [comment]
For 2.5.1 I have rigged up `JSONObject` to support that.  We will probably remove the `JSONObject.Null` class for 3.1.  I am only a little hesitant to release it in a 2.5.1 or 3.0.4 release.

**Comment by aruizca** [comment]
Thanks @jeffbrown ! Sounds good :+1:

**Comment by gantaa** [comment]
Might want to include JSONObject.NULL best practices in the migration docs from Grails 2 to Grails 3.

We used to use JSONObject.NULL in our REST responses, and they serialized as null in our JSON responses nicely in Grails 2.3.11

After upgrading to Grails 3.3.8, converting all our JSONObject.NULL references to null (due to the removal of JSONObject.NULL) now throws the following NullPointerException when rendering a JSON message with null properties :(

I'm calling
`render(status: status.code, contentType: 'application/json', text: json)`

Where json is a JSONObject with at least one property set to null

and getting:
`java.lang.NullPointerException: null
        at org.grails.web.converters.marshaller.ClosureObjectMarshaller.supports(ClosureObjectMarshaller.java:42)
        at org.grails.web.converters.configuration.DefaultConverterConfiguration.getMarshaller(DefaultConverterConfiguration.java:146)
        at grails.converters.JSON.value(JSON.java:180)
        at grails.converters.JSON.render(JSON.java:119)
        at org.grails.web.converters.AbstractConverter.writeTo(AbstractConverter.java:110)
        at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.renderWritable(ResponseRenderer.groovy:486)
        at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.render(ResponseRenderer.groovy:228)
        at grails.artefact.controller.support.ResponseRenderer$Trait$Helper$render$3.call(Unknown Source)
        at fitnerds.coreservices.controller.v1.PermissionsController.render(PermissionsController.groovy)
        at fitnerds.coreservices.controller.v1.BaseController$render$2.callCurrent(Unknown Source)
        at fitnerds.coreservices.controller.v1.BaseController.renderResponse(BaseController.groovy:83)
        at fitnerds.coreservices.controller.v1.PermissionsController.renderResponse(PermissionsController.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
        at fitnerds.coreservices.controller.v1.PermissionsController.fetchPermissions(PermissionsController.groovy:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)`

I have also tried adding the grails converters plugin.  No dice.  Any ideas? Do I need a JSON marshaller?
