### ISSUE TITLE
No such property: developmentModeActive for class: grails.ui.command.GrailsApplicationContextCommandRunner

### ISSUE THREAD

**Issue by sailingcai** [grails/grails-core#9130]
Environment:
Grails Version: 3.0.3
Groovy Version: 2.4.3
JVM Version: 1.8.0_45

Steps:
1. create app by create-app
2. add classpath "org.grails.plugins:hibernate:4.3.8.1" to build.gradle
3. run command grails schema-export

Error:
grails> schema-export
:compileJava UP-TO-DATE
:compileGroovy
:processResources
:classes
:findMainClass
:schemaExport
objc[24222]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Exception in thread "Thread-11" groovy.lang.MissingPropertyException: No such property: developmentModeActive for class: grails.ui.command.GrailsApplicationContextCommandRunner
Possible solutions: developmentModeActive
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:51)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:304)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:161)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at groovy.lang.Closure.run(Closure.java:504)
	at java.lang.Thread.run(Thread.java:745)
Generating script to ./build/ddl.sql in environment 'development' for the default DataSource

BUILD SUCCESSFUL

Total time: 14.987 secs

The project is very clean, so I guess this is a bug for grails 3.0.3.

**Comment by jeffbrown** [comment]
May be related to #9099

**Comment by graemerocher** [comment]
Yeah believe this is already fixed
