### ISSUE TITLE
Updating domain object with assigned and non integer id in unit tests causes crash when querying it later

### ISSUE THREAD

**Issue by magnomp** [grails/grails-core#9139]
If a domain object has a id of type integer (didn't test for other types, but the default long type works fine) and assigned id, if during a unit test you update any instance of it and later tries to query it, you'll get an IndexOutOfBoundsException

I post and exemple here https://bitbucket.org/magnomp/grailsiobexceptiontest

If you run "grails test-app" you'll get an IndexOutOfBoundsException with this stack trace:

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.remove(ArrayList.java:492)
    at org.grails.datastore.mapping.simple.engine.SimpleMapEntityPersister$1.deindex(SimpleMapEntityPersister.groovy:106)
    at org.grails.datastore.mapping.engine.NativeEntryEntityPersister.updatePropertyIndices(NativeEntryEntityPersister.java:1423)
    at org.grails.datastore.mapping.engine.NativeEntryEntityPersister.access$100(NativeEntryEntityPersister.java:86)
    at org.grails.datastore.mapping.engine.NativeEntryEntityPersister$4.run(NativeEntryEntityPersister.java:1122)
    at org.grails.datastore.mapping.core.impl.PendingOperationExecution.executePendingOperation(PendingOperationExecution.java:37)
    at org.grails.datastore.mapping.core.AbstractSession.flushPendingOperations(AbstractSession.java:366)
    at org.grails.datastore.mapping.core.AbstractSession.flushPendingUpdates(AbstractSession.java:345)
    at org.grails.datastore.mapping.core.AbstractSession.flush(AbstractSession.java:265)
    at org.grails.datastore.mapping.query.Query.flushBeforeQuery(Query.java:637)
    at org.grails.datastore.mapping.query.Query.list(Query.java:547)
    at org.grails.datastore.gorm.GormStaticApi.list_closure18(GormStaticApi.groovy:426)
    at groovy.lang.Closure.call(Closure.java:423)
    at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)
    at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
    at org.grails.datastore.gorm.GormStaticApi.list(GormStaticApi.groovy:425)
    at org.grails.datastore.gorm.GormEntity$Trait$Helper.list(GormEntity.groovy:505)
    at test.BarService.$tt__serviceMethod(BarService.groovy:9)
    at test.BarService.serviceMethod_closure1(BarService.groovy)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:93)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:90)
    at test.BarServiceSpec.test something(BarServiceSpec.groovy:30)
```

Change Foo's id definition to be generated or to be the default Long type and you get no exception

Grails 3.0.3

**Comment by nathan-xu** [comment]
@graemerocher 
I am pretty sure the root cause is the following code snippet in (https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-simple/src/main/groovy/org/grails/datastore/mapping/simple/engine/SimpleMapEntityPersister.groovy):
`void deindex(value, primaryKey) {
                def index = getIndexName(value)
                def indexed = indices[index]
                if (indexed) {
                    indexed.remove(primaryKey)
                }
            }`

When the primaryKey is of integer type, the 'indexed.remove' will be equivalent to 'indexed.removeAt'.

**Comment by misterarias** [comment]
I've just come across this issue, with exactly the same use case as @nathan-xu so I guess it's still there, right? 
I also have followed the advice [http://stackoverflow.com/questions/11015247/grails-getting-indexoutofboundsexception-from-datamodel-objects-in-service-duri](here) and did not save the instance inside the service, and it seems to work... I don't understand it, it seems counter-intuitive.

**Comment by nbkhope** [comment]
I have a unit test for a service. The test sets up an initial record, and then calls one of the service's method to save the record after making some changes to it. I explicitly defined `Integer id` in my domain class, and it seems this issue applies to that. I get `IndexOutOfBoundsException`, but when I remove my `Integer id` and let Grails use the default Long type, then there's no problem. 

Any chance for a fix any time soon?

**Comment by jameskleeh** [comment]
@magnomp Any idea why I can't clone the repo?

```
Jamess-MacBook-Pro:sample-projects jameskleeh$ git clone https://bitbucket.org/magnomp/grailsiobexceptiontest
Cloning into 'grailsiobexceptiontest'...
remote: Not Found
fatal: repository 'https://bitbucket.org/magnomp/grailsiobexceptiontest/' not found
```

**Comment by magnomp** [comment]
Sorry for not mention, this is a Mercurial repo, not git
