### ISSUE TITLE
Can't start interactive grails console on OS X 10.10.3

### ISSUE THREAD

**Issue by gykpro** [grails/grails-core#9161]
I'm trying grails demo, and it went well on Cent OS.
When I try to do it on OS X, I get following error:
```
$ grails create-app demo
| Application created at /Users/Twilight-work-mbp/dev/grails/demo

$ cd demo

$ grails
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0
| Error Error initializing classpath: class com.google.common.cache.CacheBuilder$3 has interface com.google.common.base.Ticker as super class (Use --stacktrace to see the full trace)

$ echo $GRAILS_OPTS 
-XX:-UseSplitVerifier -Xverify:none

$ grails --stacktrace
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0
| Error Error initializing classpath: class com.google.common.cache.CacheBuilder$3 has interface com.google.common.base.Ticker as super class (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.IncompatibleClassChangeError: class com.google.common.cache.CacheBuilder$3 has interface com.google.common.base.Ticker as super class
	at com.google.common.cache.CacheBuilder.<clinit>(CacheBuilder.java:207)
	at org.gradle.tooling.internal.provider.ClassLoaderCache.<init>(ClassLoaderCache.java:35)
	at org.gradle.tooling.internal.provider.ToolingServices$ToolingGlobalScopeServices.createClassLoaderCache(ToolingServices.java:38)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.internal.service.DefaultServiceRegistry.invoke(DefaultServiceRegistry.java:328)
	at org.gradle.internal.service.DefaultServiceRegistry.access$1200(DefaultServiceRegistry.java:58)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:641)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:597)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:439)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:479)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:607)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:596)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:439)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:479)
	at org.gradle.internal.service.DefaultServiceRegistry.doGet(DefaultServiceRegistry.java:300)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:284)
	at org.gradle.tooling.internal.provider.DefaultConnection.<init>(DefaultConnection.java:56)
	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:39)
	at org.gradle.internal.service.ServiceLocator$ServiceFactory.newInstance(ServiceLocator.java:162)
	at org.gradle.internal.service.ServiceLocator$ServiceFactory.create(ServiceLocator.java:156)
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:62)
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:43)
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:42)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:99)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:82)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
| Error Error initializing classpath: class com.google.common.cache.CacheBuilder$3 has interface com.google.common.base.Ticker as super class

```

My environment variables:

$JAVA_HOME 
/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home

$JRE_HOME 
/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre

$GRAILS_HOME 
/usr/local/grails

grails -version
| Grails Version: 3.0.3
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_51

if I run gradle:
```
$ gradle

FAILURE: Build failed with an exception.

* What went wrong:
com.google.common.io.Resources.asCharSource(Ljava/net/URL;Ljava/nio/charset/Charset;)Lcom/google/common/io/CharSource;
```
I have gradle 2.5.

Both grails(on CentOS and OS X) are installed with downloaded zip archive.

Since I can't find any dependence on Google Guava, I have to seek help here. Thanks.

**Comment by graemerocher** [comment]
this is class path conflict with your local environment

**Comment by gykpro** [comment]
Turned out to be an old jar file (Guava) in /Library/Java/Extensions/
Sorry for the trouble.
