### ISSUE TITLE
Grails command "test-app" giving error: “Error running forked test-app: Cannot invoke method containsBean() on null object”

### ISSUE THREAD

**Issue by sohampshetty** [grails/grails-core#9182]
I can run all spock test separately (as unit test) which are running smoothly (test passed), but when I run "grails test-app" command it giving above mentioned error.

1. used searchable plugin:

// plugins for the build system only
build ":tomcat:7.0.55"

// plugins for the compile step
compile ":searchable:0.6.9"
compile ":scaffolding:2.1.2"
test(":spock:0.7") {
exclude "spock-grails-support" }
compile ':cache:1.1.8'
compile ":asset-pipeline:1.9.9"
compile ":spring-security-core:2.0-RC4"
compile ":audit-logging:1.0.4"
compile ":rendering:1.0.0"

2.commented "test" block in DataSource.groovy

3.here is exact error:
Error | Fatal error running tests: Cannot invoke method containsBean() on null object.Tests FAILED| 

Error | Error running forked test-app: Cannot invoke method containsBean() on null object (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.) java.lang.NullPointerException: Cannot invoke method containsBean() on null object

 at SearchableGrailsPlugin.getConfiguration(SearchableGrailsPlugin.groovy:184)
    at SearchableGrailsPlugin.this$2$getConfiguration(SearchableGrailsPlugin.groovy)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
    at SearchableGrailsPlugin$_closure2.doCall(SearchableGrailsPlugin.groovy:69)
    at SearchableGrailsPlugin$_closure2.doCall(SearchableGrailsPlugin.groovy)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
    at SearchableGrailsPlugin$_closure2.call(SearchableGrailsPlugin.groovy)
    at SearchableGrailsPlugin$_closure2.call(SearchableGrailsPlugin.groovy)
    at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:754)
    at grails.spring.BeanBuilder.beans(BeanBuilder.java:584)
    at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:527)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.

really appreciate any help you can provide

**Comment by jeffbrown** [comment]
It looks like the error is coming from https://github.com/gpc/searchable/blob/b3716f1a771fd0002784abc438ddfc6a76ea83ca/SearchableGrailsPlugin.groovy#L184.  Without running some tests I am not sure what would lead to the problematic scenario.  Can you provide a sample app which demonstrates the problem?

**Comment by sohampshetty** [comment]
i am sorry but how can i provide that. .rar file is not getting accepted here

**Comment by jeffbrown** [comment]
@sohampshetty You could create a small sample app which demonstrates the problem and push it to a repo on GitHub.

**Comment by sohampshetty** [comment]
@jeffbrown you can download source code from sorry for giving link (company privacy).
https://www.dropbox.com/s/lxsyozsc44cmma2/grailstest.zip?dl=0

**Comment by sohampshetty** [comment]
hey @jeffbrown  I'm waiting for your response.

**Comment by jeffbrown** [comment]
@sohampshetty Thank you for providing a sample app.  We will take a look and get it straightened out.
