### ISSUE TITLE
Problem With Returning false In after Interceptor

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9183]
Controller:

    class PostController {
        def show(){
            ['fname':'Bob']
        }
    }

Interceptor:

    class TestappInterceptor{

        def TestappInterceptor() {
            match controller: 'post'
        }

        boolean after(){
            render 'test'
            false
        }
    }

Invoking the `show` action results in exception:

    ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [ModelAndView [ModelAndView: materialized View is [null]; model is {fname=Bob}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'] with root cause
    javax.servlet.ServletException: ModelAndView [ModelAndView: materialized View is [null]; model is {fname=Bob}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'
    	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1235) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]

**Comment by jeffbrown** [comment]
See https://github.com/grails/grails-core/issues/9175

**Comment by jeffbrown** [comment]
A sample app is at https://github.com/jeffbrown/testapp which is a simplified fork of code from https://github.com/orubel/testapp.

**Comment by jeffbrown** [comment]
@orubel I think that the problem can be fixed now that it is understood.  Thanks for your help.

**Comment by jeffbrown** [comment]
@orubel If you are interested in helping validate the recent changes, your input would be welcome.  If you build apps with 3.0.5.BUILD-SNAPSHOT you should be able to invoke `render(String)` or `render(Map)` from an `after` interceptor that returns `false` and that should all work.  If you do take time to do any testing, your feedback would be really appreciated.

Thanks again for all of your help.

**Comment by orubel** [comment]
I'll go ahead and give it a shot tonight.

Owen Rubel
415-971-0976
orubel@gmail.com

**Comment by orubel** [comment]
Built, added snapshot to gradle and Tested this morning. Still seeing error

ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [ModelAndView [ModelAndView: materialized View is [null]; model is {fname=Bob, lname=Dobbes, address=3401 16th ave s}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: ModelAndView [ModelAndView: materialized View is [null]; model is {fname=Bob, lname=Dobbes, address=3401 16th ave s}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1235) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicaterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:295) ~[spring-boot-actuator-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102) ~[spring-boot-actuator-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:73) ~[grails-web-mvc-3.0.4.jar:3.0.4]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChernalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67) ~[grails-web-mvc-3.0.4.jar:3.0.4]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:68) ~[spring-boot-actuator-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) ~[tomcat-embed-core-8.0.23.jar:8.0.23]
     rg.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
ERROR org.grails.web.errors.GrailsExceptionResolver - IllegalStateException occurred when processing request: [GET] /api_v0.1/post/show/1
getWriter() has already been called for this response. Stacktrace follows:
java.lang.IllegalStateException: getWriter() has already been called for this response
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by jeffbrown** [comment]
> Built, added snapshot to gradle and Tested this morning. Still seeing error

Interesting.  I am not and our functional tests are passing.  Is whatever you are doing similar to what the functional tests are doing?



The interceptor: https://github.com/grails/grails3-functional-tests/blob/a15e07bba52dfe3d03e32ea2696c231b14014d7f/app1/grails-app/controllers/functionaltests/AfterInterceptor.groovy

The controller: https://github.com/grails/grails3-functional-tests/blob/master/app1/grails-app/controllers/functionaltests/DemoController.groovy

The functional spec: https://github.com/grails/grails3-functional-tests/blob/master/app1/src/integration-test/groovy/functionaltests/InterceptorFunctionalSpec.groovy

**Comment by jeffbrown** [comment]
@orubel When I update the app at https://github.com/jeffbrown/testapp to use 3.0.5.BUILD-SNAPSHOT, it appears to work fine.  Does it work for you?

**Comment by orubel** [comment]
Ah let me integrate that like the functional tests

**Comment by jeffbrown** [comment]
> Ah let me integrate that like the functional tests

If you are doing something that isn't like what the functional tests are doing and whatever that is isn't working, I would like to know what that is.

**Comment by orubel** [comment]
well functional tests look for a view. I don't have a view. What we are sending back from controller is  ModelAndView with nulled view and viewname

**Comment by orubel** [comment]
In build.gradle, you are referencing grails.core in main repo rather than local build. Should I be doing that???

maven { url "https://repo.grails.org/grails/core" }

**Comment by jeffbrown** [comment]
> In build.gradle, you are referencing grails.core in main repo rather than local build. Should I be doing that?

No.  Just treat it like any other Grails project but use 3.0.5.BUILD-SNAPSHOT. 

I shouldn't even have mentioned the functional test project.  That is going to cause more confusion that need be.  Please ignore that.

**Comment by jeffbrown** [comment]
The simplest thing would be to update the app you have at https://github.com/orubel/testapp so it demonstrates whatever problem you are seeing and I will fix it.

Thanks again for all of the help.

**Comment by orubel** [comment]
I'm copying down your project and getting the following issue:

* What went wrong:
A problem occurred configuring root project 'testapp2'.
> Could not resolve all dependencies for configuration ':agent'.
   > Could not find org.springframework:springloaded:1.2.4.RELEASE.
     Searched in the following locations:

 file:/home/owenrubel/.m2/repository/org/springframework/springloaded/1.2.4.RELEASE/springloaded-1.2.4.RELEASE.pom

 file:/home/owenrubel/.m2/repository/org/springframework/springloaded/1.2.4.RELEASE/springloaded-1.2.4.RELEASE.jar

https://repo.grails.org/grails/core/3.0.5.BUILD-SNAPSHOT/org/springframework/springloaded/1.2.4.RELEASE/springloaded-1.2.4.RELEASE.pom

https://repo.grails.org/grails/core/3.0.5.BUILD-SNAPSHOT/org/springframework/springloaded/1.2.4.RELEASE/springloaded-1.2.4.RELEASE.jar
     Required by:
         testapp:testapp2:0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.


Going to commit back up changes

Owen Rubel
415-971-0976
orubel@gmail.com

**Comment by orubel** [comment]
Yeppers. I went ahead and pushed up the code a couple secs ago.

Owen Rubel
415-971-0976
orubel@gmail.com

**Comment by jeffbrown** [comment]
@orubel Why are you doing this?...

>  maven { url "https://repo.grails.org/grails/core/3.0.5.BUILD-SNAPSHOT" }

https://github.com/orubel/testapp/blob/fbb04306d5a490c370e89eed29b964ce3c01a340/build.gradle#L46

**Comment by orubel** [comment]
sorry. misinterpretted. when I was asking about reading maven from loca cs
remote, you said just add '3.0.5.BUILD-SNAPSHOT
<https://repo.grails.org/grails/core/3.0.5.BUILD-SNAPSHOT>' on to it

guess you meant just change the version

Owen Rubel
415-971-0976
orubel@gmail.com

**Comment by jeffbrown** [comment]
> sorry. misinterpretted. when I was asking about reading maven from loca cs
remote, you said just add '3.0.5.BUILD-SNAPSHOT

When did I say that?  I may have misspoken.  We have never setup our repo to support anything like that.  I don't know what that would even mean, but we don't support it in any case.

**Comment by orubel** [comment]
Yeah still getting same error.

I'm changed the interceptor back to check through the URI in interceptor as
that is a rarer checked test case and one that needs to be tested through
an interceptor in a plugin as applications may have additional urlmappings
and doing an interceptor based solely on CONTROLLER could have risks so a
plugin interceptor needs to be based on URI

Might this be part of the issue?

Owen Rubel
415-971-0976
orubel@gmail.com

**Comment by orubel** [comment]
Its no problem at all. Silly misunderstanding is all. Anyway, still seeing
error and just responded back that it may be that I changed back
Interceptor to read through URI as plugin Interceptors need to do it
through URI rather than CONTROLLER do to potential for implementing
application URLMAPPING to create mapping that could get picked up
accidentally by interceptor.


Owen Rubel
415-971-0976
orubel@gmail.com

**Comment by orubel** [comment]
Ok so its NOT the SAME ERROR. But it expects a view...

ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name 'show' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name 'show' in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1227) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]

This MAY have something to do with me using a URI in the Interceptor rather than a controller for matching; this shouldn't throw an error and shouldn't cause this issue but I'll test with both.

**Comment by orubel** [comment]
HA! That was it! Apparently it has to do with using URI matching in the interceptor. 

This of course is a new BUG now but using URI matching is causing a separate issue.

**Comment by orubel** [comment]
Error exists in current codebase but when you change matching in interceptor to:

match(controller:${controller})

... the error will disappear. Error only appears when matching on uri:

ex.
match(controller:/^(\/${entrypoint}\/*(.+))$/)

**Comment by jeffbrown** [comment]
> HA! That was it! Apparently it has to do with using URI matching in the interceptor.

> This of course is a new BUG now but using URI matching is causing a separate issue.

As far as I can tell that isn't correct.  The latest 3.0.5.BUILD-SNAPSHOT stuff works for me even if I use the `uri` attribute.  I think the `uri` in your latest testapp code isn't matching the request so your filter doesn't run so the normal view rendering is trying to happen.

Is that inconsistent with what you are seeing?

**Comment by orubel** [comment]
Nope not what I'm see. Regex is matching it perfectly else I would get back that 'can't find 'show' view error. I even put in a println in the controller which won't get hit if 'before()' doesn't trigger in the interceptor...

#### made it to post/show
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name 'show' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name 'show' in servlet with name 'grailsDispatcherServlet'

So the interceptor is getting hit, 'before' is sending to controller/method and 'after' is trying to get a 'view'

**Comment by jeffbrown** [comment]
> Nope not what I'm see. Regex is matching it perfectly

That surprises me.  Your expression at https://github.com/orubel/testapp/blob/41a0be6a2e759a9b777c4c1da2e6eaeac2d4b9b8/grails-app/controllers/TestappInterceptor.groovy#L9 begins with a `^` and the path matcher at https://github.com/spring-projects/spring-framework/blob/v4.1.7.RELEASE/spring-core/src/main/java/org/springframework/util/AntPathMatcher.java#L169 should be returning false if the uri begins with `pathSeparator` and the pattern does not.

I will look more closely at it tonight.

Thanks again.

**Comment by orubel** [comment]
ugh. I left 'controller:' where 'uri:' should be. Checking again :)

**Comment by jeffbrown** [comment]
> ugh. I left 'controller:' where 'uri:' should be. Checking again :)

I am surprised it was matching requests.

**Comment by orubel** [comment]
you mean like this '/^(\/${entrypoint}\/*(.+))$/'

**Comment by jeffbrown** [comment]
> you mean like this '/^(\/${entrypoint}\/*(.+))$/'

If you use that as a `uri`, it would surprise me if it matched requests.  Are you saying that it does?

**Comment by orubel** [comment]
I use something better but yes. The pathSeparator is '/' and it does begin with that

**Comment by jeffbrown** [comment]
@orubel If you can show me an example of code that doesn't work, I can fix the problem.  The code that is currently in your repo doesn't work and there are several unrelated things wrong with that code.

**Comment by orubel** [comment]
Ok let me get back to you as I'm at work and trying to juggle this and work at same time.

I just tested the URI at regexr and it is perfect. And the way I am using it is in compliance with pathSeparators so I am confused by what you are saying here. But now you are saying there are lots of things wrong with my code again so I don't know where to take this...

Can you be specific as to what you mean by 'lots'?

**Comment by jeffbrown** [comment]
> Can you be specific as to what you mean by 'lots'?

I didn't say 'lots'.  

One is that the interceptor is using `controller` where it should use `uri`.  One is that the expression begins with a `^` not a `/`.

**Comment by jeffbrown** [comment]
> so I don't know where to take this

You don't need to take it anywhere.  The only reason I was pursuing it is you said that you had identified that it wasn't working.  Now you say "I just tested the URI at regexr and it is perfect.".  As long as we agree on what "perfect" means, I think we are good to go.

Thanks for all of your help.  I am going to consider it done.

**Comment by orubel** [comment]
If I work through this this weekend and it's still an issue, I'll file
separate bug related to this so people have notes.

Owen Rubel
415-971-0976
orubel@gmail.com

On Fri, Aug 14, 2015 at 11:02 AM, Jeff Scott Brown <notifications@github.com

**Comment by jeffbrown** [comment]
> If I work through this this weekend and it's still an issue, I'll file separate bug related to this so people have notes.

Great that will be helpful.

One thing that you might change is instead of `match(uri :/^(\/${entrypoint}\/*(.+))$/)` use something like `match uri:"/${entrypoint}/**"`.  When I do that in your test app it works.

**Comment by jeffbrown** [comment]
If the expression begins with a `^` like yours does, the `AntPathMatcher` isn't going to consider it a match.  It isn't a regex matcher.

**Comment by orubel** [comment]
Ooooh. Ok. You understand my confusion. Matcher is a class used for regex Pattern matching so naturally I made the assumption. I'll research the AntPathMatcher. Thanks :)

**Comment by orubel** [comment]
Thank you very much. I had no idea about AntPathMatcher.

**Comment by jeffbrown** [comment]
> Thank you very much. I had no idea about AntPathMatcher.

In the filter docs at http://grails.github.io/grails-doc/2.5.1/guide/theWebLayer.html#applyingFilters we describe the uri as an Ant style path.  We don't point that out in the interceptor docs at http://grails.github.io/grails-doc/3.0.4/guide/theWebLayer.html#interceptors.

If you want to submit a pull request for https://github.com/grails/grails-doc/blob/4cff3d1f82f043d76d47b587b90132c74e75f9df/src/en/guide/theWebLayer/interceptors/interceptorMatching.gdoc#L46, that would be a great contribution.

**Comment by orubel** [comment]
Since this is a Grails 3.0 project, I was only reading the 3.0
documentation on Interceptors (not filters in 2.5)

There is no mention of Ant style path -
https://grails.github.io/grails-doc/latest/guide/single.html#interceptorMatching

Owen Rubel
415-971-0976
orubel@gmail.com

On Fri, Aug 14, 2015 at 11:38 AM, Jeff Scott Brown <notifications@github.com

**Comment by orubel** [comment]
It does say in that documentation that they all accept REGEX though.

Owen Rubel
415-971-0976
orubel@gmail.com

On Fri, Aug 14, 2015 at 11:38 AM, Jeff Scott Brown <notifications@github.com

**Comment by jeffbrown** [comment]
> There is no mention of Ant style path -https://grails.github.io/grails-doc/latest/guide/single.html#interceptorMatching

That is what I said above.

**Comment by orubel** [comment]
All named arguments accept either a String or a Regex expression. The possible named arguments are:

namespace - The namespace of the controller
controller - The name of the controller
action - The name of the action
method - The HTTP method
uri - The URI of the request. If this argument is used then all other arguments will be ignored and only this will be used.

**Comment by jeffbrown** [comment]
> This is where I was confused.

I am still not sure how you got a uri regex that began with `^` to match any requests.  I suspect you were mistaken about that but if you weren't it would be interesting to know under what circumstances that can happen.

**Comment by orubel** [comment]
Well if I'm mistaken output on my other projects is mistaken too :)

**Comment by jeffbrown** [comment]
I guess I am mistaken then.

In any case, the behavior described in this issue is fixed and working as intended as far as I can tell.  I you discover anything to the contrary, please comment here.  If you discover any separate problem, please file a separate issue.

**Comment by orubel** [comment]
Update: I think not knowing that this was using AntPathMatching vs Regex, this was working as a 'catchall' hack in certain cases; one of my checkins actually works BUT allows incorrect paths through too... it just doesn't parse it properly.

I believe you in saying that this isn't the proper usage but this did work... just not how one would think. And improperly at that.

Interesting improper usage but definitely not a bug.

I reconfigured everything to use AntPathMatching with wildcard in urlmapping and it works as one would think. Just wanted to give an update as to why regex passed through the request.

**Comment by jeffbrown** [comment]
> Interesting improper usage but definitely not a bug.

Great.  Thanks for the feedback.

**Comment by RPeach** [comment]
> I am still not sure how you got a uri regex that began with ^ to match any requests.

Probably this: https://github.com/grails/grails-core/issues/9179

**Comment by jeffbrown** [comment]
> Probably this: #9179

I think that makes sense.  Well done!

**Comment by orubel** [comment]
I opened a ticket in #600 just not referencing this as I noticed it didn't test with after() in the interceptor and I am unable to do redirect(),chain() or forward() in Interceptor.after() when returning false

**Comment by graemerocher** [comment]
why would you do a redirect(), chain() or forward() in an `after` method? It has to be done in the `before` method.

**Comment by jeffbrown** [comment]
> why would you do a redirect(), chain() or forward() in an after method?

I think it is a peculiar thing to want to do, but it does appear to work now.  If we want to explicitly prohibit it I think that is an enhancement that would require a code change.

**Comment by graemerocher** [comment]
@jeffbrown better to just update the documentation, in fact returning `false` should never invoke the `after` method and if you return `true` then you should not invoke that method in `after` since you cannot know if they have already been invoked or not

**Comment by jeffbrown** [comment]
> returning false should never invoke the after method

I thought we were talking about the `after` method returning `false`

**Comment by graemerocher** [comment]
@jeffbrown Ok I see, ignore my previous assertion
