### ISSUE TITLE
Grails 3.0.4: Transaction cannot be rolled back programmatically when using grails.transaction.Transactional

### ISSUE THREAD

**Issue by gilinykh** [grails/grails-core#9212]
Create ```TestService```:

```
import grails.transaction.Transactional
import org.springframework.transaction.interceptor.TransactionAspectSupport

@Transactional
class TestService {

    def serviceMethod() {
        TransactionAspectSupport.currentTransactionStatus().setRollbackOnly()
    }
}
```
 When called the ```serviceMethod()``` fails with exception:

```
ERROR org.grails.web.errors.GrailsExceptionResolver - NoTransactionException occurred when processing request: [GET] /test/index
No transaction aspect-managed TransactionStatus in scope. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
Caused by: org.springframework.transaction.NoTransactionException: No transaction aspect-managed TransactionStatus in scope
	at testtransactional.TestService.$tt__serviceMethod(TestService.groovy:12) ~[main/:na]
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:93) ~[grails-core-3.0.4.jar:3.0.4]
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:90) ~[grails-core-3.0.4.jar:3.0.4]
	at testtransactional.TestController.index(TestController.groovy:8) ~[main/:na]
	... 3 common frames omitted
```

PS: Works fine when using ```org.springframework.transaction.annotation.Transactional```

**Comment by jeffbrown** [comment]
`TransactionAspectSupport` is not supposed to be relevant when using `grails.transaction.Transactional`.  I think `TransactionAspectSupport` is only relevant to the proxies necessary when using Springs `Transactional` annotation.

**Comment by graemerocher** [comment]
There is no need to use `TransactionAspectSupport`:

    def serviceMethod() {
        transactionStatus.setRollbackOnly()
    }
