### ISSUE TITLE
Grails 3.0.6: application.yml config does not work

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-core#9248]
The following config in application.yml works fine with `org.springframework.boot:spring-boot-starter-security` in Grails 3.0.4.
```
security:
    ignored:
        - /assets/**
    basic:
        enabled: false
```
When upgrade to 3.0.6, it throws an exception:
```
Field error in object 'security' on field 'basic': rejected value [{enabled=false}]; codes [typeMismatch.security.basic,typeMismatch.basic,typeMismatch.org.springframework.boot.autoconfigure.security.SecurityProperties$Basic,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [security.basic,basic]; arguments []; default message [basic]]; default message [Failed to convert property value of type 'org.grails.config.NavigableMap' to required type 'org.springframework.boot.autoconfigure.security.SecurityProperties$Basic' for property 'basic'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.grails.config.NavigableMap] to required type [org.springframework.boot.autoconfigure.security.SecurityProperties$Basic] for property 'basic': no matching editors or conversion strategy found]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.validate(PropertiesConfigurationFactory.java:296)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:255)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:227)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:296)
	... 117 more
```

**Comment by graemerocher** [comment]
that config looks like YAML not Groovy?

**Comment by graemerocher** [comment]
It would help if you uploaded an example that reproduces the issue. Thanks.

**Comment by todoubaba** [comment]
@graemerocher, see https://github.com/todoubaba/issue9248, thanks.
