### ISSUE TITLE
NPE using the default constructor inside Promise (2.5.1)

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-core#9253]
https://github.com/grails/grails-core/blob/2.5.x/grails-plugin-mimetypes/src/main/groovy/org/codehaus/groovy/grails/plugins/web/api/RequestMimeTypesApi.groovy#L82

Something that may be important - I changed the security context holder to be INHERTABLE.

At that line request is a `DefaultMultipartHttpServletRequest`

At that line request.request is a `SecurityContextHolderAwareRequestWrapper[ FirewalledRequest[ org.apache.catalina.connector.RequestFacade@4048694b]]`. Calling `.class.name` on it returns `org.springframework.security.web.servletapi.HttpServlet3RequestFactory$Servlet3SecurityContextHolderAwareRequestWrapper`

The actual offending line is the `.getApplicationEventListeners();` called on a null context. L806 of `org.apache.catalina.connector.Request`

Stacktrace:
```
java.lang.NullPointerException
Error |
	at org.apache.catalina.connector.Request.notifyAttributeAssigned(Request.java:1493)
Error |
	at org.apache.catalina.connector.Request.setAttribute(Request.java:1483)
Error |
	at org.apache.catalina.connector.RequestFacade.setAttribute(RequestFacade.java:539)
Error |
	at javax.servlet.ServletRequestWrapper.setAttribute(ServletRequestWrapper.java:246)
Error |
	at javax.servlet.ServletRequestWrapper.setAttribute(ServletRequestWrapper.java:246)
Error |
	at javax.servlet.ServletRequestWrapper.setAttribute(ServletRequestWrapper.java:246)
Error |
	at org.codehaus.groovy.grails.plugins.web.api.RequestMimeTypesApi.getMimeTypes(RequestMimeTypesApi.groovy:82)
Error |
	at org.codehaus.groovy.grails.web.mime.DefaultMimeTypeResolver.resolveRequestMimeType(DefaultMimeTypeResolver.groovy:59)
Error |
	at org.codehaus.groovy.grails.web.mime.DefaultMimeTypeResolver.resolveRequestMimeType(DefaultMimeTypeResolver.groovy:57)
Error |
	at org.codehaus.groovy.grails.web.mime.MimeTypeUtils.resolveMimeType(MimeTypeUtils.groovy:34)
Error |
	at org.codehaus.groovy.grails.web.binding.DataBindingUtils.resolveMimeType(DataBindingUtils.java:379)
Error |
	at org.codehaus.groovy.grails.web.binding.DataBindingUtils.getMimeType(DataBindingUtils.java:361)
Error |
	at org.codehaus.groovy.grails.web.binding.DataBindingUtils.createDataBindingSource(DataBindingUtils.java:348)
Error |
	at org.codehaus.groovy.grails.web.binding.DataBindingUtils.bindObjectToDomainInstance(DataBindingUtils.java:245)
Error |
	at org.codehaus.groovy.grails.web.binding.DataBindingUtils.bindObjectToDomainInstance(DataBindingUtils.java:156)
Error |
	at org.codehaus.groovy.grails.plugins.web.api.ControllersDomainBindingApi.initialize(ControllersDomainBindingApi.java:63)
```

**Comment by graemerocher** [comment]
This would happen if the old request (not the async request) was used. Please upload an example with steps to reproduce.

**Comment by Schlogen** [comment]
https://github.com/Schlogen/test9253

Navigate to http://localhost:8080/testNPE/person/index

**Comment by Schlogen** [comment]
If I start the transaction in the controller by using `withTransaction` as the first line inside of task, it works.

**Comment by Schlogen** [comment]
I kept having issues with this. I eventually just ended up doing as a workaround:

```
Thread.start {
    Domain.withNewSession {
        Domain.withNewTransaction {
        }
    }
}
```

**Comment by graemerocher** [comment]
Duplicates #9198
