### ISSUE TITLE
GORM objects not persist-able in Integration Test fixture methods

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-core#9289]
In Grails 2.4.5 we were able to write a test like the following: 

```
    def setup() {
      new Book(title: 'The Stand').save(flush: true, failOnError: true)
    }

    void "test data was injected"() {
      expect:
      Book.count() == 1
    }
```

This no longer works in Grails 3.0.8. When I run the test above I get the following exception:

```
org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:117)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:1014)
	at org.grails.orm.hibernate.validation.HibernateDomainClassValidator.validate(HibernateDomainClassValidator.java:64)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:140)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:165)
	at bootstrap.test.data_308.BookSpec.setup(BookSpec.groovy:13)
```

Test projects for both 2.4.5 and 3.0.8 are attached. The failure can be triggered in grails 3.0.8 by running `grails test-app -integration`.

Test applications (onedrive public links):
* [bootstrap-test-data_245](http://1drv.ms/1G7Rd1N)
* [bootstrap-test-data_308](http://1drv.ms/1jiTu5p)

**Comment by joemccall86** [comment]
I'll also add that attempts to manually add a session to the `setup` method using `withNewSession` or `transactional` made that specific error go away, but `@Rollback` stopped working.

**Comment by burtbeckwith** [comment]
This is described in the docs - see the section "Using Spring's Rollback annotation" under https://grails.github.io/grails-doc/latest/guide/testing.html#integrationTesting

**Comment by joemccall86** [comment]
How embarassing, there it is plan as day. Sorry for the false-positive, and thanks for the quick reply!
