### ISSUE TITLE
Grails 2.5.1: Cannot access config in _Events.groovy

### ISSUE THREAD

**Issue by gilinykh** [grails/grails-core#9292]
Create a new app, using tomcat 8 plugin (build ":tomcat:8.0.22"). Add ```_Events.groovy``` to scripts directory:

```
import org.apache.catalina.Context
import org.apache.catalina.WebResourceRoot
import org.apache.catalina.webresources.StandardRoot
import grails.util.Holders

eventConfigureTomcat = { tomcat ->

    def ctx = tomcat.host.findChildren()[0]
    def alias = Holders.config.prop1
    def staticDir = Holders.config.prop2

    registerAliases(ctx, [(alias): staticDir])

    println "Context resources: ${ctx.resources.postResources*.base}"
}

def registerAliases(Context context, Map<String, String> aliases) {
    if (!aliases) {
        return
    }

    WebResourceRoot resources = context.resources
    if (!resources) {
        resources = new StandardRoot(context)
        context.resources = resources
    }

    aliases.each { String alias, String realPath ->
        URL realPathUrl = new File(realPath).toURI().toURL()
        resources.createWebResourceSet WebResourceRoot.ResourceSetType.POST, alias, realPathUrl, '/'
    }
}
```

Launching the app fails with:

```
Exception in thread "main" 
Error |
java.lang.NullPointerException: Cannot get property 'prop1' on null object
Error |
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
Error |
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
Error |
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)
Error |
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
Error |
	at _Events$_run_closure1.doCall(_Events.groovy:11)
```

Attempts to add ```includeTargets << grailsScript('_GrailsPackage')``` fails too: 
```
Error loading event script from file [C:\Projects\testEvents\scripts\_Events.groovy] No such property: classLoader for class: java.lang.Object (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
groovy.lang.MissingPropertyException: No such property: classLoader for class: java.lang.Object
	at grails.util.BuildSettings$1.doCall(BuildSettings.groovy:408)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at _Events.run(_Events.groovy:6)
	at org.grails.plugins.tomcat.fork.ForkedTomcatServer.createEventListener(ForkedTomcatServer.groovy:147)
	at org.grails.plugins.tomcat.fork.ForkedTomcatServer.createTomcatRunner(ForkedTomcatServer.groovy:107)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.grails.plugins.tomcat.fork.ForkedTomcatServer.runInternal(ForkedTomcatServer.groovy:85)
	at org.grails.plugins.tomcat.fork.ForkedTomcatServer.run(ForkedTomcatServer.groovy:69)
	at org.grails.plugins.tomcat.fork.ForkedTomcatServer$run.call(Unknown Source)
	at org.grails.plugins.tomcat.fork.ForkedTomcatServer.main(ForkedTomcatServer.groovy:63)
```

**Comment by graemerocher** [comment]
This kind of customization only works if you disable forking.

**Comment by jneira** [comment]
@gilinykh just in case you still need access grails config in `_Events.groovy` for grails-2.5 :smile: a possible workaround that worked for me could be:
* Replace `Holders.config` by `config`
* Create a method in the script:

```groovy
def getConfig() {
	ConfigSlurper cfgReader = new ConfigSlurper(Environment.getCurrent().getName())
	cfgReader.parse(new File("grails-app/conf/Config.groovy").toURI().toURL())
}
```
