### ISSUE TITLE
Migration from 2.5 to 3.0.8: NullPointer in unit test when defining a service bean with @Transactional

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#9297]
I have a simple unit test that uses `doWithSpring` to define a service bean for the unit test.

    @TestMixin(HibernateTestMixin)
    @Domain([Team])
    class TeamSpec extends Specification {

        static doWithSpring = {
            superService(SuperService)
        }

        def setup() {
            new Team(name: 'Hello', shortName: 'Big').save()
        }

        void "test something"() {
            expect:"fix me"
            !Team.findByName('hello')
        }
    }

This is the service class `SuperService``

    import grails.transaction.Transactional

    @Transactional(readOnly = true)
    class SuperService {

        def doSomething() {
            return true
        }
    }

and this is the domain class that uses the service as an validator.

    class Team {

        String name
        String shortName
        String image = 'noimage.jpg'

        transient superService

        static constraints = {
            name nullable: false, maxSize: 30, unique: true
            shortName nullable: true, maxSize: 5, validator: { val, obj ->
                if(!obj.superService.doSomething()) {
                    return ['existingBookingsConflict', val]
                }
                return true
            }
            image nullable: false, maxSize: 30
        }
    }

When I execute the test it results in an `NullPointerException`.

    java.lang.NullPointerException
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:90)
	at abc.Team._clinit__closure1$_closure2(Team.groovy:14)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.grails.validation.ValidatorConstraint.processValidate(ValidatorConstraint.java:87)
	at grails.validation.AbstractConstraint.validate(AbstractConstraint.java:107)
	at grails.validation.ConstrainedProperty.validate(ConstrainedProperty.java:979)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:211)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.orm.hibernate.validation.HibernateDomainClassValidator.validate(HibernateDomainClassValidator.java:72)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:140)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:101)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:112)
	at abc.TeamSpec.setup(TeamSpec.groovy:20)

The same test works fine in Grails 2.5.1 (and below). The example app can be found at https://github.com/saw303/abc.

**Comment by graemerocher** [comment]
Can be worked around by defining the following with `doWithSpring` instead:

    static doWithSpring = {
        transactionManagerPostProcessor(TransactionManagerPostProcessor)
        superService(SuperService)
    }
