### ISSUE TITLE
Application.groovy can't run grails application with intelliJ on grails 3.1.0.M1 and JDK 1.8u45

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9339]
I get following exceptions when I try to run Application.groovy

```
Error:Groovyc: BUG! exception in phase 'canonicalization' in source unit '/var/eejaz/pdev/gitlab/pdev/groovy_grails/grails/g3/bookshop/grails-app/conf/logback.groovy' Could not find which method <init>() to invoke from this list:
  public org.codehaus.groovy.grails.commons.ArtefactHandlerAdapter#<init>(java.lang.String, java.lang.Class, java.lang.Class, java.lang.String)
  public org.codehaus.groovy.grails.commons.ArtefactHandlerAdapter#<init>(java.lang.String, java.lang.Class, java.lang.Class, java.lang.String, boolean)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:935)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
	at org.jetbrains.groovy.compiler.rt.GroovyCompilerWrapper.compile(GroovyCompilerWrapper.java:62)
	at org.jetbrains.groovy.compiler.rt.DependentGroovycRunner.runGroovyc(DependentGroovycRunner.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jetbrains.groovy.compiler.rt.GroovycRunner.intMain2(GroovycRunner.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc.runGroovycInThisProcess(InProcessGroovyc.java:149)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc.access$000(InProcessGroovyc.java:48)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc$1.call(InProcessGroovyc.java:78)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc$1.call(InProcessGroovyc.java:75)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.runtime.metaclass.MethodSelectionException: Could not find which method <init>() to invoke from this list:
  public org.codehaus.groovy.grails.commons.ArtefactHandlerAdapter#<init>(java.lang.String, java.lang.Class, java.lang.Class, java.lang.String)
  public org.codehaus.groovy.grails.commons.ArtefactHandlerAdapter#<init>(java.lang.String, java.lang.Class, java.lang.Class, java.lang.String, boolean)
	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3200)
	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3137)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1710)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1529)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeConstructorOf(InvokerHelper.java:948)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.newInstance(DefaultGroovyMethods.java:15609)
	at org.grails.core.io.support.GrailsFactoriesLoader.loadFactoriesWithArguments(GrailsFactoriesLoader.groovy:65)
	at org.grails.core.io.support.GrailsFactoriesLoader.loadFactories(GrailsFactoriesLoader.groovy:47)
	at org.grails.compiler.injection.GlobalGrailsClassInjectorTransformation.visit(GlobalGrailsClassInjectorTransformation.groovy:57)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:321)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:931)
	... 22 more
```

However grails run-app command works fine.

**Comment by ejaz-ahmed** [comment]
This issue does not appear in grails 3.0.8. Just noted that Intellij can't properly recognize grails 3.1.x project created from grails cli. If it is created from Intellij interface itself, there is no issue. Looks like there might be something from Intellj side. I have reported this to the person working on grails support in Intellij and will update this issue once I hear back from him. If it turns out to be Intellij side of thing, I'll close it.

**Comment by ejaz-ahmed** [comment]
I talked about Intellij team. If I import it as gradle project, and wait quite a long time, intellij is actually doing stuff in the background even though its status bar shows it is idle, then I can run this with intellij. i have observed extra delay for grails 3.1.x in intellij as compared to 3.0. So it turns out to be intellij side.
