### ISSUE TITLE
Grails 3.0.8:inList contstraint can't be used in g:select tag

### ISSUE THREAD

**Issue by csusu** [grails/grails-core#9347]
I'v just upgraded from Grails 2.4.2 to 3.0.8 and all my gsp view pages including a **g:select** tag whose **from** property containing a **inList** reference of a domain class's constraint don't work any more, such as 
>GroovyPageView: [views/workEvent/mytasks.gsp:295] Error executing tag <g:form>: Error evaluating expression ***[WorkEvent.constraints.status.inList]*** on line [293]: No such property: status for class: WorkEvent
Possible solutions: status, start] with root cause
groovy.lang.MissingPropertyException: No such property: status for class: WorkEvent
Possible solutions: status, start
        at projects_itworks_grails_app_views_workEvent_mytasks_gsp$_run_closure2$_closure19$_closure105.doCall(projects_itworks_grails_app_views_workEvent_mytasks_gsp:59) ~[na:na]
        at projects_itworks_grails_app_views_workEvent_mytasks_gsp$_run_closure2$_closure19.doCall(projects_itworks_grails_app_views_workEvent_mytasks_gsp:59) ~[na:na]
        at projects_itworks_grails_app_views_workEvent_mytasks_gsp$_run_closure2.doCall(projects_itworks_grails_app_views_workEvent_mytasks_gsp:67) ~[na:na]
        at projects_itworks_grails_app_views_workEvent_mytasks_gsp.run(projects_itworks_grails_app_views_workEvent_mytasks_gsp:192) ~[na:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

So,is this a known bug and how can I fix it ?

**Comment by graemerocher** [comment]
You should use `WorkEvent.constrainedProperties` instead
