### ISSUE TITLE
Failed to apply gradle war plugin after upgrading Grails from 3.0.1 to 3.0.(6,7,8,9)

### ISSUE THREAD

**Issue by jd73** [grails/grails-core#9361]
I have a Grails application that builds fine at version 3.0.1.  However, when I upgrade it to 3.0.6 or later (not sure about 2-5), I get the following error:
```
10:21:30.108 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'project'.
10:21:30.108 [ERROR] [org.gradle.BuildExceptionReporter] > Failed to apply plugin [id 'org.gradle.war']
10:21:30.108 [ERROR] [org.gradle.BuildExceptionReporter]    > Cannot execute null+null
```

If I remove the 'war' plugin, it builds fine. That's not a very good workaround though.

Here's the stack trace:

```
10:21:30.109 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
10:21:30.109 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'project'.
10:21:30.110 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(    DefaultScriptRunnerFactory.java:93)
10:21:30.110 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(    DefaultScriptPluginFactory.java:148)
10:21:30.110 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
10:21:30.110 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(    DefaultScriptPluginFactory.java:153)
10:21:30.110 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38    )
10:21:30.110 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25    )
10:21:30.110 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(    ConfigureActionsProjectEvaluator.java:34)
10:21:30.111 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(    LifecycleProjectEvaluator.java:55)
10:21:30.111 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:491)
10:21:30.111 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:89)
10:21:30.111 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.    java:42)
10:21:30.111 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
10:21:30.111 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:126)
10:21:30.111 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Factories$1.create(Factories.java:22)
10:21:30.112 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(    DefaultBuildOperationExecutor.java:90)
10:21:30.112 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(    DefaultBuildOperationExecutor.java:52)
10:21:30.112 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.    java:123)
10:21:30.112 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
10:21:30.112 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:100)
10:21:30.112 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:94)
10:21:30.112 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(    DefaultBuildOperationExecutor.java:90)
10:21:30.112 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(    DefaultBuildOperationExecutor.java:62)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:94)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(    InProcessBuildActionExecuter.java:94)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner    .java:28)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter    .java:43)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter    .java:28)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(    ContinuousBuildActionExecuter.java:77)
10:21:30.113 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(    ContinuousBuildActionExecuter.java:47)
10:21:30.114 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(    DaemonUsageSuggestingBuildActionExecuter.java:51)
10:21:30.114 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(    DaemonUsageSuggestingBuildActionExecuter.java:28)
10:21:30.114 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
10:21:30.114 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
10:21:30.114 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(    CommandLineActionFactory.java:237)
10:21:30.115 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(    CommandLineActionFactory.java:210)
10:21:30.115 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.    java:35)
10:21:30.115 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.    java:24)
10:21:30.115 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(    CommandLineActionFactory.java:206)
10:21:30.115 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(    CommandLineActionFactory.java:169)
10:21:30.115 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.Main.doAction(Main.java:33)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [    id 'org.gradle.war']
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160    )
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(    DefaultObjectConfigurationAction.java:112)
10:21:30.116 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(    DefaultObjectConfigurationAction.java:35)
10:21:30.117 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(    DefaultObjectConfigurationAction.java:79)
10:21:30.117 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(    DefaultObjectConfigurationAction.java:135)
10:21:30.117 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
10:21:30.117 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
10:21:30.117 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
10:21:30.117 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
10:21:30.117 [ERROR] [org.gradle.BuildExceptionReporter]    at build_5ocov9dbopr4idkd2fje5zpqr.run(project/build.gradle:34)
10:21:30.118 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(    DefaultScriptRunnerFactory.java:91)
10:21:30.118 [ERROR] [org.gradle.BuildExceptionReporter]    ... 47 more
10:21:30.118 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException: Cannot execute null+null
10:21:30.118 [ERROR] [org.gradle.BuildExceptionReporter]    at org.grails.gradle.plugin.web.gsp.GroovyPagePlugin$_apply_closure5.doCall(GroovyPagePlugin.    groovy:66)
10:21:30.118 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
10:21:30.118 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
10:21:30.118 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
10:21:30.118 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:488)
10:21:30.119 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:58)
10:21:30.119 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
10:21:30.119 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:202)
10:21:30.119 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
10:21:30.119 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.    java:165)
10:21:30.119 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.    java:159)
10:21:30.120 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(    DefaultNamedDomainObjectCollection.java:81)
10:21:30.120 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:79)
10:21:30.120 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:97)
10:21:30.120 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.plugins.WarPlugin.apply(WarPlugin.java:74)
10:21:30.120 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.plugins.WarPlugin.apply(WarPlugin.java:38)
10:21:30.120 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(    ImperativeOnlyPluginApplicator.java:35)
10:21:30.120 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
10:21:30.121 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
10:21:30.121 [ERROR] [org.gradle.BuildExceptionReporter]    ... 58 more
```

**Comment by graemerocher** [comment]
Likely something to do with the structure of your build. Attach an example that reproduces the problem.

**Comment by jd73** [comment]
In what format would you like the example? I have a .tar.gz of the project but Github won't let me attach that.

**Comment by jd73** [comment]
https://github.com/jd73/nullNullExample

**Comment by jeffbrown** [comment]
If you move `apply plugin: 'war'` to be before `apply plugin: 'org.grails.grails-gsp'` does the problem go away?

**Comment by jd73** [comment]
That does seem to fix the problem.

**Comment by jeffbrown** [comment]
I am not sure why that works.  I just diffed your build file against a new 3.0.9 one and noticed that.  Will investigate.  Thanks for the feedback.

**Comment by jd73** [comment]
My pleasure. Thanks for the workaround.
