### ISSUE TITLE
DomainClassUnitTestMixin edge case

### ISSUE THREAD

**Issue by tcrossland** [grails/grails-core#9381]
After upgrading from 2.5.1 to 2.5.2, some unit test have started failing. Here's one of the edge cases I've isolated:

### Domain class with a `load` property and a `mapping` closure

````groovy
package my.app

class Domain {

    String load

    static mapping = {
      load column: 'amount'
    }
}
````
### Unit test for domain class

````groovy
package my.app

import grails.test.mixin.TestFor
import spock.lang.Specification

/**
 * See the API for {@link grails.test.mixin.domain.DomainClassUnitTestMixin} for usage instructions
 */
@TestFor(Domain)
class DomainSpec extends Specification {

    void "test something"() {
        expect:
        true
    }
}
````

### Stack trace in test execution
````
Failure:  |
test something(my.app.DomainSpec)
 |
java.lang.IllegalStateException: Method on class [my.app.Domain] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
        at my.app.Domain._clinit__closure1(Domain.groovy:8)
        at org.grails.datastore.mapping.config.groovy.MappingConfigurationBuilder.evaluate(MappingConfigurationBuilder.groovy:83)
        at org.grails.datastore.mapping.config.AbstractGormMappingFactory.createMappedForm(AbstractGormMappingFactory.java:58)
        at org.grails.datastore.mapping.keyvalue.mapping.config.GormKeyValueMappingFactory.createMappedForm(GormKeyValueMappingFactory.java:39)
        at org.grails.datastore.mapping.keyvalue.mapping.config.GormKeyValueMappingFactory.createMappedForm(GormKeyValueMappingFactory.java:28)
        at org.grails.datastore.mapping.keyvalue.mapping.config.KeyValuePersistentEntity.<init>(KeyValuePersistentEntity.java:35)
        at org.grails.datastore.mapping.keyvalue.mapping.config.KeyValueMappingContext.createPersistentEntity(KeyValueMappingContext.java:95)
        at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:174)
        at grails.test.mixin.domain.DomainClassUnitTestMixin.mockDomains(DomainClassUnitTestMixin.groovy:86)
        at grails.test.mixin.domain.DomainClassUnitTestMixin.mockDomain(DomainClassUnitTestMixin.groovy:119)
        at grails.test.mixin.domain.DomainClassUnitTestMixin.mockDomain(DomainClassUnitTestMixin.groovy:118)
        at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:153)
        at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
        at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
        at grails.test.runtime.TestRuntimeJunitAdapter$1$2.evaluate(TestRuntimeJunitAdapter.groovy:49)
        at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
        at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
        at grails.test.runtime.TestRuntimeJunitAdapter$3$4.evaluate(TestRuntimeJunitAdapter.groovy:76)
        at org.spockframework.runtime.extension.builtin.ClassRuleInterceptor.intercept(ClassRuleInterceptor.java:38)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
|Completed 1 unit test, 1 failed in 0m 4s
````

**Comment by tcrossland** [comment]
Correction: It seems this is not caused directly by updating from Grails 2.5.1. to Grails 2.5.2 (it also fails on 2.5.1). I'm trying to isolate the cause, may be JDK related.

**Comment by tcrossland** [comment]
Sorry, I haven't been able to isolate the cause. I've reproduced the issue with JDK 1.7.0_79 and JDK 1.8.0_60, using all Grails 2.4.x and 2.5.x. What I don't understand is why the test in question wasn't failing previously. Note that problem only seems to occur when the domain class has a property named `load` and a `mapping` block (not a particularly likely combination I expect). I'm happy to rename the property in my app, but curious to know why this fails.

Not sure if this is related, but other tests that started failing at the same time (coinciding with upgrade from 2.5.1 to 2.5.2) are ones with static metaclass methods in `setupSpec()`, e.g.:

````groovy
    def setupSpec() {
        Split.metaClass.static.executeQuery = { String hql, Collection params ->
            [10.0g]
        }
    }
````

It seems these no longer override the `TestGormStaticApi` methods.

**Comment by ttyusupov** [comment]
I think I have a small two-files test project to reproduce the issue: https://github.com/ttyusupov/grails-test-2-5-4/pull/1, grails output is listed in PR desc

**Comment by ttyusupov** [comment]
Fixed the test by commit https://github.com/ttyusupov/grails-test-2-5-4/pull/1/commits/bcb5c6c81eac3bb68d48a583bfe7556990b7f1ec. Probably this should be documented somewhere in docs or maybe better the error message to be self-documented.
