### ISSUE TITLE
stop-app command fails in grails 3.1.0.M2 

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9388]
I get following results when I run stop-app command.

```
grails> run-app
| Running application...
Grails application running at http://localhost:8080 in environment: development
grails> stop-app
| Error Command [stop-app] error: null (Use --stacktrace to see the full trace)
grails> 
grails> stop-app
| Error Command [stop-app] error: null (Use --stacktrace to see the full trace)
grails> 
```

Here is the stacktrace

```
grails> stop-app --stacktrace
| Error Command [stop-app] error: null (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.NullPointerException
	at org.grails.io.support.MainClassFinder.findMainClass(MainClassFinder.groovy:87)
	at org.grails.io.support.MainClassFinder.findMainClass(MainClassFinder.groovy)
	at org.grails.io.support.MainClassFinder$findMainClass.call(Unknown Source)
	at stop-app$_run_closure2.doCall(stop-app.groovy:14)
	at stop-app.run(stop-app.groovy:51)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
	at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:384)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:356)
	at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.doCall(GrailsCli.groovy:451)
	at org.grails.cli.GrailsCli$_handleCommandWithCancellationSupport_closure6.call(GrailsCli.groovy)
| Error Command [stop-app] error: null
```

**Comment by ejaz-ahmed** [comment]
After investigations, this issue does not appear if I create app in non-interactive grails console like this:
grails create-app bookshop31 --profile=web-api

However if I create app using interactive console, this issue appears. Launch grails first in some directory the use create-app bookshop31 --profile=web-api.

**Comment by graemerocher** [comment]
This works for me in master and I believe is fixed by https://github.com/grails/grails-core/commit/af752887219f6706d1c7ed0f234278719c91290b
