### ISSUE TITLE
RuntimeExceptions when reloading project

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#9453]
I am getting runtime error in Grails 2.5.x and 3.x. Whenever I change code in `dev` environment the following exception results over and over again.

It tries to load class definition for `ch/silviowangler/zscsupporter/ADDRESS__I` but there is only a class called `ch/silviowangler/zscsupporter/Address`

````
File /Users/saw/dev/zsc-supporter/grails-app/services/ch/silviowangler/zscsupporter/MemberService.groovy changed, recompiling...
java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:110)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:545)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:185)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:170)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:126)
	at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:678)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:310)
	at org.codehaus.groovy.control.ResolveVisitor.resolveFromModule(ResolveVisitor.java:612)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:310)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:278)
	at org.codehaus.groovy.control.ResolveVisitor.transformVariableExpression(ResolveVisitor.java:927)
	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:696)
	at org.codehaus.groovy.ast.expr.Expression.transformExpressions(Expression.java:51)
	at org.codehaus.groovy.ast.expr.ArgumentListExpression.transformExpression(ArgumentListExpression.java:69)
	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:713)
	at org.codehaus.groovy.control.ResolveVisitor.transformMethodCallExpression(ResolveVisitor.java:1063)
	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:704)
	at org.codehaus.groovy.control.ResolveVisitor.transformDeclarationExpression(ResolveVisitor.java:1090)
	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:700)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:142)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:37)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:166)
	at org.codehaus.groovy.control.ResolveVisitor.visitBlockStatement(ResolveVisitor.java:1320)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:104)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:115)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:53)
	at org.codehaus.groovy.control.ResolveVisitor.visitConstructorOrMethod(ResolveVisitor.java:203)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:126)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1086)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:53)
	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1263)
	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:178)
	at org.codehaus.groovy.control.CompilationUnit$11.call(CompilationUnit.java:651)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:931)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:542)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:525)
	at grails.boot.GrailsApp.compileGroovyFile(GrailsApp.groovy:254)
	at grails.boot.GrailsApp.recompile(GrailsApp.groovy:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:188)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.run(Closure.java:507)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springsource.loaded.ReloadException: Problem defining class ch.silviowangler.zscsupporter.ADDRESS__I
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1305)
	at org.springsource.loaded.ReloadableType.rewriteCallSitesAndDefine(ReloadableType.java:939)
	at org.springsource.loaded.ReloadableType.<init>(ReloadableType.java:173)
	at org.springsource.loaded.TypeRegistry.addType(TypeRegistry.java:1103)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:335)
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107)
	... 81 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1297)
	... 86 more
Caused by: java.lang.NoClassDefFoundError: ch/silviowangler/zscsupporter/ADDRESS__I (wrong name: ch/silviowangler/zscsupporter/Address__I)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	... 90 more
````

The affected class `Address` looks like that. There is no other class called `Address` in the classpath. 

````
package ch.silviowangler.zscsupporter

class Address {

    public static final Date END_DATE = Date.parse('dd.MM.yyyy HH:mm:ss', '31.12.2500 23:59:59')

    static belongsTo = [member: Member]

    String street
    String housenumber
    String postCode
    String city
    String additionalLine

    Date validFrom
    Date validTo

    static constraints = {
        street nullable: false, maxSize: 150, blank: false
        housenumber nullable: true, maxSize: 6
        postCode nullable: false, maxSize: 10, blank: false
        city nullable: false, maxSize: 60, blank: false
        validFrom nullable: false, attributes: [precision:"day"]
        validTo nullable: false, attributes: [precision:"day"]
        member nullable: false
        additionalLine nullable: true, maxSize: 200
    }

    @Override
    String toString() {
        return "${street} ${housenumber}, ${postCode} ${city} (${validFrom.format('dd.MM.yyyy HH:mm:ss')} - ${validTo?.format('dd.MM.yyyy HH:mm:ss')})"
    }

    String toShortFormat() {
        "${street} ${housenumber}, ${postCode} ${city}"
    }
}
````

**Comment by graemerocher** [comment]
This looks the same as https://github.com/grails/grails-core/issues/9296

**Comment by graemerocher** [comment]
As mentioned above this is almost certainly a bug in your package or class naming in your project, but if you want this looked by us please upload an example that reproduces the problem

**Comment by saw303** [comment]
After moving the constant `END_DATE` to a different class that error disappeared. The content of class `Address` is now:


    package ch.silviowangler.zscsupporter

    class Address {

    static belongsTo = [member: Member]

    String street
    String housenumber
    String postCode
    String city
    String additionalLine

    Date validFrom
    Date validTo

    static constraints = {
        street nullable: false, maxSize: 150, blank: false
        housenumber nullable: true, maxSize: 6
        postCode nullable: false, maxSize: 10, blank: false
        city nullable: false, maxSize: 60, blank: false
        validFrom nullable: false, attributes: [precision:"day"]
        validTo nullable: false, attributes: [precision:"day"]
        member nullable: false
        additionalLine nullable: true, maxSize: 200
    }

       @Override
       String toString() {
          return "${toStringShortFormat()} (${validFrom.format(Consts.DATETIME_FORMAT)} - ${validTo?.format(Consts.DATETIME_FORMAT)})"
       }

       String toStringShortFormat() {
        "${street} ${housenumber}, ${postCode} ${city}"
       }
    }

Is this behaviour expected when defining constants in domain classes?
