### ISSUE TITLE
Grails WAR on JBOSS EWS 2.0 Fails for version 3.0.9, 2.5.3 both on standalone and openshift

### ISSUE THREAD

**Issue by satshil** [grails/grails-core#9463]
Scenario
----------------------
I created vanilla a sample application using create-app and created a war out of it.
I am using provided scope for tomcat jars in build.gradle as describe in document.

Problem
----------------------
When I try to deploy this jar on JBoss ews 2.0 (based on tomcat 7) it fails. 
I am unable to trace the correct reason on openshift but my standalone offline server points me to following error

Error
-----------------------
1. Catalina_date_.log
Dec 7, 2015 12:24:05 AM org.apache.catalina.core.AprLifecycleListener init
INFO: The Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: .:/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
Dec 7, 2015 12:24:05 AM org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-8080
Dec 7, 2015 12:24:05 AM org.apache.coyote.ajp.AjpProtocol init
INFO: Initializing Coyote AJP/1.3 on ajp-8009
Dec 7, 2015 12:24:05 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 337 ms
Dec 7, 2015 12:24:05 AM org.apache.catalina.core.StandardService start
INFO: Starting service Catalina
Dec 7, 2015 12:24:05 AM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: JBoss Web/2.1.9.GA
Dec 7, 2015 12:24:05 AM org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-8080
Dec 7, 2015 12:24:05 AM org.apache.coyote.ajp.AjpProtocol start
INFO: Starting Coyote AJP/1.3 on ajp-8009
Dec 7, 2015 12:24:05 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 671 ms

2. Catalina.out
java.util.logging.ErrorManager: 4
java.io.FileNotFoundException: /logs/juli.2015-12-07.log (No such file or directory)
	at java.io.FileOutputStream.openAppend(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:192)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at java.io.FileWriter.<init>(FileWriter.java:61)
	at org.apache.juli.FileHandler.open(FileHandler.java:263)
	at org.apache.juli.FileHandler.<init>(FileHandler.java:59)
	at org.apache.juli.FileHandler.<init>(FileHandler.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:357)
	at java.lang.Class.newInstance(Class.java:310)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:418)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:363)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:241)
	at java.util.logging.LogManager$2.run(LogManager.java:264)
	at java.util.logging.LogManager$2.run(LogManager.java:262)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:262)
	at java.util.logging.LogManager.getLogManager(LogManager.java:245)
	at java.util.logging.Logger.<init>(Logger.java:225)
	at java.util.logging.LogManager$RootLogger.<init>(LogManager.java:1295)
	at java.util.logging.LogManager$RootLogger.<init>(LogManager.java:1293)
	at java.util.logging.LogManager$1.run(LogManager.java:176)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:153)
	at java.util.logging.Logger.demandLogger(Logger.java:280)
	at java.util.logging.Logger.getLogger(Logger.java:321)
	at org.jboss.logging.jdk.JDK14LoggerPlugin.init(JDK14LoggerPlugin.java:45)
	at org.jboss.logging.Logger.getDelegatePlugin(Logger.java:393)
	at org.jboss.logging.Logger.<init>(Logger.java:119)
	at org.jboss.logging.Logger.getLogger(Logger.java:357)
	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:54)
Dec 7, 2015 12:24:05 AM org.apache.catalina.core.AprLifecycleListener init
INFO: The Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: .:/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
Dec 7, 2015 12:24:05 AM org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-8080
Dec 7, 2015 12:24:05 AM org.apache.coyote.ajp.AjpProtocol init
INFO: Initializing Coyote AJP/1.3 on ajp-8009
Dec 7, 2015 12:24:05 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 337 ms
Dec 7, 2015 12:24:05 AM org.apache.catalina.core.StandardService start
INFO: Starting service Catalina
Dec 7, 2015 12:24:05 AM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: JBoss Web/2.1.9.GA
Dec 7, 2015 12:24:05 AM org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-8080
Dec 7, 2015 12:24:05 AM org.apache.coyote.ajp.AjpProtocol start
INFO: Starting Coyote AJP/1.3 on ajp-8009
Dec 7, 2015 12:24:05 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 671 ms

Other working scenarios
------------
same war works on Tomcat 7.0.54
same war works on Tomcat 7.0.65

Other Findings
-------------
I am not much deployment or tomcat expert but I found following tomcat jars in project.

Web-Inf/lib
tomcat-embed-logging-log4j-7.0.55.jar
tomcat-jdbc-7.0.55.jar
tomcat-juli-7.0.55.jar

web-inf/lib-provided
spring-boot-starter-tomcat-1.2.6.RELEASE.jar
tomcat-embed-core-8.0.26.jar
tomcat-embed-el-8.0.26.jar
tomcat-embed-logging-juli-8.0.26.jar
tomcat-embed-websocket-8.0.26.jar

**Comment by graemerocher** [comment]
Could you try remove the tomcat-judi JAR from the WAR and see if that helps? Will help us investigate the issue

**Comment by satshil** [comment]
Hi Graeme,
I managed to add some more logging settings and set level to FINEST.

jboss/conf/logging.properties
```
handlers = 1catalina.org.apache.juli.FileHandler, 2localhost.org.apache.juli.FileHandler, 3manager.org.apache.juli.FileHandler, 4admin.org.apache.juli.FileHandler, 5host-manager.org.apache.juli.FileHandler, java.util.logging.ConsoleHandler

.handlers = 1catalina.org.apache.juli.FileHandler, java.util.logging.ConsoleHandler

############################################################
# Handler specific properties.
# Describes specific configuration info for Handlers.
############################################################

1catalina.org.apache.juli.FileHandler.level = FINEST
1catalina.org.apache.juli.FileHandler.directory = ${catalina.base}/logs
1catalina.org.apache.juli.FileHandler.prefix = catalina.

2localhost.org.apache.juli.FileHandler.level = FINEST
2localhost.org.apache.juli.FileHandler.directory = ${catalina.base}/logs
2localhost.org.apache.juli.FileHandler.prefix = localhost.

3manager.org.apache.juli.FileHandler.level = FINEST
3manager.org.apache.juli.FileHandler.directory = ${catalina.base}/logs
3manager.org.apache.juli.FileHandler.prefix = manager.

5host-manager.org.apache.juli.FileHandler.level = FINEST
5host-manager.org.apache.juli.FileHandler.directory = ${catalina.base}/logs
5host-manager.org.apache.juli.FileHandler.prefix = host-manager.

java.util.logging.ConsoleHandler.level = FINEST
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter


############################################################
# Facility specific properties.
# Provides extra control for each logger.
############################################################

org.apache.catalina.core.ContainerBase.[Catalina].[localhost].level = FINEST
org.apache.catalina.core.ContainerBase.[Catalina].[localhost].handlers = 2localhost.org.apache.juli.FileHandler

org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/manager].level = FINEST
org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/manager].handlers = 3manager.org.apache.juli.FileHandler

org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/host-manager].level = FINEST
org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/host-manager].handlers = 5host-manager.org.apache.juli.FileHandler

# For example, set the com.xyz.foo logger to only log SEVERE
# messages:
org.apache.catalina.startup.ContextConfig.level = FINEST
org.apache.catalina.startup.HostConfig.level = FINEST
org.apache.catalina.session.ManagerBase.level = FINEST
org.apache.catalina.core.AprLifecycleListener.level=FINEST

```

It has following error on my local environment both tomcat-juli.jar included and excluded.

My local environment config
==========================
Grails 3.0.9
java version "1.8.0_60-ea"
Java(TM) SE Runtime Environment (build 1.8.0_60-ea-b05)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b05, mixed mode)
JBOSS-WEB-2.1.9.GA

```
java.io.FileNotFoundException: /logs/juli.2015-12-09.log (No such file or directory)
	at java.io.FileOutputStream.openAppend(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:192)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at java.io.FileWriter.<init>(FileWriter.java:61)
	at org.apache.juli.FileHandler.open(FileHandler.java:263)
	at org.apache.juli.FileHandler.<init>(FileHandler.java:59)
	at org.apache.juli.FileHandler.<init>(FileHandler.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:357)
	at java.lang.Class.newInstance(Class.java:310)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:418)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:363)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:241)
	at java.util.logging.LogManager$2.run(LogManager.java:264)
	at java.util.logging.LogManager$2.run(LogManager.java:262)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:262)
	at java.util.logging.LogManager.getLogManager(LogManager.java:245)
	at java.util.logging.Logger.<init>(Logger.java:225)
	at java.util.logging.LogManager$RootLogger.<init>(LogManager.java:1295)
	at java.util.logging.LogManager$RootLogger.<init>(LogManager.java:1293)
	at java.util.logging.LogManager$1.run(LogManager.java:176)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:153)
	at java.util.logging.Logger.demandLogger(Logger.java:280)
	at java.util.logging.Logger.getLogger(Logger.java:321)
	at org.jboss.logging.jdk.JDK14LoggerPlugin.init(JDK14LoggerPlugin.java:45)
	at org.jboss.logging.Logger.getDelegatePlugin(Logger.java:393)
	at org.jboss.logging.Logger.<init>(Logger.java:119)
	at org.jboss.logging.Logger.getLogger(Logger.java:357)
	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:54)
Dec 9, 2015 1:37:22 PM org.apache.catalina.core.AprLifecycleListener init
FINE: The Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: .:/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.core.AprLifecycleListener.init(AprLifecycleListener.java:136)
	at org.apache.catalina.core.AprLifecycleListener.lifecycleEvent(AprLifecycleListener.java:81)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.core.StandardServer.initialize(StandardServer.java:796)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:527)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:547)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:260)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:412)
Caused by: java.lang.UnsatisfiedLinkError: no tcnative-1 in java.library.path, no libtcnative-1 in java.library.pathCan't use Library.properties(.:/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java)
	at org.apache.tomcat.jni.Library.<init>(Library.java:77)
	at org.apache.tomcat.jni.Library.initialize(Library.java:178)
```

Find attached logs. Let me know how else I can help

**Comment by graemerocher** [comment]
Not sure to be honest, you will have to ask on the JBoss issue tracker what that means

**Comment by satshil** [comment]
similar issue.
http://stackoverflow.com/questions/33895757/deploying-war-to-openshift-404-error-not-found

**Comment by satshil** [comment]
In pursuit to solve the problem I tried same war on JBOSS AS 7.1.1 which cause context "/" not found error.

Environment setup
===============
1. disabled welcome page of JBOSS in standalone.xml
2. added jboss-web.xml to WEB-INF  (src/main/webapp/WEB-INF)
```
<?xml version="1.0" encoding="UTF-8"?>

<jboss-web>
    <context-root>/</context-root>
</jboss-web>
```
3. added web servlet entry into application groovy
```
grails:
    web:
        servlet:
            path: /
    profile: web
    ...
    ...
```
4. Created WAR from vanilla grails project 3.0.9.
5. renamed testApp-0.1.war.original to ROOT.war



ERROR
=============
```
11:33:12,658 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-1) Exception starting filter applicationContextIdFilter: java.lang.InstantiationException: org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter
	at java.lang.Class.newInstance(Class.java:368) [rt.jar:1.7.0_80-ea]
	at org.jboss.as.web.deployment.WebInjectionContainer.newInstance(WebInjectionContainer.java:80) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.web.deployment.WebInjectionContainer.newInstance(WebInjectionContainer.java:72) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:441) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:3269) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3865) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80-ea]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80-ea]

11:33:12,665 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-1) Exception starting filter webRequestLoggingFilter: java.lang.InstantiationException: org.springframework.boot.actuate.trace.WebRequestTraceFilter
	at java.lang.Class.newInstance(Class.java:368) [rt.jar:1.7.0_80-ea]
	at org.jboss.as.web.deployment.WebInjectionContainer.newInstance(WebInjectionContainer.java:80) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.web.deployment.WebInjectionContainer.newInstance(WebInjectionContainer.java:72) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:441) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:3269) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3865) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80-ea]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80-ea]

11:33:12,670 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-1) Exception starting filter metricFilter: java.lang.InstantiationException: org.springframework.boot.actuate.autoconfigure.MetricsFilter
	at java.lang.Class.newInstance(Class.java:368) [rt.jar:1.7.0_80-ea]
	at org.jboss.as.web.deployment.WebInjectionContainer.newInstance(WebInjectionContainer.java:80) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.web.deployment.WebInjectionContainer.newInstance(WebInjectionContainer.java:72) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:441) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:3269) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3865) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80-ea]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80-ea]

11:33:12,675 ERROR [org.apache.catalina.core.StandardContext] (MSC service thread 1-1) Error filterStart
11:33:12,675 ERROR [org.apache.catalina.core.StandardContext] (MSC service thread 1-1) Context [] startup failed due to previous errors
11:33:12,713 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC00001: Failed to start service jboss.web.deployment.default-host./: org.jboss.msc.service.StartException in service jboss.web.deployment.default-host./: JBAS018040: Failed to start context
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:95)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80-ea]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80-ea]

11:33:13,008 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 2) {"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"JBAS014671: Failed services" => {"jboss.web.deployment.default-host./" => "org.jboss.msc.service.StartException in service jboss.web.deployment.default-host./: JBAS018040: Failed to start context"}}}}
```

Help Taken from
==========
http://stackoverflow.com/questions/21957060/jboss-deploying-in-root-context
http://stackoverflow.com/questions/33143965/grails-3-war-in-jboss-eap-6-2-0-does-not-work
http://stackoverflow.com/questions/23279213/spring-boot-war-doesn%C2%B4t-work-on-jboss-7-1

**Comment by graemerocher** [comment]
Try removing the dependency

       compile "org.springframework.boot:spring-boot-starter-actuator"

As the long error is triggered from Boot's actuators

**Comment by graemerocher** [comment]
As per #9481 these are container specific configuration problems not related to Grails itself
