### ISSUE TITLE
[Grails 2.5.3] Cannot serve mp4 to Safari browser.

### ISSUE THREAD

**Issue by smallufo** [grails/grails-core#9468]
```
def index() {
    def file = new File('/tmp/big_buck_bunny_720p_50mb.mp4')
    println "file = ${file} , length = ${file.length()}"

    if (file.exists()) {
      webRequest.renderView = false;
      response.setContentType("video/mp4")
      response.setHeader("Content-disposition", "inline; filename=" + URLEncoder.encode(file.name, "UTF-8"));
      response.setHeader("Content-Length", String.valueOf(file.length()));

      InputStream is = new FileInputStream(file);

      response.outputStream << is
      response.outputStream.flush()
      response.outputStream.close()
      is.close()
    }
  } // index 
```

It can correctly serve mp4 file to Firefox , but in Safari (9.0.1 on OS/X) , it's not playing , and the server reports :

```
Broken pipe. Stacktrace follows:
java.io.IOException: Broken pipe
	at hello.StreamController$_closure2.doCall(StreamController.groovy:37)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:53)
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthRedirectFilter.doFilter(FacebookAuthRedirectFilter.groovy:46)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
	at org.tonyzampogna.xss.sanitizer.filter.XssFilter.doFilterInternal(XssFilter.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

I don't know if the problem is in Grails or Safari ?
But if I put the file into any remote file server (such as S3) , Safari can correctly play the file .

**Comment by graemerocher** [comment]
impacts 2.5.x and you should use `render file:`
