### ISSUE TITLE
Blank app with profile=web-micro throw NPE

### ISSUE THREAD

**Issue by HardyLoppmann** [grails/grails-core#9469]
use following env. on OS X
```
➜  apps git:(master) ✗ grails --version
| Grails Version: 3.0.10
| Groovy Version: 2.4.5
| JVM Version: 1.8.0_60
```
create a app with the profile "web-micro" an try to start
```
➜  apps git:(master) ✗ grails create-app foo --profile=web-micro
➜  apps git:(master) ✗ cd foo

➜  foo git:(master) ✗ grails run-app --stacktrace --verbose
| Error Error occurred running Grails CLI: null
java.lang.NullPointerException
	at org.codehaus.groovy.control.ResolveVisitor.visitConstructorOrMethod(ResolveVisitor.java:196)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:126)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1086)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:53)
	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1263)
	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:178)
	at org.codehaus.groovy.control.CompilationUnit$11.call(CompilationUnit.java:651)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:931)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:542)
	at org.springframework.boot.cli.compiler.GroovyCompiler.compile(GroovyCompiler.java:200)
	at org.springframework.boot.cli.command.run.SpringApplicationRunner.compileAndRun(SpringApplicationRunner.java:96)
	at org.springframework.boot.cli.command.run.RunCommand$RunOptionHandler.run(RunCommand.java:108)
	at org.springframework.boot.cli.command.options.OptionHandler.run(OptionHandler.java:91)
	at org.springframework.boot.cli.command.OptionParsingCommand.run(OptionParsingCommand.java:54)
	at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:223)
	at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:172)
	at org.grails.cli.boot.SpringInvoker.invokeMethod(SpringInvoker.groovy:60)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at run-app.run(run-app.groovy:14)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
	at org.grails.cli.profile.DefaultProfile.handleCommand(DefaultProfile.groovy:177)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:295)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:276)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:254)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:153)
| Error Error occurred running Grails CLI: null
➜  foo git:(master) ✗
```

**Comment by HardyLoppmann** [comment]
take a look here too http://grails.1312388.n4.nabble.com/NPE-when-run-a-app-created-with-web-micro-profile-td4659942.html

**Comment by donalmurtagh** [comment]
The web-micro profile doesn't seem to work in Grails 3.1.0. If you list the profiles it's not mentioned

`grails list-profiles`

```| Available Profiles
--------------------
* angular - A profile for creating applications using AngularJS
* rest-api - Profile for Web API applications
* base - The base profile extended by other profiles
* plugin - Profile for plugins designed to work across all profiles
* web - Profile for Web applications
* web-plugin - Profile for Plugins designed for Web applications
```

And if you try to create a web-micro app you get an error

`grails> create-app --inplace --profile=web-micro`

> Resolving dependencies...
> | Error Command [create-app] error: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.grails.profiles:web-micro:jar:3.1.0 in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

**Comment by bruno-lopes** [comment]
The same here:

` grails --version`
```
| Grails Version: 3.1.4
| Groovy Version: 2.4.6
| JVM Version: 1.8.0_74
```

`grails list-profiles`
```
| Available Profiles
--------------------
* angular - A profile for creating applications using AngularJS
* rest-api - Profile for Web API applications
* base - The base profile extended by other profiles
* plugin - Profile for plugins designed to work across all profiles
* web - Profile for Web applications
* web-plugin - Profile for Plugins designed for Web applications

```

`grails create-app testGrails314WebMicro --profile=web-micro --stacktrace`
```
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:web-micro:jar:3.1.4 in grailsCentral (https://repo.grails.org/grails/core) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.grails.profiles:web-micro:jar:3.1.4 in grailsCentral (https://repo.grails.org/grails/core)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:302)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:112)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:104)
	at org.grails.cli.profile.repository.MavenProfileRepository.resolveProfile(MavenProfileRepository.groovy:84)
	at org.grails.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:69)
	at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:139)
	at org.grails.cli.GrailsCli.executeCommandWithArgumentValidation(GrailsCli.groovy:288)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:264)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:web-micro:jar:3.1.4 in grailsCentral (https://repo.grails.org/grails/core)
```

Any plans to bring web-micro profile back to Grails?

**Comment by Schlogen** [comment]
No current plans to bring back a Grails supported `web-micro` profile. For users that desire this functionality, you can create the profile for your use.

**Comment by gekosurf** [comment]
Ouch... 
Can you provide details on how to start making this profile.
