### ISSUE TITLE
[3.1.0.M2] Multimodule project: Another unnamed CacheManager already exists in the same VM.

### ISSUE THREAD

**Issue by akozel** [grails/grails-core#9521]
I have a 'core project', and a 'manager project'.
manager depends on core, build.gradle : `compile project(':core')`.
When I run manager application localy with Idea via 'grails run-app' or 'GrailsApp.run(Application, args)' it's fine. But when I deploy war in remote tomcat 7 it throws an exception:

```
Caused by: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: DefaultConfigurationSource [ ehcache.xml or ehcache-failsafe.xml ]
	at net.sf.ehcache.CacheManager.assertNoCacheManagerExistsWithSameName(CacheManager.java:628)
	at net.sf.ehcache.CacheManager.init(CacheManager.java:392)
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:270)
	at org.hibernate.cache.ehcache.EhCacheRegionFactory.start(EhCacheRegionFactory.java:86)
	... 65 more
```

When I deploy core everything is ok.

**Comment by augrtur** [comment]
I'm seeing this in Toncat 8 on Amazon Linux but not in Tomcat 7

**Comment by graemerocher** [comment]
Please upload an example to github with steps to reproduce

**Comment by graemerocher** [comment]
No feedback provided
