### ISSUE TITLE
grails 3.0.12-SNAPSHOT - workflow problem with making tomcat7 war and running app in dev mode

### ISSUE THREAD

**Issue by rvanderwerf** [grails/grails-core#9558]
We're having a problem on a project where we tried to use the solution to make the war work for tomcat7 by setting the dependency for "org.springframework.boot:spring-boot-starter-tomcat" to 'provided' (https://github.com/grails/grails-doc/commit/68883277b556159372c481822f0325807b9320e6). However when we do that, we can no longer develop and run the app locally without setting it back to 'compile' or we get the following exception starting the app from Application.main in intellij 15:

```
Exception in thread "main" org.grails.core.exceptions.GrailsConfigurationException: Error loading application.groovy due to [java.lang.NoClassDefFoundError]: Unable to load class org.grails.web.servlet.mvc.GrailsWebRequest due to missing dependency javax/servlet/http/HttpSession
	at org.grails.core.cfg.GroovyConfigPropertySourceLoader.load(GroovyConfigPropertySourceLoader.groovy:63)
	at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:126)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:385)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:373)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:343)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:176)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:146)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:139)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:127)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:286)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:54)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:346)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:335)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at rocketmiles.app.Application.main(Application.groovy:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NoClassDefFoundError: Unable to load class org.grails.web.servlet.mvc.GrailsWebRequest due to missing dependency javax/servlet/http/HttpSession
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:391)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:265)
	at org.codehaus.groovy.ast.ClassNode.getAnnotations(ClassNode.java:1425)
	at org.codehaus.groovy.ast.ClassNode.getAnnotations(ClassNode.java:1424)
	at org.grails.datastore.gorm.query.transform.DetachedCriteriaTransformer.isDomainClass(DetachedCriteriaTransformer.java:1340)
	at org.grails.datastore.gorm.query.transform.DetachedCriteriaTransformer.visitMethodCallExpression(DetachedCriteriaTransformer.java:377)
	at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:66)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBinaryExpression(CodeVisitorSupport.java:146)
	at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:51)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:196)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:37)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:166)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitClosureExpression(CodeVisitorSupport.java:176)
	at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:45)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBinaryExpression(CodeVisitorSupport.java:146)
	at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:51)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:196)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:37)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:166)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:104)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:115)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:126)
	at org.grails.datastore.gorm.query.transform.DetachedCriteriaTransformer.visitMethod(DetachedCriteriaTransformer.java:189)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1086)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:53)
	at org.grails.datastore.gorm.query.transform.DetachedCriteriaTransformer.visitClass(DetachedCriteriaTransformer.java:176)
	at org.grails.datastore.gorm.query.transform.GlobalDetachedCriteriaASTTransformation.visit(GlobalDetachedCriteriaASTTransformation.java:51)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:321)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:931)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:212)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:222)
	at groovy.lang.GroovyClassLoader$parseClass.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at groovy.util.ConfigSlurper.parse(ConfigSlurper.groovy:170)
	at org.grails.core.cfg.GroovyConfigPropertySourceLoader.load(GroovyConfigPropertySourceLoader.groovy:57)
	... 26 more
```
Is this a bug or perhaps there is a workflow I am missing? The quickest solution I can think of would be  leave it compile, and override the war task and forcefully remove the jar from the war file but that seems hackish - perhaps there is something I am missing.

This is the block in our build.gradle:

```
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    // per ticket set this to provided or war will not run in tomcat7
    //https://github.com/grails/grails-doc/commit/68883277b556159372c481822f0325807b9320e6
    provided "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"
```

**Comment by sbglasius** [comment]
Reported to JetBrains at https://youtrack.jetbrains.com/issue/IDEA-150351?query=gradle%2Bprovided

**Comment by jeffbrown** [comment]
Please vote up https://youtrack.jetbrains.com/issue/IDEA-107048.

**Comment by jeffbrown** [comment]
> The quickest solution I can think of would be leave it compile, and override the war task and forcefully remove the jar from the war file

One problem with that is it doesn't account for the transitive dependencies.  While a bit more hassle, I think a better solution is to leave the build as it should be (provided) and after importing the project in the IDE, adjust the project dependencies in the IDE and turn those dependencies into compile time.  That way the Gradle build (which presumably is used to build the release) is left as it should be and the hackishness is quarantined to the IDE project settings.

**Comment by graemerocher** [comment]
Believe this is fixed
