### ISSUE TITLE
3.0.12-SNAPSHOT - Error running WARs under Tomcat7

### ISSUE THREAD

**Issue by rvanderwerf** [grails/grails-core#9560]
We're having an issue with running a war under grails 3.0.12-SNAPSHOT that throws an error in GrailsAutoConfiguration throws a java.net.MalformedURLException with a truncated jar file name:
Caused by: java.net.MalformedURLException: no !/ in spec
        at java.net.URL.<init>(URL.java:623) ~[na:1.7.0_80]
        at java.net.URL.<init>(URL.java:486) ~[na:1.7.0_80]
        at java.net.URL.<init>(URL.java:435) ~[na:1.7.0_80]
        at grails.boot.config.GrailsAutoConfiguration$ApplicationRelativeClassLo
ader.<init>(GrailsAutoConfiguration.groovy:222) ~[grails-core-3.0.12.BUILD-SNAPS
HOT.jar:3.0.12.BUILD-SNAPSHOT]
        at grails.boot.config.GrailsAutoConfiguration$GrailsClasspathIgnoringRes
ourceResolver.<init>(GrailsAutoConfiguration.groovy:182) ~[grails-core-3.0.12.BU
ILD-SNAPSHOT.jar:3.0.12.BUILD-SNAPSHOT]

Which causes the app not to start at all under tomcat7. I created a sample app that has the issue as well as our client app.

**Comment by rvanderwerf** [comment]
[tomcat7test.zip](https://github.com/grails/grails-core/files/88120/tomcat7test.zip)
this works with the PR I'm about to send.
