### ISSUE TITLE
AsyncWebRequest IllegalStateException when using render method with just the status code

### ISSUE THREAD

**Issue by sofiaguyang** [grails/grails-core#9585]
Rendering just the status code asynchronously throws IllegalStateException and also doubles the execution of the action (as you can see with 'hello' being printed out twice in the first image below). 

In the synchronous version, rendering does not have the same problem and an object is returned with a predefined message attribute. 

Adding a text argument to the asynchronous render call e.g. `render status: 404, text: ''` dispels the problem. I've not had the time to do a trace -- but rendering behavior is expected to be consistent whether synchronous or asynchronous. 

### Async rendering
![async-render](https://cloud.githubusercontent.com/assets/4891894/12528494/a048643c-c1d2-11e5-9f52-63c8a2ff17ab.png)
```
Grails application running at http://localhost:8080 in environment: development
hello
hello
ERROR org.grails.web.errors.GrailsExceptionResolver - IllegalStateException occurred when processing request: [POST] /keys
Can't set AsyncWebRequest with concurrent handling in progress. Stacktrace follows:
java.lang.IllegalStateException: Can't set AsyncWebRequest with concurrent handling in progress
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

### Synchronous rendering 
![screen shot 2016-01-23 at 11 55 30 am](https://cloud.githubusercontent.com/assets/4891894/12528495/aa42f0c4-c1d2-11e5-9a46-9571e1c300fe.png)

**Comment by graemerocher** [comment]
This is probably because the response has not been committed. It is hard to tell if the response has been committed by only setting the `status` code. Adding:

      response.flush() 

Will probably fix the problem in the async case.
