### ISSUE TITLE
error during grails startup

### ISSUE THREAD

**Issue by sunilpes** [grails/grails-core#9609]
I am using 3.0.12 grails java 1.8.0_25 windows 10. When i fire Grails inside my project:

| Error Error occurred running Grails CLI: mapping values are not allowed here
 in 'reader', line 21, column 7:
    grails:
          ^

mapping values are not allowed here
 in 'reader', line 21, column 7:
    grails:
          ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
        at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:124)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:104)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:502)
        at org.grails.config.CodeGenConfig.loadYml(CodeGenConfig.groovy:144)
        at org.grails.config.CodeGenConfig$_loadYml_closure1.doCall(CodeGenConfig.groovy:129)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1207)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1674)
        at org.grails.config.CodeGenConfig.loadYml(CodeGenConfig.groovy:128)
        at org.grails.cli.GrailsCli.loadApplicationConfig(GrailsCli.groovy:455)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:241)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:153)
| Error Error occurred running Grails CLI: mapping values are not allowed here
 in 'reader', line 21, column 7:
    grails:
          ^
I am facing this error 

attached appliaction.yml file
[application.txt](https://github.com/grails/grails-core/files/110166/application.txt)

**Comment by sunilpes** [comment]
wrong use document separation ---
