### ISSUE TITLE
Grails 3.1 Defining a classpath resouce in watchedResources causes StringIndexOutOfBoundsException exception

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-core#9610]
Example config:

```
    def watchedResources = ["file:./src/bpm/**/*.bpmn",
                            "classpath:*.bpmn*.xml",
                            "classpath:*.bpmn",
                            "file:./src/bpm/**/*.bpmn*.xml",
                            "file:./src/bpm/**/*.png",
                            "file:./src/taskforms/**/*.form"]
```

It originally was `"classpath*:*.bpmn"` and I tried the above with the same result

Exception occurs here: https://github.com/grails/grails-core/blob/51014578ecb64837cc82853ab96ae6e4545edf3c/grails-core/src/main/groovy/grails/boot/GrailsApp.groovy#L171

`wp.directory.path` is resolving to `"classpath:"` and the code expects it to be an absolute path.

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -48
	at java.lang.String.substring(String.java:1931)
	at java_lang_String$substring$5.call(Unknown Source)
	at grails.boot.GrailsApp.enableDevelopmentModeWatch(GrailsApp.groovy:171)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:64)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:353)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:342)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at test.plugins.Application.main(Application.groovy:9)
```

**Comment by jeffbrown** [comment]
@Schlogen Do you know if this only happens in 3.1.x?

**Comment by Schlogen** [comment]
@jeffbrown I didn't test this in 3.0.x

**Comment by MilesBehind** [comment]
In grails 3.1.5 the behaviour is really odd: using `"file:./grails-app/foo/Bar.groovy"` as watched resource, leads to the problem that no file change events are fired since the leading dot remains in the path that is compared to the path of the changed file (see lines 178 and 183 ('path') compared to lines 164 and 170 ('canonicalPath') of `GrailsApp.groovy` below). If the leading dot is omitted from the watched resource, then a StringIndexOutOfBoundsException is raised.
I think, that in lines 178 and 183 the term "path" should be replaced by "canonicalPath" to solve this problem.

GrailsApp.groovy:
```
159                    for(WatchPattern wp in new ArrayList<WatchPattern>(watchedResourcePatterns)) {
160                        boolean first = true
161                        for(watchBase in watchBaseDirectories) {
162                            if(!first) {
163                                if(wp.file != null) {
164                                    String relativePath = wp.file.canonicalPath - baseDirPath
165                                    File watchFile = new File(watchBase, relativePath)
166                                    // the base project will already been in the list of watch patterns, but we add any subprojects here
167                                    plugin.watchedResourcePatterns.add(new WatchPattern(file: watchFile, extension: wp.extension))
168                                }
169                                else if(wp.directory != null) {
170                                    String relativePath = wp.directory.canonicalPath - baseDirPath
171                                    File watchDir = new File(watchBase, relativePath)
172                                    // the base project will already been in the list of watch patterns, but we add any subprojects here
173                                    plugin.watchedResourcePatterns.add(new WatchPattern(directory: watchDir, extension: wp.extension))
174                                }
175                            }
176                            first = false
177                            if(wp.file) {
178                                def resolvedPath = new File(watchBase, wp.file.path.substring(locationLength))
179                                directoryWatcher.addWatchFile(resolvedPath)
180                            }
181                            else if(wp.directory && wp.extension) {
182
183                                def resolvedPath = new File(watchBase, wp.directory.path.substring(locationLength))
184                                directoryWatcher.addWatchDirectory(resolvedPath, wp.extension)
185                            }
186                        }
187                    }
```
