### ISSUE TITLE
WARNING: There was an error setting up reloading. Changes to classes will not be reflected: Illegal char <:> at index 1: [:]\grails-app\services

### ISSUE THREAD

**Issue by pathiksoni** [grails/grails-core#9623]
on windows Intellij when I run my grails App I am getting following error. Here is a complete stacktrace. I am using grails 2.5.3

Error |
Exception in thread "Thread-11" 
Error |
java.nio.file.InvalidPathException: Illegal char <:> at index 1: [:]\grails-app\services
Error |
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
Error |
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
Error |
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
Error |
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
Error |
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
Error |
	at java.io.File.toPath(File.java:2234)
Error |
	at org.codehaus.groovy.grails.compiler.WatchServiceDirectoryWatcher.addWatchDirectory(WatchServiceDirectoryWatcher.java:142)
Error |
	at org.codehaus.groovy.grails.compiler.DirectoryWatcher.addWatchDirectory(DirectoryWatcher.java:103)
Error |
	at org.codehaus.groovy.grails.compiler.DirectoryWatcher.addWatchDirectory(DirectoryWatcher.java:130)
Error |
	at org.codehaus.groovy.grails.project.compiler.GrailsProjectWatcher.initPluginWatchPatterns(GrailsProjectWatcher.java:189)
Error |
	at org.codehaus.groovy.grails.project.compiler.GrailsProjectWatcher.run(GrailsProjectWatcher.java:158)
....Error 
|
java.nio.file.InvalidPathException: Illegal char <:> at index 1: [:]\grails-app\services
Error |
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
Error |
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
Error |
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
Error |
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
Error |
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
Error |
	at java.io.File.toPath(File.java:2234)
Error |
	at org.codehaus.groovy.grails.compiler.WatchServiceDirectoryWatcher.addWatchDirectory(WatchServiceDirectoryWatcher.java:142)
Error |
	at org.codehaus.groovy.grails.compiler.DirectoryWatcher.addWatchDirectory(DirectoryWatcher.java:103)
Error |
	at org.codehaus.groovy.grails.compiler.DirectoryWatcher.addWatchDirectory(DirectoryWatcher.java:130)
Error |
	at org.codehaus.groovy.grails.project.compiler.GrailsProjectWatcher.initPluginWatchPatterns(GrailsProjectWatcher.java:189)
Error |
	at org.codehaus.groovy.grails.project.compiler.GrailsProjectWatcher.run(GrailsProjectWatcher.java:158)
Error |
	at java_lang_Runnable$run.call(Unknown Source)
Error |
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
Error |
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
Error |
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
Error |
	at org.codehaus.groovy.grails.cli.fork.ForkedGrailsProcess.startProjectWatcher(ForkedGrailsProcess.groovy:748)
Error |
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error |
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error |
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error |
	at java.lang.reflect.Method.invoke(Method.java:497)
Error |
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
Error |
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
Error |
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
Error |
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
Error |
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
Error |
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1155)
Error |
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
Error |
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
Error |
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
Error |
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
Error |
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
Error |
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
Error |
	at org.codehaus.groovy.grails.cli.fork.ForkedGrailsProcess$_setupReloading_closure17.doCall(ForkedGrailsProcess.groovy:737)
Error |
	at org.codehaus.groovy.grails.cli.fork.ForkedGrailsProcess$_setupReloading_closure17.doCall(ForkedGrailsProcess.groovy)
Error |
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error |
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error |
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error |
	at java.lang.reflect.Method.invoke(Method.java:497)
Error |
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
Error |
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
Error |
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
Error |
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
Error |
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
Error |
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
Error |
	at groovy.lang.Closure.call(Closure.java:426)
Error |
	at groovy.lang.Closure.call(Closure.java:420)
Error |
	at groovy.lang.Closure.run(Closure.java:507)
Error |
	at java.lang.Thread.run(Thread.java:745)

**Comment by graemerocher** [comment]
Fixed in this commit https://github.com/grails/grails-core/commit/7e319fa8a5d0969ad32df9776bcc39bcdaa2a555

**Comment by pathiksoni** [comment]
I see that the milestone is 3.0.14 Can this also be added to Grails 2.X?
