### ISSUE TITLE
[3.1.0] Mocking domains using @Mock and Mock(Domain) or GroovyMock(Domain) causes "attempted  duplicate class definition" by FastClassByCGLIB for big projects

### ISSUE THREAD

**Issue by droggo** [grails/grails-core#9632]
I'm not able to reproduce this yet on small project to provide example. But issues can be resolved by removing lines:
`SpecificDomain domain = Mock()` and `SpecificDomain domain = GroovyMock()`

It looks like using `@Mock(SpecificDomain)` and one of above, may cause duplicate class exception. There are two errors which can occur. If `@Mock()` was called before `= Mock()` (in different test files), there will be following error in line with `=Mock()`:

```
java.lang.ExceptionInInitializerError
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.objenesis.ObjenesisHelper.newInstance(ObjenesisHelper.java:43)
	at org.spockframework.mock.runtime.MockInstantiator$ObjenesisInstantiator.instantiate(MockInstantiator.java:45)
	at org.spockframework.mock.runtime.MockInstantiator.instantiate(MockInstantiator.java:31)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$CglibMockFactory.createMock(ProxyBasedMockFactory.java:92)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:49)
	at org.spockframework.mock.runtime.GroovyMockFactory.create(GroovyMockFactory.java:66)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
	at org.spockframework.lang.SpecInternals.GroovyMockImpl(SpecInternals.java:179)
	at error.DomainSpec.ensure domain may be mocked(DomainSpec.groovy:62)
Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
	at net.sf.cglib.reflect.FastClass$Generator.create(FastClass.java:64)
	at net.sf.cglib.proxy.MethodProxy.helper(MethodProxy.java:81)
	at net.sf.cglib.proxy.MethodProxy.create(MethodProxy.java:46)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
	... 16 more
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "error/SpecificDomain$$FastClassByCGLIB$$c2e943e1"
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	... 18 more
```
and for other methods in the same test:
```
java.lang.NoClassDefFoundError: Could not initialize class error.SpecificDomain$$EnhancerByCGLIB$$e65d3000
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.objenesis.ObjenesisHelper.newInstance(ObjenesisHelper.java:43)
	at org.spockframework.mock.runtime.MockInstantiator$ObjenesisInstantiator.instantiate(MockInstantiator.java:45)
	at org.spockframework.mock.runtime.MockInstantiator.instantiate(MockInstantiator.java:31)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$CglibMockFactory.createMock(ProxyBasedMockFactory.java:92)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:49)
	at org.spockframework.mock.runtime.GroovyMockFactory.create(GroovyMockFactory.java:66)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
	at org.spockframework.lang.SpecInternals.GroovyMockImpl(SpecInternals.java:179)
	at error.DomainSpec.ensure other spec can also mock domain(DomainSpec.groovy:79)
```

If `=Mock()` is called before `@Mock` in test execution order, class with `@Mock` will not compile providing following error:
```
org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:256)
	at org.springframework.cglib.reflect.FastClass$Generator.create(FastClass.java:65)
	at org.springframework.cglib.reflect.FastClass.create(FastClass.java:47)
	at org.springframework.cglib.reflect.FastClass.create(FastClass.java:40)
	at org.grails.datastore.mapping.reflect.FieldEntityAccess$FieldEntityReflector.<init>(FieldEntityAccess.java:142)
	at org.grails.datastore.mapping.reflect.FieldEntityAccess.getOrIntializeReflector(FieldEntityAccess.java:52)
	at org.grails.datastore.mapping.model.AbstractMappingContext.initialize(AbstractMappingContext.java:251)
	at grails.test.mixin.domain.DomainClassUnitTestMixin.initializeMappingContext(DomainClassUnitTestMixin.groovy:93)
	at grails.test.mixin.domain.DomainClassUnitTestMixin.mockDomains(DomainClassUnitTestMixin.groovy:87)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:153)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
	at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
	at grails.test.runtime.TestRuntimeJunitAdapter$1$2.evaluate(TestRuntimeJunitAdapter.groovy:46)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
	at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
	at grails.test.runtime.TestRuntimeJunitAdapter$3$4.evaluate(TestRuntimeJunitAdapter.groovy:73)
	at org.spockframework.runtime.extension.builtin.ClassRuleInterceptor.intercept(ClassRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:395)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
	... 37 more
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "error/SpecificDomain$$FastClassByCGLIB$$ec35be67"
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	... 39 more
```

This error seems to start after 3.1.0.RC1 - so RC2 or 3.1.0 but I have to verify it - will update later.

**Comment by droggo** [comment]
Issue is caused by delivering `testCompile "org.grails:grails-plugin-testing"` plugin to project from custom plugin instead of direct dependency. Version is the same in both application and plugin but this must make some difference anyway.

I'm not sure if this is a bug, at least solution is very simple - to add this dependency to application too.

This didn't happen in Grails 3.1.0.RC1

If you not think this is a bug, please close this issue.
