### ISSUE TITLE
Grails 3.1.0: throws IllegalAccessException when modifying a service class

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-core#9638]
```
java.lang.IllegalAccessException: Class org.springsource.loaded.ReloadableType can not access a member of class org.springframework.aop.framework.CglibAopProxy$ClassLoaderAwareUndeclaredThrowableStrategy with modifiers "public"
        at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
        at java.lang.reflect.Method.invoke(Method.java:490)
        at org.springsource.loaded.ReloadableType.reloadProxiesIfNecessary(ReloadableType.java:568)
        at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:446)
        at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:1014)
        at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104)
        at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:251)
        at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:235)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalAccessException: Class org.springsource.loaded.ReloadableType can not access a member of class org.springframework.aop.framework.CglibAopProxy$ClassLoaderAwareUndeclaredThrowableStrategy with modifiers "public"
        at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
        at java.lang.reflect.Method.invoke(Method.java:490)
        at org.springsource.loaded.ReloadableType.reloadProxiesIfNecessary(ReloadableType.java:597)
        at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:446)
        at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:1014)
        at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104)
        at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:251)
        at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:235)
        at java.lang.Thread.run(Thread.java:745)
```

The application is very simple, just have one domain, one service and one controller.

**Comment by rstjohn** [comment]
I am seeing the same issue.  Is there a work-around while this issue is being worked?

**Comment by graemerocher** [comment]
Looking at the trace, it seems the services were created using Spring proxies via cglib. This is not recommended anymore and is in fact deprecated. I have tried to reproduce with a new Grails 3.1 application and I do not encounter the error, so it must be because you have enabled Spring proxy support. Either way I cannot reproduce the error, so please upload an example with steps to reproduce.

Alternatively as a workaround disable Spring proxies by modifying `application.yml` with:

    grails:
        spring:
            transactionManagement:
                proxies: false

**Comment by todoubaba** [comment]
```yml
grails:
    spring:
        transactionManagement:
            proxies: false
```

It works now. The default config is
```yml
grails:
    spring:
        transactionManagement: false

**Comment by graemerocher** [comment]
@todoubaba this was fixed with https://github.com/grails/grails-profile-repository/commit/bf483f9ce442655f3f738cd40bc6412e4dde6810

**Comment by todoubaba** [comment]
:rose:  :+1:

**Comment by jamie-kemp** [comment]
Seem to be seeing this issue in Grails 3.1.4 with the above config change in place. The affected controller extends RestfulController and is in a nested project (exploded = true).
