### ISSUE TITLE
not-null property references a null or transient value: dateCreated

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [grails/grails-core#9650]
I'm using grails 2.4.4. I have a user domain class like this:
```
class User {
  
  String loginId
  String password
  Date dateCreated
  
  static hasOne = [profile: Profile]
  static hasMany = [posts: Post, tags: Tag, following: User]
  static mapping = {
    posts sort: "dateCreated"
  }
  
  static constraints = {
    loginId nullable: false, unique: true, size: 3..20
    password nullable: false, size: 6..8, validator: { password, user ->
      // password must not match loginId
      password != user.loginId
    }
    profile nullable: true
  }
}
```

And that's how I create the User in the grails console:
```
import com.mypackage.*

def now = new Date()
def chuck = new User(
    loginId: "chuck_norris",
    password: "highkick",
    profile: new Profile(fullName: "Chuck Norris", email: "chuck@nowhere.net"),
    dateCreated: now).save(failOnError: true)
```

The user is created just fine in `BootStrap.init` but it's not working in the console. Here's the full exception:
```
org.springframework.dao.DataIntegrityViolationException: not-null property references a null or transient value : com.grailsinaction.hubbub.User.dateCreated; nested exception is org.hibernate.PropertyValueException: not-null property references a null or transient value : com.grailsinaction.hubbub.User.dateCreated
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:182)
	at com.grailsinaction.hubbub.User.save(User.groovy)
	at com.grailsinaction.hubbub.User$save.call(Unknown Source)
	at ConsoleScript0.run(ConsoleScript0:7)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
Caused by: org.hibernate.PropertyValueException: not-null property references a null or transient value : com.grailsinaction.hubbub.User.dateCreated
	at org.hibernate.engine.internal.Nullability.checkNullability(Nullability.java:106)
	at org.hibernate.action.internal.AbstractEntityInsertAction.nullifyTransientReferencesIfNotAlready(AbstractEntityInsertAction.java:132)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:86)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:490)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:195)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:179)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:214)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:209)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:194)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:684)
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:676)
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:671)
	... 4 more
```

**Comment by jeffbrown** [comment]
You aren't really supposed to be assigning a value to `dateCreated`.  That is a special
property that GORM initializes for you.  See http://grails.github.io/grails-doc/2.4.4/guide/GORM.html#eventsAutoTimestamping for more info.

If you don't want that, you can turn off the autotimestamping with something like this in your `User` class:

```
static mapping = {
   autoTimestamp false
}
```

Or you can just give the property a different name.  I expect that the mechanism for initializing that property is not active from the console.


Separate from all of that, the `dateCreated` property is not bindable by default when passing a `Map` to the `User` constructor as you are.  That is by design.  If you want it to be bindable, then you have to express as such with something like this in `User.groovy`:

```
static constraints = {
    dateCreated bindable: true
}
```

I expect that the value you are supplying in `BootStrap.init` is actually being ignored, as it should be, and that the GORM mechanism which is in place to auto initialize that property is what is actually assigning it a value.

One way you can get around the whole thing is instead of this:

```
def now = new Date()
def chuck = new User(
    loginId: "chuck_norris",
    password: "highkick",
    profile: new Profile(fullName: "Chuck Norris", email: "chuck@nowhere.net"),
    dateCreated: now).save(failOnError: true)
```

Do something like this:

```
def chuck = new User(
    loginId: "chuck_norris",
    password: "highkick",
    profile: new Profile(fullName: "Chuck Norris", email: "chuck@nowhere.net"))
chuck.dateCreated = new Date()
chuck = chuck.save(failOnError: true)
```

**Comment by github-account-because-they-want-it** [comment]
Thank you @jeffbrown . That last block of code worked.
