### ISSUE TITLE
3.1.1 - MissingPropertyException (WARN) when running unit test annotated with @TestFor

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#9677]
stacktrace:
```
[main] WARN  g.t.r.GrailsApplicationTestPlugin - Problem in clearing Spring TestContext cache
groovy.lang.MissingPropertyException: No such property: contextCache for class: org.springframework.test.context.TestContextManager
	at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:999) [groovy-2.4.5.jar:2.4.5]
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1854) [groovy-2.4.5.jar:2.4.5]
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1830) [groovy-2.4.5.jar:2.4.5]
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3737) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:51) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296) [groovy-2.4.5.jar:2.4.5]
	at grails.test.runtime.GrailsApplicationTestPlugin.doCloseCachedSpringTestContexts(GrailsApplicationTestPlugin.groovy:342) [grails-plugin-testing-3.1.1.jar:3.1.1]

...
```

`GrailsApplicationTestPlugin` tries to invoke `TestContextManager.contextCache` which does not exist anymore: https://github.com/grails/grails-core/blob/3.1.x/grails-plugin-testing/src/main/groovy/grails/test/runtime/GrailsApplicationTestPlugin.groovy#L342

removed with spring-4.2: https://github.com/spring-projects/spring-framework/commit/0392a88c6954bdcd391eea07b513973ebee3ba08#diff-386b49756784571583840c81732e2becL82

however, seems not to affect test result.

**Comment by graemerocher** [comment]
In the end I just removed the logic that cleared the Spring contexts, these should only really be created in integration tests so I don't see why the logic was needed. Besides that the APIs to do the clearing are no longer public so it was not longer possible.
