### ISSUE TITLE
3.1.1 -- old style render not working with --profile=rest-api 

### ISSUE THREAD

**Issue by randallr** [grails/grails-core#9683]
`$grails create-app TestRestApi --profile=rest-api`

Controller:
```
class ApplicationController implements PluginManagerAware {

    GrailsApplication grailsApplication
    GrailsPluginManager pluginManager

    def index() {
        [grailsApplication: grailsApplication, pluginManager: pluginManager]
    }

    def foo() {
        render(contentType: "application/json") {
            success = true
            message = [
                    foo: 'bar'
            ]
        }
    }
}
```

Request http://localhost:8787/application/foo

```
|Running application...
Grails application running at http://localhost:8787 in environment: development
ERROR org.grails.web.errors.GrailsExceptionResolver - MissingPropertyException occurred when processing request: [GET] /application/foo
No such property: success for class: groovy.json.StreamingJsonBuilder$StreamingJsonDelegate. Stacktrace follows:
groovy.lang.MissingPropertyException: No such property: success for class: groovy.json.StreamingJsonBuilder$StreamingJsonDelegate
        at testrestapi.ApplicationController$_foo_closure1.doCall(ApplicationController.groovy:18) ~[main/:na]
        at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.renderJsonInternal(ResponseRenderer.groovy:161) ~[grails-plugin-controllers-3.1.1.jar:3.1.1]
        at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.render(ResponseRenderer.groovy:143) ~[grails-plugin-controllers-3.1.1.jar:3.1.1]
        at testrestapi.ApplicationController.foo(ApplicationController.groovy:17) ~[main/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]


```

**Comment by graemerocher** [comment]
Please see the upgrade notes http://grails.github.io/grails-doc/latest/guide/upgrading.html#upgrading3x

Section "JSON Builder Groovy Alignment"
