### ISSUE TITLE
Rendering a JSON View in Grails 3.1.1 Interceptor (Rest Profile) results in No qualifying bean of type [org.springframework.web.servlet.ViewResolver] is defined

### ISSUE THREAD

**Issue by mpas** [grails/grails-core#9688]
When trying to render a JSON view in a interceptor, the following error is returned.

No qualifying bean of type [org.springframework.web.servlet.ViewResolver] is defined.
No qualifying bean of type [org.springframework.web.servlet.ViewResolver] is defined: expected single matching bean but found 4: groovyMarkupViewResolver,jsonViewResolver,beanNameViewResolver,mvcViewResolver. Stacktrace follows:
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.web.servlet.ViewResolver] is defined: expected single matching bean but found 4: groovyMarkupViewResolver,jsonViewResolver,beanNameViewResolver,mvcViewResolver
	at grails.artefact.Interceptor$Trait$Helper.render(Interceptor.groovy:254) ~[grails-plugin-interceptors-3.1.1.jar:3.1.1]
	at device.registration.RegistrationInterceptor.before(RegistrationInterceptor.groovy:13) ~[main/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

**Comment by jeffbrown** [comment]
This is our culprit: https://github.com/grails/grails-core/blob/e59aaf1df1a1beecf59fd026dd74d3fb191eb2d6/grails-plugin-interceptors/src/main/groovy/grails/artefact/Interceptor.groovy#L254

**Comment by mpas** [comment]
Is there a workaround that i can use?
