### ISSUE TITLE
Grails 3.1 -- HibernateTestMixin

### ISSUE THREAD

**Issue by squarepegsys** [grails/grails-core#9723]
I tried setting up a test using `HibernateTestMixin` just like documented here:
https://grails.github.io/grails-doc/3.1.x/guide/testing.html#unitTestingDomains

When when I run the test I get this error:
>      java.lang.NoSuchMethodError: grails.orm.bootstrap.HibernateDatastoreSpringInitializer.setConfiguration(Lgrails/config/Config;)V
	at grails.test.runtime.gorm.HibernateTestPlugin.registerHibernateDomains(HibernateTestPlugin.groovy:220)
	at grails.test.runtime.gorm.HibernateTestPlugin.registerBeans(HibernateTestPlugin.groovy:203)
	at grails.test.runtime.gorm.HibernateTestPlugin.onTestEvent(HibernateTestPlugin.groovy:273)
	at grails.test.runtime.TestRuntime.deliverEvent(TestRuntime.groovy:295)
	at grails.test.runtime.TestRuntime.processEvents(TestRuntime.groovy:264)
	at grails.test.runtime.TestRuntime.doPublishEvent(TestRuntime.groovy:238)
	at grails.test.runtime.TestRuntime.publishEvent(TestRuntime.groovy:211)

See my example project here:
https://github.com/squarepegsys/grails3-hibernatemixin

**Comment by graemerocher** [comment]
This is a documentation issue. Simply removing the version will correct it:

```testCompile 'org.grails:grails-datastore-test-support'```

**Comment by squarepegsys** [comment]
Yes, that works. I'll update the documentation.

**Comment by squarepegsys** [comment]
I removed the version and now I get the following:

>     java.lang.NoSuchMethodError: grails.test.mixin.hibernate.HibernateTestMixin.getMainContext()Lorg/springframework/web/context/support/GenericWebApplicationContext;
	at grails.test.mixin.hibernate.HibernateTestMixin.getSessionFactory(HibernateTestMixin.groovy:94)
	at grails3.hibernatemixin.PersonSpec.Test count people(PersonSpec.groovy:17)


I updated my example

**Comment by graemerocher** [comment]
Will look into it. thanks
