### ISSUE TITLE
[3.1.2] - validate() method on Domain class causes getXyz() methods without parameters to be called

### ISSUE THREAD

**Issue by droggo** [grails/grails-core#9749]
After upgrade to 3.1.2 it seems that all getters in domains classes are considered constrained properties and are called during validatation. Even if method is marked `transient` or 'property' is added to `transients` list.

This is a big issue for us, application will not start, a lot of tests are failing, and this will also strongly influence performance. Please let us know if we should start refactoring to change method names or this is not planned and is a bug.

Application startup issue. Using spring-security plugin, we use `RoleGroup` class which has a getter for authorities - `getRoles()` (executing database query). When RoleGroup is saved, following error is thrown:
```
org.springframework.beans.InvalidPropertyException: Invalid property 'roles' of bean class [some.package.RoleGroup]: Getter for property 'roles' threw exception; nested exception is java.lang.reflect.InvocationTargetException
        at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:704) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:610) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:211) ~[grails-validation-3.1.2.jar:3.1.2]
        at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81) ~[grails-validation-3.1.2.jar:3.1.2]
        at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:122) ~[grails-datastore-gorm-hibernate-core-5.0.2.RELEASE.jar:na]
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:140) ~[grails-datastore-gorm-5.0.2.RELEASE.jar:na]
        at org.grails.datastore.gorm.GormEntity$Trait$Helper$save$1.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.6.jar:2.4.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.6.jar:2.4.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-2.4.6.jar:2.4.6]
        at some.package.RoleGroup.save(RoleGroup.groovy) 
        at some.package.RoleGroup.save(RoleGroup.groovy) 
        at org.grails.datastore.gorm.GormEntity$save.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsiteteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.6.jar:2.4.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.6.jar:2.4.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-2.4.6.jar:2.4.6]
        at some.package.UserService.createRoleGroup(UserService.groovy:75) 
```

Performance impact example:
```
class SomeDomain {
    transient Collection getImages(){
        AnotherDomain.findAllBySomeDomain(this)
    }
}
```
Since 3.1.2 of every validation of SomeDomain, query will be done to fetch all AnotherDomain objects.

If getter throws exception, which happens for some of our getter methods following error is logged: :
```
org.springframework.beans.InvalidPropertyException: Invalid property 'someProperty' of bean class [SomeDomain]: Getter for property 'someProperty' threw exception; nested exception is java.lang.reflect.InvocationTargetException
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:704)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:610)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:211)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:89)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:161)
	at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:87)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:181)
	at org.grails.datastore.gorm.GormInstanceApi.save_closure5(GormInstanceApi.groovy:170)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:310)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:169)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:109)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:87)
```

**Comment by jeffbrown** [comment]
Do you know if this was happening in 3.1.1?

**Comment by droggo** [comment]
It wasn't, we just tried to upgrade from 3.1.1 to 3.1.2

**Comment by jeffbrown** [comment]
Thanks for the feedback.

**Comment by jeffbrown** [comment]
The unit test in the project at https://github.com/jeffbrown/transientprops fails with 3.1.2 and passes with 3.1.1.

**Comment by droggo** [comment]
One more observation - it seems that this happens with `hibernate4` but not with `mongo` plugin.

**Comment by jeffbrown** [comment]
Thanks for the feedback.

**Comment by droggo** [comment]
Unfortunatelly I was wrong. The issue for Mongo is even worse, as it happens for all unit tests which do something with domain objects. Please see stacktrace below:

```
org.springframework.beans.InvalidPropertyException: Invalid property 'dbo' of bean class [some.package.Price]: Getter for property 'dbo' threw exception; nested exception is java.lang.reflect.InvocationTargetException
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:704)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:610)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:211)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:89)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:161)
	at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:87)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:181)
	at org.grails.datastore.gorm.GormInstanceApi.save_closure5(GormInstanceApi.groovy:170)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:310)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:169)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:109)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:87)
	at some.package.PriceControllerSpec.testUpdate(PriceControllerSpec.groovy:133)
Caused by: java.lang.reflect.InvocationTargetException
	at org.springframework.beans.BeanWrapperImpl$BeanPropertyHandler.getValue(BeanWrapperImpl.java:307)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:622)
	... 15 more
Caused by: org.grails.datastore.mapping.core.ConnectionNotFoundException: No datastore session found. Call Datastore.connect(..) before calling Datastore.getCurrentSession()
	at org.grails.datastore.mapping.core.AbstractDatastore.retrieveSession(AbstractDatastore.java:207)
	at grails.mongodb.MongoEntity$Trait$Helper.getDbo(MongoEntity.groovy:149)
	... 17 more
```

`getDbo()` method is from `grails.mongodb.MongoEntity` trait from mongo plugin and it definitely shouldn't be verified by validation on save. I will create empty Grails 3.1.2 project and verify it, because maybe there some additional configuration needed when upgrading from 3.1.1?

**Comment by jeffbrown** [comment]
The issue is that the transient properties are now showing up in the domain class' `constrainedProperties`.  That wasn't happening in 3.1.1.  There were some recent changes around some of that to support ad-hoc constraints.  Those changes may or may not be relevant, but we will track it down.

**Comment by droggo** [comment]
It seems to be not only transient properties problem. Before, only class 'real 'properties were used, but now it seems that all getters are, also from traits. At least mongo issue suggests that.

For fresh 3.1.2 project with mongo plugin this tests fail with above stacktrace:
```
package error

import grails.persistence.Entity
import spock.lang.Specification
import grails.test.mixin.TestFor

@TestFor(DomainWithGetter)
class DomainWithGetterValidationSpec extends Specification {

	void 'ensure domain may be saved'(){
		expect:
		new DomainWithGetter().save()
	}	
}
```
Domain is empty:
```
class DomainWithGetter {}
```

Please let me know if I can help any further, we can prepare additional tests or try to dive deeper into changes which cause that. Thank you for the fast support!

**Comment by droggo** [comment]
I have just extended the test and verified on 3.1.1. For following domain:
```
package error

class DomainWithGetter {

	static int a = 0
	static int b = 0
	static int c = 0

	String getPropertyA(){
		println "getting A"
		a++
	}

	transient String getPropertyB(){
		println "getting B"
		b++
	}

	static transients = ['propertyC']

	String getPropertyC(){
		println "getting C"
		c++
	}
}
```
When this is saved with 3.1.1 all a,b and c are equal to 0
but when this is saved with 3.1.2 all of them are equal to 2

So following test will pass on 3.1.1 but will fail on 3.1.2
```
	void 'ensure domain may be saved'(){
		DomainWithGetter domainWithGetter = new DomainWithGetter()
		expect:
		domainWithGetter.save()
		println "${DomainWithGetter.a}, ${DomainWithGetter.b}, ${DomainWithGetter.c}"
		DomainWithGetter.a == 0
		DomainWithGetter.b == 0
		DomainWithGetter.c == 0
	}	
```
Even if setters are added to class:
```
void setPropertyA(){}
transient void setPropertyB(){}
void setPropertyC(){}
```
 on 3.1.1 this test will pass still.

**Comment by gte250p** [comment]
This is a show stopper for me - old code which worked fine is now failing, because I have a class with several "Type" coercion methods (ie, The value is stored as a String in the database, but there are getNumber(), getDate(), etc. methods that you can call).  Whenever I try to save the class, all get* methods are getting called causing parse format errors - note that all of these get* methods are in my static transients list.

[Sample Project on Github](https://github.com/gte250p/grails-3.1.2_gorm-transients-error)

**Comment by jeffbrown** [comment]
> This is a show stopper for me

@gte250p We are working on a fix.  I don't think that 3.1.1 demonstrates the problem.

**Comment by gte250p** [comment]
@jeffbrown I can confirm that the above project works fine when downgraded to 3.1.1 - Thanks for your time!

**Comment by ctoestreich** [comment]
Ran into this as well, the work around for us was the following inside our domain class that was using a transient property.  If it helps any to keep velocity on 3.1.2.

Old Code:
----
``` groovy
 transient SortedSet<Content> getContents() {
        Content.findAllByManagedContent(this)?.toSet() as SortedSet<Content>
    }
```

New Code
----
``` groovy
 transient SortedSet<Content> getContents() {
        SortedSet<Content> contents = [] as SortedSet<Content>
        if(this?.id) {
            contents = Content.findAllByManagedContent(this)?.toSet() as SortedSet<Content>
        }
        contents
    }
```

**Comment by jeffbrown** [comment]
@ctoestreich I think that work around will only work before the object is persisted and I don't think the null safe operator in your `if(this?.id)` is necessary.  `this` can never evaluate to null.

**Comment by ctoestreich** [comment]
@jeffbrown Yes that is the only place it was burning us given that class is used in Bootstrap the transient/lazy collections were being interrogated and returning an empty set seems to combat the problem.  Concerning the NSO, I tend to use it liberally... so that. :hammer:

**Comment by jeffbrown** [comment]
>  Concerning the NSO, I tend to use it liberally.

@ctoestreich If `this` is ever null, the NPE you would get on `this.id` is likely the least of your worries.  ;)

**Comment by jeffbrown** [comment]
I think we may have chased this down.

The commit at https://github.com/grails/grails-core/commit/bb5fdf848ea29c31a6c29f85668873516ff4b943 aimed to make it such that properties that only have a `getter` method are constrained by default.  A consequence of that change is that transient properties that did not used to be constrained now are constrained.  I think the latest code on the `3.1.x` branch may have fixed that.

**Comment by jeffbrown** [comment]
I think this issue is fixed for transient properties.  If there are issues with other types of properties, please file an issue to track those. 

Thanks for all of the feedback.

**Comment by droggo** [comment]
@jeffbrown please see #9754 . There is still issue with `transient Boolean isSomething()`. But there is easy workaround to use `static transients` for that.
