### ISSUE TITLE
[3.1.2] - validate() method on Domain class causes getXyz() methods without parameters to be called - continued

### ISSUE THREAD

**Issue by droggo** [grails/grails-core#9754]
This is continuation of #9749 . I confirm that changes made to 3.1.x has fixed transient getters, but still normal getters (without property and without setter) are called. This is a change against 3.1.1

All unit tests on `mongo` plugin fails if domain entity is validated. There is always the same error:
```
org.springframework.beans.InvalidPropertyException: Invalid property 'dbo' of bean class [error.DomainWithGetter]: Getter for property 'dbo' threw exception; nested exception is java.lang.reflect.InvocationTargetException
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:704)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:610)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:211)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:89)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:161)
	at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:87)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:181)
	at org.grails.datastore.gorm.GormInstanceApi.save_closure5(GormInstanceApi.groovy:170)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:310)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:169)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:109)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:87)
	at error.DomainWithGetterValidationSpec.ensure domain may be saved(DomainWithGetterValidationSpec.groovy:13)
Caused by: java.lang.reflect.InvocationTargetException
	at org.springframework.beans.BeanWrapperImpl$BeanPropertyHandler.getValue(BeanWrapperImpl.java:307)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:622)
	... 15 more
Caused by: org.grails.datastore.mapping.core.ConnectionNotFoundException: No datastore session found. Call Datastore.connect(..) before calling Datastore.getCurrentSession()
	at org.grails.datastore.mapping.core.AbstractDatastore.retrieveSession(AbstractDatastore.java:207)
	at grails.mongodb.MongoEntity$Trait$Helper.getDbo(MongoEntity.groovy:149)
	... 17 more
```
As written in related issue, `getDbo()` method is from `grails.mongodb.MongoEntity` trait from mongo plugin and it definitely shouldn't be verified by validation on save. The question here is if mongo should be corrected and have this method marked `transient` or this is still unwanted change?

Test which visualizes the changes is below:
```
package error

import spock.lang.Specification
import grails.test.mixin.TestFor

@TestFor(DomainWithGetter)
class DomainWithGetterValidationSpec extends Specification {

    void 'ensure domain may be saved'(){
        expect:
        new DomainWithGetter().save()
    }   
}
```
For domain:
```
package error

class DomainWithGetter {

	static int a = 0
	static int b = 0
	static int c = 0

	String getPropertyA(){
		println "getting A"
		a++
	}

	transient String getPropertyB(){
		println "getting B"
		b++
	}

	static transients = ['propertyC']

	String getPropertyC(){
		println "getting C"
		c++
	}
}
```
Executing it on 3.1.1 it passes with none of the getters being called, but it fails on 3.1.2 with propertyA (public, non-transient getter) being called twice. propertyB and propertyC are not called since changes on 3.1.x branch

**Comment by droggo** [comment]
One more related issue. If method name is `isSomeProperty()` there are two cases this will fail:
* `transient Boolean isSomeProperty()`
* `Boolean isSomeProperty()`

But it works for:
```
static transients = ['someProperty']
```

Error is different - NotReadablePropertyException is thrown. Stacktrace below:
```
org.springframework.beans.NotReadablePropertyException: Invalid property 'propertyD' of bean class [error.DomainWithGetter]: Bean property 'propertyD' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:619)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:610)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:211)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:89)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:161)
	at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:87)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:181)
	at org.grails.datastore.gorm.GormInstanceApi.save_closure5(GormInstanceApi.groovy:170)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:310)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:169)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:109)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:87)
	at error.DomainWithGetterValidationSpec.ensure domain may be saved(DomainWithGetterValidationSpec.groovy:13)
```

**Comment by nobeans** [comment]
Sorry for your inconvenient caused by my PR (#9605).

Making getter-only property constrainable for domain class (bb5fdf848ea29c31a6c29f85668873516ff4b943) is NOT essential feature at my PR. It's just introduced from a contrast with `@Validateable`.

So I think that only the support of getter-only property should be reverted like:

```
diff --git grails-validation/src/main/groovy/org/grails/validation/DefaultConstraintEvaluator.java grails-validation/src/main/groovy/org/grails/validation/DefaultConstraintEvaluator.java
index 9a3cb19..a9e7446 100644
--- grails-validation/src/main/groovy/org/grails/validation/DefaultConstraintEvaluator.java
+++ grails-validation/src/main/groovy/org/grails/validation/DefaultConstraintEvaluator.java
@@ -176,6 +176,9 @@ public DefaultConstraintEvaluator() {
                             continue;
                         }
                     }
+                } else {
+                    // for domain class, a constraint of a property as only getter method is not supported
+                    continue;
                 }
             }
```

**Comment by droggo** [comment]
@nobeans ad-hoc constraints are really nice idea, just require final fixes to make them work correctly, no worries :)

There is yet another case which works strange. If there is a `Map property` in CommandObject it will be nullable by default which is different from previous version. May this also be cause by your changes?

for example:
```
class CommandObject implements Validateable {
	Map item
	String string
}
```
if we call `new CommandObject().validate()` it will pass on `item` but fail on `string` - so for `Map` type default nullable is not applied

**Comment by droggo** [comment]
Yet another impact is that: `isXyz()` methods are executed on command object on validation (which did not happened before) and `static transients = []` is supported on Command Objects. I'm willing to create PR with tests for all those cases, but I need information what is desired functionality?

* should `isXyz()` methods behave the same as `getXyz()` methods
* should getters without setters be automatically considered as constrained properties? Any difference between Domain and Command Object?
* should `static transients = []` and `transient method` be supported in Command Object?
* should this behave the same for methods inherited from super class and traits?

**Comment by graemerocher** [comment]
Answer to each point:

1) Yes they should
2) No they shouldn't
3) I'm not sure if this is necessary if 2) is fixed
4) Yes it should

Pull request with more tests welcome

**Comment by jeffbrown** [comment]
Number 2 there is really what caused this.  The code change mentioned above which removed the `continue` made the answer to that "yes", and that is what has caused the issues.

**Comment by droggo** [comment]
I'm working on the tests still, and it will still take some time. I want to include them in `grails-core/grails-test-suite-uber` and do PR to `3.0.x` branch, is this fine? 

It seems some more issues has occured for inherited properties/methods.

**Comment by jeffbrown** [comment]
Yes, the tests should be on `3.0.x` as well.  I did not pull any of my tests from yesterday back there as I want to wait until the whole thing is sorted out.  Tests for 3.0.x are needed.
