### ISSUE TITLE
Grails 3.1.3: java.lang.IllegalStateException: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#9759]
Trying to start the command line throws the described exception. This was not picked up prior to release because testing was using cached downloaded data.

**Comment by sotomskir** [comment]
I'm trying to update do Grails 3.1.3 and faced this exception. I can't run CLI on any project. Is there a workaround for grails 3.1.3?

**Comment by ColaColin** [comment]
Also suddenly started getting this error, no idea why. It keeps preventing me from starting the CLI on any project as well.

`grails --stacktrace --verbose
| Error Error occurred running Grails CLI: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]
java.lang.IllegalStateException: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]
        at org.grails.cli.profile.AbstractProfile$_getExtends_closure4.doCall(AbstractProfile.groovy:331)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
        at org.grails.cli.profile.AbstractProfile.getExtends(AbstractProfile.groovy:328)
        at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:411)
        at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:107)
        at org.grails.cli.profile.AbstractProfile.getCompleters(AbstractProfile.groovy:339)
        at org.grails.cli.GrailsCli.setupCompleters(GrailsCli.groovy:406)
        at org.grails.cli.GrailsCli.handleInteractiveMode(GrailsCli.groovy:388)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:275)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error occurred running Grails CLI: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]
`

**Comment by RafalPydyniak** [comment]
I'm facing the same problem. I can't start any project (even new one). Tried both on Ubuntu (14.04) and Debian 8. Tried both with java 8 and 7. On debian I've also tried to pack grails-core to jar with changes made by @graemerocher (given as solution) and replacing it in my grails/src installation directory but it still doesn't work. I've also tried to remove ~/.gradle directory (advice given by colleague of mine) but it didn't work neither.
Everything seems to work fine while using grails 3.1.2

**Comment by micronax** [comment]
Same here. Reverted back to 3.1.1 – now it works. Waiting for a patch.

**Comment by ColaColin** [comment]
Reverting back to 3.1.1 didn't help at first for me. However I then checked out the 3.1.x branch, build that and used that and it worked. Then I went back to 3.1.3 and suddenly 3.1.3 works again. Dunno why.

**Comment by kimmoes** [comment]
Having the same problem running on Bamboo but not local.

**Comment by jvesouza** [comment]
A temporarily workaround is edit build.gradle and change the version of org.grails.profiles:web from 3.1.3 to 3.1.2.

profile "org.grails.profiles:web:3.1.2"

It seems to work but I don't know if there are side effects.

**Comment by adam-ho** [comment]
Why don't you guys pull the binary from the official site then?
Downloading a package that doesn't work is a very bad idea. Remove 3.1.3 until you have a stable version.

**Comment by ColaColin** [comment]
@jvesouza that workaround seems too be flawless, we're using it in team of 8 people and it just works

**Comment by graemerocher** [comment]
Grails 3.1.4 is now out and addresses this, sorry for the inconvenience.

**Comment by gschmidl** [comment]
This didn't happen for me with 3.1.3 but happens with 3.1.4.

`Command [run-app] error: Profile [org.grails.profiles:base:3.1.4] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.4] (Use --stacktrace to see the full trace)`

**Comment by graemerocher** [comment]
@gschmidl Please run the command again with `--stacktrace` and post the stracktrace

**Comment by sosguthorpe** [comment]
I'm experiencing the same behaviour with 3.1.4 and also had the same issue with 3.1.3. I have cleared my Gradle caches and retried but still receive this message. Stack trace below:
`java.lang.IllegalStateException: Profile [org.grails.profiles:base:3.1.4] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.4]                                                                                                                                                                                                                               
        at org.grails.cli.profile.AbstractProfile$_getExtends_closure4.doCall(AbstractProfile.groovy:331)                                                                                                                                                                                                                                                                                  
        at org.grails.cli.profile.AbstractProfile.getExtends(AbstractProfile.groovy:328)                                                                                                                                                                                                                                                                                                   
        at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:411)                                                                                                                                                                                                                                                                                                  
        at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:107)                                                                                                                                                                                                                                                  
        at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:439)                                                                                                                                                                                                                                                                                                
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:362)                                                                                                                                                                                                                                                                                                                    
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:344)                                                                                                                                                                                                                                                                                                                    
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:273)                                                                                                                                                                                                                                                                                                                          
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)`

**Comment by graemerocher** [comment]
@sosguthorpe what commands are you running to produce that exception?

**Comment by sosguthorpe** [comment]
@graemerocher I was attempting to generate a controller originally however it occurs no matter what I try. Even just with the simple "grails" command.

**Comment by graemerocher** [comment]
@sosguthorpe Please post the output of `grails -version`

**Comment by sosguthorpe** [comment]
@graemerocher You are correct. I was still using 3.1.3 as my current in sdkman. Updating to 3.1.4 in sdk man does indeed fix this issue for me. Thanks, and sorry for the confusion caused.

**Comment by graemerocher** [comment]
No worries, glad you found the solution

**Comment by mgoode87** [comment]
I am running into this same issue I believe.    I have grails-3.1.3 on my machine.   I am running command as follows `grails create-domain-class quote --stacktrace`.

Then I receive this error and stack trace: 
`| Error Command [create-domain-class] error: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3] (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.IllegalStateException: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]
	at org.grails.cli.profile.AbstractProfile$_getExtends_closure4.doCall(AbstractProfile.groovy:331)
	at org.grails.cli.profile.AbstractProfile.getExtends(AbstractProfile.groovy:328)
	at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:411)
	at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:107)
	at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:439)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:362)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:344)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:273)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Command [create-domain-class] error: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]
`

I am a graduate student and grails-3.1.3 is a requirement for our class project.   If updating to grails-3.1.4 is a solution then I will just talk to my professor about it.

**Comment by graemerocher** [comment]
@mgoode87 upgrade to 3.1.4 is a requirement

**Comment by mgoode87** [comment]
@graemerocher Thanks.  I upgraded and it works.

**Comment by VenelinPetkov** [comment]
Hello,

I am observing the issue with 3.1.4... on Windows
$ grails --stacktrace --verbose
| Error Error occurred running Grails CLI: Profile [org.grails.profiles:base:3.1.4] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.4]
java.lang.IllegalStateException: Profile [org.grails.profiles:base:3.1.4] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.4]
        at org.grails.cli.profile.AbstractProfile$_getExtends_closure4.doCall(AbstractProfile.groovy:331)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
        at org.grails.cli.profile.AbstractProfile.getExtends(AbstractProfile.groovy:328)
        at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:411)
        at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:107)
        at org.grails.cli.profile.AbstractProfile.getCompleters(AbstractProfile.groovy:339)
        at org.grails.cli.GrailsCli.setupCompleters(GrailsCli.groovy:406)
        at org.grails.cli.GrailsCli.handleInteractiveMode(GrailsCli.groovy:388)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:275)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error occurred running Grails CLI: Profile [org.grails.profiles:base:3.1.4] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.4]

**Comment by RafalPydyniak** [comment]
@VenelinPetkov 
Are you sure you have upgraded your grails version to 3.1.4? (grails --version) this error also occurs if you try to run 3.1.4 project with 3.1.2 for example
