### ISSUE TITLE
[3.1.3] Static resources in plugins is unavailable

### ISSUE THREAD

**Issue by AlexKovynev** [grails/grails-core#9765]
org.hibernate.HibernateException: No Session found for current thread
	at sklad.AllInterceptor$$EPePZO8F.before(AllInterceptor.groovy:47)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Why interceptors is applied to static?

**Comment by zyro23** [comment]
ref. https://github.com/grails/grails-core/issues/9724

**Comment by AlexKovynev** [comment]
OK. What about hibernate session? Now I have to always do "...withSession{ " in interceptrors?

**Comment by AlexKovynev** [comment]
And linked question. Static resources from plugins (maybe only inline plugins) does not loaded:(

**Comment by AlexKovynev** [comment]
Guys, can be corrected in 3.1.5?:)

**Comment by graemerocher** [comment]
Upload an example with steps to reproduce

**Comment by AlexKovynev** [comment]
Unfortunately I can not. After create a simple app and run "grails" in application directory (Windows) I get the error below. How can i debug the problem? As for resources problem. I have an application and inline plugin (my fork of ckeditor for grails 3.x). In plugin directory "src\main\resources\public\" i have some files wich does not resolved for any link "/static/" or "/" after upgrade to 3.1.3 from 3.1.0

| Error Error occurred running Grails CLI: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]
java.lang.IllegalStateException: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]
        at org.grails.cli.profile.AbstractProfile$_getExtends_closure4.doCall(AbstractProfile.groovy:331)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
        at org.grails.cli.profile.AbstractProfile.getExtends(AbstractProfile.groovy:328)
        at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:411)
        at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:107)
        at org.grails.cli.profile.AbstractProfile.getCompleters(AbstractProfile.groovy:339)
        at org.grails.cli.GrailsCli.setupCompleters(GrailsCli.groovy:406)
        at org.grails.cli.GrailsCli.handleInteractiveMode(GrailsCli.groovy:388)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:275)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error occurred running Grails CLI: Profile [org.grails.profiles:base:3.1.3] declares and invalid dependency on parent profile [org.grails.profiles:base:3.1.3]

**Comment by graemerocher** [comment]
@AlexKovynev try the recently release 3.1.4 version

**Comment by AlexKovynev** [comment]
[test.zip](https://github.com/grails/grails-core/files/176761/test.zip)

Now I can create. So i have app, plugin and C:\Work\testinline\plugin1\src\main\resources\public\js\test.js

How can i locate it from browser?

settings.gradle

include 'app1', 'plugin1'


dependencies {
...
    compile project(':plugin1')
}

**Comment by AlexKovynev** [comment]
http://localhost:8080/js/test.js
http://localhost:8080/static/js/test.js
http://localhost:8080/plugin1/js/test.js
http://localhost:8080/static/plugin1/js/test.js
http://localhost:8080/plugin1/static/js/test.js

All 404

**Comment by AlexKovynev** [comment]
Guys, is there anyone?:)

**Comment by graemerocher** [comment]
Generally you don't access static JS directly like this, but instead via asset pipeline, which works fine for plugins

**Comment by AlexKovynev** [comment]
It is a pity, it's always worked before
