### ISSUE TITLE
grails.boot.GrailsApp - Application startup failed when domain static mapping contains secondary data source and caching.

### ISSUE THREAD

**Issue by steyng** [grails/grails-core#9777]
When multiple data sources are defined in a Grails 3.0.15 project, the application will fail to start if

1. The domain class is mapped to the secondary data source.
2. The static mapping for that class includes a 'cache' definition.

See the sample project at [grails-multidatasource](https://github.com/steyng/grails-multidatasource).

## Steps to reproduce.

Use the sample project which has basically been set-up as

1. grails create-app multidatasource
2. Define two data sources in application.yml, e.g. datasource and reportingDB. (Test project also makes sources read-only with no hibernate 2nd level cache).
3. Create a simple domain class to use the default data source with "cache 'read-only'"
4. Create a simple domain class to use the reportingDB data source with "cache 'read-only'"
5. grails run-app

Fails to start-up with:

```
ERROR grails.boot.GrailsApp - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'transactionManager_reportingDB' while setting constructor argument with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager_reportingDB': Cannot resolve reference to bean 'sessionFactory_reportingDB' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory_reportingDB': Invocation of init method failed; nested exception is org.hibernate.cache.NoCacheRegionFactoryAvailableException: Second-level cache is used in the application, but property hibernate.cache.region.factory_class is not given; please either disable second level cache or set correct region factory using the hibernate.cache.region.factory_class setting and make sure the second level cache provider (hibernate-infinispan, e.g.) is available on the classpath.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]

Caused by: org.hibernate.cache.NoCacheRegionFactoryAvailableException: Second-level cache is used in the application, but property hibernate.cache.region.factory_class is not given; please either disable second level cache or set correct region factory using the hibernate.cache.region.factory_class setting and make sure the second level cache provider (hibernate-infinispan, e.g.) is available on the classpath.
	at org.hibernate.cache.internal.NoCachingRegionFactory.buildEntityRegion(NoCachingRegionFactory.java:83)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:364)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859)
	at org.grails.orm.hibernate.cfg.GrailsAnnotationConfiguration.buildSessionFactory(GrailsAnnotationConfiguration.java:407)
```

Similar sort of stack trace appears in #9776

**Comment by ctoestreich** [comment]
I can confirm this is also a problem in grails 3.1.4 as we have hit this recently as well.

**Comment by graemerocher** [comment]
In the attached example, setting `hibernate_reportingDB.cache.region.factory_class` to `org.hibernate.cache.EhCacheRegionFactory` fixes the error, granted GORM should fallback to using the top level `hibernate` settings if none are specified for a secondary datastore
