### ISSUE TITLE
Grails 3.1 - FileWatcher caught serious error, see cause

### ISSUE THREAD

**Issue by Omnipresent** [grails/grails-core#9788]
Sample application: https://github.com/Omnipresent/grails3.1error

Video of error: https://youtu.be/j8rs3UiutZ4

Versions:
| Grails Version: 3.1.1
| Groovy Version: 2.4.5
| JVM Version: 1.8.0_25

Steps to reproduce:
1. Clone the above repo
2. grails run-app
3. Make change to `HelloController.groovy`
4. Notice stacktrace in console. 

Stacktrace

```bash
File /Users/bhaarat/code/grails/try3-api/grails-app/controllers/try3/api/HelloController.groovy changed, recompiling...
ERROR org.springsource.loaded.agent.Watcher - FileWatcher caught serious error, see cause
org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class try3.api.HelloController] of type [class org.grails.core.DefaultGrailsControllerClass]: InvocationTargetException
	at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:170) ~[grails-core-3.1.1.jar:3.1.1]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:784) ~[grails-core-3.1.1.jar:3.1.1]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:480) ~[grails-core-3.1.1.jar:3.1.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432) ~[springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
````

**Comment by graemerocher** [comment]
Seems to work fine in master
