### ISSUE TITLE
groovy.lang.MissingMethodException: No signature of method:

### ISSUE THREAD

**Issue by seanbrooks** [grails/grails-core#9795]
Hi,

I'm getting an error when running a groovy script on a Jenkins server and cannot figure out why.  When I run iT using the groovy console the script returns the results fine, when I run in it in Jenkings I get the error below.

#################### - script - ##########################

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.attribute.BasicFileAttributes

Path dir = Paths.get("//IUTTSTAPX111//e\$//MODELS//_Backups") 
BasicFileAttributes attrs = Files.readAttributes(dir, BasicFileAttributes) 

println """
Directory name: ${dir.fileName}
Absolute path: ${dir.toAbsolutePath()}

The file exists: ${Files.exists(dir)}
The file is readable: ${Files.isReadable(dir)}
The file is writable: ${Files.isWritable(dir)}
The file is executable: ${Files.isExecutable(dir)}
The file is a directory: ${Files.isDirectory(dir)}

Created: ${attrs.creationTime()}
Last modified: ${attrs.lastModifiedTime()}
Last accessed: ${attrs.lastAccessTime()}

Children:"""

dir.eachFile {
    println "  - ${it.fileName}"
}

#################### - error - ##########################

[IUTTSTAPX112]:

Directory name: _Backups
Absolute path: \\IUTTSTAPX112\e$\MODELS\_Backups

The file exists: true
The file is readable: true
The file is writable: false
The file is executable: true
The file is a directory: true

Created: 2015-12-07T20:47:18.203699Z
Last modified: 2016-03-13T17:34:02.505355Z
Last accessed: 2016-03-13T17:34:02.505355Z

Children: 
groovy.lang.MissingMethodException: No signature of method: sun.nio.fs.WindowsPath.eachFile() is applicable for argument types: (Script1$_run_closure1) values: [Script1$_run_closure1@3fece52]
Possible solutions: toFile(), each(groovy.lang.Closure)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at Script1.run(Script1.groovy:26)
	at org.jenkinsci.plugins.scriptler.util.GroovyScript.call(GroovyScript.java:122)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:325)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Unknown Source)
##############################################################

Would love someone to tell me why

cheers

SGB

**Comment by jeffbrown** [comment]
It looks like you are invoking `eachFile(Closure)` on a `sun.nio.fs.WindowsPath` and   `sun.nio.fs.WindowsPath` does not have an `eachFile(Closure)` method.  This doesn't appear to have anything to do with Grails.
