### ISSUE TITLE
Inline hot-reload thinks file is a domain - cannot recompile

### ISSUE THREAD

**Issue by donald-jackson** [grails/grails-core#9825]
After some struggles getting hot-reloading working it now appears that Grails thinks the classes it is trying to reload are domain classes. I am using the JaxRS plugin which has its own artefacts in grails-app/resources - when making a change to one of these files the reload is detected, but the following error is generated. I have tested making edits on services too and the same applies.

	File /home/donald/Workspace/sample/sample-core/grails-app/resources/io/sample/user/IdentityResource.groovy changed, recompiling...
	ERROR org.grails.plugins.AbstractGrailsPluginManager - Plugin [core:3.0.15] could not reload changes to file [/home/donald/Workspace/sample/sample-core/grails-app/resources/io/sample/user/IdentityResource.groovy]: io.sample.user.IdentityResource cannot be cast to groovy.lang.Script
	java.lang.ClassCastException: io.sample.user.IdentityResource cannot be cast to groovy.lang.Script
		at org.grails.spring.RuntimeSpringConfigUtilities.reloadSpringResourcesConfig(RuntimeSpringConfigUtilities.java:97) ~[grails-core-3.0.15.jar:3.0.15]
		at org.grails.plugins.CoreGrailsPlugin.onChange(CoreGrailsPlugin.groovy:202) ~[grails-core-3.0.15.jar:3.0.15]
		at org.grails.plugins.DefaultGrailsPlugin.notifyOfEvent(DefaultGrailsPlugin.java:792) ~[grails-core-3.0.15.jar:3.0.15]
		at org.grails.plugins.AbstractGrailsPluginManager.informOfClassChange(AbstractGrailsPluginManager.java:507) [grails-core-3.0.15.jar:3.0.15]
		at org.grails.plugins.AbstractGrailsPluginManager.informOfFileChange(AbstractGrailsPluginManager.java:444) [grails-core-3.0.15.jar:3.0.15]
		at grails.plugins.GrailsPluginManager$informOfFileChange$1.call(Unknown Source) [grails-core-3.0.15.jar:3.0.15]
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.5.jar:2.4.5]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.5.jar:2.4.5]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-2.4.5.jar:2.4.5]
		at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:208) [grails-core-3.0.15.jar:3.0.15]
		at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy) [grails-core-3.0.15.jar:3.0.15]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
		at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426) [springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.5.jar:2.4.5]
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.Closure.call(Closure.java:426) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.Closure.call(Closure.java:420) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.Closure.run(Closure.java:507) [groovy-2.4.5.jar:2.4.5]
		at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
	ERROR org.grails.plugins.AbstractGrailsPluginManager - Plugin [domainClass:3.0.15] could not reload changes to file [/home/donald/Workspace/sample/sample-core/grails-app/resources/io/sample/user/IdentityResource.groovy]: Cannot add Domain class [class io.sample.user.IdentityResource]. It is not a Domain!
	org.grails.core.exceptions.GrailsConfigurationException: Cannot add Domain class [class io.sample.user.IdentityResource]. It is not a Domain!
		at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:813) ~[grails-core-3.0.15.jar:3.0.15]
		at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:480) ~[grails-core-3.0.15.jar:3.0.15]
		at grails.core.GrailsApplication$addArtefact$2.call(Unknown Source) ~[na:na]
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.5.jar:2.4.5]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.5.jar:2.4.5]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-2.4.5.jar:2.4.5]
		at org.grails.plugins.domain.DomainClassGrailsPlugin.onChange(DomainClassGrailsPlugin.groovy:110) ~[grails-plugin-domain-class-3.0.15.jar:3.0.15]
		at org.grails.plugins.DefaultGrailsPlugin.notifyOfEvent(DefaultGrailsPlugin.java:792) ~[grails-core-3.0.15.jar:3.0.15]
		at org.grails.plugins.AbstractGrailsPluginManager.informOfClassChange(AbstractGrailsPluginManager.java:507) [grails-core-3.0.15.jar:3.0.15]
		at org.grails.plugins.AbstractGrailsPluginManager.informOfFileChange(AbstractGrailsPluginManager.java:444) [grails-core-3.0.15.jar:3.0.15]
		at grails.plugins.GrailsPluginManager$informOfFileChange$1.call(Unknown Source) [grails-core-3.0.15.jar:3.0.15]
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.5.jar:2.4.5]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.5.jar:2.4.5]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-2.4.5.jar:2.4.5]
		at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:208) [grails-core-3.0.15.jar:3.0.15]
		at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy) [grails-core-3.0.15.jar:3.0.15]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
		at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426) [springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.5.jar:2.4.5]
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.Closure.call(Closure.java:426) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.Closure.call(Closure.java:420) [groovy-2.4.5.jar:2.4.5]
		at groovy.lang.Closure.run(Closure.java:507) [groovy-2.4.5.jar:2.4.5]
		at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]

CentOS Linux release 7.2.1511 (Core) 
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Grails 3.0.15

**Comment by donald-jackson** [comment]
Just updated the above - applies to services as well (probably all)

**Comment by donald-jackson** [comment]
As mentioned to @graemerocher privately - inline reloading is now bizarrely working for me. Not in the grails { plugins { } } block, but directly in the dependancies { } block using compile project(":inlinePlugin")

No exploded = true anywhere to be seen. I'm not sure why this is working but it is. Using grails 3.0.15 on Linux (same as above).

**Comment by graemerocher** [comment]
Can't reproduce this with services, in 3.0.x branch of 3.1.x branch. If you continue to experience this issue please provide an example with steps to reproduce
