### ISSUE TITLE
[grails 3.x] Skip Gradle Wrapper

### ISSUE THREAD

**Issue by Luxor** [grails/grails-core#9857]
Hi,

According to the docs http://grails.github.io/grails-doc/3.1.x/ref/Command%20Line/create-app.html
It is possible to create grails application without wrapper

```
grails create-app [name] [--skip-wrapper] 
```
But from command line, I can't see "skip wrapper" feature
```
$ grails help create-app
|Command: create-app
|Description:
Creates an application

|Usage:
create-app [NAME] --profile=web

|Arguments:
* Application Name - The name of the application to create. (OPTIONAL)

|Flags:
* inplace - Used to create an application using the current directory
* profile - The profile to use
* features - The features to use
```

**In corporate environment I have limited internet connection.** So when I run any grails 
command it results in the exception below. 

How can I use grails commands without downloading wrapper and use pre-installed gradle
If I use gradle I can use some grails commands, such as test, run-app
 
```
grails run-app

Error |
Error initializing classpath: Connection timed out: connect (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.net.ConnectException: Connection timed out: connect
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ProgressReportingDownload.download(DistributionFactory.java:177)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution$1.call(DistributionFactory.java:122)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution$1.call(DistributionFactory.java:116)
```

**Comment by graemerocher** [comment]
The `--skip-wrapper` command is from Grails 2 and simply prevented the generation of the `grailsw` wrapper, so this is a stale documentation issue.

Separately to that Grails uses an embedded version of Gradle via the Gradle tooling API that it has to download to function, and there is no way to disable that. This is a one time download, so you will have to configure whatever corporate proxy necessary in order to allow Grails access to download the wrapper.

**Comment by Luxor** [comment]
Got it. Thank you
