### ISSUE TITLE
3.1.4 - Parameters for controller method respond reversed compared to documentation

### ISSUE THREAD

**Issue by jamie-kemp** [grails/grails-core#9864]
Reviewing the [documentation](http://grails.github.io/grails-doc/latest/ref/Controllers/respond.html), it demonstrates calling respond with the object as the first parameter, arguments passed as the second which I have used under Grails 2.4.x. Now, migrating to Grails 3 these appear to have swapped and now must be invoked using:

`respond(arguments, object)`

I have uploaded a [sample project](https://github.com/jamie-kemp/grails3-respond-test) demonstrating the issue. Two controllers, one in the application (/test), the other in a plugin (/other). /test demonstrating the issue with the arguments as documented resulting in an exception. /other showing swapping the arguments producing the expected result. On failure the exception is:

```
ERROR org.grails.web.errors.GrailsExceptionResolver - NumberFormatException occurred when processing request: [POST] /test
For input string: "ERROR". Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "ERROR"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.valueOf(Integer.java:582)
        at grails.artefact.controller.RestResponder$Trait$Helper.internalRespond(RestResponder.groovy:108)
        at grails.artefact.controller.RestResponder$Trait$Helper.respond(RestResponder.groovy:83)
        at rest.test.TestController.save(TestController.groovy:21)
        ... 3 common frames omitted
```

Modifying any of the controller methods under run-app also demonstrates a recurrence of #9638. Initially was following up thinking it was a exploded plugin issue hence the form of the test project, but appears to happen for the application controller as well.

**Comment by jameskleeh** [comment]
Documented https://github.com/grails/grails-doc/commit/96ae5a119b9e45d0941736063fa7097f1a8ff14b
