### ISSUE TITLE
NullPointerException thrown when unit testing a domain with constraints

### ISSUE THREAD

**Issue by adrianbk** [grails/grails-core#9887]
Given the following domain classes: 
```groovy

class BasicIntegrationScheduledJob extends ScheduledJob {
    static hasMany = [results: BasicIntegrationResult]
    static constraints = { }
}

class ScheduledJob {
    String name
    String description
    String cronExpression
    boolean enabled

    static constraints = {
        name(unique: true)
    }
}

```
And the following unit test:

```groovy
import grails.test.mixin.TestMixin
import grails.test.mixin.gorm.Domain
import grails.test.mixin.hibernate.HibernateTestMixin
import spock.lang.Specification

@Domain([BasicIntegrationScheduledJob, BasicIntegrationResult, BasicData])
@TestMixin(HibernateTestMixin)
 void "should find the latest result"() {
        given:
        def result1 = new BasicIntegrationResult(data: new BasicData(data: [d: '1'])).save(failOnError: true)
        def result2 = new BasicIntegrationResult(data: new BasicData(data: [d: '2'])).save(failOnError: true)

        BasicIntegrationScheduledJob basicIntegrationScheduledJob = new BasicIntegrationScheduledJob(
                name: 'some  sss ',
                description: 'some desc',
                cronExpression: 'cron'
        )
        basicIntegrationScheduledJob.addToResults(result1)
        basicIntegrationScheduledJob.addToResults(result2)

        basicIntegrationScheduledJob.save(failOnError: true)

        expect:
        true
    }
```

The test throws a NPE with the following stacktrace:

```
java.lang.NullPointerException
	at org.grails.orm.hibernate.validation.UniqueConstraint$2.call(UniqueConstraint.java:172)
	at org.grails.orm.hibernate.validation.UniqueConstraint$2.call(UniqueConstraint.java:148)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:196)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:140)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:110)
	at org.grails.orm.hibernate.validation.UniqueConstraint.processValidate(UniqueConstraint.java:148)
	at grails.validation.AbstractConstraint.validate(AbstractConstraint.java:107)
	at grails.validation.ConstrainedProperty.validate(ConstrainedProperty.java:979)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:211)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:122)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:140)
	at x.x.x.BasicIntegrationScheduledJobSpec.should find the latest result(BasicIntegrationScheduledJobSpec.groovy:25)
```
### Expected Behaviour

A NPE should not be thrown and the test should succeed. 
When I remove the constraint `name(unique: true)` from `ScheduledJob` the test passes.

### Actual Behaviour

A NPE is be thrown

### Environment Information

- **Operating System**: OSX 10.11.14
- **Grails Version:** 3.1.5
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
Can you try change

        @Domain([BasicIntegrationScheduledJob, BasicIntegrationResult, BasicData])

To

         @Domain([ScheduledJob, BasicIntegrationScheduledJob, BasicIntegrationResult, BasicData])

**Comment by adrianbk** [comment]
That worked. Should the `@Domain` mixin on the subclass `BasicIntegrationScheduledJob` be enough though?

**Comment by graemerocher** [comment]
At the moment you have to list all participating domain classes including parents, but  it maybe be reasonable to expect that parents are added automatically
