### ISSUE TITLE
Custom keystore during run-app -https

### ISSUE THREAD

**Issue by smilanko** [grails/grails-core#9888]
I am unable to find documentation as to how I can force a particular keystore to be used in grails 3.1.2 during the invocation of "run-app -https"

What I have observed so far, is that when the https option is passed, the following system properties are set during task execution of bootRun:

```
endpoints.shutdown.enabled:true, env:development, full.stacktrace:false, grails.env:development, grails.full.stacktrace:false, info.app.grailsVersion:3.1.2, info.app.name:coolio, info.app.version:0.1, interactive.mode.enabled:true, run.active:true, server.port:8443, server.ssl.key-password:123456, server.ssl.key-store:./build/ssl/keystore, server.ssl.key-store-password:123456, verbose:false
```

My first approach here is to try and replicate the system properties passed, so that I can override them during the boot stage. Thus, my bootRun task looks as follows:

``` groovy
bootRun {
    def dir = System.getProperty("user.dir")
    systemProperty "endpoints.shutdown.enabled", "true"
    systemProperty "server.port", "8443"
    systemProperty "server.ssl.key-password", "coolio"
    systemProperty "server.ssl.key-store:", dir + "/.keystore"
    systemProperty "server.ssl.key-store-password", "coolio"
    systemProperty "run.active", "true"
    println("########### we have " +  systemProperties)
}
```

While the properties are indeed loaded, during the invocation of "run-app" (without and with the -https argument), neither seems to allow my custom keystore to work. While both of the errors/exceptions are super generic, they are as follows:

run-app -https  or run-app 
```
Exception in thread "main" org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.IllegalArgumentException: Resource location must not be null
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:55)

...
Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.77-0.b03.el7_2.x86_64/bin/java'' finished with non-zero exit value 1
```

- **Operating System**: RedHat 7
- **Grails Version:** 3.1.2
- **JDK Version:** java-1.8.0-openjdk-1.8.0.77-0.b03.el7_2.x86_64
- **Container Version (If Applicable):** embedded tomcat

**Comment by smilanko** [comment]
Note, a solution to this is provided in this post: 

http://stackoverflow.com/questions/31033751/embedded-tomcat-enable-ssl

Unless there is an easier way to make this work in grails 3 build file, for now, I will consider this as the only solution
