### ISSUE TITLE
Remove grails-plugins-domain-class and get Unable to load class grails.test.mixin.services.ServiceUnitTestMixin due to missing dependency org/grails/datastore/mapping/core/Datastore

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#9893]
While developing a Grails 3.1 plugin with the 'plugin' profile. I thought the best practice was to remove any unnecessary dependency.  I was not using any domain class. Thus I wanted to remove the 

    provided "org.grails:grails-plugin-domain-class"

dependency from build.gradle. 

I thought it was possible but I am getting an error while running the tests.  

### Steps to Reproduce

1. clone https://github.com/sdelamo/grails-geoplugin
2. remove from _build.gradle_ line 
 __provided "org.grails:grails-plugin-domain-class"_
3. Run _gradle clean;gradle check_

### Expected Behaviour

I thought test should pass fine

### Actual Behaviour

But I am getting this error instead:

```
General error during canonicalization: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.services.ServiceUnitTestMixin due to missing dependency org/grails/datastore/mapping/core/Datastore

java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.services.ServiceUnitTestMixin due to missing dependency org/grails/datastore/mapping/core/Datastore
        at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1091)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1069)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:591)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:525)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:164)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:52)
        at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.services.ServiceUnitTestMixin due to missing dependency org/grails/datastore/mapping/core/Datastore
        at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:392)
        at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:265)
        at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:360)
        at org.codehaus.groovy.ast.ClassNode.getAllInterfaces(ClassNode.java:423)
        at org.codehaus.groovy.ast.ClassNode.getAllInterfaces(ClassNode.java:415)
        at org.grails.compiler.injection.test.TestMixinTransformation.weaveMixinsIntoClass(TestMixinTransformation.java:198)
        at org.grails.compiler.injection.test.TestMixinTransformation.weaveMixinsIntoClass(TestMixinTransformation.java:184)
        at org.grails.compiler.injection.test.TestForTransformation.weaveMixinClass(TestForTransformation.java:400)
        at org.grails.compiler.injection.test.TestForTransformation.weaveMock(TestForTransformation.java:250)
        at org.grails.compiler.injection.test.TestForTransformation.testFor(TestForTransformation.java:233)
        at org.grails.compiler.injection.test.TestForTransformation.handleTestForAnnotation(TestForTransformation.java:131)
        at org.grails.compiler.injection.test.TestForTransformation.visit(TestForTransformation.java:123)
        at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:134)
        at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:178)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1055)
        ... 19 more

1 error

:compileTestGroovy FAILED

```

### Environment Information

- **Grails Version:** 3.1.5
- **JDK Version:** 1.8.0_45

### Example Application

- https://github.com/sdelamo/grails-geoplugin

**Comment by graemerocher** [comment]
It is only the testing part that needs it so you can change the dependency to `testCompile`

**Comment by sdelamo** [comment]
Thanks @graemerocher make it testCompile solved as you said. Sorry for the late answer.
