### ISSUE TITLE
grails create-app fails

### ISSUE THREAD

**Issue by javajini** [grails/grails-core#9935]
Grails 3.1.6 fails to create an app when the standard "grails create-app <appname>" command is issued. I first downloaded 3.1.6 using SDKMAN! I subsequently downloaded it straight from the grails.org download page and finally downloaded grails-core-3.1.6 and built it from scratch. All three approaches yielded the same result.

Grails 3.1.5 and earlier work fine on my machine. I suspect that something was inadvertently left out of the 3.1.6 build.

### Steps to Reproduce

* download Grails 3.1.6

* issue the following command
```
$ grails create-app hello --stacktrace

| Error Error occurred running Grails CLI: Requested Range Not Satisfiable (416) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.apache.http.client.HttpResponseException: Requested Range Not Satisfiable (416)
	at org.eclipse.aether.transport.http.HttpTransporter.handleStatus(HttpTransporter.java:466)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:291)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:243)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:302)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:112)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:104)
	at org.grails.cli.profile.repository.MavenProfileRepository.resolveProfile(MavenProfileRepository.groovy:99)
	at org.grails.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:70)
	at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:139)
	at org.grails.cli.GrailsCli.executeCommandWithArgumentValidation(GrailsCli.groovy:289)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:265)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error occurred running Grails CLI: Requested Range Not Satisfiable (416)
```
I am running Linux on a Core2Duo. Here is the result of uname on my system if it matters. 

$ uname -a
Linux myhost 4.4.9-300.fc23.x86_64 #1 SMP Wed May 4 23:56:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behaviour

I expected to have a new application named hello created in a subdirectory of the directory where I issued the create-app command.

### Actual Behaviour

No files were created.

### Environment Information

- **Operating System**: Fedora fc23.x86_64
- **Grails Version:** 3.1.6
- **JDK Version:** 1.8.0_91
- **Container Version (If Applicable):** N/A

### Example Application

- N/A

**Comment by shawnchain** [comment]
I got that same issue under OSX 10.10.5 

mac:~ shawn$ grails -v
| Grails Version: 3.1.9
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_77

mac:~ shawn$ grails
| Error Error occurred running Grails CLI: Requested Range Not Satisfiable (416) (Use --stacktrace to see the full trace)

@graemerocher

**Comment by naxmefy** [comment]
got same on osx 10.11.5

fresh install sdkman and grails -> fails

**Comment by jeffbrown** [comment]
> got same on OS X 10.11.5

@javajini naxmefy With what version of Grails?

Does the problem go away if you delete your local maven cache?

**Comment by naxmefy** [comment]
@jeffbrown 3.1.11 the latest

Fresh install of sdkman and grails
JDK 8 0 91
Gradle 3

**Comment by todoubaba** [comment]
Same problem with 3.2.6.

\> grails --version
| Grails Version: 3.2.6
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_111

\> grails create-app test
Resolving dependencies..
| Error Error occurred running Grails CLI: Requested Range Not Satisfiable (416) (Use --stacktrace to see the full trace)

Works fine with 3.2.5.

**Comment by rob212** [comment]
I'm seeing the same with Grails 3.2.6 on macOs 10.12.4

Brand new install of Grails. First time I have ever tried using it. 

`grails create-app helloworld --stacktrace
| Warning Unrecognized flag: stacktrace.
Resolving dependencies..
| Error Error occurred running Grails CLI: Requested Range Not Satisfiable (416) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.apache.http.client.HttpResponseException: Requested Range Not Satisfiable (416)
	at org.eclipse.aether.transport.http.HttpTransporter.handleStatus(HttpTransporter.java:466)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:291)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:243)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:317)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:127)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:119)
	at org.grails.cli.profile.repository.MavenProfileRepository.resolveProfile(MavenProfileRepository.groovy:87)
	at org.grails.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:72)
	at org.grails.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:80)
	at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:216)
	at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:341)
	at org.grails.cli.GrailsCli.executeCommandWithArgumentValidation(GrailsCli.groovy:286)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:262)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
`

Has a fix been released for this?

**Comment by rob212** [comment]
Managed to resolve it by clearing out my maven cache by deleting /.m2/repository folder.

**Comment by lalitvchau** [comment]
This error to due to maven was installed in you system..

follow the below steps

1. delete the c:\Users.m2 or related directory in windows (Not sure about Unix or Mac but you can find the local cache of maven. Delete .m2 directory)
2. delete maven related environment variable.
3. delete ./gradlew
4. delete environment variable related to groovy also

try to above step.. it will work fine
