### ISSUE TITLE
Async Gorm - onComplete doesn't render JSON in a controller of the owner side

### ISSUE THREAD

**Issue by aaloise** [grails/grails-core#9941]
Using Grails 3.1.6, the owner side of an association (one-to-many, many-to-many.....) doesn't get JSON rendering when used in a method with Async Gorm in a Controller.

E.g.: Campus has many courses and a Course belongs to a Campus (bidirectional one-to-many relationship).

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a bidirectional one-to-many relationship (E.g.: Campus has many Courses and Course belongs to Campus)
2. In Bootstrap and Controllers:

```
    Campus.async.findAllByNomeIlike("%man%").onComplete{ results ->
        println results.value //Bootstrap
        render results.value //Controller
    }

    Course.async.findAllByNomeIlike("%tec%").onComplete{ results ->
        println results.value //Bootstrap
        render results.value //Controller
    }
```
3. In Bootstrap and Controllers, this works:
```
    Campus.async.findAllByNomeIlike("%$params.q%").onComplete{ results ->
        render results.value as JSON //doesn't work
    }

    Course.async.findAllByNomeIlike("%$params.q%").onComplete{ results ->
        render results.value as JSON //this works
    }
```

### Expected Behaviour

Async JSON should be rendered at both sides. In CampusController, this shoukd work:
```
def getCampus() {
        Campus.async.findAllByNomeIlike("%$params.q%").onComplete{ results ->
            render results.value as JSON
        }
}
```
But it doesn't.

In CourseController, this works:
```
def getCourses() {
    Course.async.findAllByNomeIlike("%$params.q%").onComplete{ results ->
        render results.value as JSON
    }
}
```
### Actual Behaviour

The following happens after an unsuccessful "render results.value as JSON" on the owner side:

            <ul class="errors">
                <li>An error has occurred</li>
                <li>Exception: </li>
                <li>Message: </li>
                <li>Path: </li>
            </ul>

### Environment Information

- **Operating System**: Windows 7 (64-bit)
- **Grails Version:** 3.1.6
- **JDK Version:** Oracle 1.8.0.77
- **Container Version (If Applicable):** not applicable

**Comment by aaloise** [comment]
Example of project.

This generates JSON:

http://localhost:8080/fichacatalografica/curso/getCursos?q=eng

This doesn't:

http://localhost:8080/fichacatalografica/campus/getCampus?q=man

[fichacatalografica.zip](https://github.com/grails/grails-core/files/273337/fichacatalografica.zip)

**Comment by JohnTheBeloved** [comment]
Although I don't specifically know the scenario, Had issues with grails raw JAVA POJO models(not POGO declared in the domain folder)

You can try to use the groovy converters library with this code

```
 response.setContentType("application/json")
 render JsonOutput.toJson(results.value)
```

JSONOutput is found in **import groovy.json.***

Also try to render a plain POGO without any types of other Classes, Just native types

**Comment by aaloise** [comment]
Hello @JohnTheBeloved 

Thanks for your suggestion, but unfortunately it didn't work. The some problem happens.

I think it is related to the owner side of a bidirectional relationship of domain classes. While JSON rendering works with the subordinate class, the owner doesn't.

You can see that happening by executing the project I sent.

**Comment by JohnTheBeloved** [comment]
Tried to run the Application, but receiving error

```
| Error Error occurred running Grails CLI: No profile found for name [web]. (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.IllegalStateException: No profile found for name [web].
        at org.grails.cli.GrailsCli.initializeProfile(GrailsCli.groovy:517)
        at org.grails.cli.GrailsCli.initializeApplication(GrailsCli.groovy:309)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:272)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error occurred running Grails CLI: No profile found for name [web].
```

**Comment by aaloise** [comment]
Try grails/gradle clean before running the project

**Comment by aaloise** [comment]
@JohnTheBeloved , when I remove any types of other Classes (E.g.: remove the hasMany), render works

**Comment by aaloise** [comment]
Another way to get it working on Controllers:

```
Campus.async.findAllByNomeIlike("%$params.q%",[fetch:[courses:"eager"]]).onComplete{ results ->
            render results.value as JSON
}
```

In case of Controllers, you must explicitly fetch as eager, which is not mandatory if the query is used in Bootstrap.groovy
