### ISSUE TITLE
Problem Serializing Validateable

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9986]
A class that implements the `Validateable` trait cannot be serialized because the `Validateable` trait has a property of type `BeforeValidateHelper` which is not `Serializable`.

```
// src/main/groovy/demo/Person.groovy
package demo

import grails.validation.Validateable

class Person implements Serializable, Validateable {
    String firstName
    String lastName
}
```

The following test will throw a `NotSerializableException`.

```
// src/test/groovy/demo/PersonSpec.groovy
package demo

import spock.lang.Specification

class PersonSpec extends Specification {

    void "test serialization"() {
        given:
        def p = new Person(firstName: 'Jeff', lastName: 'Brown')

        def bos = new ByteArrayOutputStream()
        def oos = new ObjectOutputStream(bos)

        when:
        oos.writeObject(p)
        oos.flush()

        def bis = new ByteArrayInputStream(bos.toByteArray())
        def ois = new ObjectInputStream(bis)
        def p2 = ois.readObject()

        then:
        p2 instanceof Person
        p2.firstName == 'Jeff'
        p2.lastName == 'Brown'
    }
}
```

Error message:

```
java.io.NotSerializableException: org.grails.datastore.gorm.support.BeforeValidateHelper

    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at demo.PersonSpec.test serialization(PersonSpec.groovy:15)
```

All of that code is in the sample project at https://github.com/jeffbrown/serializableproblem.

**Comment by martyychang** [comment]
Which version of Grails, @jeffbrown ?

**Comment by jeffbrown** [comment]
> Which version of Grails, @jeffbrown ?

Every version of Grails which contains the `Validateable` trait.  That was introduced in 3.0.0.

**Comment by jeffbrown** [comment]
Wait... that isn't right.  The trait was introduced before 3.0.0.

**Comment by jeffbrown** [comment]
The trait was introduced in 2.5.0.

**Comment by jeffbrown** [comment]
I have verified that the problem appears to happen as far back as 3.0.0.

**Comment by dheerajgoyal38** [comment]
I using grails 3.1.16 application. and i'm still facing the issue.

```
Exception occurred. org.grails.datastore.gorm.support.BeforeValidateHelper$BeforeValidateEventTriggerCaller  
java.io.NotSerializableException: org.grails.datastore.gorm.support.BeforeValidateHelper$BeforeValidateEventTriggerCaller
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
```
When i'm running the application with **grails run-app** command its working fine. But when i deployed the war file on tomcat it throws the above error. The error seems to be in **BeforeValidateEventTriggerCaller**. which has not implemented serializable
