### ISSUE TITLE
grails >=3.1.5 - Error occurred during initialization of VM

### ISSUE THREAD

**Issue by Spadavecchia** [grails/grails-core#9994]
Running application with version >=3.1.5 raises:
### stack trace
Error occurred during initialization of VM
java.lang.InternalError: java.net.MalformedURLException: unknown protocol: file
        at sun.misc.Launcher.getFileURL(Launcher.java:487)
        at sun.misc.Launcher$ExtClassLoader.getExtURLs(Launcher.java:194)
        at sun.misc.Launcher$ExtClassLoader.<init>(Launcher.java:164)
        at sun.misc.Launcher$ExtClassLoader$1.run(Launcher.java:148)
        at sun.misc.Launcher$ExtClassLoader$1.run(Launcher.java:142)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.Launcher$ExtClassLoader.getExtClassLoader(Launcher.java:141)
        at sun.misc.Launcher.<init>(Launcher.java:71)
        at sun.misc.Launcher.<clinit>(Launcher.java:57)
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1451)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
Caused by: java.net.MalformedURLException: unknown protocol: file
        at java.net.URL.<init>(URL.java:421)
        at java.net.URL.<init>(URL.java:310)
        at java.net.URL.<init>(URL.java:333)
        at sun.net.www.ParseUtil.fileToEncodedURL(ParseUtil.java:272)
        at sun.misc.Launcher.getFileURL(Launcher.java:484)
        at sun.misc.Launcher$ExtClassLoader.getExtURLs(Launcher.java:194)
        at sun.misc.Launcher$ExtClassLoader.<init>(Launcher.java:164)
        at sun.misc.Launcher$ExtClassLoader$1.run(Launcher.java:148)
        at sun.misc.Launcher$ExtClassLoader$1.run(Launcher.java:142)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.Launcher$ExtClassLoader.getExtClassLoader(Launcher.java:141)
        at sun.misc.Launcher.<init>(Launcher.java:71)
        at sun.misc.Launcher.<clinit>(Launcher.java:57)
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1451)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)

============================================================
Error raises with existing or new applications. The applications run fine with grails 3.1.4 even when using >=3.1.5 for creation

All versions above 3.1.4 (3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.2.0.M1) were tested

### Environment Information

- **Operating System**: Ubuntu 14.04LTS
- **Grails Version:** [3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.2.0.M1]
- **JDK Version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by graemerocher** [comment]
This is a problem with when your environment variables (probably `CLASSPATH` or `GRAILS_HOME`) which is defined wrong, nothing todo with Grails itself

**Comment by graemerocher** [comment]
Also please follow the issue template when reporting issues, as we would need steps to reproduce, but you have provided none and instead chose to delete the section requiring steps to reproduce

**Comment by Spadavecchia** [comment]
### Steps to reproduce:
``` sh
grails create-app whatever
cd whatever
grails run-app
```

***You was so right***. That was an enviroment variable, not `CLASSPATH` or `GRAILS_HOME` 
the error disappeared when I removed the `GRAILS_OPTS` environment variable. My `GRAILS_OPTS` was:

``` sh
export GRAILS_OPTS="
    -server
    -noverify
    -Dfile.encoding=UTF-8
    -Djava.net.preferIPv4Stack=true
    -XX:+UnlockExperimentalVMOptions
    -Dsun.reflect.inflationThreshold=100000
    -XX:+UseG1GC
    -XX:+UseFastAccessorMethods
    -XX:MinHeapFreeRatio=5
    -XX:MaxHeapFreeRatio=10
    -Xms512m
    -Xmx512m"
```
Do you know why 3.1.4 executes with that configuration and versions >=3.1.5 are failing?
***Thank you man***
